/-
Copyright (c) 2026 Poincaré project contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Poincaré project (D7-conjugate-heat-interface)
-/

import Poincare.D7.ConjugateHeat.All

set_option linter.style.haveILetI false

/-!
# Poincare.D7.ConjugateHeat.Audit

**D7 conjugate-heat layer, part 8: the `#print axioms` audit.**

One `#print axioms` command per principal declaration of the layer. Every cone is expected to be a
subset of `{propext, Classical.choice, Quot.sound}`; no `sorryAx`, no `native_decide`, and no
`proof_wanted` may appear.
-/

-- Laplacian.lean (def)
#print axioms Poincare.D7.ConjugateHeat.pairingLM
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.pairingLM_apply
-- Laplacian.lean (def)
#print axioms Poincare.D7.ConjugateHeat.scalarMulLM
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.scalarMulLM_apply
-- Laplacian.lean (def)
#print axioms Poincare.D7.ConjugateHeat.pairingOn
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.pairingOn_univ
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.pairingOn_comm
-- Laplacian.lean (def)
#print axioms Poincare.D7.ConjugateHeat.edgeLapAt
-- Laplacian.lean (def)
#print axioms Poincare.D7.ConjugateHeat.edgeLap
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.edgeLapAt_apply
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.edgeLap_apply
-- Laplacian.lean (def)
#print axioms Poincare.D7.ConjugateHeat.graphLaplacian
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.graphLaplacian_apply
-- Laplacian.lean (def)
#print axioms Poincare.D7.ConjugateHeat.laplaceBeltrami
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.laplaceBeltrami_apply
-- Laplacian.lean (def)
#print axioms Poincare.D7.ConjugateHeat.dirichletForm
-- Laplacian.lean (def)
#print axioms Poincare.D7.ConjugateHeat.boundaryPair
-- Laplacian.lean (def)
#print axioms Poincare.D7.ConjugateHeat.boundaryForm
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.boundaryForm_antisymm
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.sum_edgeLap_mul
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.green_first
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.green_second
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.dirichletForm_nonneg
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.boundaryPair_eq_zero_of_closed
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.boundaryPair_univ
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.laplaceBeltrami_selfAdjoint_univ
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.pairingLM_symm
-- Laplacian.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.scalarMulLM_selfAdjoint
-- Basic.lean (abbrev)
#print axioms Poincare.D7.ConjugateHeat.Jet
-- Basic.lean (def)
#print axioms Poincare.D7.ConjugateHeat.Jet.val
-- Basic.lean (def)
#print axioms Poincare.D7.ConjugateHeat.Jet.deriv
-- Basic.lean (structure)
#print axioms Poincare.D7.ConjugateHeat.MetricFlowInterface
-- Basic.lean (def)
#print axioms Poincare.D7.ConjugateHeat.forwardHeatLM
-- Basic.lean (def)
#print axioms Poincare.D7.ConjugateHeat.backwardHeatLM
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.forwardHeatLM_apply
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.backwardHeatLM_apply
-- Basic.lean (structure)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData
-- Basic.lean (def)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.ofInterface
-- Basic.lean (def)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.IsConjugateHeatJet
-- Basic.lean (def)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.IsHeatJet
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.isConjugateHeatJet_iff
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.isHeatJet_iff
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.isConjugateHeatJet_self
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.isHeatJet_self
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.formal_adjoint
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.formal_adjoint_of_boundaryForm_eq_zero
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.formal_adjoint_of_volumeVariation_eq_zero
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.formal_adjoint_closed
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatData.volumeVariation_eq_boundaryForm_of_heat_and_conjugate
-- Basic.lean (structure)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatIBPCertificate
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatIBPCertificate.heatPairing_sub_conjugatePairing
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatIBPCertificate.heatPairing_eq_conjugatePairing
-- Basic.lean (def)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatIBPCertificate
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatIBPCertificate_heatPairing
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatIBPCertificate_conjugatePairing
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatIBPCertificate_volumeVariation
-- Basic.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatIBPCertificate_boundaryForm
-- Instance.lean (def)
#print axioms Poincare.D7.ConjugateHeat.massOn
-- Instance.lean (def)
#print axioms Poincare.D7.ConjugateHeat.pairingOnLM
-- Instance.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.pairingOnLM_apply
-- Instance.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.pairingOnLM_apply_eq_pairingOn
-- Instance.lean (def)
#print axioms Poincare.D7.ConjugateHeat.metricFlowInterface
-- Instance.lean (def)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatData
-- Instance.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatData_forwardHeat_apply
-- Instance.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatData_backwardHeat_apply
-- Instance.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatData_formal_adjoint
-- Slab.lean (def)
#print axioms Poincare.D7.ConjugateHeat.energy
-- Slab.lean (def)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatStep
-- Slab.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatStep_eq_add_generator
-- Slab.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.energy_le_energy_conjugateHeatStep
-- Slab.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.energy_mono_slab
-- Example.lean (def)
#print axioms Poincare.D7.ConjugateHeat.cycleData
-- Example.lean (def)
#print axioms Poincare.D7.ConjugateHeat.cycleWeight
-- Example.lean (def)
#print axioms Poincare.D7.ConjugateHeat.cycleMass
-- Example.lean (def)
#print axioms Poincare.D7.ConjugateHeat.cycleScalar
-- Example.lean (def)
#print axioms Poincare.D7.ConjugateHeat.cycleU
-- Example.lean (def)
#print axioms Poincare.D7.ConjugateHeat.cycleV
-- Example.lean (def)
#print axioms Poincare.D7.ConjugateHeat.cycleDU
-- Example.lean (def)
#print axioms Poincare.D7.ConjugateHeat.cycleDV
-- Example.lean (def)
#print axioms Poincare.D7.ConjugateHeat.cycleRegion
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycleMass_pos
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycleMass_ne_zero
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycleWeight_nonneg
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycleScalar_nonneg
-- Example.lean (abbrev)
#print axioms Poincare.D7.ConjugateHeat.cycleCH
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_laplaceBeltrami_u_zero
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_laplaceBeltrami_u_one
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_laplaceBeltrami_v_zero
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_laplaceBeltrami_v_one
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_dirichletForm_zero
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_boundaryPair_uv
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_boundaryPair_vu
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_boundaryForm_value
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_green_first_value
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_green_second_value
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_pairing_forwardHeat
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_pairing_backwardHeat
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_volumeVariation_value
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_formal_adjoint_value
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_certificate_value
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_conjugateHeatJet
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycle_heatJet
-- Example.lean (def)
#print axioms Poincare.D7.ConjugateHeat.cycleSlab
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycleSlab_step
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycleSlab_energy_zero
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycleSlab_energy_last
-- Example.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.cycleSlab_energy_mono_value
-- Blocked.lean (structure)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatSpacetime
-- Blocked.lean (def)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatSpacetime.conjugateHeat
-- Blocked.lean (def)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatSpacetime.zero
-- Blocked.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatSpacetime.zero_volume
-- Blocked.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatSpacetime.zero_conjugateHeat
-- Blocked.lean (structure)
#print axioms Poincare.D7.ConjugateHeat.IsRiemannianConjugateHeatSpacetime
-- Blocked.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatSpacetime.not_isRiemannian_zero
-- Blocked.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatSpacetime.isRiemannian_zero_of_isEmpty
-- Blocked.lean (structure)
#print axioms Poincare.D7.ConjugateHeat.IsConjugateHeatKernel
-- Blocked.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.not_isConjugateHeatKernel_zero
-- Blocked.lean (def)
#print axioms Poincare.D7.ConjugateHeat.ConjugateHeatKernelExistenceStatement
-- Blocked.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.conjugateHeatKernelExistenceStatement_isProp
-- Blocked.lean (structure)
#print axioms Poincare.D7.ConjugateHeat.Blocker
-- Blocked.lean (def)
#print axioms Poincare.D7.ConjugateHeat.blockers
-- Blocked.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.blockers_length
-- Blocked.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.blockers_ne_nil
-- Blocked.lean (def)
#print axioms Poincare.D7.ConjugateHeat.MissingMathlibDependencies
-- Blocked.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.MissingMathlibDependencies_length
-- Blocked.lean (def)
#print axioms Poincare.D7.ConjugateHeat.PresentMathlibDependencies
-- Blocked.lean (theorem)
#print axioms Poincare.D7.ConjugateHeat.PresentMathlibDependencies_length
