import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.Calculus.Deriv.Pow
import Mathlib.Analysis.Calculus.Deriv.Add
import Mathlib.Analysis.Calculus.Deriv.Comp
import Mathlib.Analysis.Calculus.Deriv.Abs
import Mathlib.Analysis.Calculus.ContDiff.Basic
import Mathlib.Analysis.Calculus.IteratedDeriv.Defs
import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Basic.Real.Sign
import Poincare.D10.BochnerEuclidean.Bochner
import Poincare.D10.BochnerEuclidean.Corollary
import Poincare.D10.JacobiConstantCurvature.ODE
import Poincare.D7.Bochner.GradientEstimate

#check Ioi_mem_nhds
#check Iio_mem_nhds
#check isOpen_lt
#check Differentiable.continuous
#check DifferentiableAt.continuousAt
#check ContinuousAt.preimage_mem_nhds
#check deriv_neg
#check lt_or_gt_of_ne
#check HasDerivAt.neg
#check Poincare.D10.BochnerEuclidean.bochner_identity
#check Poincare.D10.BochnerEuclidean.bochner_identity_components
#check Poincare.D10.BochnerEuclidean.harmonic_energy_density_subharmonic
#check Poincare.D10.BochnerEuclidean.harmonic_lap_gradNormSq
#check Poincare.D10.BochnerEuclidean.hessNormSq_nonneg
#check Poincare.D10.jacobiSol
#check Poincare.D10.jacobiDeriv
#check Poincare.D10.jacobiSol_ode
#check Poincare.D10.jacobiSol_deriv
#check Poincare.D10.hasDerivAt_jacobiSol
#check Poincare.D10.hasDerivAt_jacobiDeriv
#check Poincare.D7.Bochner.BochnerCertificate
#check Poincare.D7.Bochner.GradientCertificate
#check Poincare.D7.Bochner.hessNormSq
#check Poincare.D7.Bochner.gradLaplacianDot
#check Poincare.D7.Bochner.ricciPairing
#check Poincare.D7.Bochner.gradientCertificateOfData
#check Poincare.D7.Bochner.GradientCertificate.gradient_estimate
#check Poincare.D7.Bochner.GradientCertificate.bochner_inequality
#check Poincare.D7.Bochner.BochnerCertificate.roughLaplacian_le_oneFormLaplacian
