/-
Copyright (c) 2026 D13-integrated-kernel-audit. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# D13 integrated kernel audit — downstream-use (reverse dependency) probe

For each *key input* named by a D12 blocker-closure record, this probe builds the reverse
direct-use graph of all snapshot-internal declarations (`Poincare.*`, `Probe.*`, …) and
reports every declaration that transitively consumes the input in its **proof term or
definition body** (theorem bodies are unsealed with `value? true`).

This is the machine check behind the acceptance rule "no claimed blocker closure without a
constructor of that missing input and a downstream checked use": a constructor with zero
transitive consumers is reported as `USES=0` and cannot count as a closed blocker.

Emits `D13USE<TAB><input><TAB><transitive user count><TAB><sample users>` plus
`D13USEMISSING` for inputs that do not resolve.
-/
import Poincare.D13.IntegratedAudit.SnapshotRoot
import Lean.Elab.Command

open Lean Elab Command

namespace Poincare.D13.IntegratedAudit

/-- Key inputs whose downstream consumption is asserted by D12 blocker-closure records
(or that are headline negative controls). -/
def keyInputs : List Name := [
  -- D12-connection-curvature
  "Poincare.D12.ConnectionCurvature.milnorConnection".toName,
  "Poincare.D12.ConnectionCurvature.leviCivitaExists".toName,
  "Poincare.D12.ConnectionCurvature.milnorConnection_eq_mean_iff".toName,
  -- D12-entropy-variation
  "Poincare.D12.EntropyVariation.hasDerivAt_F_of_pointwise".toName,
  "Poincare.D12.EntropyVariation.fflow_F_hasDerivAt".toName,
  "Poincare.D12.EntropyVariation.fDerivativeStatement_of_corrected_of_idempotent".toName,
  "Poincare.D12.EntropyVariation.fflow_F_hasDerivAt_closedForm".toName,
  "Poincare.D12.EntropyVariation.fflow_F_deriv_pos".toName,
  "Poincare.D12.EntropyVariation.fflow_F_strictMonoOn".toName,
  -- D12-heat-domain-repair
  "Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel".toName,
  "Poincare.D12.HeatDomain.not_fullInitialCondition_flat_of_pos".toName,
  "Poincare.D12.HeatDomain.flatHeatKernelCore_weakInitialConditionFor_integrableClass".toName,
  "Poincare.D12.HeatDomain.flatHeatKernelCore_weakInitialConditionFor_ccClass".toName,
  "Poincare.D12.HeatDomain.toHeatKernelData_of_weak_compact_finiteMeasure".toName,
  -- D12-heat-semigroup-analysis
  "Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator".toName,
  "Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator_of_bounded".toName,
  "Poincare.D12.HeatSemigroup.heatOperatorBCF_comp".toName,
  -- D12-kappa-variational
  "Poincare.D12.KappaVariational.gaussianReducedVolume_eq_one".toName,
  "Poincare.D12.KappaVariational.gaussianReducedVolumeViaL_eq_one".toName,
  "Poincare.D12.KappaVariational.constantCurvatureLMinimizerExistence".toName,
  -- D12-parabolic-local-existence
  "Poincare.D12.ParabolicLocal.gaussianSmap_continuous".toName,
  "Poincare.D12.ParabolicLocal.heatConv_semigroup".toName,
  "Poincare.D12.ParabolicLocal.gaussianS_add".toName,
  "Poincare.D12.ParabolicLocal.heatConv_tendsto_self_BUC".toName,
  "Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds".toName,
  "Poincare.D12.ParabolicLocal.derivativeLossBarrier_discharged".toName,
  -- D12-surgery-recognition
  "Poincare.D12.SurgeryRecognition.ConnectedSumDecomposition.mkV2".toName,
  "Poincare.D12.SurgeryRecognition.deckTrivial_of_simplyConnected_quotient".toName,
  "Poincare.D12.SurgeryRecognition.finiteFreeOrbit_isQuotientCoveringMap".toName,
  "Poincare.D12.SurgeryRecognition.antipodalModel".toName,
  -- D12-triangulation-topology
  "Poincare.D12.TriangulationTopology.coveringOfSimplyConnectedIsHomeo".toName,
  "Poincare.D12.TriangulationTopology.antipodalQuotientCovering".toName,
  "Poincare.D12.TriangulationTopology.diskGlueQuotHomeoSphere".toName,
  "Poincare.D12.TriangulationTopology.sphereOfTwoDisks".toName,
  "Poincare.D12.TriangulationTopology.alexanderHomeo".toName,
  "Poincare.D12.TriangulationTopology.simplexBoundaryHomeoSphere".toName,
  "Poincare.D12.TriangulationTopology.lowerHemisphereHomeoDisk".toName,
  "Poincare.D12.TriangulationTopology.simplexHomeoDisk".toName,
  -- headline negative controls
  "Poincare.D12.SemanticLedger.not_initialCondition_gaussian".toName,
  -- D12-spectral-sobolev
  "Poincare.D12.SpectralSobolev.poincare_wirtinger".toName,
  -- D12-tensor-maximum-bochner (blocked task: partial closures)
  "Poincare.D12.TensorMaximumBochner.kernelTangent_of_feasibleDirection".toName,
  "Poincare.D12.TensorMaximumBochner.hamiltonField_kernelTangent".toName,
  "Poincare.D12.TensorMaximumBochner.adjugate_posSemidef".toName,
  "Poincare.D12.TensorMaximumBochner.kernelTangent_not_feasible".toName,
  -- D12-volume-ibp
  "Poincare.D12.VolumeIBP.ChartMetric.integral_riemannianMeasure_eq".toName
]

/-- Names generated by the equation compiler / structure projection machinery; genuine
consumers are reported separately from these. -/
def isGenerated (n : Name) : Bool :=
  let s := n.toString
  ["._proof_", "._simp_", "._unsafe_rec", ".eq_", ".match_", "._f", "._sunfold",
   "._congr_simp", ".ctorIdx", ".casesOn", ".rec", ".noConfusion", "._flat_ctor",
   ".mk.inj", ".sizeOf", "._sizeOf", "._abel_", "._sparse_", "._elab", "._macro"]
    |>.any (fun p => s.contains p)

/-- Direct users map restricted to declarations *declared in* snapshot-internal modules
(this includes anonymous `example`/`_uniq` declarations, which are genuine kernel-checked
uses even though they are not reusable named theorems). -/
def buildUsers (env : Environment) : Std.HashMap Name (Array Name) := Id.run do
  let mods := env.header.moduleNames
  let isInternal (n : Name) : Bool :=
    match env.getModuleIdxFor? n with
    | some midx => (mods.getD midx .anonymous).toString.contains "Poincare"
    | none => false
  let mut users : Std.HashMap Name (Array Name) := {}
  for (n, ci) in env.constants.toList do
    if !isInternal n then continue
    let used := match ci.value? true with
      | some v => v.getUsedConstants
      | none => ci.type.getUsedConstants
    for u in used do
      if isInternal u then
        users := users.insert u ((users.getD u #[]).push n)
  return users

/-- Transitive reverse closure of `c` in the internal user graph. -/
partial def transUsers (users : Std.HashMap Name (Array Name)) (seen : Array Name)
    (todo : List Name) : Array Name :=
  match todo with
  | [] => seen
  | c :: rest =>
    if seen.contains c then transUsers users seen rest
    else
      let seen := seen.push c
      let next := (users.getD c #[]).toList.filter (fun n => !seen.contains n)
      transUsers users seen (next ++ rest)

end Poincare.D13.IntegratedAudit

open Poincare.D13.IntegratedAudit in
run_cmd do
  let env ← getEnv
  let users := buildUsers env
  for c in keyInputs do
    if (env.find? c).isNone then
      IO.println s!"D13USEMISSING\t{c}"
    else
      let all := transUsers users #[] [c]
      let others := all.filter (fun n => n != c)
      let genuine := others.filter (fun n => !isGenerated n && !n.toString.contains "_example" && !n.toString.contains "_uniq")
      let anon := others.filter (fun n => n.toString.contains "_example" || n.toString.contains "_uniq")
      let sample := (genuine.qsort (fun a b => a.toString < b.toString)).toList.take 6
      IO.println s!"D13USE\t{c}\t{others.size}\t{genuine.size}\t{anon.size}\t{";".intercalate (sample.map Name.toString)}"
