/-
D6-weekly-release — generated ledger/claim probe.

Auto-generated by tools/d6_build_release.py. 262 declarations: every
declaration referenced by the theorem/dependency ledger or named by an accepted D1-D4
result card. Compilation of this file means every claimed declaration resolves in the
D6 release package. Axiom cones are in manifest/verified-declarations.json.
-/

import ReleaseCheck

set_option linter.unusedVariables false

-- D6PROBE D4Audit.audit_certificate_compare
#check @D4Audit.audit_certificate_compare
-- D6PROBE D4Audit.audit_continuous_certificate
#check @D4Audit.audit_continuous_certificate
-- D6PROBE D4Audit.certificate_lower_bound_zero
#check @D4Audit.certificate_lower_bound_zero
-- D6PROBE D4Audit.counterexample_continuous_c_half
#check @D4Audit.counterexample_continuous_c_half
-- D6PROBE D4Audit.counterexample_discrete_c_half
#check @D4Audit.counterexample_discrete_c_half
-- D6PROBE D4Audit.counterexample_negative_step
#check @D4Audit.counterexample_negative_step
-- D6PROBE D4Audit.dissipation_sanity
#check @D4Audit.dissipation_sanity
-- D6PROBE D4Audit.finiteMeshConvergence_nonvacuous
#check @D4Audit.finiteMeshConvergence_nonvacuous
-- D6PROBE D4Audit.gibbsTerm_step_lt_of_one_le
#check @D4Audit.gibbsTerm_step_lt_of_one_le
-- D6PROBE D4Audit.gibbsTerm_strictAnti_of_one_le
#check @D4Audit.gibbsTerm_strictAnti_of_one_le
-- D6PROBE D4Audit.limit_passage_sanity
#check @D4Audit.limit_passage_sanity
-- D6PROBE D4Audit.nonvacuity_main_theorem
#check @D4Audit.nonvacuity_main_theorem
-- D6PROBE D4Audit.nonvacuity_main_theorem_strict
#check @D4Audit.nonvacuity_main_theorem_strict
-- D6PROBE D4Audit.perelmanApproximation_nonvacuous
#check @D4Audit.perelmanApproximation_nonvacuous
-- D6PROBE D4Audit.perelmanF_nonneg_sharp
#check @D4Audit.perelmanF_nonneg_sharp
-- D6PROBE D4Audit.perelmanF_step_lt_of_one_le
#check @D4Audit.perelmanF_step_lt_of_one_le
-- D6PROBE D4Audit.strict_step_needs_pos_reaction
#check @D4Audit.strict_step_needs_pos_reaction
-- D6PROBE D4Audit.strict_step_needs_pos_step
#check @D4Audit.strict_step_needs_pos_step
-- D6PROBE D4Audit.transfer_nonvacuous
#check @D4Audit.transfer_nonvacuous
-- D6PROBE Perelman.CurvatureBoundedOn
#check @Perelman.CurvatureBoundedOn
-- D6PROBE Perelman.CurvatureBoundedOn.mono
#check @Perelman.CurvatureBoundedOn.mono
-- D6PROBE Perelman.FMonotonicity
#check @Perelman.FMonotonicity
-- D6PROBE Perelman.FMonotonicity.apply
#check @Perelman.FMonotonicity.apply
-- D6PROBE Perelman.FMonotonicity_iff_antitoneOn
#check @Perelman.FMonotonicity_iff_antitoneOn
-- D6PROBE Perelman.FProfile
#check @Perelman.FProfile
-- D6PROBE Perelman.HasFrameVolumeDensity
#check @Perelman.HasFrameVolumeDensity
-- D6PROBE Perelman.HasMetricTimeDerivative
#check @Perelman.HasMetricTimeDerivative
-- D6PROBE Perelman.HasUnitMass
#check @Perelman.HasUnitMass
-- D6PROBE Perelman.IsScalarCurvature
#check @Perelman.IsScalarCurvature
-- D6PROBE Perelman.KappaNoncollapsing
#check @Perelman.KappaNoncollapsing
-- D6PROBE Perelman.MetricFamily
#check @Perelman.MetricFamily
-- D6PROBE Perelman.MetricFlowData
#check @Perelman.MetricFlowData
-- D6PROBE Perelman.MetricFlowData.Icc_subset
#check @Perelman.MetricFlowData.Icc_subset
-- D6PROBE Perelman.MuMonotonicity
#check @Perelman.MuMonotonicity
-- D6PROBE Perelman.MuMonotonicity.apply
#check @Perelman.MuMonotonicity.apply
-- D6PROBE Perelman.RicciFamily
#check @Perelman.RicciFamily
-- D6PROBE Perelman.RicciLowerBound
#check @Perelman.RicciLowerBound
-- D6PROBE Perelman.RicciTensor
#check @Perelman.RicciTensor
-- D6PROBE Perelman.RiemannianVolumePredicate
#check @Perelman.RiemannianVolumePredicate
-- D6PROBE Perelman.ScalarCurvatureData
#check @Perelman.ScalarCurvatureData
-- D6PROBE Perelman.ScalarCurvatureLowerBound
#check @Perelman.ScalarCurvatureLowerBound
-- D6PROBE Perelman.VolumeFormData
#check @Perelman.VolumeFormData
-- D6PROBE Perelman.WMonotonicity
#check @Perelman.WMonotonicity
-- D6PROBE Perelman.WMonotonicity.apply
#check @Perelman.WMonotonicity.apply
-- D6PROBE Perelman.WMonotonicity_iff_antitoneOn
#check @Perelman.WMonotonicity_iff_antitoneOn
-- D6PROBE Perelman.WProfile
#check @Perelman.WProfile
-- D6PROBE Perelman.constantFlow
#check @Perelman.constantFlow
-- D6PROBE Perelman.directionalDerivative
#check @Perelman.directionalDerivative
-- D6PROBE Perelman.gradientNormSqInBasis
#check @Perelman.gradientNormSqInBasis
-- D6PROBE Perelman.gramMatrix
#check @Perelman.gramMatrix
-- D6PROBE Perelman.hasMetricTimeDerivative_const
#check @Perelman.hasMetricTimeDerivative_const
-- D6PROBE Perelman.negTwoRicci
#check @Perelman.negTwoRicci
-- D6PROBE Perelman.perelmanF
#check @Perelman.perelmanF
-- D6PROBE Perelman.perelmanMu
#check @Perelman.perelmanMu
-- D6PROBE Perelman.perelmanMu_le
#check @Perelman.perelmanMu_le
-- D6PROBE Perelman.perelmanW
#check @Perelman.perelmanW
-- D6PROBE Perelman.riemannianVolumeDensity
#check @Perelman.riemannianVolumeDensity
-- D6PROBE Perelman.riemannianVolumeDensity_nonneg
#check @Perelman.riemannianVolumeDensity_nonneg
-- D6PROBE Perelman.riemannianVolumeDensity_pos_of_posDef
#check @Perelman.riemannianVolumeDensity_pos_of_posDef
-- D6PROBE Perelman.satisfies_ricciFlow_const_zero
#check @Perelman.satisfies_ricciFlow_const_zero
-- D6PROBE Perelman.scalarCurvatureInBasis
#check @Perelman.scalarCurvatureInBasis
-- D6PROBE Perelman.toyF
#check @Perelman.toyF
-- D6PROBE Perelman.toyF_mono
#check @Perelman.toyF_mono
-- D6PROBE Perelman.toyW
#check @Perelman.toyW
-- D6PROBE Perelman.toyW_nonneg
#check @Perelman.toyW_nonneg
-- D6PROBE Poincare.CurvatureAlgebra.CurvatureOperator.ricci
#check @Poincare.CurvatureAlgebra.CurvatureOperator.ricci
-- D6PROBE Poincare.CurvatureAlgebra.CurvatureOperator.ricci_add
#check @Poincare.CurvatureAlgebra.CurvatureOperator.ricci_add
-- D6PROBE Poincare.CurvatureAlgebra.CurvatureOperator.ricci_smul
#check @Poincare.CurvatureAlgebra.CurvatureOperator.ricci_smul
-- D6PROBE Poincare.CurvatureAlgebra.CurvatureOperator.scalarCurvature
#check @Poincare.CurvatureAlgebra.CurvatureOperator.scalarCurvature
-- D6PROBE Poincare.CurvatureAlgebra.CurvatureOperator.scalarCurvature_add
#check @Poincare.CurvatureAlgebra.CurvatureOperator.scalarCurvature_add
-- D6PROBE Poincare.CurvatureAlgebra.CurvatureOperator.scalarCurvature_smul
#check @Poincare.CurvatureAlgebra.CurvatureOperator.scalarCurvature_smul
-- D6PROBE Poincare.Longrun.CurvatureODE.ManifoldCurvatureRealization
#check @Poincare.Longrun.CurvatureODE.ManifoldCurvatureRealization
-- D6PROBE Poincare.Longrun.CurvatureODE.MetricCurvatureShadow
#check @Poincare.Longrun.CurvatureODE.MetricCurvatureShadow
-- D6PROBE Poincare.Longrun.CurvatureODE.MetricFamilySolvesRicciFlow
#check @Poincare.Longrun.CurvatureODE.MetricFamilySolvesRicciFlow
-- D6PROBE Poincare.Longrun.CurvatureODE.TensorRicciFlowODEBridge
#check @Poincare.Longrun.CurvatureODE.TensorRicciFlowODEBridge
-- D6PROBE Poincare.Longrun.CurvatureODE.TensorRicciFlowODERealization
#check @Poincare.Longrun.CurvatureODE.TensorRicciFlowODERealization
-- D6PROBE Poincare.Longrun.CurvatureODE.bridge_state_eq_ricciDiagonal
#check @Poincare.Longrun.CurvatureODE.bridge_state_eq_ricciDiagonal
-- D6PROBE Poincare.Longrun.CurvatureODE.component_monotone
#check @Poincare.Longrun.CurvatureODE.component_monotone
-- D6PROBE Poincare.Longrun.CurvatureODE.evolutionRelation_of_bridge
#check @Poincare.Longrun.CurvatureODE.evolutionRelation_of_bridge
-- D6PROBE Poincare.Longrun.CurvatureODE.nonneg_orthant_invariant
#check @Poincare.Longrun.CurvatureODE.nonneg_orthant_invariant
-- D6PROBE Poincare.Longrun.CurvatureODE.nonneg_orthant_invariant_discrete
#check @Poincare.Longrun.CurvatureODE.nonneg_orthant_invariant_discrete
-- D6PROBE Poincare.Longrun.CurvatureODE.ricciDiagonal_nonneg_of_bridge
#check @Poincare.Longrun.CurvatureODE.ricciDiagonal_nonneg_of_bridge
-- D6PROBE Poincare.Longrun.CurvatureODE.scalarCurvature_monotone_of_bridge
#check @Poincare.Longrun.CurvatureODE.scalarCurvature_monotone_of_bridge
-- D6PROBE Poincare.Longrun.CurvatureODE.scalarFunctional_monotone
#check @Poincare.Longrun.CurvatureODE.scalarFunctional_monotone
-- D6PROBE Poincare.Longrun.CurvatureODE.scalarFunctional_monotone_discrete
#check @Poincare.Longrun.CurvatureODE.scalarFunctional_monotone_discrete
-- D6PROBE Poincare.Longrun.CurvatureODE.scalarOfState_monotone
#check @Poincare.Longrun.CurvatureODE.scalarOfState_monotone
-- D6PROBE Poincare.Longrun.CurvatureODE.scalarOfState_monotone_discrete
#check @Poincare.Longrun.CurvatureODE.scalarOfState_monotone_discrete
-- D6PROBE Poincare.Longrun.CurvatureODE.zero_orthant_invariant
#check @Poincare.Longrun.CurvatureODE.zero_orthant_invariant
-- D6PROBE Poincare.Longrun.CurvatureODE.zero_scalar_monotone
#check @Poincare.Longrun.CurvatureODE.zero_scalar_monotone
-- D6PROBE Poincare.Longrun.Entropy.AntitoneCertificate.F_le_of_le
#check @Poincare.Longrun.Entropy.AntitoneCertificate.F_le_of_le
-- D6PROBE Poincare.Longrun.Entropy.AntitoneCertificate.mono
#check @Poincare.Longrun.Entropy.AntitoneCertificate.mono
-- D6PROBE Poincare.Longrun.Entropy.ContinuousAntitoneCertificate.antitoneOn
#check @Poincare.Longrun.Entropy.ContinuousAntitoneCertificate.antitoneOn
-- D6PROBE Poincare.Longrun.Entropy.ContinuousAntitoneCertificate.dissipation_nonpos
#check @Poincare.Longrun.Entropy.ContinuousAntitoneCertificate.dissipation_nonpos
-- D6PROBE Poincare.Longrun.Entropy.ContinuousAntitoneCertificate.hasDerivAt_F
#check @Poincare.Longrun.Entropy.ContinuousAntitoneCertificate.hasDerivAt_F
-- D6PROBE Poincare.Longrun.Entropy.EntropyData.F
#check @Poincare.Longrun.Entropy.EntropyData.F
-- D6PROBE Poincare.Longrun.Entropy.EntropyData.FDissipation_nonneg
#check @Poincare.Longrun.Entropy.EntropyData.FDissipation_nonneg
-- D6PROBE Poincare.Longrun.Entropy.EntropyData.F_mono_integrand
#check @Poincare.Longrun.Entropy.EntropyData.F_mono_integrand
-- D6PROBE Poincare.Longrun.Entropy.EntropyData.W
#check @Poincare.Longrun.Entropy.EntropyData.W
-- D6PROBE Poincare.Longrun.Entropy.EntropyData.conjugateWeight_pos
#check @Poincare.Longrun.Entropy.EntropyData.conjugateWeight_pos
-- D6PROBE Poincare.Longrun.Entropy.EntropyData.integrable_F
#check @Poincare.Longrun.Entropy.EntropyData.integrable_F
-- D6PROBE Poincare.Longrun.Entropy.EntropyData.integrable_W
#check @Poincare.Longrun.Entropy.EntropyData.integrable_W
-- D6PROBE Poincare.Longrun.Entropy.EntropyData.ρ_nonneg
#check @Poincare.Longrun.Entropy.EntropyData.ρ_nonneg
-- D6PROBE Poincare.Longrun.Entropy.EntropyData.τ_pos
#check @Poincare.Longrun.Entropy.EntropyData.τ_pos
-- D6PROBE Poincare.Longrun.Entropy.LinearDecayCertificate.decay
#check @Poincare.Longrun.Entropy.LinearDecayCertificate.decay
-- D6PROBE Poincare.Longrun.Entropy.LinearDecayCertificate.rate_pos
#check @Poincare.Longrun.Entropy.LinearDecayCertificate.rate_pos
-- D6PROBE Poincare.Longrun.Entropy.MonotoneCertificate.mono
#check @Poincare.Longrun.Entropy.MonotoneCertificate.mono
-- D6PROBE Poincare.Longrun.Entropy.continuousMonotoneCertificateOfBridge
#check @Poincare.Longrun.Entropy.continuousMonotoneCertificateOfBridge
-- D6PROBE Poincare.Longrun.Entropy.entropyRegularityBridge_zero
#check @Poincare.Longrun.Entropy.entropyRegularityBridge_zero
-- D6PROBE Poincare.Longrun.Entropy.finiteCurvatureDatum_F
#check @Poincare.Longrun.Entropy.finiteCurvatureDatum_F
-- D6PROBE Poincare.Longrun.Entropy.finiteCurvatureDatum_W
#check @Poincare.Longrun.Entropy.finiteCurvatureDatum_W
-- D6PROBE Poincare.Longrun.Entropy.heatEnergyCertificate_zero
#check @Poincare.Longrun.Entropy.heatEnergyCertificate_zero
-- D6PROBE Poincare.Longrun.Entropy.heatEnergy_le_initial
#check @Poincare.Longrun.Entropy.heatEnergy_le_initial
-- D6PROBE Poincare.Longrun.Entropy.heatEnergy_nonneg
#check @Poincare.Longrun.Entropy.heatEnergy_nonneg
-- D6PROBE Poincare.Longrun.Evolution.continuousPerelmanCertificate
#check @Poincare.Longrun.Evolution.continuousPerelmanCertificate
-- D6PROBE Poincare.Longrun.Evolution.continuousPerelmanFMonotone_of_approximation
#check @Poincare.Longrun.Evolution.continuousPerelmanFMonotone_of_approximation
-- D6PROBE Poincare.Longrun.Evolution.finiteReactionEntropyData_F
#check @Poincare.Longrun.Evolution.finiteReactionEntropyData_F
-- D6PROBE Poincare.Longrun.Evolution.gibbsTerm_step_lt
#check @Poincare.Longrun.Evolution.gibbsTerm_step_lt
-- D6PROBE Poincare.Longrun.Evolution.gibbsTerm_strictAnti
#check @Poincare.Longrun.Evolution.gibbsTerm_strictAnti
-- D6PROBE Poincare.Longrun.Evolution.hasDerivWithinAt_perelmanF
#check @Poincare.Longrun.Evolution.hasDerivWithinAt_perelmanF
-- D6PROBE Poincare.Longrun.Evolution.perelmanAntitoneCertificate
#check @Poincare.Longrun.Evolution.perelmanAntitoneCertificate
-- D6PROBE Poincare.Longrun.Evolution.perelmanAntitoneCertificate_discrete
#check @Poincare.Longrun.Evolution.perelmanAntitoneCertificate_discrete
-- D6PROBE Poincare.Longrun.Evolution.perelmanF_antitone
#check @Poincare.Longrun.Evolution.perelmanF_antitone
-- D6PROBE Poincare.Longrun.Evolution.perelmanF_antitone_discrete
#check @Poincare.Longrun.Evolution.perelmanF_antitone_discrete
-- D6PROBE Poincare.Longrun.Evolution.perelmanF_monotone_of_tensorBridge
#check @Poincare.Longrun.Evolution.perelmanF_monotone_of_tensorBridge
-- D6PROBE Poincare.Longrun.Evolution.perelmanF_step_lt
#check @Poincare.Longrun.Evolution.perelmanF_step_lt
-- D6PROBE Poincare.Longrun.Geometry.AbstractConnection.curvature_bianchi
#check @Poincare.Longrun.Geometry.AbstractConnection.curvature_bianchi
-- D6PROBE Poincare.Longrun.Geometry.AbstractConnection.curvature_cyclic_decomp
#check @Poincare.Longrun.Geometry.AbstractConnection.curvature_cyclic_decomp
-- D6PROBE Poincare.Longrun.Geometry.AbstractConnection.curvature_skew
#check @Poincare.Longrun.Geometry.AbstractConnection.curvature_skew
-- D6PROBE Poincare.Longrun.Geometry.AbstractConnection.toCurvatureOperator
#check @Poincare.Longrun.Geometry.AbstractConnection.toCurvatureOperator
-- D6PROBE Poincare.Longrun.Geometry.CovariantDerivativeCurvatureStatement
#check @Poincare.Longrun.Geometry.CovariantDerivativeCurvatureStatement
-- D6PROBE Poincare.Longrun.Geometry.LeviCivitaExistenceStatement
#check @Poincare.Longrun.Geometry.LeviCivitaExistenceStatement
-- D6PROBE Poincare.Longrun.Geometry.LieBracketData.jacobi_reverse
#check @Poincare.Longrun.Geometry.LieBracketData.jacobi_reverse
-- D6PROBE Poincare.Longrun.Geometry.MetricData.form_raiseIndex
#check @Poincare.Longrun.Geometry.MetricData.form_raiseIndex
-- D6PROBE Poincare.Longrun.Geometry.MetricData.scalarCurvature_eq_sum_basis
#check @Poincare.Longrun.Geometry.MetricData.scalarCurvature_eq_sum_basis
-- D6PROBE Poincare.Longrun.Geometry.curvatureForm
#check @Poincare.Longrun.Geometry.curvatureForm
-- D6PROBE Poincare.Longrun.Geometry.curvatureForm_first_bianchi
#check @Poincare.Longrun.Geometry.curvatureForm_first_bianchi
-- D6PROBE Poincare.Longrun.Geometry.curvatureForm_first_pair_skew
#check @Poincare.Longrun.Geometry.curvatureForm_first_pair_skew
-- D6PROBE Poincare.Longrun.Geometry.leviCivitaExistence_iff_nonempty
#check @Poincare.Longrun.Geometry.leviCivitaExistence_iff_nonempty
-- D6PROBE Poincare.Longrun.Geometry.leviCivita_nabla_unique
#check @Poincare.Longrun.Geometry.leviCivita_nabla_unique
-- D6PROBE Poincare.Longrun.Geometry.meanConnection_isMetricCompatible_iff
#check @Poincare.Longrun.Geometry.meanConnection_isMetricCompatible_iff
-- D6PROBE Poincare.Longrun.Geometry.mean_curvature_apply
#check @Poincare.Longrun.Geometry.mean_curvature_apply
-- D6PROBE Poincare.Longrun.Geometry.mean_endoRicci
#check @Poincare.Longrun.Geometry.mean_endoRicci
-- D6PROBE Poincare.Longrun.Geometry.mean_ricci_comm
#check @Poincare.Longrun.Geometry.mean_ricci_comm
-- D6PROBE Poincare.Longrun.PDE.ContinuousHeatHypotheses
#check @Poincare.Longrun.PDE.ContinuousHeatHypotheses
-- D6PROBE Poincare.Longrun.PDE.ContinuousHeatMaximumPrincipleInterface
#check @Poincare.Longrun.PDE.ContinuousHeatMaximumPrincipleInterface
-- D6PROBE Poincare.Longrun.PDE.HeatGridEvolution
#check @Poincare.Longrun.PDE.HeatGridEvolution
-- D6PROBE Poincare.Longrun.PDE.HeatGridEvolution.energy_nonincreasing
#check @Poincare.Longrun.PDE.HeatGridEvolution.energy_nonincreasing
-- D6PROBE Poincare.Longrun.PDE.HeatGridEvolution.le_of_initial_le
#check @Poincare.Longrun.PDE.HeatGridEvolution.le_of_initial_le
-- D6PROBE Poincare.Longrun.PDE.HeatGridEvolution.le_sup'_initial
#check @Poincare.Longrun.PDE.HeatGridEvolution.le_sup'_initial
-- D6PROBE Poincare.Longrun.PDE.HeatGridEvolution.succ_le
#check @Poincare.Longrun.PDE.HeatGridEvolution.succ_le
-- D6PROBE Poincare.Longrun.PDE.continuousHeatHypotheses_affine
#check @Poincare.Longrun.PDE.continuousHeatHypotheses_affine
-- D6PROBE Poincare.Longrun.PDE.continuousHeatHypotheses_quadratic
#check @Poincare.Longrun.PDE.continuousHeatHypotheses_quadratic
-- D6PROBE Poincare.Longrun.PDE.continuousHeatHypotheses_zero
#check @Poincare.Longrun.PDE.continuousHeatHypotheses_zero
-- D6PROBE Poincare.Longrun.PDE.continuousHeatMaxPrinciple_affine
#check @Poincare.Longrun.PDE.continuousHeatMaxPrinciple_affine
-- D6PROBE Poincare.Longrun.PDE.continuousHeatMaxPrinciple_of_timeIndependent
#check @Poincare.Longrun.PDE.continuousHeatMaxPrinciple_of_timeIndependent
-- D6PROBE Poincare.Longrun.PDE.continuousHeatMaxPrinciple_quadratic
#check @Poincare.Longrun.PDE.continuousHeatMaxPrinciple_quadratic
-- D6PROBE Poincare.Longrun.PDE.continuousHeatMaxPrinciple_zero
#check @Poincare.Longrun.PDE.continuousHeatMaxPrinciple_zero
-- D6PROBE Poincare.Longrun.PDE.convex_combo_sq_le
#check @Poincare.Longrun.PDE.convex_combo_sq_le
-- D6PROBE Poincare.Longrun.PDE.energy_heatStep_le
#check @Poincare.Longrun.PDE.energy_heatStep_le
-- D6PROBE Poincare.Longrun.PDE.energy_nonneg
#check @Poincare.Longrun.PDE.energy_nonneg
-- D6PROBE Poincare.Longrun.PDE.energy_step_le
#check @Poincare.Longrun.PDE.energy_step_le
-- D6PROBE Poincare.Longrun.PDE.heatStep_le
#check @Poincare.Longrun.PDE.heatStep_le
-- D6PROBE Poincare.Longrun.PDE.heatStep_sq_le
#check @Poincare.Longrun.PDE.heatStep_sq_le
-- D6PROBE Poincare.Longrun.PDE.strict_grid_max_principle
#check @Poincare.Longrun.PDE.strict_grid_max_principle
-- D6PROBE Poincare.Longrun.PDE.strict_grid_max_principle_max
#check @Poincare.Longrun.PDE.strict_grid_max_principle_max
-- D6PROBE Poincare.Longrun.PDE.sum_shift_pred
#check @Poincare.Longrun.PDE.sum_shift_pred
-- D6PROBE Poincare.Longrun.PDE.sum_shift_succ
#check @Poincare.Longrun.PDE.sum_shift_succ
-- D6PROBE Poincare.Longrun.Surgery.ChainCertificate.append
#check @Poincare.Longrun.Surgery.ChainCertificate.append
-- D6PROBE Poincare.Longrun.Surgery.ChainCertificate.compact_preserved
#check @Poincare.Longrun.Surgery.ChainCertificate.compact_preserved
-- D6PROBE Poincare.Longrun.Surgery.ChainCertificate.orientable_preserved
#check @Poincare.Longrun.Surgery.ChainCertificate.orientable_preserved
-- D6PROBE Poincare.Longrun.Surgery.ChainCertificate.preservation
#check @Poincare.Longrun.Surgery.ChainCertificate.preservation
-- D6PROBE Poincare.Longrun.Surgery.ChainCertificate.simplyConnected_preserved
#check @Poincare.Longrun.Surgery.ChainCertificate.simplyConnected_preserved
-- D6PROBE Poincare.Longrun.Surgery.ExtinctionTheorem
#check @Poincare.Longrun.Surgery.ExtinctionTheorem
-- D6PROBE Poincare.Longrun.Surgery.ExtinctionTheorem.extincts_of_complexity
#check @Poincare.Longrun.Surgery.ExtinctionTheorem.extincts_of_complexity
-- D6PROBE Poincare.Longrun.Surgery.ExtinctionTheorem.finitelyMany_of_complexity
#check @Poincare.Longrun.Surgery.ExtinctionTheorem.finitelyMany_of_complexity
-- D6PROBE Poincare.Longrun.Surgery.ExtinctionTheorem.terminalSphere_of_complexity
#check @Poincare.Longrun.Surgery.ExtinctionTheorem.terminalSphere_of_complexity
-- D6PROBE Poincare.Longrun.Surgery.LedgerPredicates
#check @Poincare.Longrun.Surgery.LedgerPredicates
-- D6PROBE Poincare.Longrun.Surgery.MissingInputs
#check @Poincare.Longrun.Surgery.MissingInputs
-- D6PROBE Poincare.Longrun.Surgery.NeckAnalysis
#check @Poincare.Longrun.Surgery.NeckAnalysis
-- D6PROBE Poincare.Longrun.Surgery.NeckAnalysis.admissible_of_highCurvature
#check @Poincare.Longrun.Surgery.NeckAnalysis.admissible_of_highCurvature
-- D6PROBE Poincare.Longrun.Surgery.NeckAnalysis.certificate
#check @Poincare.Longrun.Surgery.NeckAnalysis.certificate
-- D6PROBE Poincare.Longrun.Surgery.NeckAnalysis.deltaNeck_of_highCurvature
#check @Poincare.Longrun.Surgery.NeckAnalysis.deltaNeck_of_highCurvature
-- D6PROBE Poincare.Longrun.Surgery.NeckAnalysis.realizes_of_highCurvature
#check @Poincare.Longrun.Surgery.NeckAnalysis.realizes_of_highCurvature
-- D6PROBE Poincare.Longrun.Surgery.NeckAnalysis.target_preserved_of_highCurvature
#check @Poincare.Longrun.Surgery.NeckAnalysis.target_preserved_of_highCurvature
-- D6PROBE Poincare.Longrun.Surgery.SurgeryCertificate
#check @Poincare.Longrun.Surgery.SurgeryCertificate
-- D6PROBE Poincare.Longrun.Surgery.SurgeryCertificate.ofHomeomorph
#check @Poincare.Longrun.Surgery.SurgeryCertificate.ofHomeomorph
-- D6PROBE Poincare.Longrun.Surgery.SurgeryCertificate.ofHomotopyEquiv
#check @Poincare.Longrun.Surgery.SurgeryCertificate.ofHomotopyEquiv
-- D6PROBE Poincare.Longrun.Surgery.SurgeryCertificate.trivial
#check @Poincare.Longrun.Surgery.SurgeryCertificate.trivial
-- D6PROBE Poincare.Longrun.Surgery.SurgeryDatum
#check @Poincare.Longrun.Surgery.SurgeryDatum
-- D6PROBE Poincare.Longrun.Surgery.SurgeryDatum.post
#check @Poincare.Longrun.Surgery.SurgeryDatum.post
-- D6PROBE Poincare.Longrun.Surgery.SurgeryDatum.pre
#check @Poincare.Longrun.Surgery.SurgeryDatum.pre
-- D6PROBE Poincare.Longrun.Surgery.ToyChain.le
#check @Poincare.Longrun.Surgery.ToyChain.le
-- D6PROBE Poincare.Longrun.Surgery.ToyChain.no_infinite
#check @Poincare.Longrun.Surgery.ToyChain.no_infinite
-- D6PROBE Poincare.Longrun.Surgery.ToyChain.reflTransGen
#check @Poincare.Longrun.Surgery.ToyChain.reflTransGen
-- D6PROBE Poincare.Longrun.Surgery.ToyChain.value
#check @Poincare.Longrun.Surgery.ToyChain.value
-- D6PROBE Poincare.Longrun.Surgery.ToyRel
#check @Poincare.Longrun.Surgery.ToyRel
-- D6PROBE Poincare.Longrun.Surgery.canonicalLedger
#check @Poincare.Longrun.Surgery.canonicalLedger
-- D6PROBE Poincare.Longrun.Surgery.extincts_and_target
#check @Poincare.Longrun.Surgery.extincts_and_target
-- D6PROBE Poincare.Longrun.Surgery.toyCertificate
#check @Poincare.Longrun.Surgery.toyCertificate
-- D6PROBE Poincare.Longrun.Surgery.toyChain321_compact
#check @Poincare.Longrun.Surgery.toyChain321_compact
-- D6PROBE Poincare.Longrun.Surgery.toyChain321_preserves
#check @Poincare.Longrun.Surgery.toyChain321_preserves
-- D6PROBE Poincare.Longrun.Surgery.toyRel_functional
#check @Poincare.Longrun.Surgery.toyRel_functional
-- D6PROBE Poincare.Longrun.Surgery.toyRel_lt
#check @Poincare.Longrun.Surgery.toyRel_lt
-- D6PROBE Poincare.Longrun.Surgery.toyRel_nonempty
#check @Poincare.Longrun.Surgery.toyRel_nonempty
-- D6PROBE Poincare.Longrun.Surgery.toyRel_not_refl
#check @Poincare.Longrun.Surgery.toyRel_not_refl
-- D6PROBE Poincare.Longrun.Surgery.toyRel_odd_iff
#check @Poincare.Longrun.Surgery.toyRel_odd_iff
-- D6PROBE Poincare.Longrun.Surgery.toyRel_succ
#check @Poincare.Longrun.Surgery.toyRel_succ
-- D6PROBE Poincare.Longrun.Surgery.toy_extinction_skeleton
#check @Poincare.Longrun.Surgery.toy_extinction_skeleton
-- D6PROBE Poincare.Longrun.Topology.CompactThreeManifold.exists_finite_chart_cover
#check @Poincare.Longrun.Topology.CompactThreeManifold.exists_finite_chart_cover
-- D6PROBE Poincare.Longrun.Topology.CompactThreeManifold.exists_mem_chart_source
#check @Poincare.Longrun.Topology.CompactThreeManifold.exists_mem_chart_source
-- D6PROBE Poincare.Longrun.Topology.CompactThreeManifold.toLocallyCompactSpace
#check @Poincare.Longrun.Topology.CompactThreeManifold.toLocallyCompactSpace
-- D6PROBE Poincare.Longrun.Topology.CompactThreeManifold.toParacompactSpace
#check @Poincare.Longrun.Topology.CompactThreeManifold.toParacompactSpace
-- D6PROBE Poincare.Longrun.Topology.CompactThreeManifold.toSecondCountableTopology
#check @Poincare.Longrun.Topology.CompactThreeManifold.toSecondCountableTopology
-- D6PROBE Poincare.Longrun.Topology.CompactThreeManifold.toSigmaCompactSpace
#check @Poincare.Longrun.Topology.CompactThreeManifold.toSigmaCompactSpace
-- D6PROBE Poincare.Longrun.Topology.CompactThreeManifold.toTopologicalManifold
#check @Poincare.Longrun.Topology.CompactThreeManifold.toTopologicalManifold
-- D6PROBE Poincare.Longrun.Topology.KappaNoncollapsingCertificate.apply
#check @Poincare.Longrun.Topology.KappaNoncollapsingCertificate.apply
-- D6PROBE Poincare.Longrun.Topology.KappaNoncollapsingCertificate.exists_uniform_unit_ball_lower_bound
#check @Poincare.Longrun.Topology.KappaNoncollapsingCertificate.exists_uniform_unit_ball_lower_bound
-- D6PROBE Poincare.Longrun.Topology.KappaNoncollapsingCertificate.mono
#check @Poincare.Longrun.Topology.KappaNoncollapsingCertificate.mono
-- D6PROBE Poincare.Longrun.Topology.KappaNoncollapsingCertificate.toNormalizedBallVolumeLowerBound
#check @Poincare.Longrun.Topology.KappaNoncollapsingCertificate.toNormalizedBallVolumeLowerBound
-- D6PROBE Poincare.Longrun.Topology.KappaNoncollapsingCertificate.volume_ball_ne_zero
#check @Poincare.Longrun.Topology.KappaNoncollapsingCertificate.volume_ball_ne_zero
-- D6PROBE Poincare.Longrun.Topology.KappaNoncollapsingCertificate.volume_ball_pos
#check @Poincare.Longrun.Topology.KappaNoncollapsingCertificate.volume_ball_pos
-- D6PROBE Poincare.Longrun.Topology.KappaNoncollapsingCertificate.volume_unit_ball_lower
#check @Poincare.Longrun.Topology.KappaNoncollapsingCertificate.volume_unit_ball_lower
-- D6PROBE Poincare.Longrun.Topology.NormalizedBallVolumeLowerBound.mono
#check @Poincare.Longrun.Topology.NormalizedBallVolumeLowerBound.mono
-- D6PROBE Poincare.Longrun.Topology.NormalizedBallVolumeLowerBound.toKappaNoncollapsingCertificate
#check @Poincare.Longrun.Topology.NormalizedBallVolumeLowerBound.toKappaNoncollapsingCertificate
-- D6PROBE Poincare.Longrun.Topology.NormalizedBallVolumeLowerBound.unit_ball_lower
#check @Poincare.Longrun.Topology.NormalizedBallVolumeLowerBound.unit_ball_lower
-- D6PROBE Poincare.Longrun.Topology.NormalizedBallVolumeLowerBound.volume_ball_pos
#check @Poincare.Longrun.Topology.NormalizedBallVolumeLowerBound.volume_ball_pos
-- D6PROBE Poincare.Longrun.Topology.NormalizedVolumeLowerBound.add
#check @Poincare.Longrun.Topology.NormalizedVolumeLowerBound.add
-- D6PROBE Poincare.Longrun.Topology.NormalizedVolumeLowerBound.apply
#check @Poincare.Longrun.Topology.NormalizedVolumeLowerBound.apply
-- D6PROBE Poincare.Longrun.Topology.NormalizedVolumeLowerBound.bddBelow_range
#check @Poincare.Longrun.Topology.NormalizedVolumeLowerBound.bddBelow_range
-- D6PROBE Poincare.Longrun.Topology.NormalizedVolumeLowerBound.const_iff
#check @Poincare.Longrun.Topology.NormalizedVolumeLowerBound.const_iff
-- D6PROBE Poincare.Longrun.Topology.NormalizedVolumeLowerBound.exists_lower_bound
#check @Poincare.Longrun.Topology.NormalizedVolumeLowerBound.exists_lower_bound
-- D6PROBE Poincare.Longrun.Topology.NormalizedVolumeLowerBound.mono
#check @Poincare.Longrun.Topology.NormalizedVolumeLowerBound.mono
-- D6PROBE Poincare.Longrun.Topology.NormalizedVolumeLowerBound.nonneg
#check @Poincare.Longrun.Topology.NormalizedVolumeLowerBound.nonneg
-- D6PROBE Poincare.Longrun.Topology.NormalizedVolumeLowerBound.pos
#check @Poincare.Longrun.Topology.NormalizedVolumeLowerBound.pos
-- D6PROBE Poincare.Longrun.Topology.NormalizedVolumeLowerBound.smul
#check @Poincare.Longrun.Topology.NormalizedVolumeLowerBound.smul
-- D6PROBE Poincare.Longrun.Topology.kappaNoncollapsingCertificate_iff_normalizedBallVolumeLowerBound
#check @Poincare.Longrun.Topology.kappaNoncollapsingCertificate_iff_normalizedBallVolumeLowerBound
-- D6PROBE Poincare.Longrun.Topology.normalizedBallVolume_nonneg
#check @Poincare.Longrun.Topology.normalizedBallVolume_nonneg
-- D6PROBE Probe.CurvatureTensor
#check @Probe.CurvatureTensor
-- D6PROBE Probe.CurvatureTensor.antisymm
#check @Probe.CurvatureTensor.antisymm
-- D6PROBE Probe.CurvatureTensor.bianchi
#check @Probe.CurvatureTensor.bianchi
-- D6PROBE Probe.CurvatureTensor.bianchi_toy
#check @Probe.CurvatureTensor.bianchi_toy
-- D6PROBE Probe.CurvatureTensor.endo
#check @Probe.CurvatureTensor.endo
-- D6PROBE Probe.CurvatureTensor.ricci
#check @Probe.CurvatureTensor.ricci
-- D6PROBE Probe.CurvatureTensor.ricci_add_toy
#check @Probe.CurvatureTensor.ricci_add_toy
-- D6PROBE Probe.CurvatureTensor.ricci_zero_toy
#check @Probe.CurvatureTensor.ricci_zero_toy
-- D6PROBE Probe.CurvatureTensor.self_eq_zero
#check @Probe.CurvatureTensor.self_eq_zero
-- D6PROBE Probe.CurvatureTensor.zero
#check @Probe.CurvatureTensor.zero
-- D6PROBE Probe.PdeApi.HeatSlabMaximumPrincipleInterface
#check @Probe.PdeApi.HeatSlabMaximumPrincipleInterface
-- D6PROBE Probe.PdeApi.continuousOn_Icc_exists_max
#check @Probe.PdeApi.continuousOn_Icc_exists_max
-- D6PROBE Probe.PdeApi.deriv_sq
#check @Probe.PdeApi.deriv_sq
-- D6PROBE Probe.PdeApi.discreteLaplacian_affine
#check @Probe.PdeApi.discreteLaplacian_affine
-- D6PROBE Probe.PdeApi.heat_slab_affine_interface
#check @Probe.PdeApi.heat_slab_affine_interface
-- D6PROBE Probe.PdeApi.heat_slab_nonpos_of_interface
#check @Probe.PdeApi.heat_slab_nonpos_of_interface
-- D6PROBE Probe.PdeApi.heat_slab_zero_interface
#check @Probe.PdeApi.heat_slab_zero_interface
-- D6PROBE Probe.PdeApi.iteratedDeriv_two_cube
#check @Probe.PdeApi.iteratedDeriv_two_cube
-- D6PROBE Probe.PdeApi.strict_finite_grid_max_principle
#check @Probe.PdeApi.strict_finite_grid_max_principle
-- D6PROBE Probe.PdeApi.strict_finite_grid_max_principle_max
#check @Probe.PdeApi.strict_finite_grid_max_principle_max
-- D6PROBE Probe.inner_self_nonneg_toy
#check @Probe.inner_self_nonneg_toy
-- D6PROBE Probe.leviCivita_isLeviCivita_toy
#check @Probe.leviCivita_isLeviCivita_toy
-- D6PROBE Probe.leviCivita_uniqueness_toy
#check @Probe.leviCivita_uniqueness_toy
-- D6PROBE Probe.torsion_antisymm_toy
#check @Probe.torsion_antisymm_toy
-- D6PROBE Probe.trace_id_toy
#check @Probe.trace_id_toy
