/-
D9 adversarial audit — #print axioms for every flagged declaration (auditor-written).
-/
import ReleaseCheck
import Audit.D9.IndepFindings

#print axioms D4Audit.gibbsTerm_strictAnti_of_one_le
#print axioms D4Audit.weak_discrete_monotonicity_false
#print axioms D4Audit.counterexample_continuous_c_half
#print axioms D4Audit.gibbsTerm_half_one_lt_two
#print axioms D4Audit.negTrajCont_hasDeriv
#print axioms D4Audit.counterexample_discrete_c_half
#print axioms D4Audit.negative_reaction_continuous_counterexample
#print axioms D4Audit.noSignEvolution_neg
#print axioms D4Audit.strict_step_positive_control
#print axioms D4Audit.negTrajDisc_step
#print axioms Poincare.Longrun.Evolution.PerelmanEvolutionBoundary.hc
#print axioms Poincare.Longrun.Evolution.PerelmanEvolutionBoundary.entropy_bridge
#print axioms Poincare.Longrun.Evolution.PerelmanEvolutionBoundary.evolves
#print axioms Poincare.Longrun.Evolution.PerelmanEvolutionBoundary.identification
#print axioms Poincare.Longrun.Evolution.PerelmanEvolutionBoundary.tensor_realization
#print axioms Poincare.Longrun.Evolution.perelmanF_limit_le_of_discrete
#print axioms Poincare.Longrun.Evolution.continuousPerelmanFMonotone_of_approximation
#print axioms Poincare.Longrun.Evolution.PerelmanApproximation.mk.sizeOf_spec
#print axioms Poincare.Longrun.Evolution.PerelmanApproximation.hc
#print axioms Poincare.Longrun.Evolution.PerelmanApproximation.evolves
#print axioms Poincare.Longrun.Evolution.squareTraj_evolution
#print axioms Poincare.Longrun.Evolution.perelmanF_step_increases_of_negative_step
#print axioms Poincare.Longrun.Evolution.squareTraj_counterexample
#print axioms Poincare.Longrun.Evolution.perelmanF_dissipation_pos_at_c_zero
#print axioms Poincare.Longrun.Evolution.perelmanF_step_increases_of_c_zero
#print axioms Poincare.Longrun.Evolution.eulerStep_squareField_one
#print axioms Poincare.Longrun.Evolution.perelmanF_one_two_le
#print axioms Poincare.Longrun.Evolution.squareField_eval
#print axioms D5ReleaseCheck.release_check_compiles
#print axioms Poincare.Longrun.Topology.missingSphereRecognitionAlgorithm
#print axioms Poincare.Longrun.Topology.missingKappaPersistenceUnderSurgery
#print axioms Poincare.Longrun.Topology.missingCanonicalNeighborhoodTheorem
#print axioms Poincare.Longrun.Topology.missingKappaNoncollapsing
#print axioms Poincare.Longrun.Topology.missingKappaNoncollapsing_iff
#print axioms Poincare.Longrun.Geometry.CovariantDerivativeCurvatureStatement
#print axioms Poincare.Longrun.Geometry.LeviCivitaExistenceStatement
#print axioms Poincare.Longrun.Evolution.gibbsTerm_strictAnti
#print axioms Poincare.Longrun.Evolution.gibbsTerm_step_lt
#print axioms Poincare.Longrun.Evolution.perelmanF_step_lt
#print axioms Poincare.Longrun.Evolution.gibbsTerm_antitone
#print axioms Poincare.Longrun.Evolution.gibbsTerm_step_le
#print axioms Poincare.Longrun.Surgery.ExtinctionTheorem.finitelyMany_of_complexity
#print axioms Poincare.Longrun.Surgery.ExtinctionTheorem.extincts_of_complexity
#print axioms Poincare.Longrun.Surgery.ExtinctionTheorem.terminalSphere_of_complexity
#print axioms Poincare.Longrun.Surgery.NeckAnalysis.deltaNeck_of_highCurvature
#print axioms Poincare.Longrun.Surgery.NeckAnalysis.admissible_of_highCurvature
#print axioms Poincare.Longrun.Surgery.NeckAnalysis.target_preserved_of_highCurvature
#print axioms Poincare.Longrun.Topology.KappaNoncollapsingCertificate.apply
#print axioms Poincare.Longrun.Topology.KappaNoncollapsingCertificate.volume_ball_pos
#print axioms Poincare.Longrun.Topology.NormalizedVolumeLowerBound.apply
#print axioms Poincare.Longrun.Topology.NormalizedBallVolumeLowerBound.toKappaNoncollapsingCertificate
#print axioms Poincare.Longrun.Topology.kappaNoncollapsingCertificate_iff_normalizedBallVolumeLowerBound
#print axioms Perelman.FMonotonicity.apply
#print axioms Perelman.WMonotonicity.apply
#print axioms Perelman.MuMonotonicity.apply
#print axioms Poincare.Longrun.Entropy.AntitoneCertificate.F_le_of_le
#print axioms Poincare.Longrun.Entropy.AntitoneCertificate.eq_of_le_of_eq
#print axioms Poincare.Longrun.Entropy.ContinuousAntitoneCertificate.antitoneOn
#print axioms Poincare.Longrun.Entropy.ContinuousMonotoneCertificate.monotoneOn
#print axioms Poincare.Longrun.Topology.CompactThreeManifold.toSigmaCompactSpace
#print axioms Poincare.Longrun.Topology.CompactThreeManifold.toParacompactSpace
#print axioms Poincare.Longrun.Topology.CompactThreeManifold.exists_finite_chart_cover
#print axioms Probe.PdeApi.heat_slab_nonpos_of_interface
#print axioms Probe.PdeApi.heat_slab_zero_interface
#print axioms Probe.PdeApi.heat_slab_affine_interface
#print axioms Poincare.Longrun.PDE.continuousHeatMaxPrinciple_of_timeIndependent
#print axioms Poincare.Longrun.CurvatureODE.component_monotone
#print axioms Poincare.Longrun.CurvatureODE.scalarFunctional_monotone
#print axioms Poincare.Longrun.CurvatureODE.nonneg_orthant_invariant
#print axioms Poincare.Longrun.Evolution.perelmanF_antitone
#print axioms Poincare.Longrun.Evolution.perelmanF_step_le
#print axioms Poincare.Longrun.Evolution.perelmanF_step_lt
#print axioms D4Audit.gibbsTerm_step_lt_of_one_le
#print axioms D4Audit.perelmanF_step_lt_of_one_le
#print axioms D4Audit.nonvacuity_main_theorem
#print axioms Poincare.Longrun.Evolution.continuousPerelmanFMonotone_of_approximation
#print axioms Poincare.Longrun.Evolution.perelmanF_limit_le_of_discrete
#print axioms D9Indep.releaseCheck_marker_is_True
#print axioms D9Indep.missingSphereRecognitionAlgorithm_trivial
#print axioms D9Indep.missingKappaPersistenceUnderSurgery_trivial
#print axioms D9Indep.missingCanonicalNeighborhoodTheorem_trivial
#print axioms D9Indep.missingKappaNoncollapsing_vacuous
#print axioms D9Indep.covariantDerivativeCurvatureStatement_trivial
#print axioms D9Indep.perelmanApproximation_iff_fields
#print axioms D9Indep.perelmanEvolutionBoundary_iff_fields
#print axioms D9Indep.extinctionTheorem_iff_prop_chain
#print axioms D9Indep.neckAnalysis_iff_prop_chain
#print axioms D9Indep.gibbs_threshold_exactly_one
#print axioms D9Indep.continuous_monotonicity_needs_identification
#print axioms D9Indep.limit_passage_needs_monotonicity
