/-
Independent reverse-use probe for D13-deturck-shorttime-producer (generated by gen_useprobe.py).
Reports direct users of each constructor in the elaborated environment and whether
each declared downstream pair mentions the constructor in type and/or value.
-/
import Poincare.D13.DeturckProducer.PicardModel
import Poincare.D13.DeturckProducer.FlatInstance
import Lean.Util.CollectAxioms

open Lean Elab Command

namespace D13XUse_D13_deturck_shorttime_producer

def constructors : List Name := [
  "Poincare.D13.DeturckProducer.PicardModel.RicciDeTurckPicardModel.of_metric".toName,
  "Poincare.D13.DeturckProducer.PicardModel.RicciDeTurckPicardModel.existsUnique_mildSolution_of_model".toName,
  "Poincare.D13.DeturckProducer.PicardModel.ricciFlow_of_model".toName,
  "Poincare.D13.DeturckProducer.PicardModel.deTurckShortTimeExistence_of_classicalOutput".toName,
  "Poincare.D13.DeturckProducer.PicardModel.RicciDeTurckPicardModel".toName]

def pairs : List (Name × Name) := [
  ("Poincare.D13.DeturckProducer.PicardModel.RicciDeTurckPicardModel.of_metric".toName, "Poincare.D13.DeturckProducer.PicardModel.RicciDeTurckPicardModel.existsUnique_mildSolution_of_model".toName),
  ("Poincare.D13.DeturckProducer.PicardModel.deTurckShortTimeExistence_of_classicalOutput".toName, "Poincare.D13.DeturckProducer.PicardModel.ricciFlow_of_model".toName)]

end D13XUse_D13_deturck_shorttime_producer

open D13XUse_D13_deturck_shorttime_producer in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let mut rows : Array (Name × Name × Bool × Bool) := #[]
  for (ctor, down) in pairs do
    let inType := match env.find? down with
      | some ci => ci.type.getUsedConstants.contains ctor
      | none => false
    let inValue := match env.find? down with
      | some ci => (match ci.value? true with
          | some v => v.getUsedConstants.contains ctor
          | none => false)
      | none => false
    rows := rows.push (ctor, down, inType, inValue)
  -- reverse direct-use census: declarations whose type or value mentions the constructor
  let scanPrefixes : List Name := ["Poincare.D13.DeturckProducer".toName,
    "Poincare.D13.ToppingAdapter".toName]
  let inScan (n : Name) : Bool :=
    match env.getModuleIdxFor? n with
    | some midx =>
        let m := mods.getD midx .anonymous
        scanPrefixes.isEmpty || scanPrefixes.any (fun r => r.isPrefixOf m)
    | none => scanPrefixes.isEmpty
  let decls := env.constants.fold (fun acc n _ => if inScan n then acc.push n else acc) #[]
  for ctor in constructors do
    IO.println s!"D13XEXISTS	{ctor}	{(env.find? ctor).isSome}"
    let mut direct : Array Name := #[]
    for d in decls do
      if d == ctor then continue
      match env.find? d with
      | some ci =>
          let inT := ci.type.getUsedConstants.contains ctor
          let inV := match ci.value? true with
            | some v => v.getUsedConstants.contains ctor
            | none => false
          if inT || inV then direct := direct.push d
      | none => pure ()
    IO.println s!"D13XUSE\t{ctor}\tdirect_users\t{direct.size}"
    for d in direct.qsort (fun a b => a.toString < b.toString) do
      IO.println s!"D13XUSER\t{ctor}\t{d}"
  for (ctor, down, inT, inV) in rows do
    IO.println s!"D13XPAIR\t{ctor}\t{down}\ttype={inT}\tvalue={inV}\tdown_exists={(env.find? down).isSome}"
  IO.println s!"D13XUSE_DONE\tD13-deturck-shorttime-producer"
