#!/usr/bin/env python3
"""L5 topology audit — generate the two collision-free detector passes.

Reads `audit-evidence/collisions.json` (produced by `l5_module_conflicts.py`) and the shared
audit body `audit-evidence/probes/_l5_body.lean`, and writes
  probes/L5Detector{A,B}.lean          (one import list per pass)
  probes/L5AuditPositive{A,B}.lean     (positive roots; A annotates the lane, B does not)

Usage: python3 l5_generate_probes.py <worktree-root>
"""
import json
import pathlib
import sys

wt = pathlib.Path(sys.argv[1]).resolve()
ev = wt / "audit-evidence"
coll = json.loads((ev / "collisions.json").read_text())
body = (ev / "probes" / "_l5_body.lean").read_text()
passA = coll["partition"]["pass_audit_side_a"]   # excludes the Monotonicity/Kappa copies
passB = coll["partition"]["pass_audit_side_b"]   # excludes the D7 originals
docA = ("Pass A — audits the `Poincare.D7.Bochner.*` / `Poincare.D7.ConjugateHeat.Basic` side "
        "(and every collision-free module except the 14 modules whose transitive closure imports "
        "the duplicate `Poincare.D7.Monotonicity.*`/`D7.Kappa.*` declarations).")
docB = ("Pass B — audits the `Poincare.D7.Monotonicity.*` / `Poincare.D7.Kappa.*` side "
        "(and every collision-free module except the 25 modules whose transitive closure imports "
        "the `D7.Bochner.*`/`D7.ConjugateHeat.Basic` originals).")
for tag, mods, doc in (("A", passA, docA), ("B", passB, docB)):
    header = (f"/-\nL5-topology-audit — independent fail-closed kernel detector, {doc}\n\n"
              f"{len(mods)} modules imported.  The union of pass A and pass B covers all 462 buildable\n"
              "modules of `release/`; the passes differ only in the 39 modules touching the three\n"
              "colliding declaration clusters recorded in `audit-evidence/collisions.json`.\n"
              "Generated by `audit-evidence/tools/l5_generate_probes.py` (do not edit by hand).\n-/\n")
    (ev / "probes" / f"L5Detector{tag}.lean").write_text(header + "\n".join(f"import {m}" for m in mods) + "\n" + body)
    root = (f"/-\nL5-topology-audit — positive root for pass {tag} (expected exit 0, `L5VERDICT PASS`).\n-/\n"
            f"import L5Detector{tag}\n\nopen L5Audit\n\n"
            f"run_cmd runAudit packageRoots knownNegControls {'true' if tag == 'A' else 'false'}\n")
    (ev / "probes" / f"L5AuditPositive{tag}.lean").write_text(root)
print("pass A modules:", len(passA), "pass B modules:", len(passB))
