#!/usr/bin/env python3
"""Generate the D13 integrated-audit Lean roots from the snapshot provenance manifest.

Outputs:
  release/Poincare/D13/IntegratedAudit/SnapshotRoot.lean    (imports all clean new modules)
  release/Poincare/D13/IntegratedAudit/ExpectedModules.lean (pinned module list for fail-closed checks)
  audit-evidence/modules.json                               (machine-readable module inventory)
"""
import json
from pathlib import Path

WT = Path("/data3/guoshaoyang/workdir/lean_poincare/longrun/worktrees/D13-integrated-kernel-audit")
REL = WT / "release"
EVID = WT / "audit-evidence"
AUDIT_DIR = REL / "Poincare" / "D13" / "IntegratedAudit"

# Modules that intentionally declare a forbidden axiom (negative controls).
NEG_CONTROL_MODULES = {
    "Poincare.D12.TriangulationTopology.NegControl.NegControl":
        "intentional negative control: declares `axiom d12NegControlBadAxiom : False`",
    "Poincare.D12.VolumeIBP.Audit":
        "task-local audit driver with intentional negative control `axiom negativeControl : False`",
}


def module_of(path: str) -> str:
    assert path.endswith(".lean")
    return path[:-5].replace("/", ".")


def main() -> int:
    prov = json.loads((EVID / "snapshot-provenance.json").read_text())
    mods = []
    for r in prov["files"]:
        m = module_of(r["path"])
        mods.append({"module": m, "path": r["path"], "sha256": r["sha256"], "origin": r["origin"]})
    mods.sort(key=lambda x: x["module"])
    clean = [m for m in mods if m["module"] not in NEG_CONTROL_MODULES]
    neg = [m for m in mods if m["module"] in NEG_CONTROL_MODULES]
    (EVID / "modules.json").write_text(json.dumps(
        {"all": mods, "clean": clean, "negative_controls": neg,
         "negative_control_reasons": NEG_CONTROL_MODULES}, indent=1) + "\n")

    AUDIT_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["/-", "D13 integrated kernel audit — merged snapshot root (generated).",
             "",
             "Imports every clean (non-negative-control) module added by D11 and D12 in this",
             "snapshot.  Successful elaboration of this single root IS the collision check:",
             "Lean rejects two imported modules that declare the same constant name.",
             "",
             "Generated by audit-evidence/tools/generate_audit_roots.py — do not edit by hand.",
             "-/"]
    lines += [f"import {m['module']}" for m in clean]
    (AUDIT_DIR / "SnapshotRoot.lean").write_text("\n".join(lines) + "\n")

    lines = ["/-", "D13 integrated kernel audit — pinned expected-module list (generated).", "",
             "Generated by audit-evidence/tools/generate_audit_roots.py — do not edit by hand.",
             "-/", "", "namespace Poincare.D13.IntegratedAudit", "",
             "/-- Every clean module contributed by D11/D12 in this snapshot. -/",
             "def expectedCleanModules : List Lean.Name := ["]
    for m in clean:
        lines.append(f'  "{m["module"]}".toName,')
    lines += ["  ]", "",
              "/-- Modules intentionally declaring a forbidden axiom (negative controls). -/",
              "def negativeControlModules : List Lean.Name := ["]
    for m in neg:
        lines.append(f'  "{m["module"]}".toName,')
    lines += ["  ]", "", "end Poincare.D13.IntegratedAudit", ""]
    (AUDIT_DIR / "ExpectedModules.lean").write_text("\n".join(lines) + "\n")

    print(f"clean modules: {len(clean)}; negative-control modules: {len(neg)}")
    for m in neg:
        print("  NEG:", m["module"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
