import UpstreamAdaptersPetersen.Adapters
import UpstreamAdaptersPetersen.DownstreamUse

/-!
# Fail-closed axiom audit: UpstreamAdaptersPetersen

Generated by `evidence/make-audit-file.py` from **every declaration**
in the authored modules of this library (discovered from the
comment-stripped sources; anonymous instances and `private`
declarations are refused).  The audit therefore covers the whole
authored surface, not a curated list.

Each `#print axioms` line prints the axiom cone of the declaration;
`evidence/check-axioms.py` parses the output and fails closed unless
every cone is a subset of `{propext, Classical.choice, Quot.sound}`.
`evidence/check-audit-coverage.py` verifies that the set of audited
names equals the set of authored declarations and that the log
contains one record per audited name.

A `sorryAx` entry here would mean a proof is admitted.
-/

namespace UpstreamAdaptersPetersen.Audit

#print axioms UpstreamAdaptersPetersen.Adapters.curvatureTensor_indexLowering
#print axioms UpstreamAdaptersPetersen.Adapters.curvatureTensor_coordinates
#print axioms UpstreamAdaptersPetersen.Adapters.contMDiff_curvatureTensorFour
#print axioms UpstreamAdaptersPetersen.Adapters.curvatureTensor_derivation
#print axioms UpstreamAdaptersPetersen.Adapters.expMap_localDiffeomorphism
#print axioms UpstreamAdaptersPetersen.Adapters.expMap_smul
#print axioms UpstreamAdaptersPetersen.Adapters.expMap_zero
#print axioms UpstreamAdaptersPetersen.Adapters.isGeodesicOn_of_isChartGeodesicOn
#print axioms UpstreamAdaptersPetersen.Adapters.segment_isGeodesic
#print axioms UpstreamAdaptersPetersen.Adapters.energyLocalMinimum_isGeodesic
#print axioms UpstreamAdaptersPetersen.Adapters.curvatureTensorTypes
#print axioms UpstreamAdaptersPetersen.Adapters.curvatureTensor_zero_first
#print axioms UpstreamAdaptersPetersen.Adapters.curvatureTensor_eq_ricci_identity
#print axioms UpstreamAdaptersPetersen.Adapters.expMap
#print axioms UpstreamAdaptersPetersen.Adapters.RicciCurvature
#print axioms UpstreamAdaptersPetersen.Adapters.IsJacobiField
#print axioms UpstreamAdaptersPetersen.Adapters.ConjugatePoint
#print axioms UpstreamAdaptersPetersen.Adapters.myersRicciDiameterBound_of_ricciLowerBound
#print axioms UpstreamAdaptersPetersen.Adapters.leviCivita
#print axioms UpstreamAdaptersPetersen.Adapters.koszul
#print axioms UpstreamAdaptersPetersen.DownstreamUse.Plane
#print axioms UpstreamAdaptersPetersen.DownstreamUse.euclidean_curvatureTensorAt_eq_zero
#print axioms UpstreamAdaptersPetersen.DownstreamUse.euclidean_expMap_zero
#print axioms UpstreamAdaptersPetersen.DownstreamUse.euclidean_expMap_zero_smul

end UpstreamAdaptersPetersen.Audit
