/- GENERATED by baseline/tools/gen_grouped_audit.py — do not edit. -/
import Poincare.D7.Kappa.All
import Poincare.D7.Kappa.Audit
import Poincare.D7.Kappa.EntropyBridge
import Poincare.D7.Kappa.Nonvacuity
import Poincare.D7.Kappa.Probe
import Poincare.D7.Kappa.Statements
import Poincare.D7.Monotonicity.All
import Poincare.D7.Monotonicity.Blockers
import Poincare.D7.Monotonicity.BochnerCertificate
import Poincare.D7.Monotonicity.BochnerGradientEstimate
import Poincare.D7.Monotonicity.ConjugateHeatCertificate
import Poincare.D7.Monotonicity.FMonotonicity
import Poincare.D7.Monotonicity.Nonvacuity
import Poincare.D7.Monotonicity.WMuMonotonicity

open Lean Elab Command

namespace L1BaselineAuditG2

/-- Modules whose declarations are enumerated in this partition. -/
def targetModules : Array Name := #[
  `Poincare.D7.Kappa.All,
  `Poincare.D7.Kappa.Audit,
  `Poincare.D7.Kappa.EntropyBridge,
  `Poincare.D7.Kappa.Nonvacuity,
  `Poincare.D7.Kappa.Probe,
  `Poincare.D7.Kappa.Statements,
  `Poincare.D7.Monotonicity.All,
  `Poincare.D7.Monotonicity.Blockers,
  `Poincare.D7.Monotonicity.BochnerCertificate,
  `Poincare.D7.Monotonicity.BochnerGradientEstimate,
  `Poincare.D7.Monotonicity.ConjugateHeatCertificate,
  `Poincare.D7.Monotonicity.FMonotonicity,
  `Poincare.D7.Monotonicity.Nonvacuity,
  `Poincare.D7.Monotonicity.WMuMonotonicity
]

/-- Kernel axioms approved for this baseline. -/
def approvedAxioms : Array Name := #[``propext, ``Classical.choice, ``Quot.sound]

/-- Documented negative controls: their cones MUST be flagged. -/
def expectedBad : Array Name := #[
  `d12NegControlBadAxiom,
  `d12NegControlBadTheorem,
  `Poincare.D12.VolumeIBP.Audit.negativeControl
]

def kindOf : ConstantInfo → String
  | .axiomInfo _ => "axiom"
  | .defnInfo v =>
      if v.safety == .unsafe then "unsafe_def"
      else if v.safety == .partial then "partial_def" else "def"
  | .thmInfo _ => "theorem"
  | .opaqueInfo _ => "opaque"
  | .quotInfo _ => "quot"
  | .inductInfo _ => "inductive"
  | .ctorInfo _ => "ctor"
  | .recInfo _ => "recursor"

end L1BaselineAuditG2

open L1BaselineAuditG2 in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let rows : Array (Name × ConstantInfo × Name) :=
    env.constants.fold (fun acc n ci =>
      match env.getModuleIdxFor? n with
      | some midx =>
          let m := mods.getD midx .anonymous
          if targetModules.contains m then acc.push (n, ci, m) else acc
      | none => acc) #[]
  let mut nDecl : Nat := 0
  let mut nTheorem : Nat := 0
  let mut nDef : Nat := 0
  let mut nAxiom : Nat := 0
  let mut nUnsafe : Nat := 0
  let mut nPartial : Nat := 0
  let mut nSorry : Nat := 0
  let mut nNative : Nat := 0
  let mut nUnexpected : Nat := 0
  let mut nExpectedSeen : Nat := 0
  let mut nCollectFail : Nat := 0
  let mut modulesSeen : Array Name := #[]
  let mut deps : Array String := #[]
  for (n, ci, m) in rows do
    if !modulesSeen.contains m then modulesSeen := modulesSeen.push m
    nDecl := nDecl + 1
    let kind := kindOf ci
    if kind == "theorem" then nTheorem := nTheorem + 1
    if kind == "def" || kind == "partial_def" then nDef := nDef + 1
    if kind == "axiom" then nAxiom := nAxiom + 1
    if kind == "unsafe_def" then nUnsafe := nUnsafe + 1
    if kind == "partial_def" then nPartial := nPartial + 1
    let used := ci.type.getUsedConstants ++ (ci.value?.map (·.getUsedConstants)).getD #[]
    for d in used do
      match env.getModuleIdxFor? d with
      | some didx =>
          if targetModules.contains (mods.getD didx .anonymous) then
            deps := deps.push s!"{n}\t{d}"
      | none => pure ()
    let axs ←
      try
        Lean.collectAxioms n
      catch _ =>
        nCollectFail := nCollectFail + 1
        pure #[]
    let extra := axs.filter (fun a => !approvedAxioms.contains a)
    if extra.contains `sorryAx then nSorry := nSorry + 1
    if extra.any (fun a => a.toString.contains "native") then nNative := nNative + 1
    if !extra.isEmpty then
      if expectedBad.contains n then nExpectedSeen := nExpectedSeen + 1
      else nUnexpected := nUnexpected + 1
    IO.println s!"L1AXROW\t{n}\t{kind}\t{m}\t{String.intercalate "," (axs.toList.map toString)}\t{String.intercalate "," (extra.toList.map toString)}\t{n.isInternal}"
  for m in modulesSeen do
    IO.println s!"L1MOD\t{m}\t{(rows.filter (fun r => r.2.2 == m)).size}"
  for d in deps do IO.println s!"L1DEP\t{d}"
  IO.println s!"L1SUM\tpartition\tG2"
  IO.println s!"L1SUM\tdeclarations\t{nDecl}"
  IO.println s!"L1SUM\ttheorems\t{nTheorem}"
  IO.println s!"L1SUM\tdefs\t{nDef}"
  IO.println s!"L1SUM\taxioms\t{nAxiom}"
  IO.println s!"L1SUM\tunsafe\t{nUnsafe}"
  IO.println s!"L1SUM\tpartial\t{nPartial}"
  IO.println s!"L1SUM\tsorry\t{nSorry}"
  IO.println s!"L1SUM\tnative\t{nNative}"
  IO.println s!"L1SUM\tunexpected_violations\t{nUnexpected}"
  IO.println s!"L1SUM\texpected_negative_controls_seen\t{nExpectedSeen}"
  IO.println s!"L1SUM\tcollect_failures\t{nCollectFail}"
  IO.println s!"L1SUM\tpackage_modules_with_declarations\t{modulesSeen.size}"
  IO.println s!"L1SUM\tdeclared_modules_imported\t{targetModules.size}"
  IO.println s!"L1SUM\tdep_edges\t{deps.size}"
  let ok := nUnexpected == 0 && nCollectFail == 0 && nSorry == 0
    && nUnsafe == 0 && nNative == 0
    && (nExpectedSeen == 0 || nExpectedSeen == expectedBad.size)
  if ok then
    IO.println "L1AXVERDICT\tPASS"
  else
    IO.println "L1AXVERDICT\tFAIL"
    throwError "L1 baseline axiom audit G2 FAILED (unexpected={nUnexpected}, collect_fail={nCollectFail}, sorry={nSorry}, unsafe={nUnsafe}, native={nNative}, expected_seen={nExpectedSeen}/{expectedBad.size})"
