/- GENERATED by baseline/tools/gen_dep_audit.py — corrected proof-level dependency graph; do not edit. -/
import Poincare.D7.Kappa.All
import Poincare.D7.Kappa.Audit
import Poincare.D7.Kappa.EntropyBridge
import Poincare.D7.Kappa.Nonvacuity
import Poincare.D7.Kappa.Probe
import Poincare.D7.Kappa.Statements
import Poincare.D7.Monotonicity.All
import Poincare.D7.Monotonicity.Blockers
import Poincare.D7.Monotonicity.BochnerCertificate
import Poincare.D7.Monotonicity.BochnerGradientEstimate
import Poincare.D7.Monotonicity.ConjugateHeatCertificate
import Poincare.D7.Monotonicity.FMonotonicity
import Poincare.D7.Monotonicity.Nonvacuity
import Poincare.D7.Monotonicity.WMuMonotonicity

open Lean Elab Command

namespace L1DepAuditG2

/-- Modules whose declarations are enumerated in this partition. -/
def targetModules : Array Name := #[
  `Poincare.D7.Kappa.All,
  `Poincare.D7.Kappa.Audit,
  `Poincare.D7.Kappa.EntropyBridge,
  `Poincare.D7.Kappa.Nonvacuity,
  `Poincare.D7.Kappa.Probe,
  `Poincare.D7.Kappa.Statements,
  `Poincare.D7.Monotonicity.All,
  `Poincare.D7.Monotonicity.Blockers,
  `Poincare.D7.Monotonicity.BochnerCertificate,
  `Poincare.D7.Monotonicity.BochnerGradientEstimate,
  `Poincare.D7.Monotonicity.ConjugateHeatCertificate,
  `Poincare.D7.Monotonicity.FMonotonicity,
  `Poincare.D7.Monotonicity.Nonvacuity,
  `Poincare.D7.Monotonicity.WMuMonotonicity
]

end L1DepAuditG2

open L1DepAuditG2 in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let rows : Array (Name × ConstantInfo × Name) :=
    env.constants.fold (fun acc n ci =>
      match env.getModuleIdxFor? n with
      | some midx =>
          let m := mods.getD midx .anonymous
          if targetModules.contains m then acc.push (n, ci, m) else acc
      | none => acc) #[]
  let mut nDecl : Nat := 0
  let mut nEdges : Nat := 0
  let mut deps : Array String := #[]
  for (n, _ci, _m) in rows do
    nDecl := nDecl + 1
    -- corrected: include theorem/opaque proof bodies (allowOpaque := true)
    let used := _ci.type.getUsedConstants
      ++ ((ConstantInfo.value? _ci (allowOpaque := true)).map (·.getUsedConstants)).getD #[]
    for d in used do
      match env.getModuleIdxFor? d with
      | some didx =>
          if targetModules.contains (mods.getD didx .anonymous) then
            deps := deps.push s!"{n}\t{d}"
            nEdges := nEdges + 1
      | none => pure ()
  IO.println s!"L2SUM\tpartition\tG2"
  IO.println s!"L2SUM\tdeclarations\t{nDecl}"
  IO.println s!"L2SUM\tedges\t{nEdges}"
  IO.println s!"L2SUM\tdistinct_declared\t{rows.size}"
  for d in deps do IO.println s!"L2DEP\t{d}"
  IO.println "L2DEPVERDICT\tDONE"
