#!/usr/bin/env python3
"""Generate per-partition declaration *type* dumps for the independent replay.

The frozen grouped axiom audit (`baseline/audit/AxiomAudit_G{1,2}.lean`) records, for every
declaration in the two import-disjoint partitions, its name / kind / module / axiom cone.
For the L1-C1 replay we additionally want the declarations' *types*, so that a from-scratch
build in a different directory can be compared declaration-by-declaration at the level of
the elaborated term, not only at the level of the axiom cone.

This reuses the exact same partition (`baseline/audit/partition.json`, computed by
gen_grouped_audit.py from the frozen import graph) so the two dumps are over the same
12,361-declaration set.

Outputs:  baseline/c1/typeaudit/TypeAudit_G{1,2}.lean
Run with: cd <tree> && lake env lean <abs>/baseline/c1/typeaudit/TypeAudit_G1.lean
"""
import json
import os

WT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PART = os.path.join(WT, "baseline", "audit", "partition.json")
OUTDIR = os.path.join(WT, "baseline", "c1", "typeaudit")

TEMPLATE = """/- GENERATED by baseline/c1/gen_type_audit.py -- do not edit. -/
@IMPORTS@

open Lean Elab Command

namespace L1TypeAudit@LABEL@

/-- Modules whose declarations are dumped in this partition (same partition as the
frozen axiom audit). -/
def targetModules : Array Name := #[
@MODULES@
]

end L1TypeAudit@LABEL@

open L1TypeAudit@LABEL@ in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let mut count : Nat := 0
  for (n, ci) in env.constants.toList do
    match env.getModuleIdxFor? n with
    | some midx =>
        if targetModules.contains (mods.getD midx .anonymous) then
          logInfo m!"L1TYPE\\t{n}\\t{ci.type}"
          count := count + 1
    | none => pure ()
  logInfo m!"L1TYPEDONE\\t{count}"
"""


def main():
    with open(PART, encoding="utf-8") as fh:
        part = json.load(fh)
    os.makedirs(OUTDIR, exist_ok=True)
    for label in ("G1", "G2"):
        mods = part["groups"][label]["modules"]
        imports = "\n".join("import %s" % m for m in mods)
        body = TEMPLATE.replace("@IMPORTS@", imports)
        body = body.replace("@MODULES@", "\n".join("  `%s," % m for m in mods))
        body = body.replace("@LABEL@", label)
        path = os.path.join(OUTDIR, "TypeAudit_%s.lean" % label)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(body)
        print("wrote %s (%d modules)" % (path, len(mods)))


if __name__ == "__main__":
    main()
