/-
D5-clean-rebuild — claim-resolution probe (generated).

Each `#check @name` below is a declaration named by a D1-D4 result card.
Errors here are recorded as informational claim discrepancies, not gate failures.
-/

import ReleaseCheck

#check @D4Audit.audit_certificate_compare
#check @D4Audit.audit_continuous_certificate
#check @D4Audit.certificate_lower_bound_zero
#check @D4Audit.counterexample_continuous_c_half
#check @D4Audit.counterexample_discrete_c_half
#check @D4Audit.counterexample_negative_step
#check @D4Audit.dissipation_sanity
#check @D4Audit.finiteMeshConvergence_nonvacuous
#check @D4Audit.gibbsTerm_step_lt_of_one_le
#check @D4Audit.gibbsTerm_strictAnti_of_one_le
#check @D4Audit.limit_passage_sanity
#check @D4Audit.nonvacuity_main_theorem
#check @D4Audit.nonvacuity_main_theorem_strict
#check @D4Audit.perelmanApproximation_nonvacuous
#check @D4Audit.perelmanF_nonneg_sharp
#check @D4Audit.perelmanF_step_lt_of_one_le
#check @D4Audit.strict_step_needs_pos_reaction
#check @D4Audit.strict_step_needs_pos_step
#check @D4Audit.transfer_nonvacuous
#check @Perelman.CurvatureBoundedOn
#check @Perelman.CurvatureBoundedOn.mono
#check @Perelman.FMonotonicity
#check @Perelman.FProfile
#check @Perelman.HasFrameVolumeDensity
#check @Perelman.HasMetricTimeDerivative
#check @Perelman.HasUnitMass
#check @Perelman.IsScalarCurvature
#check @Perelman.KappaNoncollapsing
#check @Perelman.MetricFamily
#check @Perelman.MetricFlowData
#check @Perelman.MetricFlowData.Icc_subset
#check @Perelman.MuMonotonicity
#check @Perelman.RicciLowerBound
#check @Perelman.RiemannianVolumePredicate
#check @Perelman.ScalarCurvatureData
#check @Perelman.ScalarCurvatureLowerBound
#check @Perelman.VolumeFormData
#check @Perelman.WMonotonicity
#check @Perelman.WProfile
#check @Perelman.constantFlow
#check @Perelman.directionalDerivative
#check @Perelman.gradientNormSqInBasis
#check @Perelman.gramMatrix
#check @Perelman.hasMetricTimeDerivative_const
#check @Perelman.negTwoRicci
#check @Perelman.perelmanF
#check @Perelman.perelmanMu
#check @Perelman.perelmanMu_le
#check @Perelman.perelmanW
#check @Perelman.riemannianVolumeDensity
#check @Perelman.riemannianVolumeDensity_nonneg
#check @Perelman.riemannianVolumeDensity_pos_of_posDef
#check @Perelman.satisfies_ricciFlow_const_zero
#check @Perelman.scalarCurvatureInBasis
#check @Perelman.toyF
#check @Perelman.toyF_mono
#check @Perelman.toyW
#check @Perelman.toyW_nonneg
#check @Poincare.CurvatureAlgebra.CurvatureOperator.ricci
#check @Poincare.CurvatureAlgebra.CurvatureOperator.ricci_add
#check @Poincare.CurvatureAlgebra.CurvatureOperator.ricci_smul
#check @Poincare.CurvatureAlgebra.CurvatureOperator.scalarCurvature
#check @Poincare.CurvatureAlgebra.CurvatureOperator.scalarCurvature_add
#check @Poincare.Longrun.CurvatureODE.ManifoldCurvatureRealization
#check @Poincare.Longrun.CurvatureODE.MetricCurvatureShadow
#check @Poincare.Longrun.CurvatureODE.MetricFamilySolvesRicciFlow
#check @Poincare.Longrun.CurvatureODE.TensorRicciFlowODEBridge
#check @Poincare.Longrun.CurvatureODE.TensorRicciFlowODERealization
#check @Poincare.Longrun.CurvatureODE.bridge_state_eq_ricciDiagonal
#check @Poincare.Longrun.CurvatureODE.component_monotone
#check @Poincare.Longrun.CurvatureODE.evolutionRelation_of_bridge
#check @Poincare.Longrun.CurvatureODE.nonneg_orthant_invariant
#check @Poincare.Longrun.CurvatureODE.nonneg_orthant_invariant_discrete
#check @Poincare.Longrun.CurvatureODE.ricciDiagonal_nonneg_of_bridge
#check @Poincare.Longrun.CurvatureODE.scalarCurvature_monotone_of_bridge
#check @Poincare.Longrun.CurvatureODE.scalarFunctional_monotone
#check @Poincare.Longrun.CurvatureODE.scalarFunctional_monotone_discrete
#check @Poincare.Longrun.CurvatureODE.scalarOfState_monotone
#check @Poincare.Longrun.CurvatureODE.scalarOfState_monotone_discrete
#check @Poincare.Longrun.CurvatureODE.zero_orthant_invariant
#check @Poincare.Longrun.CurvatureODE.zero_scalar_monotone
#check @Poincare.Longrun.Evolution.gibbsTerm_step_lt
#check @Poincare.Longrun.Evolution.gibbsTerm_strictAnti
#check @Poincare.Longrun.Evolution.perelmanF_antitone
#check @Poincare.Longrun.Evolution.perelmanF_step_lt
#check @Poincare.Longrun.Geometry.AbstractConnection.curvature_bianchi
#check @Poincare.Longrun.Geometry.AbstractConnection.curvature_skew
#check @Poincare.Longrun.Geometry.AbstractConnection.toCurvatureOperator
#check @Poincare.Longrun.Geometry.CovariantDerivativeCurvatureStatement
#check @Poincare.Longrun.Geometry.LeviCivitaExistenceStatement
#check @Poincare.Longrun.Geometry.LieBracketData.jacobi_reverse
#check @Poincare.Longrun.Geometry.MetricData.form_raiseIndex
#check @Poincare.Longrun.Geometry.MetricData.scalarCurvature_eq_sum_basis
#check @Poincare.Longrun.Geometry.curvatureForm
#check @Poincare.Longrun.Geometry.curvatureForm_first_bianchi
#check @Poincare.Longrun.Geometry.curvatureForm_first_pair_skew
#check @Poincare.Longrun.Geometry.leviCivitaExistence_iff_nonempty
#check @Poincare.Longrun.Geometry.leviCivita_nabla_unique
#check @Poincare.Longrun.Geometry.meanConnection_isMetricCompatible_iff
#check @Poincare.Longrun.Geometry.mean_curvature_apply
#check @Poincare.Longrun.Geometry.mean_endoRicci
#check @Poincare.Longrun.Geometry.mean_ricci_comm
#check @Poincare.Longrun.PDE.ContinuousHeatHypotheses
#check @Poincare.Longrun.PDE.ContinuousHeatMaximumPrincipleInterface
#check @Poincare.Longrun.PDE.HeatGridEvolution
#check @Poincare.Longrun.PDE.HeatGridEvolution.energy_nonincreasing
#check @Poincare.Longrun.PDE.HeatGridEvolution.le_of_initial_le
#check @Poincare.Longrun.PDE.HeatGridEvolution.le_sup'_initial
#check @Poincare.Longrun.PDE.HeatGridEvolution.succ_le
#check @Poincare.Longrun.PDE.continuousHeatHypotheses_affine
#check @Poincare.Longrun.PDE.continuousHeatHypotheses_quadratic
#check @Poincare.Longrun.PDE.continuousHeatHypotheses_zero
#check @Poincare.Longrun.PDE.continuousHeatMaxPrinciple_affine
#check @Poincare.Longrun.PDE.continuousHeatMaxPrinciple_of_timeIndependent
#check @Poincare.Longrun.PDE.continuousHeatMaxPrinciple_quadratic
#check @Poincare.Longrun.PDE.continuousHeatMaxPrinciple_zero
#check @Poincare.Longrun.PDE.convex_combo_sq_le
#check @Poincare.Longrun.PDE.energy_heatStep_le
#check @Poincare.Longrun.PDE.energy_nonneg
#check @Poincare.Longrun.PDE.energy_step_le
#check @Poincare.Longrun.PDE.heatStep_le
#check @Poincare.Longrun.PDE.heatStep_sq_le
#check @Poincare.Longrun.PDE.strict_grid_max_principle
#check @Poincare.Longrun.PDE.strict_grid_max_principle_max
#check @Poincare.Longrun.PDE.sum_shift_pred
#check @Poincare.Longrun.PDE.sum_shift_succ
#check @Poincare.Longrun.Surgery.ChainCertificate.append
#check @Poincare.Longrun.Surgery.ChainCertificate.compact_preserved
#check @Poincare.Longrun.Surgery.ChainCertificate.orientable_preserved
#check @Poincare.Longrun.Surgery.ChainCertificate.preservation
#check @Poincare.Longrun.Surgery.ChainCertificate.simplyConnected_preserved
#check @Poincare.Longrun.Surgery.ExtinctionTheorem
#check @Poincare.Longrun.Surgery.ExtinctionTheorem.extincts_of_complexity
#check @Poincare.Longrun.Surgery.ExtinctionTheorem.finitelyMany_of_complexity
#check @Poincare.Longrun.Surgery.ExtinctionTheorem.terminalSphere_of_complexity
#check @Poincare.Longrun.Surgery.LedgerPredicates
#check @Poincare.Longrun.Surgery.MissingInputs
#check @Poincare.Longrun.Surgery.NeckAnalysis
#check @Poincare.Longrun.Surgery.NeckAnalysis.admissible_of_highCurvature
#check @Poincare.Longrun.Surgery.NeckAnalysis.certificate
#check @Poincare.Longrun.Surgery.NeckAnalysis.deltaNeck_of_highCurvature
#check @Poincare.Longrun.Surgery.NeckAnalysis.realizes_of_highCurvature
#check @Poincare.Longrun.Surgery.NeckAnalysis.target_preserved_of_highCurvature
#check @Poincare.Longrun.Surgery.SurgeryCertificate
#check @Poincare.Longrun.Surgery.SurgeryCertificate.ofHomeomorph
#check @Poincare.Longrun.Surgery.SurgeryCertificate.ofHomotopyEquiv
#check @Poincare.Longrun.Surgery.SurgeryCertificate.trivial
#check @Poincare.Longrun.Surgery.SurgeryDatum
#check @Poincare.Longrun.Surgery.SurgeryDatum.post
#check @Poincare.Longrun.Surgery.SurgeryDatum.pre
#check @Poincare.Longrun.Surgery.ToyChain.le
#check @Poincare.Longrun.Surgery.ToyChain.no_infinite
#check @Poincare.Longrun.Surgery.ToyChain.reflTransGen
#check @Poincare.Longrun.Surgery.ToyChain.value
#check @Poincare.Longrun.Surgery.ToyRel
#check @Poincare.Longrun.Surgery.canonicalLedger
#check @Poincare.Longrun.Surgery.extincts_and_target
#check @Poincare.Longrun.Surgery.toyCertificate
#check @Poincare.Longrun.Surgery.toyChain321_compact
#check @Poincare.Longrun.Surgery.toyChain321_preserves
#check @Poincare.Longrun.Surgery.toyRel_functional
#check @Poincare.Longrun.Surgery.toyRel_lt
#check @Poincare.Longrun.Surgery.toyRel_nonempty
#check @Poincare.Longrun.Surgery.toyRel_not_refl
#check @Poincare.Longrun.Surgery.toyRel_odd_iff
#check @Poincare.Longrun.Surgery.toyRel_succ
#check @Poincare.Longrun.Surgery.toy_extinction_skeleton
#check @Poincare.Longrun.Topology.kappaNoncollapsingCertificate_iff_normalizedBallVolumeLowerBound
#check @Probe.CurvatureTensor
#check @Probe.CurvatureTensor.antisymm
#check @Probe.CurvatureTensor.bianchi
#check @Probe.CurvatureTensor.bianchi_toy
#check @Probe.CurvatureTensor.endo
#check @Probe.CurvatureTensor.ricci
#check @Probe.CurvatureTensor.ricci_add_toy
#check @Probe.CurvatureTensor.ricci_zero_toy
#check @Probe.CurvatureTensor.self_eq_zero
#check @Probe.CurvatureTensor.zero
#check @Probe.PdeApi.HeatSlabMaximumPrincipleInterface
#check @Probe.PdeApi.continuousOn_Icc_exists_max
#check @Probe.PdeApi.deriv_sq
#check @Probe.PdeApi.discreteLaplacian_affine
#check @Probe.PdeApi.heat_slab_affine_interface
#check @Probe.PdeApi.heat_slab_nonpos_of_interface
#check @Probe.PdeApi.heat_slab_zero_interface
#check @Probe.PdeApi.iteratedDeriv_two_cube
#check @Probe.PdeApi.strict_finite_grid_max_principle
#check @Probe.PdeApi.strict_finite_grid_max_principle_max
#check @Probe.inner_self_nonneg_toy
#check @Probe.leviCivita_isLeviCivita_toy
#check @Probe.leviCivita_uniqueness_toy
#check @Probe.torsion_antisymm_toy
#check @Probe.trace_id_toy
