-- A3 declaration-kind audit for D12-spectral-sobolev
-- generated by D13-cross-audit-360-cards; do not edit

import Poincare.D12.SpectralSobolev.Basic
import Poincare.D12.SpectralSobolev.Examples
import Poincare.D12.SpectralSobolev.HeatConvergence
import Poincare.D12.SpectralSobolev.Poincare
import Poincare.D12.SpectralSobolev.Semigroup

set_option maxHeartbeats 400000


open Lean Elab Command

def a3KindNames : List Name := [
  `Poincare.D12.SpectralSobolev.heatWeight,
  `Poincare.D12.SpectralSobolev.heatWeight_zero,
  `Poincare.D12.SpectralSobolev.heatWeight_pos,
  `Poincare.D12.SpectralSobolev.heatWeight_nonneg,
  `Poincare.D12.SpectralSobolev.heatWeight_le_one,
  `Poincare.D12.SpectralSobolev.heatWeight_abs_le_one,
  `Poincare.D12.SpectralSobolev.heatWeight_tendsto_one,
  `Poincare.D12.SpectralSobolev.heatCoeffs,
  `Poincare.D12.SpectralSobolev.heatCoeffs_apply,
  `Poincare.D12.SpectralSobolev.summable_sq_heatCoeff,
  `Poincare.D12.SpectralSobolev.heatCoeffsL2,
  `Poincare.D12.SpectralSobolev.heatEvolve,
  `Poincare.D12.SpectralSobolev.heatSeries_hasSum,
  `Poincare.D12.SpectralSobolev.fourierCoeff_heatEvolve,
  `Poincare.D12.SpectralSobolev.heatEvolve_norm_le,
  `Poincare.D12.SpectralSobolev.heatEvolve_tendsto_self,
  `Poincare.D12.SpectralSobolev.heatEvolve_fourierLp,
  `Poincare.D12.SpectralSobolev.norm_heatEvolve_fourierLp,
  `Poincare.D12.SpectralSobolev.sq_eigenvalue_pos,
  `Poincare.D12.SpectralSobolev.heatWeight_lt_one_of_pos,
  `Poincare.D12.SpectralSobolev.heatEvolve_zero,
  `Poincare.D12.SpectralSobolev.heatEvolve_add,
  `Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic,
  `Poincare.D12.SpectralSobolev.sq_norm_eigenvalue,
  `Poincare.D12.SpectralSobolev.sq_norm_fourierCoeffOn_deriv_periodic,
  `Poincare.D12.SpectralSobolev.fourierCoeffOn_zero_eq_mean,
  `Poincare.D12.SpectralSobolev.poincare_wirtinger,
  `Poincare.D12.SpectralSobolev.norm_sin_le_one,
  `Poincare.D12.SpectralSobolev.norm_cos_le_one,
  `Poincare.D12.SpectralSobolev.sine_wave_hypotheses,
  `Poincare.D12.SpectralSobolev.integral_sin_sq_period,
  `Poincare.D12.SpectralSobolev.integral_cos_sq_period,
  `Poincare.D12.SpectralSobolev.poincare_wirtinger_sine,
  `Poincare.D12.SpectralSobolev.poincare_wirtinger_sine_saturates,
  `Poincare.D12.SpectralSobolev.poincare_constant_sharp,
  `Poincare.D12.SpectralSobolev.heat_evolution_first_mode_nontrivial
]

run_cmd do
  let mut counts : Std.HashMap String Nat := {}
  for n in a3KindNames do
    let ci ← getConstInfo n
    let k : String ← match ci with
      | .axiomInfo _  => pure "axiom"
      | .defnInfo _   => pure "def"
      | .thmInfo _    => pure "theorem"
      | .opaqueInfo _ => pure "opaque"
      | .quotInfo _   => pure "quot"
      | .inductInfo _ => pure "inductive"
      | .ctorInfo _   => pure "ctor"
      | .recInfo _    => pure "rec"
    let res ← liftTermElabM <| Lean.Meta.forallTelescopeReducing ci.type fun _ body => do
      if ← Lean.Meta.isProp body then pure "PropResult"
      else match body with
        | .sort l => pure (match l with | .zero => "PropFormer" | _ => "TypeFormer")
        | _ => pure "DataResult"
    counts := counts.insert (k ++ ":" ++ res) (counts.getD (k ++ ":" ++ res) 0 + 1)
    logInfo m!"A3KIND\t{n}\t{k}\t{res}"
  logInfo m!"A3KIND-SUMMARY\t{toString counts.toList}"

