-- A3 round-9 full-namespace Prop-gated assumption-as-conclusion screen for D12-spectral-sobolev
-- generated by audit360/gen_taut_full.py; do not edit
import Audit.CounterexampleAudit
import Audit.CurvatureODEAudit
import Audit.EvolutionAudit
import Audit.GeometryAudit
import Audit.PromotedEvolutionAudit
import D6AuditReport
import Ledger.DefinitionSmoke
import Ledger.PerelmanDefinitions
import Poincare.Basic
import Poincare.D12.SpectralSobolev.All
import Poincare.D12.SpectralSobolev.AxiomAudit
import Poincare.D12.SpectralSobolev.Basic
import Poincare.D12.SpectralSobolev.Examples
import Poincare.D12.SpectralSobolev.HeatConvergence
import Poincare.D12.SpectralSobolev.Poincare
import Poincare.D12.SpectralSobolev.Semigroup
import Poincare.Longrun.CurvatureODE
import Poincare.Longrun.CurvatureODE.Bridge
import Poincare.Longrun.CurvatureODE.Evolution
import Poincare.Longrun.CurvatureODE.Invariant
import Poincare.Longrun.CurvatureODE.Monotonicity
import Poincare.Longrun.CurvatureODE.ScalarODE
import Poincare.Longrun.CurvatureODE.State
import Poincare.Longrun.Entropy
import Poincare.Longrun.Entropy.AxiomAudit
import Poincare.Longrun.Entropy.Bridge
import Poincare.Longrun.Entropy.Certificate
import Poincare.Longrun.Entropy.DiscreteHeat
import Poincare.Longrun.Entropy.FiniteGeometry
import Poincare.Longrun.Entropy.Functional
import Poincare.Longrun.Evolution
import Poincare.Longrun.Evolution.Bridge
import Poincare.Longrun.Evolution.Continuous
import Poincare.Longrun.Evolution.Counterexample
import Poincare.Longrun.Evolution.Discrete
import Poincare.Longrun.Evolution.Functional
import Poincare.Longrun.Evolution.Gibbs
import Poincare.Longrun.Geometry
import Poincare.Longrun.Geometry.ConnectionAdapter
import Poincare.Longrun.Geometry.Contraction
import Poincare.Longrun.Geometry.LeviCivitaBlocked
import Poincare.Longrun.Geometry.MetricData
import Poincare.Longrun.PDE.AxiomAudit
import Poincare.Longrun.PDE.ContinuousInterface
import Poincare.Longrun.PDE.DiscreteMaximumPrinciple
import Poincare.Longrun.PDE.Energy
import Poincare.Longrun.PDE.HeatGrid
import Poincare.Longrun.Surgery
import Poincare.Longrun.Surgery.Axioms
import Poincare.Longrun.Surgery.Basic
import Poincare.Longrun.Surgery.Chain
import Poincare.Longrun.Surgery.Missing
import Poincare.Longrun.Surgery.Toy
import Poincare.Longrun.Topology.AxiomAudit
import Poincare.Longrun.Topology.Basic
import Poincare.Longrun.Topology.CompactThreeManifold
import Poincare.Longrun.Topology.MissingTheorems
import Poincare.Longrun.Topology.Noncollapsing
import Poincare.Longrun.Topology.NormalizedVolume
import Poincare.Longrun.Topology.Stage6Bridge
import Poincare.Stage1.CurvatureAlgebra
import Poincare.Stage1.RiemannAdapter
import Poincare.Stage6.SphereSimplyConnected
import Poincare.Stage6.TopologyBridge
import Probe.GeometryApi
import Probe.PdeApi
import ReleaseAudit
import ReleaseCheck

open Lean Meta Elab Command

namespace A3TautFullScreen

/-- Positive control for the full-namespace screen. -/
theorem a3TautFullCtl (P : Prop) (h : P) : P := h

/-- Flag strings for one declaration value/type; empty means clean. -/
def checkOne (v ty : Expr) : MetaM (Array String) := do
  let ty ← instantiateMVars ty
  forallTelescopeReducing ty fun xs concl => do
    let concl ← instantiateMVars concl
    if !(← isProp concl) then return #[]
    let mut res : Array String := #[]
    let mut idxs : Array Nat := #[]
    if ← isDefEq concl (mkConst ``True) then
      res := res.push "conclusion-defeq-True"
    for h : i in [0:xs.size] do
      let d ← instantiateMVars (← xs[i].fvarId!.getType)
      if ← isDefEq d concl then
        idxs := idxs.push i
        let nm ← xs[i].fvarId!.getUserName
        res := res.push s!"hypothesis-eq-conclusion:{nm}"
    let bodyRes ← lambdaTelescope v fun ys body => do
      let mut out : Array String := #[]
      let body ← instantiateMVars body
      if let .fvar fid := body.getAppFn then
        if body.getAppArgs.all (fun a => a.isFVar) then
          for i in idxs do
            if h : i < ys.size then
              if ys[i].fvarId! == fid then
                let nm ← ys[i].fvarId!.getUserName
                out := out.push s!"proof-is-hypothesis:{nm}"
      return out
    return res ++ bodyRes

end A3TautFullScreen

open Lean Meta Elab Command in
run_cmd do
  let env ← getEnv
  let root : Name := `Poincare.D12
  let mut checked : Nat := 0
  let mut propChecked : Nat := 0
  let mut flags : Nat := 0
  match env.find? ``A3TautFullScreen.a3TautFullCtl with
  | none => logError m!"A3TAUTFULL-CONTROL-MISSING"
  | some ctl =>
    let ctlV? := match ctl with
      | .thmInfo v => some v.value
      | .defnInfo v => some v.value
      | _ => none
    match ctlV? with
    | none => logError m!"A3TAUTFULL-CONTROL-MISSING"
    | some v =>
      let outs ← liftTermElabM (A3TautFullScreen.checkOne v ctl.type)
      if outs.size == 0 then
        logError m!"A3TAUTFULL-CONTROL-MISSING"
      else
        logInfo m!"A3TAUTFULL-CONTROL-FLAGGED: {outs.toList}"
  for (n, ci) in env.constants.toList do
    if !root.isPrefixOf n then continue
    checked := checked + 1
    let v? := match ci with
      | .thmInfo v => some v.value
      | .defnInfo v => some v.value
      | _ => none
    match v? with
    | none => pure ()
    | some v =>
      let outs ← liftTermElabM do
        let ty ← instantiateMVars ci.type
        forallTelescopeReducing ty fun xs concl => do
          let concl ← instantiateMVars concl
          if !(← isProp concl) then return #[]
          let mut res : Array String := #[]
          let mut idxs : Array Nat := #[]
          if ← isDefEq concl (mkConst ``True) then
            res := res.push "conclusion-defeq-True"
          for h : i in [0:xs.size] do
            let d ← instantiateMVars (← xs[i].fvarId!.getType)
            if ← isDefEq d concl then
              idxs := idxs.push i
              let nm ← xs[i].fvarId!.getUserName
              res := res.push s!"hypothesis-eq-conclusion:{nm}"
          let bodyRes ← lambdaTelescope v fun ys body => do
            let mut out : Array String := #[]
            let body ← instantiateMVars body
            if let .fvar fid := body.getAppFn then
              if body.getAppArgs.all (fun a => a.isFVar) then
                for i in idxs do
                  if h : i < ys.size then
                    if ys[i].fvarId! == fid then
                      let nm ← ys[i].fvarId!.getUserName
                      out := out.push s!"proof-is-hypothesis:{nm}"
            return out
          return res ++ bodyRes
      propChecked := propChecked + 1
      if outs.size > 0 then
        flags := flags + 1
        logInfo m!"A3TAUTFULL-FLAG: {n} {outs.toList}"
  logInfo m!"A3TAUTFULL: checked {checked} constants, {propChecked} with proof values, flags {flags}"
