-- A3 unused-hypothesis screen for D12-spectral-sobolev
-- generated by audit360/gen_unused_hyp.py; do not edit
import Audit.CounterexampleAudit
import Audit.CurvatureODEAudit
import Audit.EvolutionAudit
import Audit.GeometryAudit
import Audit.PromotedEvolutionAudit
import D6AuditReport
import Ledger.DefinitionSmoke
import Ledger.PerelmanDefinitions
import Poincare.Basic
import Poincare.D12.SpectralSobolev.All
import Poincare.D12.SpectralSobolev.AxiomAudit
import Poincare.D12.SpectralSobolev.Basic
import Poincare.D12.SpectralSobolev.Examples
import Poincare.D12.SpectralSobolev.HeatConvergence
import Poincare.D12.SpectralSobolev.Poincare
import Poincare.D12.SpectralSobolev.Semigroup
import Poincare.Longrun.CurvatureODE
import Poincare.Longrun.CurvatureODE.Bridge
import Poincare.Longrun.CurvatureODE.Evolution
import Poincare.Longrun.CurvatureODE.Invariant
import Poincare.Longrun.CurvatureODE.Monotonicity
import Poincare.Longrun.CurvatureODE.ScalarODE
import Poincare.Longrun.CurvatureODE.State
import Poincare.Longrun.Entropy
import Poincare.Longrun.Entropy.AxiomAudit
import Poincare.Longrun.Entropy.Bridge
import Poincare.Longrun.Entropy.Certificate
import Poincare.Longrun.Entropy.DiscreteHeat
import Poincare.Longrun.Entropy.FiniteGeometry
import Poincare.Longrun.Entropy.Functional
import Poincare.Longrun.Evolution
import Poincare.Longrun.Evolution.Bridge
import Poincare.Longrun.Evolution.Continuous
import Poincare.Longrun.Evolution.Counterexample
import Poincare.Longrun.Evolution.Discrete
import Poincare.Longrun.Evolution.Functional
import Poincare.Longrun.Evolution.Gibbs
import Poincare.Longrun.Geometry
import Poincare.Longrun.Geometry.ConnectionAdapter
import Poincare.Longrun.Geometry.Contraction
import Poincare.Longrun.Geometry.LeviCivitaBlocked
import Poincare.Longrun.Geometry.MetricData
import Poincare.Longrun.PDE.AxiomAudit
import Poincare.Longrun.PDE.ContinuousInterface
import Poincare.Longrun.PDE.DiscreteMaximumPrinciple
import Poincare.Longrun.PDE.Energy
import Poincare.Longrun.PDE.HeatGrid
import Poincare.Longrun.Surgery
import Poincare.Longrun.Surgery.Axioms
import Poincare.Longrun.Surgery.Basic
import Poincare.Longrun.Surgery.Chain
import Poincare.Longrun.Surgery.Missing
import Poincare.Longrun.Surgery.Toy
import Poincare.Longrun.Topology.AxiomAudit
import Poincare.Longrun.Topology.Basic
import Poincare.Longrun.Topology.CompactThreeManifold
import Poincare.Longrun.Topology.MissingTheorems
import Poincare.Longrun.Topology.Noncollapsing
import Poincare.Longrun.Topology.NormalizedVolume
import Poincare.Longrun.Topology.Stage6Bridge
import Poincare.Stage1.CurvatureAlgebra
import Poincare.Stage1.RiemannAdapter
import Poincare.Stage6.SphereSimplyConnected
import Poincare.Stage6.TopologyBridge
import Probe.GeometryApi
import Probe.PdeApi
import ReleaseAudit
import ReleaseCheck

open Lean Elab Command

namespace A3Unused

partial def usedBinders (e : Expr) : Std.HashSet Nat :=
  go e 0 {}
where
  go (e : Expr) (depth : Nat) (acc : Std.HashSet Nat) : Std.HashSet Nat :=
    match e with
    | .bvar i => if i < depth then acc.insert (depth - 1 - i) else acc
    | .lam _ d b _ => go b (depth + 1) (go d depth acc)
    | .forallE _ d b _ => go b (depth + 1) (go d depth acc)
    | .app f a => go a depth (go f depth acc)
    | .letE _ t v b _ => go b (depth + 1) (go v depth (go t depth acc))
    | .mdata _ b => go b depth acc
    | .proj _ _ b => go b depth acc
    | _ => acc

partial def leadingLams (e : Expr) : Nat :=
  match e with
  | .lam _ _ b _ => leadingLams b + 1
  | _ => 0

partial def leadingForalls (e : Expr) : Nat :=
  match e with
  | .forallE _ _ b _ => leadingForalls b + 1
  | _ => 0

partial def binderInfos (e : Expr) : List (Name × Expr × BinderInfo) :=
  match e with
  | .forallE n d b bi => (n, d, bi) :: binderInfos b
  | _ => []

def binderTag (bi : BinderInfo) : String :=
  if bi == BinderInfo.instImplicit then "instance"
  else if bi == BinderInfo.implicit then "implicit"
  else if bi == BinderInfo.strictImplicit then "strictImplicit"
  else "explicit"

end A3Unused

run_cmd do
  let env ← getEnv
  let targets : List Name := [``Poincare.D12.SpectralSobolev.heatWeight, ``Poincare.D12.SpectralSobolev.heatWeight_zero, ``Poincare.D12.SpectralSobolev.heatWeight_pos, ``Poincare.D12.SpectralSobolev.heatWeight_nonneg, ``Poincare.D12.SpectralSobolev.heatWeight_le_one, ``Poincare.D12.SpectralSobolev.heatWeight_abs_le_one, ``Poincare.D12.SpectralSobolev.heatWeight_tendsto_one, ``Poincare.D12.SpectralSobolev.heatCoeffs, ``Poincare.D12.SpectralSobolev.heatCoeffs_apply, ``Poincare.D12.SpectralSobolev.summable_sq_heatCoeff, ``Poincare.D12.SpectralSobolev.heatCoeffsL2, ``Poincare.D12.SpectralSobolev.heatEvolve, ``Poincare.D12.SpectralSobolev.heatSeries_hasSum, ``Poincare.D12.SpectralSobolev.fourierCoeff_heatEvolve, ``Poincare.D12.SpectralSobolev.heatEvolve_norm_le, ``Poincare.D12.SpectralSobolev.heatEvolve_tendsto_self, ``Poincare.D12.SpectralSobolev.heatEvolve_fourierLp, ``Poincare.D12.SpectralSobolev.norm_heatEvolve_fourierLp, ``Poincare.D12.SpectralSobolev.sq_eigenvalue_pos, ``Poincare.D12.SpectralSobolev.heatWeight_lt_one_of_pos, ``Poincare.D12.SpectralSobolev.heatEvolve_zero, ``Poincare.D12.SpectralSobolev.heatEvolve_add, ``Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic, ``Poincare.D12.SpectralSobolev.sq_norm_eigenvalue, ``Poincare.D12.SpectralSobolev.sq_norm_fourierCoeffOn_deriv_periodic, ``Poincare.D12.SpectralSobolev.fourierCoeffOn_zero_eq_mean, ``Poincare.D12.SpectralSobolev.poincare_wirtinger, ``Poincare.D12.SpectralSobolev.norm_sin_le_one, ``Poincare.D12.SpectralSobolev.norm_cos_le_one, ``Poincare.D12.SpectralSobolev.sine_wave_hypotheses, ``Poincare.D12.SpectralSobolev.integral_sin_sq_period, ``Poincare.D12.SpectralSobolev.integral_cos_sq_period, ``Poincare.D12.SpectralSobolev.poincare_wirtinger_sine, ``Poincare.D12.SpectralSobolev.poincare_wirtinger_sine_saturates, ``Poincare.D12.SpectralSobolev.poincare_constant_sharp, ``Poincare.D12.SpectralSobolev.heat_evolution_first_mode_nontrivial]
  let mut flagged : Nat := 0
  let mut explicitFlagged : Nat := 0
  let mut checked : Nat := 0
  let mut skipped : Nat := 0
  for t in targets do
    match env.find? t with
    | none => logError m!"A3UNUSED: missing {t}"
    | some ci =>
      let v? := match ci with
        | .thmInfo v => some v.value
        | .defnInfo v => some v.value
        | _ => none
      match v? with
      | none => skipped := skipped + 1
      | some v =>
        let nv := A3Unused.leadingLams v
        let nt := A3Unused.leadingForalls ci.type
        if nv == nt && nv > 0 then
          checked := checked + 1
          let used := A3Unused.usedBinders v
          let infos := A3Unused.binderInfos ci.type
          for i in List.range nv do
            if !used.contains i then
              let (n, d, bi) := infos[i]!
              flagged := flagged + 1
              let tag := A3Unused.binderTag bi
              if tag == "explicit" then explicitFlagged := explicitFlagged + 1
              logInfo m!"A3UNUSED-FLAG: {t} binder#{i} ({n} : {d}) [{tag}]"
        else
          skipped := skipped + 1
  logInfo m!"A3UNUSED: checked {checked}, skipped {skipped}, flags {flagged}, explicit flags {explicitFlagged}"
