/-
Independent reverse-use probe for D13-integrated-kernel-audit (generated by gen_useprobe.py).
Reports direct users of each constructor in the elaborated environment and whether
each declared downstream pair mentions the constructor in type and/or value.
-/
import Poincare.D13.IntegratedAudit.SnapshotRoot
import ReleaseCheck
import Lean.Util.CollectAxioms

open Lean Elab Command

namespace D13XUse_D13_integrated_kernel_audit

def constructors : List Name := [
  "Poincare.D12.ConnectionCurvature.leviCivitaExists".toName,
  "Poincare.D12.ConnectionCurvature.milnorConnection".toName,
  "Poincare.D12.EntropyVariation.fDerivativeStatement_of_corrected_of_idempotent".toName,
  "Poincare.D12.EntropyVariation.fflow_F_hasDerivAt".toName,
  "Poincare.D12.EntropyVariation.hasDerivAt_F_of_pointwise".toName,
  "Poincare.D12.HeatDomain.flatHeatKernelCore_weakInitialConditionFor_integrableClass".toName,
  "Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel".toName,
  "Poincare.D12.HeatDomain.not_fullInitialCondition_flat_of_pos".toName,
  "Poincare.D12.HeatSemigroup.heatOperatorBCF_comp".toName,
  "Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator".toName,
  "Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator_of_bounded".toName,
  "Poincare.D12.KappaVariational.constantCurvatureLMinimizerExistence".toName,
  "Poincare.D12.KappaVariational.gaussianReducedVolumeViaL_eq_one".toName,
  "Poincare.D12.KappaVariational.gaussianReducedVolume_eq_one".toName,
  "Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds".toName,
  "Poincare.D12.ParabolicLocal.gaussianSmap_continuous".toName,
  "Poincare.D12.ParabolicLocal.heatConv_semigroup".toName,
  "Poincare.D12.ParabolicLocal.heatConv_tendsto_self_BUC".toName,
  "Poincare.D12.SurgeryRecognition.ConnectedSumDecomposition.mkV2".toName,
  "Poincare.D12.SurgeryRecognition.deckTrivial_of_simplyConnected_quotient".toName,
  "Poincare.D12.SurgeryRecognition.finiteFreeOrbit_isQuotientCoveringMap".toName,
  "Poincare.D12.TensorMaximumBochner.adjugate_posSemidef".toName,
  "Poincare.D12.TensorMaximumBochner.hamiltonField_kernelTangent".toName,
  "Poincare.D12.TensorMaximumBochner.kernelTangent_of_feasibleDirection".toName,
  "Poincare.D12.TriangulationTopology.alexanderHomeo".toName,
  "Poincare.D12.TriangulationTopology.antipodalQuotientCovering".toName,
  "Poincare.D12.TriangulationTopology.coveringOfSimplyConnectedIsHomeo".toName,
  "Poincare.D12.TriangulationTopology.diskGlueQuotHomeoSphere".toName,
  "Poincare.D12.TriangulationTopology.simplexHomeoDisk".toName,
  "Poincare.D12.TriangulationTopology.sphereOfTwoDisks".toName]

def pairs : List (Name × Name) := [
  ("Poincare.D12.ConnectionCurvature.leviCivitaExists".toName, "Poincare.D12.ConnectionCurvature.SoThreeModel.so3MeanLeviCivita".toName),
  ("Poincare.D12.ConnectionCurvature.leviCivitaExists".toName, "Poincare.D12.ConnectionCurvature.SoThreeModel.so3_ricci_e00".toName),
  ("Poincare.D12.ConnectionCurvature.milnorConnection".toName, "Poincare.D12.ConnectionCurvature.SoThreeModel.so3_ricci_e00".toName),
  ("Poincare.D12.ConnectionCurvature.milnorConnection".toName, "Poincare.D12.ConnectionCurvature.leviCivitaExists".toName),
  ("Poincare.D12.EntropyVariation.fflow_F_deriv_pos".toName, "Poincare.D12.EntropyVariation.fflow_F_strictMonoOn".toName),
  ("Poincare.D12.EntropyVariation.fflow_F_hasDerivAt".toName, "Poincare.D12.EntropyVariation.fflow_F_hasDerivAt_closedForm".toName),
  ("Poincare.D12.EntropyVariation.fflow_F_hasDerivAt_closedForm".toName, "Poincare.D12.EntropyVariation.fflow_F_deriv_pos".toName),
  ("Poincare.D12.EntropyVariation.fflow_F_strictMonoOn".toName, "Poincare.D12.EntropyVariation.derivative_sign_distinction".toName),
  ("Poincare.D12.EntropyVariation.hasDerivAt_F_of_pointwise".toName, "Poincare.D12.EntropyVariation.fflow_F_hasDerivAt".toName),
  ("Poincare.D12.HeatDomain.flatHeatKernelCore_weakInitialConditionFor_integrableClass".toName, "Poincare.D12.HeatDomain.flatHeatKernelCore_weakInitialConditionFor_ccClass".toName),
  ("Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel".toName, "Poincare.D12.HeatDomain.not_fullInitialCondition_flat_of_pos".toName),
  ("Poincare.D12.HeatDomain.not_fullInitialCondition_flat_of_pos".toName, "Poincare.D12.HeatDomain.flat_positive_dimension_weak_not_full".toName),
  ("Poincare.D12.HeatDomain.toHeatKernelData_of_weak_compact_finiteMeasure".toName, "Poincare.D7.HeatKernel.punitHeatKernelData".toName),
  ("Poincare.D12.HeatSemigroup.heatOperatorBCF_comp".toName, "Poincare.D12.HeatSemigroup.heatOperator_gaussianKernel_L1_tendsto_seq".toName),
  ("Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator".toName, "Poincare.D12.HeatSemigroup.heatOperatorBCF_comp".toName),
  ("Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator".toName, "Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator_integral_norm_eq_zero".toName),
  ("Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator_of_bounded".toName, "Poincare.D12.HeatSemigroup.heatOperatorBCF_comp".toName),
  ("Poincare.D12.KappaVariational.constantCurvatureLMinimizerExistence".toName, "Poincare.D12.KappaVariational.constantCurvature_reducedLength_le".toName),
  ("Poincare.D12.KappaVariational.gaussianReducedVolumeViaL_eq_one".toName, "Poincare.D12.KappaVariational.gaussianUniformReducedVolumeLowerBound".toName),
  ("Poincare.D12.KappaVariational.gaussianReducedVolume_eq_one".toName, "Poincare.D12.KappaVariational.gaussianReducedVolumeCertificate_volume".toName),
  ("Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds".toName, "Poincare.D12.ParabolicLocal.derivativeLossBarrier_discharged".toName),
  ("Poincare.D12.ParabolicLocal.gaussianS_add".toName, "Poincare.D12.ParabolicLocal.linearCandidate_isFixedPt".toName),
  ("Poincare.D12.ParabolicLocal.heatConv_semigroup".toName, "Poincare.D12.ParabolicLocal.linearCandidate_isFixedPt".toName),
  ("Poincare.D12.ParabolicLocal.heatConv_tendsto_self_BUC".toName, "Poincare.D12.ParabolicLocal.gaussianS_tendsto_self".toName),
  ("Poincare.D12.ParabolicLocal.heatConv_tendsto_self_BUC".toName, "Poincare.D12.ParabolicLocal.gaussianSmap_continuous".toName),
  ("Poincare.D12.SurgeryRecognition.ConnectedSumDecomposition.mkV2".toName, "Poincare.D12.SurgeryRecognition.stage6Target_of_v2decomposition".toName),
  ("Poincare.D12.SurgeryRecognition.deckTrivial_of_simplyConnected_quotient".toName, "Poincare.D12.SurgeryRecognition.sphericalPieceRecognition_of_spaceForm".toName),
  ("Poincare.D12.TriangulationTopology.alexanderHomeo".toName, "Poincare.D12.TriangulationTopology.diskGlueQuotHomeoSphere".toName),
  ("Poincare.D12.TriangulationTopology.coveringOfSimplyConnectedIsHomeo".toName, "Poincare.D12.TriangulationTopology.sphericalSpaceFormRecognition".toName),
  ("Poincare.D12.TriangulationTopology.diskGlueQuotHomeoSphere".toName, "Poincare.D12.TriangulationTopology.sphereOfTwoDisks".toName)]

end D13XUse_D13_integrated_kernel_audit

open D13XUse_D13_integrated_kernel_audit in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let mut rows : Array (Name × Name × Bool × Bool) := #[]
  for (ctor, down) in pairs do
    let inType := match env.find? down with
      | some ci => ci.type.getUsedConstants.contains ctor
      | none => false
    let inValue := match env.find? down with
      | some ci => (match ci.value? true with
          | some v => v.getUsedConstants.contains ctor
          | none => false)
      | none => false
    rows := rows.push (ctor, down, inType, inValue)
  -- reverse direct-use census: declarations whose type or value mentions the constructor
  let scanPrefixes : List Name := ["Poincare.D12".toName,
    "Poincare.D7".toName,
    "Poincare.D13".toName,
    "Poincare.D11".toName]
  let inScan (n : Name) : Bool :=
    match env.getModuleIdxFor? n with
    | some midx =>
        let m := mods.getD midx .anonymous
        scanPrefixes.isEmpty || scanPrefixes.any (fun r => r.isPrefixOf m)
    | none => scanPrefixes.isEmpty
  let decls := env.constants.fold (fun acc n _ => if inScan n then acc.push n else acc) #[]
  for ctor in constructors do
    IO.println s!"D13XEXISTS	{ctor}	{(env.find? ctor).isSome}"
    let mut direct : Array Name := #[]
    for d in decls do
      if d == ctor then continue
      match env.find? d with
      | some ci =>
          let inT := ci.type.getUsedConstants.contains ctor
          let inV := match ci.value? true with
            | some v => v.getUsedConstants.contains ctor
            | none => false
          if inT || inV then direct := direct.push d
      | none => pure ()
    IO.println s!"D13XUSE\t{ctor}\tdirect_users\t{direct.size}"
    for d in direct.qsort (fun a b => a.toString < b.toString) do
      IO.println s!"D13XUSER\t{ctor}\t{d}"
  for (ctor, down, inT, inV) in rows do
    IO.println s!"D13XPAIR\t{ctor}\t{down}\ttype={inT}\tvalue={inV}\tdown_exists={(env.find? down).isSome}"
  IO.println s!"D13XUSE_DONE\tD13-integrated-kernel-audit"
