-- A3 independent probe for D12-spectral-sobolev
-- generated by D13-cross-audit-360-cards; do not edit

import Poincare.D12.SpectralSobolev.Basic
import Poincare.D12.SpectralSobolev.Examples
import Poincare.D12.SpectralSobolev.HeatConvergence
import Poincare.D12.SpectralSobolev.Poincare
import Poincare.D12.SpectralSobolev.Semigroup

set_option maxHeartbeats 200000

#check Poincare.D12.SpectralSobolev.heatWeight
#check Poincare.D12.SpectralSobolev.heatWeight_zero
#check Poincare.D12.SpectralSobolev.heatWeight_pos
#check Poincare.D12.SpectralSobolev.heatWeight_nonneg
#check Poincare.D12.SpectralSobolev.heatWeight_le_one
#check Poincare.D12.SpectralSobolev.heatWeight_abs_le_one
#check Poincare.D12.SpectralSobolev.heatWeight_tendsto_one
#check Poincare.D12.SpectralSobolev.heatCoeffs
#check Poincare.D12.SpectralSobolev.heatCoeffs_apply
#check Poincare.D12.SpectralSobolev.summable_sq_heatCoeff
#check Poincare.D12.SpectralSobolev.heatCoeffsL2
#check Poincare.D12.SpectralSobolev.heatEvolve
#check Poincare.D12.SpectralSobolev.heatSeries_hasSum
#check Poincare.D12.SpectralSobolev.fourierCoeff_heatEvolve
#check Poincare.D12.SpectralSobolev.heatEvolve_norm_le
#check Poincare.D12.SpectralSobolev.heatEvolve_tendsto_self
#check Poincare.D12.SpectralSobolev.heatEvolve_fourierLp
#check Poincare.D12.SpectralSobolev.norm_heatEvolve_fourierLp
#check Poincare.D12.SpectralSobolev.sq_eigenvalue_pos
#check Poincare.D12.SpectralSobolev.heatWeight_lt_one_of_pos
#check Poincare.D12.SpectralSobolev.heatEvolve_zero
#check Poincare.D12.SpectralSobolev.heatEvolve_add
#check Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic
#check Poincare.D12.SpectralSobolev.sq_norm_eigenvalue
#check Poincare.D12.SpectralSobolev.sq_norm_fourierCoeffOn_deriv_periodic
#check Poincare.D12.SpectralSobolev.fourierCoeffOn_zero_eq_mean
#check Poincare.D12.SpectralSobolev.poincare_wirtinger
#check Poincare.D12.SpectralSobolev.norm_sin_le_one
#check Poincare.D12.SpectralSobolev.norm_cos_le_one
#check Poincare.D12.SpectralSobolev.sine_wave_hypotheses
#check Poincare.D12.SpectralSobolev.integral_sin_sq_period
#check Poincare.D12.SpectralSobolev.integral_cos_sq_period
#check Poincare.D12.SpectralSobolev.poincare_wirtinger_sine
#check Poincare.D12.SpectralSobolev.poincare_wirtinger_sine_saturates
#check Poincare.D12.SpectralSobolev.poincare_constant_sharp
#check Poincare.D12.SpectralSobolev.heat_evolution_first_mode_nontrivial

#print axioms Poincare.D12.SpectralSobolev.heatWeight
#print axioms Poincare.D12.SpectralSobolev.heatWeight_zero
#print axioms Poincare.D12.SpectralSobolev.heatWeight_pos
#print axioms Poincare.D12.SpectralSobolev.heatWeight_nonneg
#print axioms Poincare.D12.SpectralSobolev.heatWeight_le_one
#print axioms Poincare.D12.SpectralSobolev.heatWeight_abs_le_one
#print axioms Poincare.D12.SpectralSobolev.heatWeight_tendsto_one
#print axioms Poincare.D12.SpectralSobolev.heatCoeffs
#print axioms Poincare.D12.SpectralSobolev.heatCoeffs_apply
#print axioms Poincare.D12.SpectralSobolev.summable_sq_heatCoeff
#print axioms Poincare.D12.SpectralSobolev.heatCoeffsL2
#print axioms Poincare.D12.SpectralSobolev.heatEvolve
#print axioms Poincare.D12.SpectralSobolev.heatSeries_hasSum
#print axioms Poincare.D12.SpectralSobolev.fourierCoeff_heatEvolve
#print axioms Poincare.D12.SpectralSobolev.heatEvolve_norm_le
#print axioms Poincare.D12.SpectralSobolev.heatEvolve_tendsto_self
#print axioms Poincare.D12.SpectralSobolev.heatEvolve_fourierLp
#print axioms Poincare.D12.SpectralSobolev.norm_heatEvolve_fourierLp
#print axioms Poincare.D12.SpectralSobolev.sq_eigenvalue_pos
#print axioms Poincare.D12.SpectralSobolev.heatWeight_lt_one_of_pos
#print axioms Poincare.D12.SpectralSobolev.heatEvolve_zero
#print axioms Poincare.D12.SpectralSobolev.heatEvolve_add
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic
#print axioms Poincare.D12.SpectralSobolev.sq_norm_eigenvalue
#print axioms Poincare.D12.SpectralSobolev.sq_norm_fourierCoeffOn_deriv_periodic
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_zero_eq_mean
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger
#print axioms Poincare.D12.SpectralSobolev.norm_sin_le_one
#print axioms Poincare.D12.SpectralSobolev.norm_cos_le_one
#print axioms Poincare.D12.SpectralSobolev.sine_wave_hypotheses
#print axioms Poincare.D12.SpectralSobolev.integral_sin_sq_period
#print axioms Poincare.D12.SpectralSobolev.integral_cos_sq_period
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger_sine
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger_sine_saturates
#print axioms Poincare.D12.SpectralSobolev.poincare_constant_sharp
#print axioms Poincare.D12.SpectralSobolev.heat_evolution_first_mode_nontrivial
