-- A3 round-9 kernel assumption-as-conclusion screen for D12-spectral-sobolev
-- generated by audit360/gen_taut_screen.py; do not edit
import Audit.CounterexampleAudit
import Audit.CurvatureODEAudit
import Audit.EvolutionAudit
import Audit.GeometryAudit
import Audit.PromotedEvolutionAudit
import D6AuditReport
import Ledger.DefinitionSmoke
import Ledger.PerelmanDefinitions
import Poincare.Basic
import Poincare.D12.SpectralSobolev.All
import Poincare.D12.SpectralSobolev.AxiomAudit
import Poincare.D12.SpectralSobolev.Basic
import Poincare.D12.SpectralSobolev.Examples
import Poincare.D12.SpectralSobolev.HeatConvergence
import Poincare.D12.SpectralSobolev.Poincare
import Poincare.D12.SpectralSobolev.Semigroup
import Poincare.Longrun.CurvatureODE
import Poincare.Longrun.CurvatureODE.Bridge
import Poincare.Longrun.CurvatureODE.Evolution
import Poincare.Longrun.CurvatureODE.Invariant
import Poincare.Longrun.CurvatureODE.Monotonicity
import Poincare.Longrun.CurvatureODE.ScalarODE
import Poincare.Longrun.CurvatureODE.State
import Poincare.Longrun.Entropy
import Poincare.Longrun.Entropy.AxiomAudit
import Poincare.Longrun.Entropy.Bridge
import Poincare.Longrun.Entropy.Certificate
import Poincare.Longrun.Entropy.DiscreteHeat
import Poincare.Longrun.Entropy.FiniteGeometry
import Poincare.Longrun.Entropy.Functional
import Poincare.Longrun.Evolution
import Poincare.Longrun.Evolution.Bridge
import Poincare.Longrun.Evolution.Continuous
import Poincare.Longrun.Evolution.Counterexample
import Poincare.Longrun.Evolution.Discrete
import Poincare.Longrun.Evolution.Functional
import Poincare.Longrun.Evolution.Gibbs
import Poincare.Longrun.Geometry
import Poincare.Longrun.Geometry.ConnectionAdapter
import Poincare.Longrun.Geometry.Contraction
import Poincare.Longrun.Geometry.LeviCivitaBlocked
import Poincare.Longrun.Geometry.MetricData
import Poincare.Longrun.PDE.AxiomAudit
import Poincare.Longrun.PDE.ContinuousInterface
import Poincare.Longrun.PDE.DiscreteMaximumPrinciple
import Poincare.Longrun.PDE.Energy
import Poincare.Longrun.PDE.HeatGrid
import Poincare.Longrun.Surgery
import Poincare.Longrun.Surgery.Axioms
import Poincare.Longrun.Surgery.Basic
import Poincare.Longrun.Surgery.Chain
import Poincare.Longrun.Surgery.Missing
import Poincare.Longrun.Surgery.Toy
import Poincare.Longrun.Topology.AxiomAudit
import Poincare.Longrun.Topology.Basic
import Poincare.Longrun.Topology.CompactThreeManifold
import Poincare.Longrun.Topology.MissingTheorems
import Poincare.Longrun.Topology.Noncollapsing
import Poincare.Longrun.Topology.NormalizedVolume
import Poincare.Longrun.Topology.Stage6Bridge
import Poincare.Stage1.CurvatureAlgebra
import Poincare.Stage1.RiemannAdapter
import Poincare.Stage6.SphereSimplyConnected
import Poincare.Stage6.TopologyBridge
import Probe.GeometryApi
import Probe.PdeApi
import ReleaseAudit
import ReleaseCheck

open Lean Meta Elab Command

namespace A3TautScreen

/-- Positive control: the conclusion is literally the hypothesis.  The screen
must flag it. -/
theorem a3TautCtl (P : Prop) (h : P) : P := h

end A3TautScreen

open Lean Meta Elab Command in
run_cmd do
  let env ← getEnv
  let targets : List Name := [``A3TautScreen.a3TautCtl, ``Poincare.D12.SpectralSobolev.heatWeight, ``Poincare.D12.SpectralSobolev.heatWeight_zero, ``Poincare.D12.SpectralSobolev.heatWeight_pos, ``Poincare.D12.SpectralSobolev.heatWeight_nonneg, ``Poincare.D12.SpectralSobolev.heatWeight_le_one, ``Poincare.D12.SpectralSobolev.heatWeight_abs_le_one, ``Poincare.D12.SpectralSobolev.heatWeight_tendsto_one, ``Poincare.D12.SpectralSobolev.heatCoeffs, ``Poincare.D12.SpectralSobolev.heatCoeffs_apply, ``Poincare.D12.SpectralSobolev.summable_sq_heatCoeff, ``Poincare.D12.SpectralSobolev.heatCoeffsL2, ``Poincare.D12.SpectralSobolev.heatEvolve, ``Poincare.D12.SpectralSobolev.heatSeries_hasSum, ``Poincare.D12.SpectralSobolev.fourierCoeff_heatEvolve, ``Poincare.D12.SpectralSobolev.heatEvolve_norm_le, ``Poincare.D12.SpectralSobolev.heatEvolve_tendsto_self, ``Poincare.D12.SpectralSobolev.heatEvolve_fourierLp, ``Poincare.D12.SpectralSobolev.norm_heatEvolve_fourierLp, ``Poincare.D12.SpectralSobolev.sq_eigenvalue_pos, ``Poincare.D12.SpectralSobolev.heatWeight_lt_one_of_pos, ``Poincare.D12.SpectralSobolev.heatEvolve_zero, ``Poincare.D12.SpectralSobolev.heatEvolve_add, ``Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic, ``Poincare.D12.SpectralSobolev.sq_norm_eigenvalue, ``Poincare.D12.SpectralSobolev.sq_norm_fourierCoeffOn_deriv_periodic, ``Poincare.D12.SpectralSobolev.fourierCoeffOn_zero_eq_mean, ``Poincare.D12.SpectralSobolev.poincare_wirtinger, ``Poincare.D12.SpectralSobolev.norm_sin_le_one, ``Poincare.D12.SpectralSobolev.norm_cos_le_one, ``Poincare.D12.SpectralSobolev.sine_wave_hypotheses, ``Poincare.D12.SpectralSobolev.integral_sin_sq_period, ``Poincare.D12.SpectralSobolev.integral_cos_sq_period, ``Poincare.D12.SpectralSobolev.poincare_wirtinger_sine, ``Poincare.D12.SpectralSobolev.poincare_wirtinger_sine_saturates, ``Poincare.D12.SpectralSobolev.poincare_constant_sharp, ``Poincare.D12.SpectralSobolev.heat_evolution_first_mode_nontrivial]
  let mut checked : Nat := 0
  let mut flags : Nat := 0
  for t in targets do
    match env.find? t with
    | none => logError m!"A3TAUT-MISSING: {t}"
    | some ci =>
      let v? := match ci with
        | .thmInfo v => some v.value
        | .defnInfo v => some v.value
        | _ => none
      match v? with
      | none => pure ()
      | some v =>
        checked := checked + 1
        let (typeRes, idxs) ← liftTermElabM do
          let ty ← instantiateMVars ci.type
          forallTelescopeReducing ty fun xs concl => do
            let mut res : Array String := #[]
            let mut idxs : Array Nat := #[]
            let concl ← instantiateMVars concl
            if ← isDefEq concl (mkConst ``True) then
              res := res.push "conclusion-defeq-True"
            for h : i in [0:xs.size] do
              let d ← instantiateMVars (← xs[i].fvarId!.getType)
              if ← isDefEq d concl then
                idxs := idxs.push i
                let n ← xs[i].fvarId!.getUserName
                res := res.push s!"hypothesis-eq-conclusion:{n}"
            return (res, idxs)
        let bodyRes ← liftTermElabM do
          lambdaTelescope v fun ys body => do
            let mut out : Array String := #[]
            let body ← instantiateMVars body
            let head := body.getAppFn
            if let .fvar fid := head then
              if body.getAppArgs.all (fun a => a.isFVar) then
                for i in idxs do
                  if h : i < ys.size then
                    if ys[i].fvarId! == fid then
                      let n ← ys[i].fvarId!.getUserName
                      out := out.push s!"proof-is-hypothesis:{n}"
            return out
        let outs := typeRes ++ bodyRes
        if outs.size > 0 then
          flags := flags + 1
          logInfo m!"A3TAUT-FLAG: {t} {outs.toList}"
  logInfo m!"A3TAUT: checked {checked}, flags {flags}"
