-- A3 declaration-kind audit for D12-comparison-geodesics
-- generated by D13-cross-audit-360-cards; do not edit

import Poincare.D12.ComparisonGeodesics.Definitions
import Poincare.D12.ComparisonGeodesics.ModelEuclidean
import Poincare.D12.ComparisonGeodesics.RiccatiComparison
import Poincare.D12.ComparisonGeodesics.SingularRiccati
import Poincare.D12.ComparisonGeodesics.SturmComparison
import Poincare.D12.ComparisonGeodesics.VolumeRatio

set_option maxHeartbeats 400000


open Lean Elab Command

def a3KindNames : List Name := [
  `Poincare.D12.ComparisonGeodesics.sturm_zero_comparison,
  `Poincare.D12.ComparisonGeodesics.logDeriv_le_of_le,
  `Poincare.D12.ComparisonGeodesics.solution_le_of_same_initial,
  `Poincare.D12.ComparisonGeodesics.riccati_le_of_singular_normalization,
  `Poincare.D12.ComparisonGeodesics.riccati_ge_of_singular_normalization,
  `Poincare.D12.ComparisonGeodesics.euclideanNormalizedOn_not_continuousOn_zero,
  `Poincare.D12.ComparisonGeodesics.areaRatio_antitone_of_logDeriv_le,
  `Poincare.D12.ComparisonGeodesics.radialVolume_pos_of_pos,
  `Poincare.D12.ComparisonGeodesics.volumeRatio_antitone,
  `Poincare.D12.ComparisonGeodesics.bishopGromovVolumeRatio,
  `Poincare.D12.ComparisonGeodesics.bishopGromov_volume_le,
  `Poincare.D12.ComparisonGeodesics.euclidModel_singular_comparison_ge,
  `Poincare.D12.ComparisonGeodesics.euclidModel_bishopGromov,
  `Poincare.D12.ComparisonGeodesics.euclidModel_volume,
  `Poincare.D12.ComparisonGeodesics.riccati_delta_le_exp,
  `Poincare.D12.ComparisonGeodesics.riccati_delta_ge_exp,
  `Poincare.D12.ComparisonGeodesics.riccati_le_of_initial,
  `Poincare.D12.ComparisonGeodesics.riccati_ge_of_initial,
  `Poincare.D12.ComparisonGeodesics.wronskian_deriv,
  `Poincare.D12.ComparisonGeodesics.wronskian_antitoneOn_of_le,
  `Poincare.D12.ComparisonGeodesics.sturm_zero_comparison_of_pos,
  `Poincare.D12.ComparisonGeodesics.sign_constant_of_no_zero,
  `Poincare.D12.ComparisonGeodesics.deriv_nonpos_of_posOn_Ioo_of_eq_at_right,
  `Poincare.D12.ComparisonGeodesics.nonneg_of_continuousOn_of_posOn_Ioo,
  `Poincare.D12.ComparisonGeodesics.logDeriv_hasDerivAt,
  `Poincare.D12.ComparisonGeodesics.logDeriv_riccati,
  `Poincare.D12.ComparisonGeodesics.areaRatio_hasDerivAt,
  `Poincare.D12.ComparisonGeodesics.radialVolume_hasDerivAt,
  `Poincare.D12.ComparisonGeodesics.radialVolume_numerator_le_zero,
  `Poincare.D12.ComparisonGeodesics.hasDerivAtR_id,
  `Poincare.D12.ComparisonGeodesics.hasDerivAtR_const,
  `Poincare.D12.ComparisonGeodesics.hasDerivAtR_inv,
  `Poincare.D12.ComparisonGeodesics.hasDerivAtR_pow
]

run_cmd do
  let mut counts : Std.HashMap String Nat := {}
  for n in a3KindNames do
    let ci ← getConstInfo n
    let k : String ← match ci with
      | .axiomInfo _  => pure "axiom"
      | .defnInfo _   => pure "def"
      | .thmInfo _    => pure "theorem"
      | .opaqueInfo _ => pure "opaque"
      | .quotInfo _   => pure "quot"
      | .inductInfo _ => pure "inductive"
      | .ctorInfo _   => pure "ctor"
      | .recInfo _    => pure "rec"
    let res ← liftTermElabM <| Lean.Meta.forallTelescopeReducing ci.type fun _ body => do
      if ← Lean.Meta.isProp body then pure "PropResult"
      else match body with
        | .sort l => pure (match l with | .zero => "PropFormer" | _ => "TypeFormer")
        | _ => pure "DataResult"
    counts := counts.insert (k ++ ":" ++ res) (counts.getD (k ++ ":" ++ res) 0 + 1)
    logInfo m!"A3KIND\t{n}\t{k}\t{res}"
  logInfo m!"A3KIND-SUMMARY\t{toString counts.toList}"

