import Poincare.D13.ManifoldIBP.ChartSum
import Poincare.D13.ManifoldIBP.DisjointModel
import Poincare.D13.ManifoldIBP.GlobalMeasure
import Poincare.D13.ManifoldIBP.OverlapIBP
import Poincare.D13.ManifoldIBP.SmoothAtlasIBP
import Poincare.D13.ManifoldIBP.SmoothPartition
import Poincare.D13.VolumeForm.Basic
import Poincare.D13.VolumeForm.Gluing

#print Poincare.D13.ManifoldIBP.ChartSumData.density
#print Poincare.D13.ManifoldIBP.ChartSumData.driftLaplacian
#print Poincare.D13.ManifoldIBP.ChartSumData.gradInnerInverse
#print Poincare.D13.ManifoldIBP.ChartSumData.laplacian
#print Poincare.D13.ManifoldIBP.ChartSumData.divergence
#print Poincare.D13.ManifoldIBP.ChartSumData.globalIntegral
#print Poincare.D13.ManifoldIBP.ChartSumData.globalIntegralUnweighted
#print Poincare.D13.ManifoldIBP.OverlapAtlas.weight
#print Poincare.D13.ManifoldIBP.OverlapAtlas.chartPiece
#print Poincare.D13.ManifoldIBP.overlapOf
#print Poincare.D13.ManifoldIBP.jacobianOf
#print Poincare.D13.ManifoldIBP.OverlapAtlas.dilationAtlasTwoData
#print Poincare.D13.ManifoldIBP.OverlapAtlas.disjointAtlasData
#print Poincare.D13.ManifoldIBP.OverlapAtlas.disjointAtlasMeasure
#print Poincare.D13.ManifoldIBP.OverlapAtlas.weightedChartMeasure
#print Poincare.D13.ManifoldIBP.OverlapAtlas.disjointAtlas_weightedIBP
#print Poincare.D13.ManifoldIBP.OverlapAtlas.integral_disjointAtlasMeasure
#print Poincare.D13.ManifoldIBP.OverlapAtlas.dilationAtlasTwo_integral_eq_chart
#print Poincare.D13.ManifoldIBP.OverlapAtlas.pouPiece
#print Poincare.D13.ManifoldIBP.OverlapAtlas.pouPairing
#print Poincare.D13.ManifoldIBP.OverlapAtlas.hsAtlas
#print Poincare.D13.ManifoldIBP.OverlapAtlas.dilationAtlas
#print Poincare.D13.ManifoldIBP.OverlapAtlas.gradInnerInverse_finset_sum
#print Poincare.D13.VolumeForm.chartVolumeForm
#print Poincare.D13.VolumeForm.gluedDensity
#print Poincare.D13.VolumeForm.ChartPartitionOfUnity.gluedDensity_eq_of_supportCompatible
#print Poincare.D13.VolumeForm.ChartPartitionOfUnity.integral_gluedDensity_eq_sum
#print Poincare.D13.Riemannian.chartGramMatrix
#print Poincare.D13.Riemannian.chartMetricCoeff
#print Poincare.D13.Riemannian.chartTransition
#print Poincare.D13.Riemannian.chartOverlap
#print Poincare.D13.Riemannian.extendedSmoothChartMetric
#print Poincare.D13.VolumeForm.chartVolumeForm_pullback_orientationPreserving
#print Poincare.D13.Riemannian.trivializationAt_symm_eq_tangentCoordChange
#print Poincare.D13.Riemannian.chartGramMatrix_change
#print Poincare.D13.Riemannian.chartGramMatrix_det_pos
#print Poincare.D13.Riemannian.chartFrameVec_eq_symm_tangentCoordChange
#print Poincare.D13.ManifoldIBP.OverlapAtlas.dilationAtlasTwo_chartMeasure_absolutelyContinuous
#print Poincare.D13.ManifoldIBP.OverlapAtlas.dilationAtlasTwo_globalMeasure_eq_chartMeasure
