-- A3 declaration-kind audit for D12-tensor-maximum-bochner
-- generated by D13-cross-audit-360-cards; do not edit

import Poincare.D12.TensorMaximumBochner.Audit
import Poincare.D12.TensorMaximumBochner.TangentCone

set_option maxHeartbeats 400000


open Lean Elab Command

def a3KindNames : List Name := [
  `Poincare.D12.TensorMaximumBochner.KernelTangent,
  `Poincare.D12.TensorMaximumBochner.StrictKernelTangent,
  `Poincare.D12.TensorMaximumBochner.FeasibleDirection,
  `Poincare.D12.TensorMaximumBochner.continuous_dotProduct_mulVec,
  `Poincare.D12.TensorMaximumBochner.kernelTangent_of_feasibleDirection,
  `Poincare.D12.TensorMaximumBochner.kernelTangent_of_posSemidef_path,
  `Poincare.D12.TensorMaximumBochner.counterexampleA,
  `Poincare.D12.TensorMaximumBochner.counterexampleA_posSemidef,
  `Poincare.D12.TensorMaximumBochner.counterexample_kernelTangent,
  `Poincare.D12.TensorMaximumBochner.counterexample_not_feasible,
  `Poincare.D12.TensorMaximumBochner.kernelTangent_not_feasible,
  `Poincare.D12.TensorMaximumBochner.adjugate_eq_det_smul_inv,
  `Poincare.D12.TensorMaximumBochner.adjugate_posSemidef,
  `Poincare.D12.TensorMaximumBochner.hamiltonField,
  `Poincare.D12.TensorMaximumBochner.dotProduct_mulVec_sq,
  `Poincare.D12.TensorMaximumBochner.hamiltonField_kernelTangent,
  `Poincare.D12.TensorMaximumBochner.hamiltonField_not_strengthened,
  `Poincare.D12.TensorMaximumBochner.hamiltonField_kernel_witness,
  `Poincare.D12.TensorMaximumBochner.counterexample_nondegenerate,
  `Poincare.D12.TensorMaximumBochner.Audit.d12_kernel_tangent_necessary_audited
]

run_cmd do
  let mut counts : Std.HashMap String Nat := {}
  for n in a3KindNames do
    let ci ← getConstInfo n
    let k : String ← match ci with
      | .axiomInfo _  => pure "axiom"
      | .defnInfo _   => pure "def"
      | .thmInfo _    => pure "theorem"
      | .opaqueInfo _ => pure "opaque"
      | .quotInfo _   => pure "quot"
      | .inductInfo _ => pure "inductive"
      | .ctorInfo _   => pure "ctor"
      | .recInfo _    => pure "rec"
    let res ← liftTermElabM <| Lean.Meta.forallTelescopeReducing ci.type fun _ body => do
      if ← Lean.Meta.isProp body then pure "PropResult"
      else match body with
        | .sort l => pure (match l with | .zero => "PropFormer" | _ => "TypeFormer")
        | _ => pure "DataResult"
    counts := counts.insert (k ++ ":" ++ res) (counts.getD (k ++ ":" ++ res) 0 + 1)
    logInfo m!"A3KIND\t{n}\t{k}\t{res}"
  logInfo m!"A3KIND-SUMMARY\t{toString counts.toList}"

