/-
Independent D13 cross-audit probe for D13-manifold-ibp-volume-form (clean).
Generated by audit/tools/gen_probe.py. Fail-closed: any project axiom, unsafe
declaration, sorryAx / native_decide / unapproved axiom in any dependency cone
aborts elaboration.
-/
import Poincare.D13.Audit
import Poincare.D13.BochnerFlat
import Poincare.D13.Bridge
import Poincare.D13.CertificateOn
import Poincare.D13.EuclideanChart
import Poincare.D13.GaussianF
import Poincare.D13.GaussianMoment
import Poincare.D13.HeatBridge
import Poincare.D13.HeatKernelBridge
import Poincare.D13.ManifoldIBP
import Poincare.D13.ManifoldIBP.Blocked
import Poincare.D13.ManifoldIBP.ChartSum
import Poincare.D13.ManifoldIBP.DisjointModel
import Poincare.D13.ManifoldIBP.GlobalIBP
import Poincare.D13.ManifoldIBP.GlobalMeasure
import Poincare.D13.ManifoldIBP.IntegrableTransfer
import Poincare.D13.ManifoldIBP.OverlapIBP
import Poincare.D13.ManifoldIBP.OverlapIBPData
import Poincare.D13.ManifoldIBP.OverlapIBPModel
import Poincare.D13.ManifoldIBP.OverlapModel
import Poincare.D13.ManifoldIBP.OverlapOperatorCheck
import Poincare.D13.ManifoldIBP.POUAssembly
import Poincare.D13.ManifoldIBP.POUAssemblyAE
import Poincare.D13.ManifoldIBP.POUConstruction
import Poincare.D13.ManifoldIBP.POUModel
import Poincare.D13.ManifoldIBP.PartialChartModel
import Poincare.D13.ManifoldIBP.PartialChartModelPOU
import Poincare.D13.ManifoldIBP.SmoothAtlas
import Poincare.D13.ManifoldIBP.SmoothAtlasIBP
import Poincare.D13.ManifoldIBP.SmoothAtlasModel
import Poincare.D13.ManifoldIBP.SmoothAtlasPartial
import Poincare.D13.ManifoldIBP.SmoothAtlasPartialAE
import Poincare.D13.ManifoldIBP.SmoothPartition
import Poincare.D13.ManifoldIBP.Transfer
import Poincare.D13.ManifoldIBP.VolumeFormBridge
import Poincare.D13.Riemannian
import Poincare.D13.Riemannian.AtlasBridge
import Poincare.D13.Riemannian.AtlasPairing
import Poincare.D13.Riemannian.ChartMetricBridge
import Poincare.D13.Riemannian.MetricBridge
import Poincare.D13.Riemannian.MetricBridgeSmooth
import Poincare.D13.Riemannian.PullbackPairing
import Poincare.D13.VolumeForm
import Poincare.D13.VolumeForm.Basic
import Poincare.D13.VolumeForm.Gluing
import Poincare.D13.VolumeForm.Transformation
import Lean.Util.CollectAxioms

open Lean Elab Command

namespace D13XAudit_D13_manifold_ibp_volume_form_clean

def approvedAxioms : List Name := ["propext".toName, "Classical.choice".toName, "Quot.sound".toName]

def packageRoots : List Name := [
  "Poincare".toName, "Probe".toName, "Ledger".toName, "Audit".toName,
  "ReleaseCheck".toName, "ReleaseAudit".toName, "D6AuditReport".toName]

/-- D6 baseline modules are pre-existing; every *other* reachable package module is audited. -/
def baseModules : List Name := [
  "Audit.CounterexampleAudit".toName,
  "Audit.CurvatureODEAudit".toName,
  "Audit.EvolutionAudit".toName,
  "Audit.GeometryAudit".toName,
  "Audit.PromotedEvolutionAudit".toName,
  "D6AuditReport".toName,
  "D6LedgerProbe".toName,
  "Ledger.DefinitionSmoke".toName,
  "Ledger.PerelmanDefinitions".toName,
  "Poincare.Basic".toName,
  "Poincare.Longrun.CurvatureODE".toName,
  "Poincare.Longrun.CurvatureODE.Bridge".toName,
  "Poincare.Longrun.CurvatureODE.Evolution".toName,
  "Poincare.Longrun.CurvatureODE.Invariant".toName,
  "Poincare.Longrun.CurvatureODE.Monotonicity".toName,
  "Poincare.Longrun.CurvatureODE.ScalarODE".toName,
  "Poincare.Longrun.CurvatureODE.State".toName,
  "Poincare.Longrun.Entropy".toName,
  "Poincare.Longrun.Entropy.AxiomAudit".toName,
  "Poincare.Longrun.Entropy.Bridge".toName,
  "Poincare.Longrun.Entropy.Certificate".toName,
  "Poincare.Longrun.Entropy.DiscreteHeat".toName,
  "Poincare.Longrun.Entropy.FiniteGeometry".toName,
  "Poincare.Longrun.Entropy.Functional".toName,
  "Poincare.Longrun.Evolution".toName,
  "Poincare.Longrun.Evolution.Bridge".toName,
  "Poincare.Longrun.Evolution.Continuous".toName,
  "Poincare.Longrun.Evolution.Counterexample".toName,
  "Poincare.Longrun.Evolution.Discrete".toName,
  "Poincare.Longrun.Evolution.Functional".toName,
  "Poincare.Longrun.Evolution.Gibbs".toName,
  "Poincare.Longrun.Geometry".toName,
  "Poincare.Longrun.Geometry.ConnectionAdapter".toName,
  "Poincare.Longrun.Geometry.Contraction".toName,
  "Poincare.Longrun.Geometry.LeviCivitaBlocked".toName,
  "Poincare.Longrun.Geometry.MetricData".toName,
  "Poincare.Longrun.PDE.AxiomAudit".toName,
  "Poincare.Longrun.PDE.ContinuousInterface".toName,
  "Poincare.Longrun.PDE.DiscreteMaximumPrinciple".toName,
  "Poincare.Longrun.PDE.Energy".toName,
  "Poincare.Longrun.PDE.HeatGrid".toName,
  "Poincare.Longrun.Surgery".toName,
  "Poincare.Longrun.Surgery.Axioms".toName,
  "Poincare.Longrun.Surgery.Basic".toName,
  "Poincare.Longrun.Surgery.Chain".toName,
  "Poincare.Longrun.Surgery.Missing".toName,
  "Poincare.Longrun.Surgery.Toy".toName,
  "Poincare.Longrun.Topology.AxiomAudit".toName,
  "Poincare.Longrun.Topology.Basic".toName,
  "Poincare.Longrun.Topology.CompactThreeManifold".toName,
  "Poincare.Longrun.Topology.MissingTheorems".toName,
  "Poincare.Longrun.Topology.Noncollapsing".toName,
  "Poincare.Longrun.Topology.NormalizedVolume".toName,
  "Poincare.Longrun.Topology.Stage6Bridge".toName,
  "Poincare.Stage1.CurvatureAlgebra".toName,
  "Poincare.Stage1.RiemannAdapter".toName,
  "Poincare.Stage6.SphereSimplyConnected".toName,
  "Poincare.Stage6.TopologyBridge".toName,
  "Probe.GeometryApi".toName,
  "Probe.PdeApi".toName,
  "ReleaseAudit".toName,
  "ReleaseCheck".toName,
  "ReleaseClaims".toName]

def excludedModules : List Name := [
  "Poincare.D12.VolumeIBP.Audit".toName,
  "Poincare.D13.Audit".toName]

def kindOf : ConstantInfo → String
  | .axiomInfo _ => "axiom"
  | .defnInfo v => match v.safety with
      | .«unsafe» => "unsafe_def"
      | .«partial» => "partial_def"
      | .safe => "def"
  | .thmInfo _ => "theorem"
  | .opaqueInfo _ => "opaque"
  | .quotInfo _ => "quot"
  | .inductInfo _ => "induct"
  | .ctorInfo _ => "ctor"
  | .recInfo _ => "rec"

end D13XAudit_D13_manifold_ibp_volume_form_clean

open D13XAudit_D13_manifold_ibp_volume_form_clean in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let audited (m : Name) : Bool :=
    packageRoots.any (fun r => r.isPrefixOf m) && !baseModules.contains m && !excludedModules.contains m
  let rows := env.constants.fold (fun acc n ci =>
    match env.getModuleIdxFor? n with
    | some midx =>
        let m := mods.getD midx .anonymous
        if audited m then acc.push (n, ci, m) else acc
    | none => acc) #[]
  let mut moduleSet : Array Name := #[]
  for (_, _, m) in rows do
    if !moduleSet.contains m then moduleSet := moduleSet.push m
  let mut nAxiom := 0
  let mut nUnsafe := 0
  let mut nSorry := 0
  let mut nNative := 0
  let mut nOther := 0
  let mut nFail := 0
  let mut nProofWanted := 0
  let mut nPartial := 0
  let mut nThm := 0
  for (n, ci, m) in rows do
    if n.toString.contains "proof_wanted" then nProofWanted := nProofWanted + 1
    match ci with
    | .axiomInfo _ => nAxiom := nAxiom + 1
    | .defnInfo v =>
        match v.safety with
        | .«unsafe» => nUnsafe := nUnsafe + 1
        | .«partial» => nPartial := nPartial + 1
        | .safe => pure ()
    | .thmInfo _ => nThm := nThm + 1
    | _ => pure ()
    let axs ←
      try
        Lean.collectAxioms n
      catch _ =>
        nFail := nFail + 1
        pure #[]
    for a in axs do
      if a == ``sorryAx then nSorry := nSorry + 1
      else if a.toString.contains "native_decide" || a == ``ofReduceBool then nNative := nNative + 1
      else if !approvedAxioms.contains a then nOther := nOther + 1
    IO.println s!"D13XDECL	{n}	{kindOf ci}	{m}	{";".intercalate (axs.toList.map Name.toString)}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	modules	{moduleSet.size}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	declarations	{rows.size}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	theorems	{nThm}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	partial_defs	{nPartial}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	project_axioms	{nAxiom}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	unsafe	{nUnsafe}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	sorry_cones	{nSorry}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	native_decide_cones	{nNative}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	unapproved_axiom_cones	{nOther}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	collect_failures	{nFail}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	proof_wanted	{nProofWanted}"
  if nAxiom + nUnsafe + nSorry + nNative + nOther + nFail + nProofWanted > 0 then
    IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	VERDICT	FAIL"
    throwError "D13XAudit: forbidden dependency found (D13-manifold-ibp-volume-form, clean)"
  else
    IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	VERDICT	PASS"
