/-
Independent D13 cross-audit probe for D13-manifold-ibp-volume-form (negcontrol).
Generated by audit/tools/gen_probe.py. Fail-closed: any project axiom, unsafe
declaration, sorryAx / native_decide / unapproved axiom in any dependency cone
aborts elaboration.
-/
import Poincare.D12.VolumeIBP.Audit
import Poincare.D13.Audit
import Poincare.D13.CertificateOn
import Lean.Util.CollectAxioms

open Lean Elab Command

namespace D13XAudit_D13_manifold_ibp_volume_form_negcontrol

def approvedAxioms : List Name := [``propext, ``Classical.choice, ``Quot.sound]

def auditedModules : List Name := [`Poincare.D12.VolumeIBP.Audit, `Poincare.D13.Audit, `Poincare.D13.CertificateOn]

def kindOf : ConstantInfo → String
  | .axiomInfo _ => "axiom"
  | .defnInfo v => match v.safety with
      | .«unsafe» => "unsafe_def"
      | .«partial» => "partial_def"
      | .safe => "def"
  | .thmInfo _ => "theorem"
  | .opaqueInfo _ => "opaque"
  | .quotInfo _ => "quot"
  | .inductInfo _ => "induct"
  | .ctorInfo _ => "ctor"
  | .recInfo _ => "rec"

end D13XAudit_D13_manifold_ibp_volume_form_negcontrol

open D13XAudit_D13_manifold_ibp_volume_form_negcontrol in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let mut cs : Array (Name × ConstantInfo × Name) := #[]
  env.constants.fold (fun acc n ci =>
    match env.getModuleIdxFor? n with
    | some midx =>
        let m := mods.getD midx .anonymous
        if auditedModules.contains m then acc.push (n, ci, m) else acc
    | none => acc) #[]
  let cs := cs.qsort (fun a b => a.1.toString < b.1.toString)
  let mut nAxiom := 0
  let mut nUnsafe := 0
  let mut nSorry := 0
  let mut nNative := 0
  let mut nOther := 0
  let mut nCollectFail := 0
  let mut nProofWanted := 0
  let mut nPartial := 0
  let mut nThm := 0
  for (n, ci, m) in cs do
    if n.toString.contains "proof_wanted" then nProofWanted := nProofWanted + 1
    match ci with
    | .axiomInfo _ => nAxiom := nAxiom + 1
    | .defnInfo v =>
        match v.safety with
        | .«unsafe» => nUnsafe := nUnsafe + 1
        | .«partial» => nPartial := nPartial + 1
        | .safe => pure ()
    | .thmInfo _ => nThm := nThm + 1
    | _ => pure ()
    let axs ←
      try
        Lean.collectAxioms n
      catch _ =>
        nCollectFail := nCollectFail + 1
        pure #[]
    for a in axs do
      if a == ``sorryAx then nSorry := nSorry + 1
      else if a.toString.contains "native_decide" || a == ``ofReduceBool then nNative := nNative + 1
      else if !approvedAxioms.contains a then nOther := nOther + 1
    IO.println s!"D13XDECL	{n}	{kindOf ci}	{m}	{";".intercalate (axs.toList.map Name.toString)}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	modules	{auditedModules.length}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	declarations	{cs.size}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	theorems	{nThm}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	partial_defs	{nPartial}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	project_axioms	{nAxiom}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	unsafe	{nUnsafe}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	sorry_cones	{nSorry}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	native_decide_cones	{nNative}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	unapproved_axiom_cones	{nOther}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	collect_failures	{nCollectFail}"
  IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	proof_wanted	{nProofWanted}"
  if nAxiom + nUnsafe + nSorry + nNative + nOther + nCollectFail + nProofWanted > 0 then
    IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	VERDICT	FAIL"
    throwError "D13XAudit: forbidden dependency found (D13-manifold-ibp-volume-form, negcontrol)"
  else
    IO.println s!"D13XAUDIT	D13-manifold-ibp-volume-form	VERDICT	PASS"
