#!/usr/bin/env python3
"""Generate an independent `A3Probe.lean` for a card whose proved_declarations
entries are prose strings mixing names and descriptions.

Resolution is done against the staged sources by the same namespace-aware scan
used since round 1 (`prepare.scan_decls`), but name extraction is independent:
each entry contributes every dotted identifier token that occurs before the
first ` : ` and every token after a `,`/`/` separator in the entry tail.

Usage: python3 r11/gen_probe_prose.py <card>
Writes: audit360/pkgs/<card>/A3Probe.lean and A3ProbeResolved.json
"""
import importlib.util
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
AUD = os.path.dirname(HERE)
WT = os.path.dirname(AUD)
TOK = re.compile(r"[A-Za-z_][A-Za-z0-9_']*(?:\.[A-Za-z_][A-Za-z0-9_']*)+")


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    card = sys.argv[1]
    prod = os.path.join("/data3/guoshaoyang/workdir/lean_poincare/longrun/worktrees", card,
                        "longrun", "results", card + ".json")
    dst = os.path.join(AUD, "pkgs", card)
    prep = load("prepare", os.path.join(AUD, "prepare.py"))
    pd = json.load(open(prod, encoding="utf-8")).get("proved_declarations")
    entries = pd if isinstance(pd, list) else list(pd.values()) if isinstance(pd, dict) else []
    declared = []
    for e in entries:
        s = e if isinstance(e, str) else json.dumps(e)
        head = s.split(" : ")[0]
        for t in TOK.findall(head):
            declared.append(t)
        # grouped entries: names after separators in the tail
        if "/" in head or "," in head:
            for part in re.split(r"[/,]", head):
                for t in TOK.findall(part):
                    declared.append(t)
    # unique, keep order
    seen, ordered = set(), []
    for d in declared:
        if d not in seen:
            seen.add(d)
            ordered.append(d)
    # namespace-aware scan of the staged sources
    scan = {}
    for dirpath, dirnames, filenames in os.walk(dst):
        dirnames[:] = [d for d in dirnames if d != ".lake"]
        for fn in filenames:
            if fn.endswith(".lean") and not fn.startswith("A3"):
                rel_mod = os.path.relpath(os.path.join(dirpath, fn), dst)[:-5].replace("/", ".")
                scan.update(prep.scan_decls(os.path.join(dirpath, fn), rel_mod))
    resolved, unresolved = [], []
    for name in ordered:
        if name in scan:
            resolved.append({"declared": name, "fq": name, "module": scan[name]})
            continue
        cands = sorted({fq for fq in scan if fq == name or fq.endswith("." + name)})
        if len(cands) == 1:
            resolved.append({"declared": name, "fq": cands[0], "module": scan[cands[0]]})
            continue
        short = name.split(".")[-1]
        hits = sorted({fq for fq in scan if fq.split(".")[-1] == short})
        if len(hits) == 1:
            resolved.append({"declared": name, "fq": hits[0], "module": scan[hits[0]],
                             "note": "short-name match"})
        else:
            unresolved.append({"declared": name, "candidates": sorted(set(cands) | set(hits))[:8]})
    # dedupe resolved by fq
    seen, dedup = set(), []
    for r in resolved:
        if r["fq"] not in seen:
            seen.add(r["fq"])
            dedup.append(r)
    mods = sorted({r["module"] for r in dedup})
    probe = ["-- A3 independent probe (prose-entry resolver) for " + card,
             "-- generated by D13-cross-audit-360-cards r11/gen_probe_prose.py",
             ""] + ["import " + m for m in mods] + [
             "", "set_option maxHeartbeats 400000", ""]
    probe += ["#check " + r["fq"] for r in dedup]
    probe += [""]
    probe += ["#print axioms " + r["fq"] for r in dedup]
    open(os.path.join(dst, "A3Probe.lean"), "w", encoding="utf-8").write("\n".join(probe) + "\n")
    meta = {"card": card, "declared_candidates": len(ordered), "resolved": dedup,
            "unresolved": unresolved, "modules": mods}
    json.dump(meta, open(os.path.join(dst, "A3ProbeResolved.json"), "w"), indent=1)
    print(f"{card}: candidates={len(ordered)} resolved={len(dedup)} unresolved={len(unresolved)} "
          f"modules={len(mods)}")
    for u in unresolved:
        print("  UNRESOLVED", u)


if __name__ == "__main__":
    main()
