/-
L5-topology-audit — independent fail-closed kernel detector, Pass A — audits the `Poincare.D7.Bochner.*` / `Poincare.D7.ConjugateHeat.Basic` side (and every collision-free module except the 14 modules whose transitive closure imports the duplicate `Poincare.D7.Monotonicity.*`/`D7.Kappa.*` declarations).

448 modules imported.  The union of pass A and pass B covers all 462 buildable
modules of `release/`; the passes differ only in the 39 modules touching the three
colliding declaration clusters recorded in `audit-evidence/collisions.json`.
Generated by `audit-evidence/tools/l5_generate_probes.py` (do not edit by hand).
-/
import Audit.CounterexampleAudit
import Audit.CurvatureODEAudit
import Audit.EvolutionAudit
import Audit.GeometryAudit
import Audit.PromotedEvolutionAudit
import D6AuditReport
import Ledger.DefinitionSmoke
import Ledger.PerelmanDefinitions
import Poincare.Basic
import Poincare.D10.BochnerEuclidean.Axioms
import Poincare.D10.BochnerEuclidean.Basic
import Poincare.D10.BochnerEuclidean.Bochner
import Poincare.D10.BochnerEuclidean.Compat
import Poincare.D10.BochnerEuclidean.Corollary
import Poincare.D10.GaussianToolbox.Basic
import Poincare.D10.GaussianToolbox.Convolution
import Poincare.D10.GaussianToolbox.Multivariate
import Poincare.D10.GaussianToolbox.PrintAxioms
import Poincare.D10.HeatKernelEuclidean.AxiomAudit
import Poincare.D10.HeatKernelEuclidean.Basic
import Poincare.D10.HeatKernelEuclidean.GaussianIntegral
import Poincare.D10.HeatKernelEuclidean.HeatEquation
import Poincare.D10.HeatKernelEuclidean.Mass
import Poincare.D10.HeatKernelEuclidean.Semigroup
import Poincare.D10.JacobiConstantCurvature.AxiomAudit
import Poincare.D10.JacobiConstantCurvature.Basic
import Poincare.D10.JacobiConstantCurvature.Comparison
import Poincare.D10.JacobiConstantCurvature.ODE
import Poincare.D10.MaximumPrincipleRN.AxiomAudit
import Poincare.D10.MaximumPrincipleRN.Basic
import Poincare.D10.MaximumPrincipleRN.SecondDerivativeTest
import Poincare.D10.MaximumPrincipleRN.Semidiscrete
import Poincare.D10.MaximumPrincipleRN.WeakMaximumPrinciple
import Poincare.D10.TriangulationLowDim.Audit
import Poincare.D10.TriangulationLowDim.Complex
import Poincare.D10.TriangulationLowDim.Models
import Poincare.D10.TriangulationLowDim.Moise
import Poincare.D11.BochnerManifold.Axioms
import Poincare.D11.BochnerManifold.Basic
import Poincare.D11.BochnerManifold.Corollaries
import Poincare.D11.BochnerManifold.D7Bridge
import Poincare.D11.BochnerManifold.ModelSpace
import Poincare.D11.BochnerManifold.Probe
import Poincare.D11.BochnerManifold.RadialBochner
import Poincare.D11.ComparisonModels.AxiomAudit
import Poincare.D11.ComparisonModels.Basic
import Poincare.D11.ComparisonModels.BishopGromov
import Poincare.D11.ComparisonModels.LaplacianComparison
import Poincare.D11.ComparisonModels.ModelMetrics
import Poincare.D11.HeatKernelBridge.All
import Poincare.D11.HeatKernelBridge.AxiomAudit
import Poincare.D11.HeatKernelBridge.Basic
import Poincare.D11.HeatKernelBridge.EuclideanInstance
import Poincare.D11.HeatKernelBridge.EuclideanLaplacian
import Poincare.D11.HeatKernelBridge.InitialCondition
import Poincare.D11.HeatKernelBridge.ZeroDimension
import Poincare.D11.MaximumPrincipleTensor.AxiomAudit
import Poincare.D11.MaximumPrincipleTensor.Basic
import Poincare.D11.MaximumPrincipleTensor.Euler
import Poincare.D11.MaximumPrincipleTensor.Flow
import Poincare.D11.MaximumPrincipleTensor.ScalarODE
import Poincare.D11.ReducedVolume.All
import Poincare.D11.ReducedVolume.Audit
import Poincare.D11.ReducedVolume.Basic
import Poincare.D11.ReducedVolume.Probe
import Poincare.D11.ReducedVolume.Statements
import Poincare.D11.ReducedVolume.StraightRays
import Poincare.D11.ReducedVolume.Volume
import Poincare.D11.SpectralTorus.AxiomsCheck
import Poincare.D11.SpectralTorus.Basic
import Poincare.D11.SpectralTorus.Laplacian
import Poincare.D11.SpectralTorus.Parseval
import Poincare.D11.SpectralTorus.Poincare
import Poincare.D11.SpectralTorus.Sobolev
import Poincare.D12.ComparisonGeodesics.AxiomAudit
import Poincare.D12.ComparisonGeodesics.Definitions
import Poincare.D12.ComparisonGeodesics.ModelEuclidean
import Poincare.D12.ComparisonGeodesics.RiccatiComparison
import Poincare.D12.ComparisonGeodesics.SingularRiccati
import Poincare.D12.ComparisonGeodesics.SturmComparison
import Poincare.D12.ComparisonGeodesics.VolumeRatio
import Poincare.D12.ConnectionCurvature
import Poincare.D12.ConnectionCurvature.ChartLeviCivita
import Poincare.D12.ConnectionCurvature.ChartLeviCivitaForm
import Poincare.D12.ConnectionCurvature.ChartLeviCivitaSmooth
import Poincare.D12.ConnectionCurvature.ChartModel1D
import Poincare.D12.ConnectionCurvature.ConformalChartModel
import Poincare.D12.ConnectionCurvature.MilnorLeviCivita
import Poincare.D12.ConnectionCurvature.RicciSymmetry
import Poincare.D12.ConnectionCurvature.SoThreeModel
import Poincare.D12.EntropyVariation.All
import Poincare.D12.EntropyVariation.AxiomAudit
import Poincare.D12.EntropyVariation.EntropyDerivative
import Poincare.D12.EntropyVariation.FFlowModel
import Poincare.D12.EntropyVariation.GaussianShrinker
import Poincare.D12.EntropyVariation.SignDistinction
import Poincare.D12.EntropyVariation.WeightedIntegral
import Poincare.D12.GeometricCompactness.AxiomAudit
import Poincare.D12.GeometricCompactness.Basic
import Poincare.D12.GeometricCompactness.Criterion
import Poincare.D12.GeometricCompactness.Frontier
import Poincare.D12.GeometricCompactness.GridFamily
import Poincare.D12.HeatDomain.All
import Poincare.D12.HeatDomain.AxiomAudit
import Poincare.D12.HeatDomain.CompactCompatibility
import Poincare.D12.HeatDomain.Counterexample
import Poincare.D12.HeatDomain.FlatInstance
import Poincare.D12.HeatDomain.TestFunction
import Poincare.D12.HeatSemigroup.All
import Poincare.D12.HeatSemigroup.AxiomAudit
import Poincare.D12.HeatSemigroup.Basic
import Poincare.D12.HeatSemigroup.Example
import Poincare.D12.HeatSemigroup.L1Contraction
import Poincare.D12.HeatSemigroup.LinfContraction
import Poincare.D12.HeatSemigroup.ManifoldObligations
import Poincare.D12.HeatSemigroup.Semigroup
import Poincare.D12.HeatSemigroup.Smoothing
import Poincare.D12.HeatSemigroup.StrongContinuity
import Poincare.D12.HeatSemigroup.StrongContinuityL1
import Poincare.D12.KappaVariational.All
import Poincare.D12.KappaVariational.Audit
import Poincare.D12.KappaVariational.CurvatureEnergy
import Poincare.D12.KappaVariational.GaussianNormalization
import Poincare.D12.KappaVariational.Statements
import Poincare.D12.KappaVariational.Transfer
import Poincare.D12.ParabolicLocal.AxiomAudit
import Poincare.D12.ParabolicLocal.BUC
import Poincare.D12.ParabolicLocal.DerivativeLoss
import Poincare.D12.ParabolicLocal.Duhamel
import Poincare.D12.ParabolicLocal.Examples
import Poincare.D12.ParabolicLocal.GaussianConv
import Poincare.D12.ParabolicLocal.GaussianSemigroup
import Poincare.D12.ParabolicLocal.GaussianSetup
import Poincare.D12.ParabolicLocal.MildExistence
import Poincare.D12.ParabolicLocal.Obligations
import Poincare.D12.ParabolicLocal.ParametricIntegral
import Poincare.D12.SemanticLedger.AxiomAudit
import Poincare.D12.SemanticLedger.Defect
import Poincare.D12.SemanticLedger.LedgerProbe
import Poincare.D12.SpectralSobolev.All
import Poincare.D12.SpectralSobolev.AxiomAudit
import Poincare.D12.SpectralSobolev.Basic
import Poincare.D12.SpectralSobolev.Examples
import Poincare.D12.SpectralSobolev.HeatConvergence
import Poincare.D12.SpectralSobolev.Poincare
import Poincare.D12.SpectralSobolev.Semigroup
import Poincare.D12.SurgeryRecognition.All
import Poincare.D12.SurgeryRecognition.Audit
import Poincare.D12.SurgeryRecognition.BallGluing
import Poincare.D12.SurgeryRecognition.ConnectedSumTopology
import Poincare.D12.SurgeryRecognition.CoveringRecognition
import Poincare.D12.SurgeryRecognition.DeckTrivial
import Poincare.D12.SurgeryRecognition.ExpandedInterfaces
import Poincare.D12.SurgeryRecognition.SphereOfSpheres
import Poincare.D12.TensorMaximumBochner.Audit
import Poincare.D12.TensorMaximumBochner.BochnerIdentity
import Poincare.D12.TensorMaximumBochner.PositivityPreservation
import Poincare.D12.TensorMaximumBochner.So3Model
import Poincare.D12.TensorMaximumBochner.So3Polynomial
import Poincare.D12.TensorMaximumBochner.So3RicciFlow
import Poincare.D12.TensorMaximumBochner.TangentCone
import Poincare.D12.TensorMaximumBochner.TensorCalculus
import Poincare.D12.TriangulationTopology.AntipodalQuotient
import Poincare.D12.TriangulationTopology.AxiomAudit
import Poincare.D12.TriangulationTopology.CoveringLemma
import Poincare.D12.TriangulationTopology.DiskGluing
import Poincare.D12.TriangulationTopology.Downstream
import Poincare.D12.TriangulationTopology.HemisphereDisk
import Poincare.D12.TriangulationTopology.MoiseBranch
import Poincare.D12.TriangulationTopology.NegControl.NegControl
import Poincare.D12.TriangulationTopology.SimplexBoundary
import Poincare.D12.TriangulationTopology.SimplexCone
import Poincare.D12.TriangulationTopology.SphereGluing
import Poincare.D12.TriangulationTopology.SphereMissedPoint
import Poincare.D12.TriangulationTopology.SphereOfTwoDisks
import Poincare.D12.TriangulationTopology.SpherePolygonal
import Poincare.D12.TriangulationTopology.SphereRecognition
import Poincare.D12.TriangulationTopology.SphereSimplyConnected
import Poincare.D12.TriangulationTopology.SphereSimplyConnectedMain
import Poincare.D12.TriangulationTopology.TwoHemisphereInstance
import Poincare.D12.VolumeIBP
import Poincare.D12.VolumeIBP.Audit
import Poincare.D12.VolumeIBP.Basic
import Poincare.D12.VolumeIBP.Blocked
import Poincare.D12.VolumeIBP.ChangeOfVariables
import Poincare.D12.VolumeIBP.Compat
import Poincare.D12.VolumeIBP.Divergence
import Poincare.D12.VolumeIBP.Example
import Poincare.D12.VolumeIBP.IBP
import Poincare.D12.VolumeIBP.Regularity
import Poincare.D13.CriticalPathReview.AxiomAudit
import Poincare.D13.CriticalPathReview.B1DimensionOne
import Poincare.D13.CriticalPathReview.NegControl
import Poincare.D13.CriticalPathReview.PrintAxioms
import Poincare.D13.CriticalPathReview.PrintAxiomsAll
import Poincare.D13.CriticalPathReview.ScalarViability
import Poincare.D13.CriticalPathReview.StatementAudit
import Poincare.D13.CriticalPathReview.UsageProbe
import Poincare.D13.IntegratedAudit.AuditCore
import Poincare.D13.IntegratedAudit.DependencyProbe
import Poincare.D13.IntegratedAudit.ExpectedModules
import Poincare.D13.IntegratedAudit.FullAudit
import Poincare.D13.IntegratedAudit.KernelAudit
import Poincare.D13.IntegratedAudit.NonvacuityProbe
import Poincare.D13.IntegratedAudit.SelfAudit
import Poincare.D13.IntegratedAudit.SnapshotRoot
import Poincare.D13.IntegratedAudit.StatementAudit
import Poincare.D13.IntegratedAudit.UsageProbe
import Poincare.D7.Bochner.Audit
import Poincare.D7.Bochner.Basic
import Poincare.D7.Bochner.Blocked
import Poincare.D7.Bochner.Euclidean
import Poincare.D7.Bochner.Example
import Poincare.D7.Bochner.GradientEstimate
import Poincare.D7.Bochner.Probe
import Poincare.D7.Canonical.All
import Poincare.D7.Canonical.Audit
import Poincare.D7.Canonical.Basic
import Poincare.D7.Canonical.Classification
import Poincare.D7.Canonical.Curvature
import Poincare.D7.Canonical.Models
import Poincare.D7.Canonical.Probe
import Poincare.D7.Canonical.Statements
import Poincare.D7.Compactness.All
import Poincare.D7.Compactness.Audit
import Poincare.D7.Compactness.Basic
import Poincare.D7.Compactness.ManifoldStatements
import Poincare.D7.Compactness.Nonvacuity
import Poincare.D7.Compactness.Probe
import Poincare.D7.Compactness.TotalBounded
import Poincare.D7.Compactness.ToyCompactness
import Poincare.D7.ConjugateHeat.All
import Poincare.D7.ConjugateHeat.Audit
import Poincare.D7.ConjugateHeat.Basic
import Poincare.D7.ConjugateHeat.Blocked
import Poincare.D7.ConjugateHeat.Example
import Poincare.D7.ConjugateHeat.Instance
import Poincare.D7.ConjugateHeat.Laplacian
import Poincare.D7.ConjugateHeat.Probe
import Poincare.D7.ConjugateHeat.Slab
import Poincare.D7.Curvature
import Poincare.D7.Curvature.Audit
import Poincare.D7.Curvature.Basic
import Poincare.D7.Curvature.Blocked
import Poincare.D7.Curvature.Bridge
import Poincare.D7.Curvature.Example
import Poincare.D7.Curvature.Probe
import Poincare.D7.Curvature.Sectional
import Poincare.D7.Curvature.Symmetries
import Poincare.D7.Divergence
import Poincare.D7.Divergence.Audit
import Poincare.D7.Divergence.Basic
import Poincare.D7.Divergence.Blocked
import Poincare.D7.Divergence.Example
import Poincare.D7.Divergence.Graph
import Poincare.D7.Divergence.Probe
import Poincare.D7.Divergence.Slab
import Poincare.D7.EvolutionSharp.AxiomAudit
import Poincare.D7.EvolutionSharp.Certificates
import Poincare.D7.EvolutionSharp.FunctionalSharp
import Poincare.D7.EvolutionSharp.GibbsSharp
import Poincare.D7.EvolutionSharp.Implications
import Poincare.D7.EvolutionSharp.ReleaseAudit
import Poincare.D7.EvolutionSharp.Witnesses
import Poincare.D7.Geodesic.AxiomAudit
import Poincare.D7.Geodesic.Basic
import Poincare.D7.Geodesic.FlatUniqueness
import Poincare.D7.Geodesic.ManifoldInterfaces
import Poincare.D7.Geodesic.MathlibProbe
import Poincare.D7.Geodesic.MetricSpeed
import Poincare.D7.Geodesic.Reparam
import Poincare.D7.Geodesic.Smoke
import Poincare.D7.HeatKernel.All
import Poincare.D7.HeatKernel.Audit
import Poincare.D7.HeatKernel.Basic
import Poincare.D7.HeatKernel.Blocked
import Poincare.D7.HeatKernel.Content
import Poincare.D7.HeatKernel.Example
import Poincare.D7.HeatKernel.Grid
import Poincare.D7.HeatKernel.Instance
import Poincare.D7.HeatKernel.Probe
import Poincare.D7.Kappa.Basic
import Poincare.D7.LeviCivita.Audit
import Poincare.D7.LeviCivita.Basic
import Poincare.D7.LeviCivita.Blocked
import Poincare.D7.LeviCivita.Coefficients
import Poincare.D7.LeviCivita.Koszul
import Poincare.D7.LeviCivita.Probe
import Poincare.D7.LeviCivita.Smoke
import Poincare.D7.Limit.All
import Poincare.D7.Limit.Audit
import Poincare.D7.Limit.Basic
import Poincare.D7.Limit.Blocked
import Poincare.D7.Limit.Convergence
import Poincare.D7.Limit.ErrorRecursion
import Poincare.D7.Limit.Example
import Poincare.D7.Limit.Probe
import Poincare.D7.Limit.Refinement
import Poincare.D7.Limit.Stability
import Poincare.D7.Monotonicity.ReducedVolumeInput
import Poincare.D7.Recognition.All
import Poincare.D7.Recognition.Assembly
import Poincare.D7.Recognition.Audit
import Poincare.D7.Recognition.Basic
import Poincare.D7.Recognition.Homeomorphism
import Poincare.D7.Recognition.Probe
import Poincare.D7.Reduced.All
import Poincare.D7.Reduced.Audit
import Poincare.D7.Reduced.Basic
import Poincare.D7.Reduced.Certificate
import Poincare.D7.Reduced.Gaussian
import Poincare.D7.Reduced.Probe
import Poincare.D7.Reduced.Statements
import Poincare.D7.RicciScalar
import Poincare.D7.RicciScalar.Audit
import Poincare.D7.RicciScalar.Basic
import Poincare.D7.RicciScalar.Bridge
import Poincare.D7.RicciScalar.Example
import Poincare.D7.RicciScalar.Probe
import Poincare.D7.RicciScalar.Product
import Poincare.D7.RicciScalar.Scalar
import Poincare.D7.RicciScalar.Variation
import Poincare.D7.ShortTime
import Poincare.D7.ShortTime.Audit
import Poincare.D7.ShortTime.Basic
import Poincare.D7.ShortTime.Equivalence
import Poincare.D7.ShortTime.Example
import Poincare.D7.ShortTime.Gauge
import Poincare.D7.ShortTime.MatrixDeriv
import Poincare.D7.ShortTime.ODE
import Poincare.D7.ShortTime.Probe
import Poincare.D7.ShortTime.Statements
import Poincare.D7.SurgeryFlow.All
import Poincare.D7.SurgeryFlow.Audit
import Poincare.D7.SurgeryFlow.Basic
import Poincare.D7.SurgeryFlow.Extinction
import Poincare.D7.SurgeryFlow.Probe
import Poincare.D7.SurgeryFlow.Statements
import Poincare.D7.SurgeryFlow.Times
import Poincare.D7.TensorLaplacian
import Poincare.D7.TensorLaplacian.Audit
import Poincare.D7.TensorLaplacian.Basic
import Poincare.D7.TensorLaplacian.Blocked
import Poincare.D7.TensorLaplacian.Commutation
import Poincare.D7.TensorLaplacian.Evolution
import Poincare.D7.TensorLaplacian.Example
import Poincare.D7.TensorLaplacian.Probe
import Poincare.D7.Volume
import Poincare.D7.Volume.Audit
import Poincare.D7.Volume.Basic
import Poincare.D7.Volume.Blocked
import Poincare.D7.Volume.ChangeOfVariables
import Poincare.D7.Volume.Example
import Poincare.D7.Volume.Probe
import Poincare.D7.Volume.Scaling
import Poincare.D8.Fidelity.AxiomAudit
import Poincare.D8.Fidelity.Bridge
import Poincare.D8.Fidelity.FidelityCard
import Poincare.D8.Fidelity.MoiseData
import Poincare.D8.Fidelity.MoiseStatement
import Poincare.D8.Fidelity.SmoothStructure
import Poincare.D9.AncientKappa.Basic
import Poincare.D9.AncientKappa.Classification
import Poincare.D9.AncientKappa.GaussianSoliton
import Poincare.D9.AncientKappa.PrintAxioms
import Poincare.D9.CheegerGromov.AxiomAudit
import Poincare.D9.CheegerGromov.CheegerGromov
import Poincare.D9.CheegerGromov.DiscreteModel
import Poincare.D9.CheegerGromov.PointedConvergence
import Poincare.D9.DeTurck.ConnectionLayer
import Poincare.D9.DeTurck.StatementOnly
import Poincare.D9.DeTurck.SymbolModel
import Poincare.D9.ParabolicEstimates.AxiomAudit
import Poincare.D9.ParabolicEstimates.Basic
import Poincare.D9.ParabolicEstimates.Gronwall
import Poincare.D9.ParabolicEstimates.MatrixModel
import Poincare.D9.ParabolicEstimates.Statements
import Poincare.D9.Surfaces.All
import Poincare.D9.Surfaces.AxiomAudit
import Poincare.D9.Surfaces.Basic
import Poincare.D9.Surfaces.HomogeneousODE
import Poincare.D9.Surfaces.Statements
import Poincare.D9.TensorAlgebra.AxiomAudit
import Poincare.D9.TensorAlgebra.Interface
import Poincare.D9.TensorAlgebra.Props
import Poincare.D9.TensorAlgebra.Toy
import Poincare.Longrun.CurvatureODE
import Poincare.Longrun.CurvatureODE.Bridge
import Poincare.Longrun.CurvatureODE.Evolution
import Poincare.Longrun.CurvatureODE.Invariant
import Poincare.Longrun.CurvatureODE.Monotonicity
import Poincare.Longrun.CurvatureODE.ScalarODE
import Poincare.Longrun.CurvatureODE.State
import Poincare.Longrun.Entropy
import Poincare.Longrun.Entropy.AxiomAudit
import Poincare.Longrun.Entropy.Bridge
import Poincare.Longrun.Entropy.Certificate
import Poincare.Longrun.Entropy.DiscreteHeat
import Poincare.Longrun.Entropy.FiniteGeometry
import Poincare.Longrun.Entropy.Functional
import Poincare.Longrun.Evolution
import Poincare.Longrun.Evolution.Bridge
import Poincare.Longrun.Evolution.Continuous
import Poincare.Longrun.Evolution.Counterexample
import Poincare.Longrun.Evolution.Discrete
import Poincare.Longrun.Evolution.Functional
import Poincare.Longrun.Evolution.Gibbs
import Poincare.Longrun.Geometry
import Poincare.Longrun.Geometry.ConnectionAdapter
import Poincare.Longrun.Geometry.Contraction
import Poincare.Longrun.Geometry.LeviCivitaBlocked
import Poincare.Longrun.Geometry.MetricData
import Poincare.Longrun.PDE.AxiomAudit
import Poincare.Longrun.PDE.ContinuousInterface
import Poincare.Longrun.PDE.DiscreteMaximumPrinciple
import Poincare.Longrun.PDE.Energy
import Poincare.Longrun.PDE.HeatGrid
import Poincare.Longrun.Surgery
import Poincare.Longrun.Surgery.Axioms
import Poincare.Longrun.Surgery.Basic
import Poincare.Longrun.Surgery.Chain
import Poincare.Longrun.Surgery.Missing
import Poincare.Longrun.Surgery.Toy
import Poincare.Longrun.Topology.AxiomAudit
import Poincare.Longrun.Topology.Basic
import Poincare.Longrun.Topology.CompactThreeManifold
import Poincare.Longrun.Topology.MissingTheorems
import Poincare.Longrun.Topology.Noncollapsing
import Poincare.Longrun.Topology.NormalizedVolume
import Poincare.Longrun.Topology.Stage6Bridge
import Poincare.Stage1.CurvatureAlgebra
import Poincare.Stage1.RiemannAdapter
import Poincare.Stage6.SphereSimplyConnected
import Poincare.Stage6.TopologyBridge
import Poincare.VKPort.HatcherLib.Ch1.AlgebraicConstructions
import Poincare.VKPort.HatcherLib.Ch1.BasicConstructions
import Poincare.VKPort.HatcherLib.Ch1.VanKampen
import Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid
import Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep
import Poincare.VKPort.HatcherLib.Ch1.VanKampenGrid
import Poincare.VKPort.HatcherLib.Ch1.VanKampenSubdivision
import Poincare.VKPort.HatcherLib.Ch1.VanKampenSweep
import Poincare.VKPort.HatcherLib.Ch1.VanKampenWordCalculus
import Poincare.VKPort.HatcherLib.VKProbe
import Probe.GeometryApi
import Probe.PdeApi
import ReleaseAudit
import ReleaseCheck
import Lean.Util.CollectAxioms
import Lean.Elab.Command

set_option autoImplicit false
set_option maxHeartbeats 0

open Lean Elab Command Meta

namespace L5Audit

/-- The only axioms accepted in a released dependency cone. -/
def approvedAxioms : List Name :=
  ["propext".toName, "Classical.choice".toName, "Quot.sound".toName]

def sorryAxiom : Name := "sorryAx".toName
def nativeAxioms : List Name := ["ofReduceBool".toName, "Lean.ofReduceBool".toName]

/-- Negative controls intentionally present in the release tree: the three forbidden axiom
declarations and the two theorems that consume them.  They are *excused* only when the
caller passes them as `excluded` (the positive run does); they are always reported by name
with their axiom cones, and a run with `excluded := []` must fail on them. -/
def knownNegControls : List Name :=
  ["d12NegControlBadAxiom".toName,
   "d12NegControlBadTheorem".toName,
   "Poincare.D12.VolumeIBP.Audit.negativeControl".toName,
   "Poincare.D13.CriticalPathReview.NegControl.negControlBadAxiom".toName,
   "Poincare.D13.CriticalPathReview.NegControl.negControlBadTheorem".toName]

/-- Package top-level namespaces (audit scope). -/
def packageRoots : List Name :=
  ["Poincare".toName, "Probe".toName, "Ledger".toName, "Audit".toName,
   "ReleaseCheck".toName, "ReleaseAudit".toName, "D6AuditReport".toName,
   "ReleaseClaims".toName, "D6LedgerProbe".toName, "L5NegControlFresh".toName]

/-- Topology lane: recognition, triangulation, surgery, end game and the audited interface
layers that feed them. -/
def laneRoots : List Name :=
  ["Poincare.D7.Recognition".toName,
   "Poincare.D7.SurgeryFlow".toName,
   "Poincare.D7.Limit".toName,
   "Poincare.D10.TriangulationLowDim".toName,
   "Poincare.D12.SurgeryRecognition".toName,
   "Poincare.D12.TriangulationTopology".toName,
   "Poincare.D12.SemanticLedger".toName,
   "Poincare.D13.CriticalPathReview".toName,
   "Poincare.Longrun.Surgery".toName,
   "Poincare.Longrun.Topology".toName,
   "Poincare.Stage6".toName,
   "Poincare.D8.Fidelity".toName,
   "Poincare.VKPort".toName]

def isUnder (roots : List Name) (m : Name) : Bool :=
  roots.any (fun r => r.isPrefixOf m)

def kindOf : ConstantInfo → String
  | .axiomInfo _ => "axiom"
  | .defnInfo v =>
      match v.safety with
      | .«unsafe» => "unsafe_def"
      | .«partial» => "partial_def"
      | .safe => "def"
  | .thmInfo _ => "theorem"
  | .opaqueInfo _ => "opaque"
  | .quotInfo _ => "quot"
  | .inductInfo _ => "induct"
  | .ctorInfo _ => "ctor"
  | .recInfo _ => "rec"

/-- Fail-closed package audit.  `excluded` lists the *declarations* excused from the
unexpected-kernel-dependency verdict (never axiom *names*); every cone is still computed and
reported, so excusing is visible in the log. -/
def runAudit (roots : List Name) (excluded : List Name) (annotate : Bool) : CommandElabM Unit := do
  let env ← getEnv
  let imported := env.header.moduleNames
  let moduleOf (n : Name) : Name :=
    match env.getModuleIdxFor? n with
    | some i => imported.getD i .anonymous
    | none => .anonymous
  -- fail-closed module inventory: every imported package module is named in the log
  let pkgMods := imported.filter (fun m => isUnder roots m)
  IO.println s!"L5MOD\timported_total\t{imported.size}"
  IO.println s!"L5MOD\timported_package\t{pkgMods.size}"
  for m in pkgMods do IO.println s!"L5MOD\t{m}"
  let rows : Array (Name × ConstantInfo × Name) :=
    env.constants.fold (fun acc n ci =>
      let m := moduleOf n
      if isUnder roots m then acc.push (n, ci, m) else acc) #[]
  let mut decls := 0
  let mut theorems := 0
  let mut axiomsUnexpected : Array Name := #[]
  let mut unsafeD : Array Name := #[]
  let mut partialD : Array Name := #[]
  let mut sorryUnexpected : Array Name := #[]
  let mut nativeUnexpected : Array Name := #[]
  let mut unapprovedUnexpected : Array (Name × Name) := #[]
  let mut unapprovedAll : Array (Name × Name) := #[]
  let mut proofWanted : Array Name := #[]
  let mut collectFail : Array (Name × String) := #[]
  for (n, ci, m) in rows do
    decls := decls + 1
    if n.toString.contains "proof_wanted" then proofWanted := proofWanted.push n
    match ci with
    | .axiomInfo _ => if !excluded.contains n then axiomsUnexpected := axiomsUnexpected.push n
    | .defnInfo v =>
        match v.safety with
        | .«unsafe» => unsafeD := unsafeD.push n
        | .«partial» => partialD := partialD.push n
        | .safe => pure ()
    | .thmInfo _ => theorems := theorems + 1
    | _ => pure ()
    let axs ←
      try Lean.collectAxioms n
      catch _ =>
        collectFail := collectFail.push (n, "collectAxioms raised an exception")
        pure #[]
    for a in axs do
      if a == sorryAxiom then
        if !excluded.contains n then sorryUnexpected := sorryUnexpected.push n
      else if nativeAxioms.contains a then
        if !excluded.contains n then nativeUnexpected := nativeUnexpected.push n
      else if !approvedAxioms.contains a then
        unapprovedAll := unapprovedAll.push (n, a)
        if !excluded.contains n then unapprovedUnexpected := unapprovedUnexpected.push (n, a)
  let modsWithDecls := rows.foldl (fun acc (_, _, m) => if acc.contains m then acc else acc.push m) #[]
  IO.println s!"L5PKG\tdeclarations\t{decls}"
  IO.println s!"L5PKG\ttheorems\t{theorems}"
  IO.println s!"L5PKG\tmodules_with_declarations\t{modsWithDecls.size}"
  IO.println s!"L5PKG\tproject_axiom_declarations_unexpected\t{axiomsUnexpected.size}"
  IO.println s!"L5PKG\tunsafe_declarations\t{unsafeD.size}"
  IO.println s!"L5PKG\tpartial_declarations\t{partialD.size}"
  IO.println s!"L5PKG\tsorryAx_declarations_unexpected\t{sorryUnexpected.size}"
  IO.println s!"L5PKG\tnative_decide_declarations_unexpected\t{nativeUnexpected.size}"
  IO.println s!"L5PKG\tunapproved_axiom_declarations_all\t{unapprovedAll.size}"
  IO.println s!"L5PKG\tunapproved_axiom_declarations_unexpected\t{unapprovedUnexpected.size}"
  IO.println s!"L5PKG\tproof_wanted_declarations\t{proofWanted.size}"
  IO.println s!"L5PKG\tcollect_failures\t{collectFail.size}"
  for n in axiomsUnexpected do IO.println s!"L5PKGFAIL\tproject_axiom\t{n}"
  for n in unsafeD do IO.println s!"L5PKGFAIL\tunsafe\t{n}"
  for n in sorryUnexpected do IO.println s!"L5PKGFAIL\tsorryAx\t{n}"
  for n in nativeUnexpected do IO.println s!"L5PKGFAIL\tnative_decide\t{n}"
  for (n, a) in unapprovedUnexpected do IO.println s!"L5PKGFAIL\tunapproved_axiom\t{n}\t{a}"
  for n in proofWanted do IO.println s!"L5PKGFAIL\tproof_wanted\t{n}"
  for (n, e) in collectFail do IO.println s!"L5PKGFAIL\tcollect_exception\t{n}\t{e}"
  -- negative-control registry: always reported, with exact cones
  IO.println s!"L5NEGCLUSTER\tregistered\t{knownNegControls.length}"
  for n in knownNegControls do
    let present := env.constants.contains n
    let kind := match env.find? n with
      | some ci => kindOf ci
      | none => "ABSENT"
    let axs ←
      try Lean.collectAxioms n
      catch _ => pure #[]
    IO.println s!"L5NEGCLUSTER\t{n}\tpresent={present}\tkind={kind}\tcone={";".intercalate (axs.toList.map Name.toString)}"
  if annotate then
    let laneRows := rows.filter (fun (_, _, m) => isUnder laneRoots m)
    for (n, ci, _) in laneRows do
      let axs ←
        try Lean.collectAxioms n
        catch _ => pure #[]
      IO.println s!"L5DECL\t{n}\t{kindOf ci}\t{";".intercalate (axs.toList.map Name.toString)}"
    for (n, ci, _) in laneRows do
      let ty ← liftTermElabM (Meta.ppExpr ci.type)
      IO.println s!"L5TYPE\t{n}\t{kindOf ci}\t{(" ".intercalate (ty.pretty.splitOn "\n"))}"
    for (n, ci, _) in laneRows do
      match ci with
      | .defnInfo _ | .opaqueInfo _ =>
          let isP ← liftTermElabM (Meta.isProp ci.type)
          if isP then IO.println s!"L5PROP\t{n}\t{kindOf ci}"
      | _ => pure ()
    IO.println "L5EQUIV\tbegin"
    for (n, ci, _) in laneRows do
      if let .thmInfo _ := ci then
        try
          liftTermElabM do
            forallTelescopeReducing ci.type fun _ body => do
              for x in ← getLCtx do
                if !x.isLet && !x.isImplementationDetail then
                  let same := Expr.equal x.type body
                  let deq ← try Meta.isDefEq x.type body catch _ => pure false
                  if same || deq then
                    let ty ← Meta.ppExpr ci.type
                    IO.println s!"L5EQUIV\tHIT\t{n}\tsyntactic={same}\tdefeq={deq}\t{(" ".intercalate (ty.pretty.splitOn "\n"))}"
        catch _ => pure ()
    IO.println "L5EQUIV\tend"
    let laneSet : NameMap Unit := laneRows.foldl (fun acc (n, _, _) => acc.insert n ()) {}
    let mut consumers : NameMap (Array Name) := {}
    for (n, ci, _) in rows do
      let used := ci.type.getUsedConstants.toList.eraseDups.toArray
      let used := match ci.value? true with
        | some v => used ++ v.getUsedConstants.toList.eraseDups.toArray
        | none => used
      for u in used do
        if laneSet.contains u then
          consumers := consumers.insert u (((consumers.find? u).getD #[]).push n)
    let mut zeroUse := 0
    for (n, ci, _) in laneRows do
      let cs := (consumers.find? n).getD #[]
      if cs.isEmpty then zeroUse := zeroUse + 1
      IO.println s!"L5USE\t{n}\t{kindOf ci}\t{cs.size}\t{";".intercalate (cs.toList.eraseDups.take 8 |>.map Name.toString)}"
    IO.println s!"L5USE\tlane_declarations\t{laneRows.size}"
    IO.println s!"L5USE\tlane_declarations_with_zero_package_consumers\t{zeroUse}"
  let failed := !axiomsUnexpected.isEmpty || !unsafeD.isEmpty || !sorryUnexpected.isEmpty ||
      !nativeUnexpected.isEmpty || !unapprovedUnexpected.isEmpty || !proofWanted.isEmpty ||
      !collectFail.isEmpty
  if failed then
    IO.println "L5VERDICT\tFAIL"
    throwError "L5Audit: unexpected forbidden kernel dependency detected (see L5PKGFAIL lines)"
  else
    IO.println "L5VERDICT\tPASS — every audited declaration except the registered negative-control cluster depends only on {propext, Classical.choice, Quot.sound}"

end L5Audit
