import Poincare.D7.TensorLaplacian

/-!
# Poincare.D7.TensorLaplacian.Audit

**D7 tensor Laplacian layer, part 7: the `#print axioms` audit.**

Every principal declaration of `Poincare.D7.TensorLaplacian` is audited below. The file
compiles with `lake env lean` and the printed axiom cones are recorded in the result card.

All proofs are complete: no `sorry`, `axiom`, `unsafe`, `native_decide`, or `proof_wanted`.
-/

#print axioms Poincare.D7.TensorLaplacian.BlockerManifoldCurvature
#print axioms Poincare.D7.TensorLaplacian.BlockerManifoldCurvature_ne_nil
#print axioms Poincare.D7.TensorLaplacian.BlockerSmoothCommutation
#print axioms Poincare.D7.TensorLaplacian.BlockerSmoothCommutation_ne_nil
#print axioms Poincare.D7.TensorLaplacian.BlockerSmoothRoughLaplacian
#print axioms Poincare.D7.TensorLaplacian.BlockerSmoothRoughLaplacian_ne_nil
#print axioms Poincare.D7.TensorLaplacian.BlockerSmoothScalarEvolution
#print axioms Poincare.D7.TensorLaplacian.BlockerSmoothScalarEvolution_ne_nil
#print axioms Poincare.D7.TensorLaplacian.BlockerSmoothTensorBundle
#print axioms Poincare.D7.TensorLaplacian.BlockerSmoothTensorBundle_ne_nil
#print axioms Poincare.D7.TensorLaplacian.BlockerSmoothTensorConnection
#print axioms Poincare.D7.TensorLaplacian.BlockerSmoothTensorConnection_ne_nil
#print axioms Poincare.D7.TensorLaplacian.IsRicciFlowVelocity
#print axioms Poincare.D7.TensorLaplacian.IsSmoothScalarEvolutionDatum
#print axioms Poincare.D7.TensorLaplacian.IsSmoothTensorLaplacianDatum
#print axioms Poincare.D7.TensorLaplacian.MissingMathlibDependencies
#print axioms Poincare.D7.TensorLaplacian.MissingMathlibDependencies_length
#print axioms Poincare.D7.TensorLaplacian.MissingMathlibDependencies_ne_nil
#print axioms Poincare.D7.TensorLaplacian.PresentMathlibDependencies
#print axioms Poincare.D7.TensorLaplacian.PresentMathlibDependencies_length
#print axioms Poincare.D7.TensorLaplacian.PresentMathlibDependencies_ne_nil
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.anchor
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.bianchi
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.divdivH
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.flow
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.lapScal
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.mk
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.pairingH_eq
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.scalDeriv
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.scalPath
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.scalPath_zero
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.scalarDeriv_eq
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.scalar_evolution
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.scalar_evolution_forall
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.scalar_evolution_iff
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.traceH_eq
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.variation
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.variation_rhs_eq
#print axioms Poincare.D7.TensorLaplacian.ScalarEvolutionCertificate.velocity
#print axioms Poincare.D7.TensorLaplacian.SmoothCommutationStatement
#print axioms Poincare.D7.TensorLaplacian.SmoothCurvatureCertificateStatement
#print axioms Poincare.D7.TensorLaplacian.SmoothFrameTraceCommutationStatement
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.divdivH
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.isSmooth_zero
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.lapTrace
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.laplaceScal
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.metricVelocity
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.mk
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.pairingH
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.ricciForm
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.ricciNormSq
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.scal
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.scalarDeriv
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionDatum.zero
#print axioms Poincare.D7.TensorLaplacian.SmoothScalarEvolutionStatement
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.curvatureAction
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.dim
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.frame
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.isSmoothTensorField
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.isSmooth_zero
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.lieBracket
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.metricInner
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.mk
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.ricciAction
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.roughLaplacian
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.tensorNabla
#print axioms Poincare.D7.TensorLaplacian.SmoothTensorLaplacianDatum.zero
#print axioms Poincare.D7.TensorLaplacian.So3Example.so3EvolutionCertificate
#print axioms Poincare.D7.TensorLaplacian.So3Example.so3_evolution_identity
#print axioms Poincare.D7.TensorLaplacian.So3Example.so3_evolution_rhs_pos
#print axioms Poincare.D7.TensorLaplacian.So3Example.so3_ricciForm_basis_zero
#print axioms Poincare.D7.TensorLaplacian.So3Example.so3_ricciNormSq_pos
#print axioms Poincare.D7.TensorLaplacian.So3Example.so3_vector_curvature_witness
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.HasParallelCurvature
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.RicciCommutationCertificate
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.RicciCommutationCertificate.mk
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.RicciCommutationCertificate.ricciEndo
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.RicciCommutationCertificate.ricci_contraction_eq
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.ScalarCurvatureCommutationCertificate
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.ScalarCurvatureCommutationCertificate.frame_trace_eq
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.ScalarCurvatureCommutationCertificate.mk
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.ScalarCurvatureCommutationCertificate.toRicciCommutationCertificate
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.commutator_term
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_add₁
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_add₂
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_add₃
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_certificate
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_certificate_apply
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_neg₃
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_self
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_skew
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_skew_add_zero
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_smul₁
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_smul₂
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_smul₃
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_sub₃
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_zero₁
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_zero₂
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.curvature_zero₃
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.mk
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla_add
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla_add₁
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla_neg
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla_neg₁
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla_smul
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla_smul₁
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla_sub
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla_sub₁
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla_zero
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.nabla_zero₁
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.ricciContraction
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_add
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_apply
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_commutator_eq_zero_of_flat
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_commutator_frame_trace
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_commutator_general
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_commutator_of_bracket_zero
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_commutator_of_parallel
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_commutator_ricci
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_eq_zero_of_nabla_nabla_eq_zero
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_neg
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_smul
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_sub
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacian_zero
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.roughLaplacianₗ
#print axioms Poincare.D7.TensorLaplacian.TensorConnectionData.second_covariant_derivative_commutation
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.bianchi_wrong
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.divdivH
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.flow
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.lapScal
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.mk
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.pairingH
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.pairing_eq
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.ricNormSq
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.scal
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.scalDeriv
#print axioms Poincare.D7.TensorLaplacian.WrongBianchiData.variation
#print axioms Poincare.D7.TensorLaplacian.flatCertificate
#print axioms Poincare.D7.TensorLaplacian.isRicciFlowVelocity_ricciFlowVelocity
#print axioms Poincare.D7.TensorLaplacian.pairingH
#print axioms Poincare.D7.TensorLaplacian.pairingH_ricciFlowVelocity
#print axioms Poincare.D7.TensorLaplacian.prodTensorData
#print axioms Poincare.D7.TensorLaplacian.ricciFlowVelocity
#print axioms Poincare.D7.TensorLaplacian.ricciNormSq
#print axioms Poincare.D7.TensorLaplacian.ricciNormSq_nonneg
#print axioms Poincare.D7.TensorLaplacian.scalarTensorData
#print axioms Poincare.D7.TensorLaplacian.traceH
#print axioms Poincare.D7.TensorLaplacian.traceH_ricciFlowVelocity
#print axioms Poincare.D7.TensorLaplacian.vectorTensorData
#print axioms Poincare.D7.TensorLaplacian.wrongBianchiExample
#print axioms Poincare.D7.TensorLaplacian.wrongBianchi_identity_fails
