/- GENERATED by baseline/c1/gen_type_audit.py -- do not edit. -/
import Audit.CounterexampleAudit
import Audit.CurvatureODEAudit
import Audit.EvolutionAudit
import Audit.GeometryAudit
import Audit.PromotedEvolutionAudit
import D6AuditReport
import Ledger.DefinitionSmoke
import Ledger.PerelmanDefinitions
import Poincare.Basic
import Poincare.D10.BochnerEuclidean.Axioms
import Poincare.D10.BochnerEuclidean.Basic
import Poincare.D10.BochnerEuclidean.Bochner
import Poincare.D10.BochnerEuclidean.Compat
import Poincare.D10.BochnerEuclidean.Corollary
import Poincare.D10.GaussianToolbox.Basic
import Poincare.D10.GaussianToolbox.Convolution
import Poincare.D10.GaussianToolbox.Multivariate
import Poincare.D10.GaussianToolbox.PrintAxioms
import Poincare.D10.HeatKernelEuclidean.AxiomAudit
import Poincare.D10.HeatKernelEuclidean.Basic
import Poincare.D10.HeatKernelEuclidean.GaussianIntegral
import Poincare.D10.HeatKernelEuclidean.HeatEquation
import Poincare.D10.HeatKernelEuclidean.Mass
import Poincare.D10.HeatKernelEuclidean.Semigroup
import Poincare.D10.JacobiConstantCurvature.AxiomAudit
import Poincare.D10.JacobiConstantCurvature.Basic
import Poincare.D10.JacobiConstantCurvature.Comparison
import Poincare.D10.JacobiConstantCurvature.ODE
import Poincare.D10.MaximumPrincipleRN.AxiomAudit
import Poincare.D10.MaximumPrincipleRN.Basic
import Poincare.D10.MaximumPrincipleRN.SecondDerivativeTest
import Poincare.D10.MaximumPrincipleRN.Semidiscrete
import Poincare.D10.MaximumPrincipleRN.WeakMaximumPrinciple
import Poincare.D10.TriangulationLowDim.Audit
import Poincare.D10.TriangulationLowDim.Complex
import Poincare.D10.TriangulationLowDim.Models
import Poincare.D10.TriangulationLowDim.Moise
import Poincare.D11.BochnerManifold.Axioms
import Poincare.D11.BochnerManifold.Basic
import Poincare.D11.BochnerManifold.Corollaries
import Poincare.D11.BochnerManifold.D7Bridge
import Poincare.D11.BochnerManifold.ModelSpace
import Poincare.D11.BochnerManifold.Probe
import Poincare.D11.BochnerManifold.RadialBochner
import Poincare.D11.ComparisonModels.AxiomAudit
import Poincare.D11.ComparisonModels.Basic
import Poincare.D11.ComparisonModels.BishopGromov
import Poincare.D11.ComparisonModels.LaplacianComparison
import Poincare.D11.ComparisonModels.ModelMetrics
import Poincare.D11.HeatKernelBridge.All
import Poincare.D11.HeatKernelBridge.AxiomAudit
import Poincare.D11.HeatKernelBridge.Basic
import Poincare.D11.HeatKernelBridge.EuclideanInstance
import Poincare.D11.HeatKernelBridge.EuclideanLaplacian
import Poincare.D11.HeatKernelBridge.InitialCondition
import Poincare.D11.HeatKernelBridge.ZeroDimension
import Poincare.D11.MaximumPrincipleTensor.AxiomAudit
import Poincare.D11.MaximumPrincipleTensor.Basic
import Poincare.D11.MaximumPrincipleTensor.Euler
import Poincare.D11.MaximumPrincipleTensor.Flow
import Poincare.D11.MaximumPrincipleTensor.ScalarODE
import Poincare.D11.ReducedVolume.All
import Poincare.D11.ReducedVolume.Audit
import Poincare.D11.ReducedVolume.Basic
import Poincare.D11.ReducedVolume.Probe
import Poincare.D11.ReducedVolume.Statements
import Poincare.D11.ReducedVolume.StraightRays
import Poincare.D11.ReducedVolume.Volume
import Poincare.D11.SpectralTorus.AxiomsCheck
import Poincare.D11.SpectralTorus.Basic
import Poincare.D11.SpectralTorus.Laplacian
import Poincare.D11.SpectralTorus.Parseval
import Poincare.D11.SpectralTorus.Poincare
import Poincare.D11.SpectralTorus.Sobolev
import Poincare.D12.ComparisonGeodesics.AxiomAudit
import Poincare.D12.ComparisonGeodesics.Definitions
import Poincare.D12.ComparisonGeodesics.ModelEuclidean
import Poincare.D12.ComparisonGeodesics.RiccatiComparison
import Poincare.D12.ComparisonGeodesics.SingularRiccati
import Poincare.D12.ComparisonGeodesics.SturmComparison
import Poincare.D12.ComparisonGeodesics.VolumeRatio
import Poincare.D12.ConnectionCurvature
import Poincare.D12.ConnectionCurvature.ChartLeviCivita
import Poincare.D12.ConnectionCurvature.ChartLeviCivitaForm
import Poincare.D12.ConnectionCurvature.ChartLeviCivitaSmooth
import Poincare.D12.ConnectionCurvature.ChartModel1D
import Poincare.D12.ConnectionCurvature.ConformalChartModel
import Poincare.D12.ConnectionCurvature.MilnorLeviCivita
import Poincare.D12.ConnectionCurvature.RicciSymmetry
import Poincare.D12.ConnectionCurvature.SoThreeModel
import Poincare.D12.EntropyVariation.All
import Poincare.D12.EntropyVariation.AxiomAudit
import Poincare.D12.EntropyVariation.EntropyDerivative
import Poincare.D12.EntropyVariation.FFlowModel
import Poincare.D12.EntropyVariation.GaussianShrinker
import Poincare.D12.EntropyVariation.SignDistinction
import Poincare.D12.EntropyVariation.WeightedIntegral
import Poincare.D12.GeometricCompactness.AxiomAudit
import Poincare.D12.GeometricCompactness.Basic
import Poincare.D12.GeometricCompactness.Criterion
import Poincare.D12.GeometricCompactness.Frontier
import Poincare.D12.GeometricCompactness.GridFamily
import Poincare.D12.HeatDomain.All
import Poincare.D12.HeatDomain.AxiomAudit
import Poincare.D12.HeatDomain.CompactCompatibility
import Poincare.D12.HeatDomain.Counterexample
import Poincare.D12.HeatDomain.FlatInstance
import Poincare.D12.HeatDomain.TestFunction
import Poincare.D12.HeatSemigroup.All
import Poincare.D12.HeatSemigroup.AxiomAudit
import Poincare.D12.HeatSemigroup.Basic
import Poincare.D12.HeatSemigroup.Example
import Poincare.D12.HeatSemigroup.L1Contraction
import Poincare.D12.HeatSemigroup.LinfContraction
import Poincare.D12.HeatSemigroup.ManifoldObligations
import Poincare.D12.HeatSemigroup.Semigroup
import Poincare.D12.HeatSemigroup.Smoothing
import Poincare.D12.HeatSemigroup.StrongContinuity
import Poincare.D12.HeatSemigroup.StrongContinuityL1
import Poincare.D12.KappaVariational.All
import Poincare.D12.KappaVariational.Audit
import Poincare.D12.KappaVariational.CurvatureEnergy
import Poincare.D12.KappaVariational.GaussianNormalization
import Poincare.D12.KappaVariational.Statements
import Poincare.D12.KappaVariational.Transfer
import Poincare.D12.ParabolicLocal.AxiomAudit
import Poincare.D12.ParabolicLocal.BUC
import Poincare.D12.ParabolicLocal.DerivativeLoss
import Poincare.D12.ParabolicLocal.Duhamel
import Poincare.D12.ParabolicLocal.Examples
import Poincare.D12.ParabolicLocal.GaussianConv
import Poincare.D12.ParabolicLocal.GaussianSemigroup
import Poincare.D12.ParabolicLocal.GaussianSetup
import Poincare.D12.ParabolicLocal.MildExistence
import Poincare.D12.ParabolicLocal.Obligations
import Poincare.D12.ParabolicLocal.ParametricIntegral
import Poincare.D12.SemanticLedger.AxiomAudit
import Poincare.D12.SemanticLedger.Defect
import Poincare.D12.SemanticLedger.LedgerProbe
import Poincare.D12.SpectralSobolev.All
import Poincare.D12.SpectralSobolev.AxiomAudit
import Poincare.D12.SpectralSobolev.Basic
import Poincare.D12.SpectralSobolev.Examples
import Poincare.D12.SpectralSobolev.HeatConvergence
import Poincare.D12.SpectralSobolev.Poincare
import Poincare.D12.SpectralSobolev.Semigroup
import Poincare.D12.SurgeryRecognition.All
import Poincare.D12.SurgeryRecognition.Audit
import Poincare.D12.SurgeryRecognition.BallGluing
import Poincare.D12.SurgeryRecognition.ConnectedSumTopology
import Poincare.D12.SurgeryRecognition.CoveringRecognition
import Poincare.D12.SurgeryRecognition.DeckTrivial
import Poincare.D12.SurgeryRecognition.ExpandedInterfaces
import Poincare.D12.SurgeryRecognition.SphereOfSpheres
import Poincare.D12.TensorMaximumBochner.Audit
import Poincare.D12.TensorMaximumBochner.BochnerIdentity
import Poincare.D12.TensorMaximumBochner.PositivityPreservation
import Poincare.D12.TensorMaximumBochner.So3Model
import Poincare.D12.TensorMaximumBochner.So3Polynomial
import Poincare.D12.TensorMaximumBochner.So3RicciFlow
import Poincare.D12.TensorMaximumBochner.TangentCone
import Poincare.D12.TensorMaximumBochner.TensorCalculus
import Poincare.D12.TriangulationTopology.AntipodalQuotient
import Poincare.D12.TriangulationTopology.AxiomAudit
import Poincare.D12.TriangulationTopology.CoveringLemma
import Poincare.D12.TriangulationTopology.DiskGluing
import Poincare.D12.TriangulationTopology.Downstream
import Poincare.D12.TriangulationTopology.HemisphereDisk
import Poincare.D12.TriangulationTopology.MoiseBranch
import Poincare.D12.TriangulationTopology.NegControl.NegControl
import Poincare.D12.TriangulationTopology.SimplexBoundary
import Poincare.D12.TriangulationTopology.SimplexCone
import Poincare.D12.TriangulationTopology.SphereGluing
import Poincare.D12.TriangulationTopology.SphereMissedPoint
import Poincare.D12.TriangulationTopology.SphereOfTwoDisks
import Poincare.D12.TriangulationTopology.SpherePolygonal
import Poincare.D12.TriangulationTopology.SphereRecognition
import Poincare.D12.TriangulationTopology.SphereSimplyConnected
import Poincare.D12.TriangulationTopology.SphereSimplyConnectedMain
import Poincare.D12.TriangulationTopology.TwoHemisphereInstance
import Poincare.D12.VolumeIBP
import Poincare.D12.VolumeIBP.Audit
import Poincare.D12.VolumeIBP.Basic
import Poincare.D12.VolumeIBP.Blocked
import Poincare.D12.VolumeIBP.ChangeOfVariables
import Poincare.D12.VolumeIBP.Compat
import Poincare.D12.VolumeIBP.Divergence
import Poincare.D12.VolumeIBP.Example
import Poincare.D12.VolumeIBP.IBP
import Poincare.D12.VolumeIBP.Regularity
import Poincare.D13.IntegratedAudit.AuditCore
import Poincare.D13.IntegratedAudit.DependencyProbe
import Poincare.D13.IntegratedAudit.ExpectedModules
import Poincare.D13.IntegratedAudit.FullAudit
import Poincare.D13.IntegratedAudit.KernelAudit
import Poincare.D13.IntegratedAudit.NonvacuityProbe
import Poincare.D13.IntegratedAudit.SelfAudit
import Poincare.D13.IntegratedAudit.SnapshotRoot
import Poincare.D13.IntegratedAudit.StatementAudit
import Poincare.D13.IntegratedAudit.UsageProbe
import Poincare.D7.Bochner.Audit
import Poincare.D7.Bochner.Basic
import Poincare.D7.Bochner.Blocked
import Poincare.D7.Bochner.Euclidean
import Poincare.D7.Bochner.Example
import Poincare.D7.Bochner.GradientEstimate
import Poincare.D7.Bochner.Probe
import Poincare.D7.Canonical.All
import Poincare.D7.Canonical.Audit
import Poincare.D7.Canonical.Basic
import Poincare.D7.Canonical.Classification
import Poincare.D7.Canonical.Curvature
import Poincare.D7.Canonical.Models
import Poincare.D7.Canonical.Probe
import Poincare.D7.Canonical.Statements
import Poincare.D7.Compactness.All
import Poincare.D7.Compactness.Audit
import Poincare.D7.Compactness.Basic
import Poincare.D7.Compactness.ManifoldStatements
import Poincare.D7.Compactness.Nonvacuity
import Poincare.D7.Compactness.Probe
import Poincare.D7.Compactness.TotalBounded
import Poincare.D7.Compactness.ToyCompactness
import Poincare.D7.ConjugateHeat.All
import Poincare.D7.ConjugateHeat.Audit
import Poincare.D7.ConjugateHeat.Basic
import Poincare.D7.ConjugateHeat.Blocked
import Poincare.D7.ConjugateHeat.Example
import Poincare.D7.ConjugateHeat.Instance
import Poincare.D7.ConjugateHeat.Laplacian
import Poincare.D7.ConjugateHeat.Probe
import Poincare.D7.ConjugateHeat.Slab
import Poincare.D7.Curvature
import Poincare.D7.Curvature.Audit
import Poincare.D7.Curvature.Basic
import Poincare.D7.Curvature.Blocked
import Poincare.D7.Curvature.Bridge
import Poincare.D7.Curvature.Example
import Poincare.D7.Curvature.Probe
import Poincare.D7.Curvature.Sectional
import Poincare.D7.Curvature.Symmetries
import Poincare.D7.Divergence
import Poincare.D7.Divergence.Audit
import Poincare.D7.Divergence.Basic
import Poincare.D7.Divergence.Blocked
import Poincare.D7.Divergence.Example
import Poincare.D7.Divergence.Graph
import Poincare.D7.Divergence.Probe
import Poincare.D7.Divergence.Slab
import Poincare.D7.EvolutionSharp.AxiomAudit
import Poincare.D7.EvolutionSharp.Certificates
import Poincare.D7.EvolutionSharp.FunctionalSharp
import Poincare.D7.EvolutionSharp.GibbsSharp
import Poincare.D7.EvolutionSharp.Implications
import Poincare.D7.EvolutionSharp.ReleaseAudit
import Poincare.D7.EvolutionSharp.Witnesses
import Poincare.D7.Geodesic.AxiomAudit
import Poincare.D7.Geodesic.Basic
import Poincare.D7.Geodesic.FlatUniqueness
import Poincare.D7.Geodesic.ManifoldInterfaces
import Poincare.D7.Geodesic.MathlibProbe
import Poincare.D7.Geodesic.MetricSpeed
import Poincare.D7.Geodesic.Reparam
import Poincare.D7.Geodesic.Smoke
import Poincare.D7.HeatKernel.All
import Poincare.D7.HeatKernel.Audit
import Poincare.D7.HeatKernel.Basic
import Poincare.D7.HeatKernel.Blocked
import Poincare.D7.HeatKernel.Content
import Poincare.D7.HeatKernel.Example
import Poincare.D7.HeatKernel.Grid
import Poincare.D7.HeatKernel.Instance
import Poincare.D7.HeatKernel.Probe
import Poincare.D7.Kappa.Basic
import Poincare.D7.LeviCivita.Audit
import Poincare.D7.LeviCivita.Basic
import Poincare.D7.LeviCivita.Blocked
import Poincare.D7.LeviCivita.Coefficients
import Poincare.D7.LeviCivita.Koszul
import Poincare.D7.LeviCivita.Probe
import Poincare.D7.LeviCivita.Smoke
import Poincare.D7.Limit.All
import Poincare.D7.Limit.Audit
import Poincare.D7.Limit.Basic
import Poincare.D7.Limit.Blocked
import Poincare.D7.Limit.Convergence
import Poincare.D7.Limit.ErrorRecursion
import Poincare.D7.Limit.Example
import Poincare.D7.Limit.Probe
import Poincare.D7.Limit.Refinement
import Poincare.D7.Limit.Stability
import Poincare.D7.Monotonicity.ReducedVolumeInput
import Poincare.D7.Recognition.All
import Poincare.D7.Recognition.Assembly
import Poincare.D7.Recognition.Audit
import Poincare.D7.Recognition.Basic
import Poincare.D7.Recognition.Homeomorphism
import Poincare.D7.Recognition.Probe
import Poincare.D7.Reduced.All
import Poincare.D7.Reduced.Audit
import Poincare.D7.Reduced.Basic
import Poincare.D7.Reduced.Certificate
import Poincare.D7.Reduced.Gaussian
import Poincare.D7.Reduced.Probe
import Poincare.D7.Reduced.Statements
import Poincare.D7.RicciScalar
import Poincare.D7.RicciScalar.Audit
import Poincare.D7.RicciScalar.Basic
import Poincare.D7.RicciScalar.Bridge
import Poincare.D7.RicciScalar.Example
import Poincare.D7.RicciScalar.Probe
import Poincare.D7.RicciScalar.Product
import Poincare.D7.RicciScalar.Scalar
import Poincare.D7.RicciScalar.Variation
import Poincare.D7.ShortTime
import Poincare.D7.ShortTime.Audit
import Poincare.D7.ShortTime.Basic
import Poincare.D7.ShortTime.Equivalence
import Poincare.D7.ShortTime.Example
import Poincare.D7.ShortTime.Gauge
import Poincare.D7.ShortTime.MatrixDeriv
import Poincare.D7.ShortTime.ODE
import Poincare.D7.ShortTime.Probe
import Poincare.D7.ShortTime.Statements
import Poincare.D7.SurgeryFlow.All
import Poincare.D7.SurgeryFlow.Audit
import Poincare.D7.SurgeryFlow.Basic
import Poincare.D7.SurgeryFlow.Extinction
import Poincare.D7.SurgeryFlow.Probe
import Poincare.D7.SurgeryFlow.Statements
import Poincare.D7.SurgeryFlow.Times
import Poincare.D7.TensorLaplacian
import Poincare.D7.TensorLaplacian.Audit
import Poincare.D7.TensorLaplacian.Basic
import Poincare.D7.TensorLaplacian.Blocked
import Poincare.D7.TensorLaplacian.Commutation
import Poincare.D7.TensorLaplacian.Evolution
import Poincare.D7.TensorLaplacian.Example
import Poincare.D7.TensorLaplacian.Probe
import Poincare.D7.Volume
import Poincare.D7.Volume.Audit
import Poincare.D7.Volume.Basic
import Poincare.D7.Volume.Blocked
import Poincare.D7.Volume.ChangeOfVariables
import Poincare.D7.Volume.Example
import Poincare.D7.Volume.Probe
import Poincare.D7.Volume.Scaling
import Poincare.D8.Fidelity.AxiomAudit
import Poincare.D8.Fidelity.Bridge
import Poincare.D8.Fidelity.FidelityCard
import Poincare.D8.Fidelity.MoiseData
import Poincare.D8.Fidelity.MoiseStatement
import Poincare.D8.Fidelity.SmoothStructure
import Poincare.D9.AncientKappa.Basic
import Poincare.D9.AncientKappa.Classification
import Poincare.D9.AncientKappa.GaussianSoliton
import Poincare.D9.AncientKappa.PrintAxioms
import Poincare.D9.CheegerGromov.AxiomAudit
import Poincare.D9.CheegerGromov.CheegerGromov
import Poincare.D9.CheegerGromov.DiscreteModel
import Poincare.D9.CheegerGromov.PointedConvergence
import Poincare.D9.DeTurck.ConnectionLayer
import Poincare.D9.DeTurck.StatementOnly
import Poincare.D9.DeTurck.SymbolModel
import Poincare.D9.ParabolicEstimates.AxiomAudit
import Poincare.D9.ParabolicEstimates.Basic
import Poincare.D9.ParabolicEstimates.Gronwall
import Poincare.D9.ParabolicEstimates.MatrixModel
import Poincare.D9.ParabolicEstimates.Statements
import Poincare.D9.Surfaces.All
import Poincare.D9.Surfaces.AxiomAudit
import Poincare.D9.Surfaces.Basic
import Poincare.D9.Surfaces.HomogeneousODE
import Poincare.D9.Surfaces.Statements
import Poincare.D9.TensorAlgebra.AxiomAudit
import Poincare.D9.TensorAlgebra.Interface
import Poincare.D9.TensorAlgebra.Props
import Poincare.D9.TensorAlgebra.Toy
import Poincare.Longrun.CurvatureODE
import Poincare.Longrun.CurvatureODE.Bridge
import Poincare.Longrun.CurvatureODE.Evolution
import Poincare.Longrun.CurvatureODE.Invariant
import Poincare.Longrun.CurvatureODE.Monotonicity
import Poincare.Longrun.CurvatureODE.ScalarODE
import Poincare.Longrun.CurvatureODE.State
import Poincare.Longrun.Entropy
import Poincare.Longrun.Entropy.AxiomAudit
import Poincare.Longrun.Entropy.Bridge
import Poincare.Longrun.Entropy.Certificate
import Poincare.Longrun.Entropy.DiscreteHeat
import Poincare.Longrun.Entropy.FiniteGeometry
import Poincare.Longrun.Entropy.Functional
import Poincare.Longrun.Evolution
import Poincare.Longrun.Evolution.Bridge
import Poincare.Longrun.Evolution.Continuous
import Poincare.Longrun.Evolution.Counterexample
import Poincare.Longrun.Evolution.Discrete
import Poincare.Longrun.Evolution.Functional
import Poincare.Longrun.Evolution.Gibbs
import Poincare.Longrun.Geometry
import Poincare.Longrun.Geometry.ConnectionAdapter
import Poincare.Longrun.Geometry.Contraction
import Poincare.Longrun.Geometry.LeviCivitaBlocked
import Poincare.Longrun.Geometry.MetricData
import Poincare.Longrun.PDE.AxiomAudit
import Poincare.Longrun.PDE.ContinuousInterface
import Poincare.Longrun.PDE.DiscreteMaximumPrinciple
import Poincare.Longrun.PDE.Energy
import Poincare.Longrun.PDE.HeatGrid
import Poincare.Longrun.Surgery
import Poincare.Longrun.Surgery.Axioms
import Poincare.Longrun.Surgery.Basic
import Poincare.Longrun.Surgery.Chain
import Poincare.Longrun.Surgery.Missing
import Poincare.Longrun.Surgery.Toy
import Poincare.Longrun.Topology.AxiomAudit
import Poincare.Longrun.Topology.Basic
import Poincare.Longrun.Topology.CompactThreeManifold
import Poincare.Longrun.Topology.MissingTheorems
import Poincare.Longrun.Topology.Noncollapsing
import Poincare.Longrun.Topology.NormalizedVolume
import Poincare.Longrun.Topology.Stage6Bridge
import Poincare.Stage1.CurvatureAlgebra
import Poincare.Stage1.RiemannAdapter
import Poincare.Stage6.SphereSimplyConnected
import Poincare.Stage6.TopologyBridge
import Poincare.VKPort.HatcherLib.Ch1.AlgebraicConstructions
import Poincare.VKPort.HatcherLib.Ch1.BasicConstructions
import Poincare.VKPort.HatcherLib.Ch1.VanKampen
import Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid
import Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep
import Poincare.VKPort.HatcherLib.Ch1.VanKampenGrid
import Poincare.VKPort.HatcherLib.Ch1.VanKampenSubdivision
import Poincare.VKPort.HatcherLib.Ch1.VanKampenSweep
import Poincare.VKPort.HatcherLib.Ch1.VanKampenWordCalculus
import Poincare.VKPort.HatcherLib.VKProbe
import Probe.GeometryApi
import Probe.PdeApi
import ReleaseAudit
import ReleaseCheck

open Lean Elab Command

namespace L1TypeAuditG1

/-- Modules whose declarations are dumped in this partition (same partition as the
frozen axiom audit). -/
def targetModules : Array Name := #[
  `Audit.CounterexampleAudit,
  `Audit.CurvatureODEAudit,
  `Audit.EvolutionAudit,
  `Audit.GeometryAudit,
  `Audit.PromotedEvolutionAudit,
  `D6AuditReport,
  `Ledger.DefinitionSmoke,
  `Ledger.PerelmanDefinitions,
  `Poincare.Basic,
  `Poincare.D10.BochnerEuclidean.Axioms,
  `Poincare.D10.BochnerEuclidean.Basic,
  `Poincare.D10.BochnerEuclidean.Bochner,
  `Poincare.D10.BochnerEuclidean.Compat,
  `Poincare.D10.BochnerEuclidean.Corollary,
  `Poincare.D10.GaussianToolbox.Basic,
  `Poincare.D10.GaussianToolbox.Convolution,
  `Poincare.D10.GaussianToolbox.Multivariate,
  `Poincare.D10.GaussianToolbox.PrintAxioms,
  `Poincare.D10.HeatKernelEuclidean.AxiomAudit,
  `Poincare.D10.HeatKernelEuclidean.Basic,
  `Poincare.D10.HeatKernelEuclidean.GaussianIntegral,
  `Poincare.D10.HeatKernelEuclidean.HeatEquation,
  `Poincare.D10.HeatKernelEuclidean.Mass,
  `Poincare.D10.HeatKernelEuclidean.Semigroup,
  `Poincare.D10.JacobiConstantCurvature.AxiomAudit,
  `Poincare.D10.JacobiConstantCurvature.Basic,
  `Poincare.D10.JacobiConstantCurvature.Comparison,
  `Poincare.D10.JacobiConstantCurvature.ODE,
  `Poincare.D10.MaximumPrincipleRN.AxiomAudit,
  `Poincare.D10.MaximumPrincipleRN.Basic,
  `Poincare.D10.MaximumPrincipleRN.SecondDerivativeTest,
  `Poincare.D10.MaximumPrincipleRN.Semidiscrete,
  `Poincare.D10.MaximumPrincipleRN.WeakMaximumPrinciple,
  `Poincare.D10.TriangulationLowDim.Audit,
  `Poincare.D10.TriangulationLowDim.Complex,
  `Poincare.D10.TriangulationLowDim.Models,
  `Poincare.D10.TriangulationLowDim.Moise,
  `Poincare.D11.BochnerManifold.Axioms,
  `Poincare.D11.BochnerManifold.Basic,
  `Poincare.D11.BochnerManifold.Corollaries,
  `Poincare.D11.BochnerManifold.D7Bridge,
  `Poincare.D11.BochnerManifold.ModelSpace,
  `Poincare.D11.BochnerManifold.Probe,
  `Poincare.D11.BochnerManifold.RadialBochner,
  `Poincare.D11.ComparisonModels.AxiomAudit,
  `Poincare.D11.ComparisonModels.Basic,
  `Poincare.D11.ComparisonModels.BishopGromov,
  `Poincare.D11.ComparisonModels.LaplacianComparison,
  `Poincare.D11.ComparisonModels.ModelMetrics,
  `Poincare.D11.HeatKernelBridge.All,
  `Poincare.D11.HeatKernelBridge.AxiomAudit,
  `Poincare.D11.HeatKernelBridge.Basic,
  `Poincare.D11.HeatKernelBridge.EuclideanInstance,
  `Poincare.D11.HeatKernelBridge.EuclideanLaplacian,
  `Poincare.D11.HeatKernelBridge.InitialCondition,
  `Poincare.D11.HeatKernelBridge.ZeroDimension,
  `Poincare.D11.MaximumPrincipleTensor.AxiomAudit,
  `Poincare.D11.MaximumPrincipleTensor.Basic,
  `Poincare.D11.MaximumPrincipleTensor.Euler,
  `Poincare.D11.MaximumPrincipleTensor.Flow,
  `Poincare.D11.MaximumPrincipleTensor.ScalarODE,
  `Poincare.D11.ReducedVolume.All,
  `Poincare.D11.ReducedVolume.Audit,
  `Poincare.D11.ReducedVolume.Basic,
  `Poincare.D11.ReducedVolume.Probe,
  `Poincare.D11.ReducedVolume.Statements,
  `Poincare.D11.ReducedVolume.StraightRays,
  `Poincare.D11.ReducedVolume.Volume,
  `Poincare.D11.SpectralTorus.AxiomsCheck,
  `Poincare.D11.SpectralTorus.Basic,
  `Poincare.D11.SpectralTorus.Laplacian,
  `Poincare.D11.SpectralTorus.Parseval,
  `Poincare.D11.SpectralTorus.Poincare,
  `Poincare.D11.SpectralTorus.Sobolev,
  `Poincare.D12.ComparisonGeodesics.AxiomAudit,
  `Poincare.D12.ComparisonGeodesics.Definitions,
  `Poincare.D12.ComparisonGeodesics.ModelEuclidean,
  `Poincare.D12.ComparisonGeodesics.RiccatiComparison,
  `Poincare.D12.ComparisonGeodesics.SingularRiccati,
  `Poincare.D12.ComparisonGeodesics.SturmComparison,
  `Poincare.D12.ComparisonGeodesics.VolumeRatio,
  `Poincare.D12.ConnectionCurvature,
  `Poincare.D12.ConnectionCurvature.ChartLeviCivita,
  `Poincare.D12.ConnectionCurvature.ChartLeviCivitaForm,
  `Poincare.D12.ConnectionCurvature.ChartLeviCivitaSmooth,
  `Poincare.D12.ConnectionCurvature.ChartModel1D,
  `Poincare.D12.ConnectionCurvature.ConformalChartModel,
  `Poincare.D12.ConnectionCurvature.MilnorLeviCivita,
  `Poincare.D12.ConnectionCurvature.RicciSymmetry,
  `Poincare.D12.ConnectionCurvature.SoThreeModel,
  `Poincare.D12.EntropyVariation.All,
  `Poincare.D12.EntropyVariation.AxiomAudit,
  `Poincare.D12.EntropyVariation.EntropyDerivative,
  `Poincare.D12.EntropyVariation.FFlowModel,
  `Poincare.D12.EntropyVariation.GaussianShrinker,
  `Poincare.D12.EntropyVariation.SignDistinction,
  `Poincare.D12.EntropyVariation.WeightedIntegral,
  `Poincare.D12.GeometricCompactness.AxiomAudit,
  `Poincare.D12.GeometricCompactness.Basic,
  `Poincare.D12.GeometricCompactness.Criterion,
  `Poincare.D12.GeometricCompactness.Frontier,
  `Poincare.D12.GeometricCompactness.GridFamily,
  `Poincare.D12.HeatDomain.All,
  `Poincare.D12.HeatDomain.AxiomAudit,
  `Poincare.D12.HeatDomain.CompactCompatibility,
  `Poincare.D12.HeatDomain.Counterexample,
  `Poincare.D12.HeatDomain.FlatInstance,
  `Poincare.D12.HeatDomain.TestFunction,
  `Poincare.D12.HeatSemigroup.All,
  `Poincare.D12.HeatSemigroup.AxiomAudit,
  `Poincare.D12.HeatSemigroup.Basic,
  `Poincare.D12.HeatSemigroup.Example,
  `Poincare.D12.HeatSemigroup.L1Contraction,
  `Poincare.D12.HeatSemigroup.LinfContraction,
  `Poincare.D12.HeatSemigroup.ManifoldObligations,
  `Poincare.D12.HeatSemigroup.Semigroup,
  `Poincare.D12.HeatSemigroup.Smoothing,
  `Poincare.D12.HeatSemigroup.StrongContinuity,
  `Poincare.D12.HeatSemigroup.StrongContinuityL1,
  `Poincare.D12.KappaVariational.All,
  `Poincare.D12.KappaVariational.Audit,
  `Poincare.D12.KappaVariational.CurvatureEnergy,
  `Poincare.D12.KappaVariational.GaussianNormalization,
  `Poincare.D12.KappaVariational.Statements,
  `Poincare.D12.KappaVariational.Transfer,
  `Poincare.D12.ParabolicLocal.AxiomAudit,
  `Poincare.D12.ParabolicLocal.BUC,
  `Poincare.D12.ParabolicLocal.DerivativeLoss,
  `Poincare.D12.ParabolicLocal.Duhamel,
  `Poincare.D12.ParabolicLocal.Examples,
  `Poincare.D12.ParabolicLocal.GaussianConv,
  `Poincare.D12.ParabolicLocal.GaussianSemigroup,
  `Poincare.D12.ParabolicLocal.GaussianSetup,
  `Poincare.D12.ParabolicLocal.MildExistence,
  `Poincare.D12.ParabolicLocal.Obligations,
  `Poincare.D12.ParabolicLocal.ParametricIntegral,
  `Poincare.D12.SemanticLedger.AxiomAudit,
  `Poincare.D12.SemanticLedger.Defect,
  `Poincare.D12.SemanticLedger.LedgerProbe,
  `Poincare.D12.SpectralSobolev.All,
  `Poincare.D12.SpectralSobolev.AxiomAudit,
  `Poincare.D12.SpectralSobolev.Basic,
  `Poincare.D12.SpectralSobolev.Examples,
  `Poincare.D12.SpectralSobolev.HeatConvergence,
  `Poincare.D12.SpectralSobolev.Poincare,
  `Poincare.D12.SpectralSobolev.Semigroup,
  `Poincare.D12.SurgeryRecognition.All,
  `Poincare.D12.SurgeryRecognition.Audit,
  `Poincare.D12.SurgeryRecognition.BallGluing,
  `Poincare.D12.SurgeryRecognition.ConnectedSumTopology,
  `Poincare.D12.SurgeryRecognition.CoveringRecognition,
  `Poincare.D12.SurgeryRecognition.DeckTrivial,
  `Poincare.D12.SurgeryRecognition.ExpandedInterfaces,
  `Poincare.D12.SurgeryRecognition.SphereOfSpheres,
  `Poincare.D12.TensorMaximumBochner.Audit,
  `Poincare.D12.TensorMaximumBochner.BochnerIdentity,
  `Poincare.D12.TensorMaximumBochner.PositivityPreservation,
  `Poincare.D12.TensorMaximumBochner.So3Model,
  `Poincare.D12.TensorMaximumBochner.So3Polynomial,
  `Poincare.D12.TensorMaximumBochner.So3RicciFlow,
  `Poincare.D12.TensorMaximumBochner.TangentCone,
  `Poincare.D12.TensorMaximumBochner.TensorCalculus,
  `Poincare.D12.TriangulationTopology.AntipodalQuotient,
  `Poincare.D12.TriangulationTopology.AxiomAudit,
  `Poincare.D12.TriangulationTopology.CoveringLemma,
  `Poincare.D12.TriangulationTopology.DiskGluing,
  `Poincare.D12.TriangulationTopology.Downstream,
  `Poincare.D12.TriangulationTopology.HemisphereDisk,
  `Poincare.D12.TriangulationTopology.MoiseBranch,
  `Poincare.D12.TriangulationTopology.NegControl.NegControl,
  `Poincare.D12.TriangulationTopology.SimplexBoundary,
  `Poincare.D12.TriangulationTopology.SimplexCone,
  `Poincare.D12.TriangulationTopology.SphereGluing,
  `Poincare.D12.TriangulationTopology.SphereMissedPoint,
  `Poincare.D12.TriangulationTopology.SphereOfTwoDisks,
  `Poincare.D12.TriangulationTopology.SpherePolygonal,
  `Poincare.D12.TriangulationTopology.SphereRecognition,
  `Poincare.D12.TriangulationTopology.SphereSimplyConnected,
  `Poincare.D12.TriangulationTopology.SphereSimplyConnectedMain,
  `Poincare.D12.TriangulationTopology.TwoHemisphereInstance,
  `Poincare.D12.VolumeIBP,
  `Poincare.D12.VolumeIBP.Audit,
  `Poincare.D12.VolumeIBP.Basic,
  `Poincare.D12.VolumeIBP.Blocked,
  `Poincare.D12.VolumeIBP.ChangeOfVariables,
  `Poincare.D12.VolumeIBP.Compat,
  `Poincare.D12.VolumeIBP.Divergence,
  `Poincare.D12.VolumeIBP.Example,
  `Poincare.D12.VolumeIBP.IBP,
  `Poincare.D12.VolumeIBP.Regularity,
  `Poincare.D13.IntegratedAudit.AuditCore,
  `Poincare.D13.IntegratedAudit.DependencyProbe,
  `Poincare.D13.IntegratedAudit.ExpectedModules,
  `Poincare.D13.IntegratedAudit.FullAudit,
  `Poincare.D13.IntegratedAudit.KernelAudit,
  `Poincare.D13.IntegratedAudit.NonvacuityProbe,
  `Poincare.D13.IntegratedAudit.SelfAudit,
  `Poincare.D13.IntegratedAudit.SnapshotRoot,
  `Poincare.D13.IntegratedAudit.StatementAudit,
  `Poincare.D13.IntegratedAudit.UsageProbe,
  `Poincare.D7.Bochner.Audit,
  `Poincare.D7.Bochner.Basic,
  `Poincare.D7.Bochner.Blocked,
  `Poincare.D7.Bochner.Euclidean,
  `Poincare.D7.Bochner.Example,
  `Poincare.D7.Bochner.GradientEstimate,
  `Poincare.D7.Bochner.Probe,
  `Poincare.D7.Canonical.All,
  `Poincare.D7.Canonical.Audit,
  `Poincare.D7.Canonical.Basic,
  `Poincare.D7.Canonical.Classification,
  `Poincare.D7.Canonical.Curvature,
  `Poincare.D7.Canonical.Models,
  `Poincare.D7.Canonical.Probe,
  `Poincare.D7.Canonical.Statements,
  `Poincare.D7.Compactness.All,
  `Poincare.D7.Compactness.Audit,
  `Poincare.D7.Compactness.Basic,
  `Poincare.D7.Compactness.ManifoldStatements,
  `Poincare.D7.Compactness.Nonvacuity,
  `Poincare.D7.Compactness.Probe,
  `Poincare.D7.Compactness.TotalBounded,
  `Poincare.D7.Compactness.ToyCompactness,
  `Poincare.D7.ConjugateHeat.All,
  `Poincare.D7.ConjugateHeat.Audit,
  `Poincare.D7.ConjugateHeat.Basic,
  `Poincare.D7.ConjugateHeat.Blocked,
  `Poincare.D7.ConjugateHeat.Example,
  `Poincare.D7.ConjugateHeat.Instance,
  `Poincare.D7.ConjugateHeat.Laplacian,
  `Poincare.D7.ConjugateHeat.Probe,
  `Poincare.D7.ConjugateHeat.Slab,
  `Poincare.D7.Curvature,
  `Poincare.D7.Curvature.Audit,
  `Poincare.D7.Curvature.Basic,
  `Poincare.D7.Curvature.Blocked,
  `Poincare.D7.Curvature.Bridge,
  `Poincare.D7.Curvature.Example,
  `Poincare.D7.Curvature.Probe,
  `Poincare.D7.Curvature.Sectional,
  `Poincare.D7.Curvature.Symmetries,
  `Poincare.D7.Divergence,
  `Poincare.D7.Divergence.Audit,
  `Poincare.D7.Divergence.Basic,
  `Poincare.D7.Divergence.Blocked,
  `Poincare.D7.Divergence.Example,
  `Poincare.D7.Divergence.Graph,
  `Poincare.D7.Divergence.Probe,
  `Poincare.D7.Divergence.Slab,
  `Poincare.D7.EvolutionSharp.AxiomAudit,
  `Poincare.D7.EvolutionSharp.Certificates,
  `Poincare.D7.EvolutionSharp.FunctionalSharp,
  `Poincare.D7.EvolutionSharp.GibbsSharp,
  `Poincare.D7.EvolutionSharp.Implications,
  `Poincare.D7.EvolutionSharp.ReleaseAudit,
  `Poincare.D7.EvolutionSharp.Witnesses,
  `Poincare.D7.Geodesic.AxiomAudit,
  `Poincare.D7.Geodesic.Basic,
  `Poincare.D7.Geodesic.FlatUniqueness,
  `Poincare.D7.Geodesic.ManifoldInterfaces,
  `Poincare.D7.Geodesic.MathlibProbe,
  `Poincare.D7.Geodesic.MetricSpeed,
  `Poincare.D7.Geodesic.Reparam,
  `Poincare.D7.Geodesic.Smoke,
  `Poincare.D7.HeatKernel.All,
  `Poincare.D7.HeatKernel.Audit,
  `Poincare.D7.HeatKernel.Basic,
  `Poincare.D7.HeatKernel.Blocked,
  `Poincare.D7.HeatKernel.Content,
  `Poincare.D7.HeatKernel.Example,
  `Poincare.D7.HeatKernel.Grid,
  `Poincare.D7.HeatKernel.Instance,
  `Poincare.D7.HeatKernel.Probe,
  `Poincare.D7.Kappa.Basic,
  `Poincare.D7.LeviCivita.Audit,
  `Poincare.D7.LeviCivita.Basic,
  `Poincare.D7.LeviCivita.Blocked,
  `Poincare.D7.LeviCivita.Coefficients,
  `Poincare.D7.LeviCivita.Koszul,
  `Poincare.D7.LeviCivita.Probe,
  `Poincare.D7.LeviCivita.Smoke,
  `Poincare.D7.Limit.All,
  `Poincare.D7.Limit.Audit,
  `Poincare.D7.Limit.Basic,
  `Poincare.D7.Limit.Blocked,
  `Poincare.D7.Limit.Convergence,
  `Poincare.D7.Limit.ErrorRecursion,
  `Poincare.D7.Limit.Example,
  `Poincare.D7.Limit.Probe,
  `Poincare.D7.Limit.Refinement,
  `Poincare.D7.Limit.Stability,
  `Poincare.D7.Monotonicity.ReducedVolumeInput,
  `Poincare.D7.Recognition.All,
  `Poincare.D7.Recognition.Assembly,
  `Poincare.D7.Recognition.Audit,
  `Poincare.D7.Recognition.Basic,
  `Poincare.D7.Recognition.Homeomorphism,
  `Poincare.D7.Recognition.Probe,
  `Poincare.D7.Reduced.All,
  `Poincare.D7.Reduced.Audit,
  `Poincare.D7.Reduced.Basic,
  `Poincare.D7.Reduced.Certificate,
  `Poincare.D7.Reduced.Gaussian,
  `Poincare.D7.Reduced.Probe,
  `Poincare.D7.Reduced.Statements,
  `Poincare.D7.RicciScalar,
  `Poincare.D7.RicciScalar.Audit,
  `Poincare.D7.RicciScalar.Basic,
  `Poincare.D7.RicciScalar.Bridge,
  `Poincare.D7.RicciScalar.Example,
  `Poincare.D7.RicciScalar.Probe,
  `Poincare.D7.RicciScalar.Product,
  `Poincare.D7.RicciScalar.Scalar,
  `Poincare.D7.RicciScalar.Variation,
  `Poincare.D7.ShortTime,
  `Poincare.D7.ShortTime.Audit,
  `Poincare.D7.ShortTime.Basic,
  `Poincare.D7.ShortTime.Equivalence,
  `Poincare.D7.ShortTime.Example,
  `Poincare.D7.ShortTime.Gauge,
  `Poincare.D7.ShortTime.MatrixDeriv,
  `Poincare.D7.ShortTime.ODE,
  `Poincare.D7.ShortTime.Probe,
  `Poincare.D7.ShortTime.Statements,
  `Poincare.D7.SurgeryFlow.All,
  `Poincare.D7.SurgeryFlow.Audit,
  `Poincare.D7.SurgeryFlow.Basic,
  `Poincare.D7.SurgeryFlow.Extinction,
  `Poincare.D7.SurgeryFlow.Probe,
  `Poincare.D7.SurgeryFlow.Statements,
  `Poincare.D7.SurgeryFlow.Times,
  `Poincare.D7.TensorLaplacian,
  `Poincare.D7.TensorLaplacian.Audit,
  `Poincare.D7.TensorLaplacian.Basic,
  `Poincare.D7.TensorLaplacian.Blocked,
  `Poincare.D7.TensorLaplacian.Commutation,
  `Poincare.D7.TensorLaplacian.Evolution,
  `Poincare.D7.TensorLaplacian.Example,
  `Poincare.D7.TensorLaplacian.Probe,
  `Poincare.D7.Volume,
  `Poincare.D7.Volume.Audit,
  `Poincare.D7.Volume.Basic,
  `Poincare.D7.Volume.Blocked,
  `Poincare.D7.Volume.ChangeOfVariables,
  `Poincare.D7.Volume.Example,
  `Poincare.D7.Volume.Probe,
  `Poincare.D7.Volume.Scaling,
  `Poincare.D8.Fidelity.AxiomAudit,
  `Poincare.D8.Fidelity.Bridge,
  `Poincare.D8.Fidelity.FidelityCard,
  `Poincare.D8.Fidelity.MoiseData,
  `Poincare.D8.Fidelity.MoiseStatement,
  `Poincare.D8.Fidelity.SmoothStructure,
  `Poincare.D9.AncientKappa.Basic,
  `Poincare.D9.AncientKappa.Classification,
  `Poincare.D9.AncientKappa.GaussianSoliton,
  `Poincare.D9.AncientKappa.PrintAxioms,
  `Poincare.D9.CheegerGromov.AxiomAudit,
  `Poincare.D9.CheegerGromov.CheegerGromov,
  `Poincare.D9.CheegerGromov.DiscreteModel,
  `Poincare.D9.CheegerGromov.PointedConvergence,
  `Poincare.D9.DeTurck.ConnectionLayer,
  `Poincare.D9.DeTurck.StatementOnly,
  `Poincare.D9.DeTurck.SymbolModel,
  `Poincare.D9.ParabolicEstimates.AxiomAudit,
  `Poincare.D9.ParabolicEstimates.Basic,
  `Poincare.D9.ParabolicEstimates.Gronwall,
  `Poincare.D9.ParabolicEstimates.MatrixModel,
  `Poincare.D9.ParabolicEstimates.Statements,
  `Poincare.D9.Surfaces.All,
  `Poincare.D9.Surfaces.AxiomAudit,
  `Poincare.D9.Surfaces.Basic,
  `Poincare.D9.Surfaces.HomogeneousODE,
  `Poincare.D9.Surfaces.Statements,
  `Poincare.D9.TensorAlgebra.AxiomAudit,
  `Poincare.D9.TensorAlgebra.Interface,
  `Poincare.D9.TensorAlgebra.Props,
  `Poincare.D9.TensorAlgebra.Toy,
  `Poincare.Longrun.CurvatureODE,
  `Poincare.Longrun.CurvatureODE.Bridge,
  `Poincare.Longrun.CurvatureODE.Evolution,
  `Poincare.Longrun.CurvatureODE.Invariant,
  `Poincare.Longrun.CurvatureODE.Monotonicity,
  `Poincare.Longrun.CurvatureODE.ScalarODE,
  `Poincare.Longrun.CurvatureODE.State,
  `Poincare.Longrun.Entropy,
  `Poincare.Longrun.Entropy.AxiomAudit,
  `Poincare.Longrun.Entropy.Bridge,
  `Poincare.Longrun.Entropy.Certificate,
  `Poincare.Longrun.Entropy.DiscreteHeat,
  `Poincare.Longrun.Entropy.FiniteGeometry,
  `Poincare.Longrun.Entropy.Functional,
  `Poincare.Longrun.Evolution,
  `Poincare.Longrun.Evolution.Bridge,
  `Poincare.Longrun.Evolution.Continuous,
  `Poincare.Longrun.Evolution.Counterexample,
  `Poincare.Longrun.Evolution.Discrete,
  `Poincare.Longrun.Evolution.Functional,
  `Poincare.Longrun.Evolution.Gibbs,
  `Poincare.Longrun.Geometry,
  `Poincare.Longrun.Geometry.ConnectionAdapter,
  `Poincare.Longrun.Geometry.Contraction,
  `Poincare.Longrun.Geometry.LeviCivitaBlocked,
  `Poincare.Longrun.Geometry.MetricData,
  `Poincare.Longrun.PDE.AxiomAudit,
  `Poincare.Longrun.PDE.ContinuousInterface,
  `Poincare.Longrun.PDE.DiscreteMaximumPrinciple,
  `Poincare.Longrun.PDE.Energy,
  `Poincare.Longrun.PDE.HeatGrid,
  `Poincare.Longrun.Surgery,
  `Poincare.Longrun.Surgery.Axioms,
  `Poincare.Longrun.Surgery.Basic,
  `Poincare.Longrun.Surgery.Chain,
  `Poincare.Longrun.Surgery.Missing,
  `Poincare.Longrun.Surgery.Toy,
  `Poincare.Longrun.Topology.AxiomAudit,
  `Poincare.Longrun.Topology.Basic,
  `Poincare.Longrun.Topology.CompactThreeManifold,
  `Poincare.Longrun.Topology.MissingTheorems,
  `Poincare.Longrun.Topology.Noncollapsing,
  `Poincare.Longrun.Topology.NormalizedVolume,
  `Poincare.Longrun.Topology.Stage6Bridge,
  `Poincare.Stage1.CurvatureAlgebra,
  `Poincare.Stage1.RiemannAdapter,
  `Poincare.Stage6.SphereSimplyConnected,
  `Poincare.Stage6.TopologyBridge,
  `Poincare.VKPort.HatcherLib.Ch1.AlgebraicConstructions,
  `Poincare.VKPort.HatcherLib.Ch1.BasicConstructions,
  `Poincare.VKPort.HatcherLib.Ch1.VanKampen,
  `Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid,
  `Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep,
  `Poincare.VKPort.HatcherLib.Ch1.VanKampenGrid,
  `Poincare.VKPort.HatcherLib.Ch1.VanKampenSubdivision,
  `Poincare.VKPort.HatcherLib.Ch1.VanKampenSweep,
  `Poincare.VKPort.HatcherLib.Ch1.VanKampenWordCalculus,
  `Poincare.VKPort.HatcherLib.VKProbe,
  `Probe.GeometryApi,
  `Probe.PdeApi,
  `ReleaseAudit,
  `ReleaseCheck,
]

end L1TypeAuditG1

open L1TypeAuditG1 in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let mut count : Nat := 0
  for (n, ci) in env.constants.toList do
    match env.getModuleIdxFor? n with
    | some midx =>
        if targetModules.contains (mods.getD midx .anonymous) then
          logInfo m!"L1TYPE\t{n}\t{ci.type}"
          count := count + 1
    | none => pure ()
  logInfo m!"L1TYPEDONE\t{count}"
