/- GENERATED by baseline/c1/gen_type_audit.py -- do not edit. -/
import Poincare.D7.Kappa.All
import Poincare.D7.Kappa.Audit
import Poincare.D7.Kappa.EntropyBridge
import Poincare.D7.Kappa.Nonvacuity
import Poincare.D7.Kappa.Probe
import Poincare.D7.Kappa.Statements
import Poincare.D7.Monotonicity.All
import Poincare.D7.Monotonicity.Blockers
import Poincare.D7.Monotonicity.BochnerCertificate
import Poincare.D7.Monotonicity.BochnerGradientEstimate
import Poincare.D7.Monotonicity.ConjugateHeatCertificate
import Poincare.D7.Monotonicity.FMonotonicity
import Poincare.D7.Monotonicity.Nonvacuity
import Poincare.D7.Monotonicity.WMuMonotonicity

open Lean Elab Command

namespace L1TypeAuditG2

/-- Modules whose declarations are dumped in this partition (same partition as the
frozen axiom audit). -/
def targetModules : Array Name := #[
  `Poincare.D7.Kappa.All,
  `Poincare.D7.Kappa.Audit,
  `Poincare.D7.Kappa.EntropyBridge,
  `Poincare.D7.Kappa.Nonvacuity,
  `Poincare.D7.Kappa.Probe,
  `Poincare.D7.Kappa.Statements,
  `Poincare.D7.Monotonicity.All,
  `Poincare.D7.Monotonicity.Blockers,
  `Poincare.D7.Monotonicity.BochnerCertificate,
  `Poincare.D7.Monotonicity.BochnerGradientEstimate,
  `Poincare.D7.Monotonicity.ConjugateHeatCertificate,
  `Poincare.D7.Monotonicity.FMonotonicity,
  `Poincare.D7.Monotonicity.Nonvacuity,
  `Poincare.D7.Monotonicity.WMuMonotonicity,
]

end L1TypeAuditG2

open L1TypeAuditG2 in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let mut count : Nat := 0
  for (n, ci) in env.constants.toList do
    match env.getModuleIdxFor? n with
    | some midx =>
        if targetModules.contains (mods.getD midx .anonymous) then
          logInfo m!"L1TYPE\t{n}\t{ci.type}"
          count := count + 1
    | none => pure ()
  logInfo m!"L1TYPEDONE\t{count}"
