name = "PoincareWorktree"
version = "0.1.0"
defaultTargets = ["Poincare"]
srcDir = "release"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "Poincare"
globs = ["Poincare.+"]
