/-
Copyright (c) 2026 Poincaré project contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Poincaré project (D7-heat-kernel-existence)
-/

import Poincare.D7.HeatKernel.Grid

set_option linter.style.haveILetI false
set_option linter.unusedSectionVars false
set_option linter.unnecessarySimpa false
set_option linter.unusedVariables false

/-!
# Poincare.D7.HeatKernel.Content

**D7 heat-kernel layer, part 3: monotonicity of the discrete heat content.**

Two monotone quantities of the finite-grid heat flow `u (n+1) = heatStep P (u n)` are proved to be
nonincreasing in the discrete time `n`:

* the **heat content** `heatContent μ u = ∑ x, μ x * u x` with respect to a density `μ`, under the
  column condition `∑ x, μ x * P x y ≤ μ y` (the discrete divergence/contraction condition);
* the **`L²` energy** `l2Energy u = ∑ x, (u x)^2`, under nonnegative entries and the row and column
  bounds `∑ y, P x y ≤ 1` and `∑ x, P x y ≤ 1`.

The weighted Cauchy–Schwarz inequality `weighted_cauchy_schwarz` is the elementary ingredient of the
energy monotonicity. The results are then instantiated on the grid flow generated by a finite-grid
heat kernel `K` (`heatContent_gridFlow_antitone`, `l2Energy_gridFlow_antitone`).

All proofs are complete: no `sorry`, `axiom`, `unsafe`, `native_decide`, or `proof_wanted`.
-/

namespace Poincare.D7.HeatKernel

open scoped BigOperators

variable {X : Type*} [Fintype X]

/-- **The discrete heat content** of a temperature field `u` with respect to a density `μ`:
`heatContent μ u = ∑ x, μ x * u x`. -/
def heatContent (μ u : X → ℝ) : ℝ := ∑ x, μ x * u x

/-- **The `L²` energy** of a temperature field: `l2Energy u = ∑ x, (u x)^2`. -/
def l2Energy (u : X → ℝ) : ℝ := ∑ x, (u x) ^ 2

/-- **The weighted Cauchy–Schwarz inequality**: for a nonnegative weight `a`,
`(∑ x, a x * b x)^2 ≤ (∑ x, a x) * (∑ x, a x * b x^2)`. -/
theorem weighted_cauchy_schwarz (a b : X → ℝ) (ha : ∀ x, 0 ≤ a x) :
    (∑ x, a x * b x) ^ 2 ≤ (∑ x, a x) * (∑ x, a x * (b x) ^ 2) := by
  have key := Finset.sum_mul_sq_le_sq_mul_sq (Finset.univ : Finset X)
    (fun x => Real.sqrt (a x)) (fun x => Real.sqrt (a x) * b x)
  have h1 : ∀ x, Real.sqrt (a x) * (Real.sqrt (a x) * b x) = a x * b x := by
    intro x
    rw [← mul_assoc, ← sq, Real.sq_sqrt (ha x)]
  have h2 : ∀ x, Real.sqrt (a x) ^ 2 = a x := fun x => Real.sq_sqrt (ha x)
  have h3 : ∀ x, (Real.sqrt (a x) * b x) ^ 2 = a x * (b x) ^ 2 := by
    intro x
    rw [mul_pow, Real.sq_sqrt (ha x)]
  calc (∑ x, a x * b x) ^ 2
      = (∑ x, Real.sqrt (a x) * (Real.sqrt (a x) * b x)) ^ 2 := by
        congr 1
        exact Finset.sum_congr rfl (fun x _ => (h1 x).symm)
    _ ≤ (∑ x, Real.sqrt (a x) ^ 2) * (∑ x, (Real.sqrt (a x) * b x) ^ 2) := key
    _ = (∑ x, a x) * (∑ x, a x * (b x) ^ 2) := by
        rw [Finset.sum_congr rfl (fun x _ => h2 x),
          Finset.sum_congr rfl (fun x _ => h3 x)]

/-- **One-step monotonicity of the heat content.** If the transition matrix `P` is nonnegative, the
temperature field `u` is nonnegative, and the density `μ` contracts along the columns,
`∑ x, μ x * P x y ≤ μ y`, then `heatContent μ (heatStep P u) ≤ heatContent μ u`. -/
theorem heatContent_heatStep_le (P : Matrix X X ℝ) (μ u : X → ℝ)
    (hP : ∀ x y, 0 ≤ P x y) (hμ : ∀ x, 0 ≤ μ x) (hu : ∀ x, 0 ≤ u x)
    (hcol : ∀ y, ∑ x, μ x * P x y ≤ μ y) :
    heatContent μ (heatStep P u) ≤ heatContent μ u := by
  have expand : heatContent μ (heatStep P u) = ∑ y, (∑ x, μ x * P x y) * u y := by
    simp only [heatContent, heatStep, Finset.mul_sum]
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl (fun y _ => ?_)
    rw [Finset.sum_mul]
    exact Finset.sum_congr rfl (fun x _ => by ring)
  rw [expand]
  calc ∑ y, (∑ x, μ x * P x y) * u y ≤ ∑ y, μ y * u y := by
        refine Finset.sum_le_sum (fun y _ => ?_)
        exact mul_le_mul_of_nonneg_right (hcol y) (hu y)
    _ = heatContent μ u := rfl

/-- **Monotonicity of the discrete heat content in time.** Along the discrete heat flow, the heat
content is antitone. -/
theorem heatContent_antitone (P : Matrix X X ℝ) (μ : X → ℝ) (u : ℕ → X → ℝ)
    (hP : ∀ x y, 0 ≤ P x y) (hμ : ∀ x, 0 ≤ μ x) (hu : ∀ n x, 0 ≤ u n x)
    (hcol : ∀ y, ∑ x, μ x * P x y ≤ μ y)
    (hstep : ∀ n, u (n + 1) = heatStep P (u n)) :
    Antitone (fun n => heatContent μ (u n)) := by
  apply antitone_nat_of_succ_le
  intro n
  rw [hstep n]
  exact heatContent_heatStep_le P μ (u n) hP hμ (hu n) hcol

/-- **One-step monotonicity of the `L²` energy.** If `P` is nonnegative with row and column sums
at most `1`, then the energy does not increase under one heat step. -/
theorem l2Energy_heatStep_le (P : Matrix X X ℝ) (u : X → ℝ)
    (hP : ∀ x y, 0 ≤ P x y) (hrow : ∀ x, ∑ y, P x y ≤ 1)
    (hcol : ∀ y, ∑ x, P x y ≤ 1) :
    l2Energy (heatStep P u) ≤ l2Energy u := by
  have hstep : ∀ x, (heatStep P u x) ^ 2 ≤ (∑ y, P x y) * (∑ y, P x y * (u y) ^ 2) := by
    intro x
    have hcs := weighted_cauchy_schwarz (fun y => P x y) u (fun y => hP x y)
    simpa [heatStep] using hcs
  have hrow1 : ∀ x, (∑ y, P x y) * (∑ y, P x y * (u y) ^ 2)
      ≤ 1 * (∑ y, P x y * (u y) ^ 2) := by
    intro x
    exact mul_le_mul_of_nonneg_right (hrow x)
      (Finset.sum_nonneg (fun y _ => mul_nonneg (hP x y) (sq_nonneg _)))
  calc l2Energy (heatStep P u) = ∑ x, (heatStep P u x) ^ 2 := rfl
    _ ≤ ∑ x, (∑ y, P x y) * (∑ y, P x y * (u y) ^ 2) :=
        Finset.sum_le_sum (fun x _ => hstep x)
    _ ≤ ∑ x, 1 * (∑ y, P x y * (u y) ^ 2) := Finset.sum_le_sum (fun x _ => hrow1 x)
    _ = ∑ x, ∑ y, P x y * (u y) ^ 2 := by simp only [one_mul]
    _ = ∑ y, (∑ x, P x y) * (u y) ^ 2 := by
        rw [Finset.sum_comm]
        refine Finset.sum_congr rfl (fun y _ => ?_)
        rw [Finset.sum_mul]
    _ ≤ ∑ y, 1 * (u y) ^ 2 := by
        refine Finset.sum_le_sum (fun y _ => ?_)
        exact mul_le_mul_of_nonneg_right (hcol y) (sq_nonneg _)
    _ = l2Energy u := by simp [l2Energy]

/-- **Monotonicity of the `L²` energy in time.** -/
theorem l2Energy_antitone (P : Matrix X X ℝ) (u : ℕ → X → ℝ)
    (hP : ∀ x y, 0 ≤ P x y) (hrow : ∀ x, ∑ y, P x y ≤ 1)
    (hcol : ∀ y, ∑ x, P x y ≤ 1)
    (hstep : ∀ n, u (n + 1) = heatStep P (u n)) :
    Antitone (fun n => l2Energy (u n)) := by
  apply antitone_nat_of_succ_le
  intro n
  rw [hstep n]
  exact l2Energy_heatStep_le P (u n) hP hrow hcol

variable [DecidableEq X]
variable {step : Matrix X X ℝ} {d : X → X → ℝ} {dim C_up c_up C_lo c_lo : ℝ}

/-- **Monotonicity of the heat content along the finite-grid kernel flow.** -/
theorem heatContent_gridFlow_antitone (K : FiniteGridHeatKernel step d dim C_up c_up C_lo c_lo)
    (f μ : X → ℝ) (hstep : ∀ x y, 0 ≤ step x y) (hf : ∀ x, 0 ≤ f x) (hμ : ∀ x, 0 ≤ μ x)
    (hcol : ∀ y, ∑ x, μ x * step x y ≤ μ y) :
    Antitone (fun n => heatContent μ (gridFlow K f n)) :=
  heatContent_antitone step μ (fun n => gridFlow K f n) hstep hμ
    (gridFlow_nonneg K f hf hstep) hcol (fun n => gridFlow_succ K f n)

/-- **Monotonicity of the `L²` energy along the finite-grid kernel flow.** -/
theorem l2Energy_gridFlow_antitone (K : FiniteGridHeatKernel step d dim C_up c_up C_lo c_lo)
    (f : X → ℝ) (hstep : ∀ x y, 0 ≤ step x y) (hrow : ∀ x, ∑ y, step x y ≤ 1)
    (hcol : ∀ y, ∑ x, step x y ≤ 1) :
    Antitone (fun n => l2Energy (gridFlow K f n)) :=
  l2Energy_antitone step (fun n => gridFlow K f n) hstep hrow hcol
    (fun n => gridFlow_succ K f n)

end Poincare.D7.HeatKernel
