#!/usr/bin/env python3
"""Generate an independent reverse-use / pair probe for one D13 card.

spec JSON: {"task": str, "imports": [module...], "constructors": [decl...],
            "pairs": [[constructor, downstream], ...]}
Emits audit/probes/<task>/UseProbe.lean.  For every constructor it counts transitive
proof-term consumers among the imported environment's declarations (unsealing values with
value? true is not needed: ConstantInfo.value? yields the stored value), and for every pair
reports whether the constructor occurs in the downstream's type and in its value.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROBES = ROOT / "probes"


def main(spec_path: str):
    spec = json.loads(Path(spec_path).read_text())
    task = spec["task"]
    imports = "\n".join("import " + m for m in spec["imports"])
    ctors = ",\n  ".join('"' + c + '".toName' for c in spec["constructors"])
    pairs = ",\n  ".join('("' + a + '".toName, "' + b + '".toName)' for a, b in spec["pairs"])
    ns = "D13XUse_" + "".join(ch if ch.isalnum() else "_" for ch in task)
    prefixes = ",\n    ".join('"' + p + '".toName' for p in spec.get("scan_prefixes", []))
    text = """@HEADER@
@IMPORTS@
import Lean.Util.CollectAxioms

open Lean Elab Command

namespace @NS@

def constructors : List Name := [
  @CTORS@]

def pairs : List (Name × Name) := [
  @PAIRS@]

end @NS@

open @NS@ in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let mut rows : Array (Name × Name × Bool × Bool) := #[]
  for (ctor, down) in pairs do
    let inType := match env.find? down with
      | some ci => ci.type.getUsedConstants.contains ctor
      | none => false
    let inValue := match env.find? down with
      | some ci => (match ci.value? true with
          | some v => v.getUsedConstants.contains ctor
          | none => false)
      | none => false
    rows := rows.push (ctor, down, inType, inValue)
  -- reverse direct-use census: declarations whose type or value mentions the constructor
  let scanPrefixes : List Name := [@PREFIXES@]
  let inScan (n : Name) : Bool :=
    match env.getModuleIdxFor? n with
    | some midx =>
        let m := mods.getD midx .anonymous
        scanPrefixes.isEmpty || scanPrefixes.any (fun r => r.isPrefixOf m)
    | none => scanPrefixes.isEmpty
  let decls := env.constants.fold (fun acc n _ => if inScan n then acc.push n else acc) #[]
  for ctor in constructors do
    IO.println s!"D13XEXISTS\t{ctor}\t{(env.find? ctor).isSome}"
    let mut direct : Array Name := #[]
    for d in decls do
      if d == ctor then continue
      match env.find? d with
      | some ci =>
          let inT := ci.type.getUsedConstants.contains ctor
          let inV := match ci.value? true with
            | some v => v.getUsedConstants.contains ctor
            | none => false
          if inT || inV then direct := direct.push d
      | none => pure ()
    IO.println s!"D13XUSE\\t{ctor}\\tdirect_users\\t{direct.size}"
    for d in direct.qsort (fun a b => a.toString < b.toString) do
      IO.println s!"D13XUSER\\t{ctor}\\t{d}"
  for (ctor, down, inT, inV) in rows do
    IO.println s!"D13XPAIR\\t{ctor}\\t{down}\\ttype={inT}\\tvalue={inV}\\tdown_exists={(env.find? down).isSome}"
  IO.println s!"D13XUSE_DONE\\t@TASK@"
"""
    header = ("/-\nIndependent reverse-use probe for @TASK@ (generated by gen_useprobe.py).\n"
              "Reports direct users of each constructor in the elaborated environment and whether\n"
              "each declared downstream pair mentions the constructor in type and/or value.\n-/")
    text = (text.replace("@HEADER@", header).replace("@IMPORTS@", imports)
                .replace("@CTORS@", ctors).replace("@PAIRS@", pairs)
                .replace("@NS@", ns)
                        .replace("@PREFIXES@", prefixes).replace("@TASK@", task))
    outdir = PROBES / task
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "UseProbe.lean").write_text(text)
    print(f"wrote {outdir / 'UseProbe.lean'} ({len(spec['constructors'])} constructors, {len(spec['pairs'])} pairs)")


if __name__ == "__main__":
    main(sys.argv[1])
