#!/usr/bin/env python3
"""Generate a complete-namespace axiom audit module for each rebuilt package:
enumerate every constant under the card's `Poincare.D12` root in the compiled
environment and check its transitive axiom cone against the permitted set.
This catches declarations that the producer card never listed.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PKGS = os.path.join(HERE, "pkgs")
CARDS = [
    "D12-connection-curvature",
    "D12-volume-ibp",
    "D12-spectral-sobolev",
    "D12-semantic-ledger",
    "D12-comparison-geodesics",
    "D12-geometric-compactness",
    "D12-surgery-recognition",
]

BODY = r'''
open Lean Elab Command

run_cmd do
  let env ← getEnv
  let allowed : List Name := [``propext, ``Classical.choice, ``Quot.sound]
  let root : Name := `Poincare.D12
  let mut count : Nat := 0
  let mut bad : Array (Name × List Name) := #[]
  let mut skipped : Array Name := #[]
  for (n, _ci) in env.constants.toList do
    if root.isPrefixOf n then
      if n == `Poincare.D12.VolumeIBP.Audit.negativeControl then
        skipped := skipped.push n
      else
        count := count + 1
        let axs ← Lean.collectAxioms n
        let unapproved := axs.toList.filter (fun a => !allowed.contains a)
        if !unapproved.isEmpty then
          bad := bad.push (n, unapproved)
  logInfo m!"A3FULL: {toString count} declarations under Poincare.D12 audited"
  logInfo m!"A3FULL: skipped documented negative controls: {toString (skipped.toList.map Name.toString)}"
  for (n, u) in bad do
    logError m!"A3FULL-BAD: {n} -> {u.map Name.toString}"
  if !bad.isEmpty then
    throwError "A3FULL: FAIL ({toString bad.size} declarations with unapproved axioms)"
  logInfo m!"A3FULL: PASS"
'''


def main():
    for card in CARDS:
        pkg = os.path.join(PKGS, card)
        lib = os.path.join(pkg, ".lake", "build", "lib", "lean")
        mods = []
        for dirpath, dirnames, filenames in os.walk(lib):
            for fn in filenames:
                if fn.endswith(".olean"):
                    rel = os.path.relpath(os.path.join(dirpath, fn), lib)
                    mod = rel[:-6].replace(os.sep, ".")
                    if mod.startswith("A3"):
                        continue
                    mods.append(mod)
        mods = sorted(set(mods))
        lines = ["-- A3 complete-namespace audit for " + card,
                 "-- generated by D13-cross-audit-360-cards; imports every built module",
                 ""]
        lines += ["import " + m for m in mods]
        lines += ["", BODY]
        with open(os.path.join(pkg, "A3FullAudit.lean"), "w") as f:
            f.write("\n".join(lines) + "\n")
        print(card, len(mods), "modules")


if __name__ == "__main__":
    main()
