#!/usr/bin/env python3
"""Round-9 screen generator: kernel-level "assumption-as-conclusion" (tautology)
screen.

The round-7 finding F18 exposed that the string-based vacuity screen was blind on
signature-form binders.  This generator emits, for every staged card package, an
`A3TautScreen.lean` that runs **inside the kernel environment** (metaprogram over
`ConstantInfo`, no pretty-printer heuristics) and flags, for every audited
declaration of that card:

  * `hypothesis-eq-conclusion:<binder>` — a forall-binder whose type is
    **definitionally equal** to the final conclusion (the conclusion is assumed);
  * `conclusion-defeq-True` — the conclusion is definitionally `True`;
  * `proof-is-hypothesis:<binder>` — the proof body is an assumption-like term
    (a bound variable, or a bound variable applied only to bound variables)
    whose type is definitionally the flagged conclusion binder.

A positive control theorem `a3TautCtl (P : Prop) (h : P) : P := h` is declared in
the same file and must be flagged; the script fails if it is not.  Imports and
target names are taken from the package's own `A3Meta.json` (resolved audited
names) and `A3UnusedHypFull.lean` (the full import set), so the screen sees the
same environment as the axiom probes.

Usage: python3 audit360/gen_taut_screen.py [card ...]
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKGS = os.path.join(HERE, "pkgs")
CARDS = ["D12-connection-curvature", "D12-volume-ibp", "D12-spectral-sobolev",
         "D12-semantic-ledger", "D12-comparison-geodesics", "D12-geometric-compactness",
         "D12-surgery-recognition"]

BODY = r'''
open Lean Meta Elab Command

namespace A3TautScreen

/-- Positive control: the conclusion is literally the hypothesis.  The screen
must flag it. -/
theorem a3TautCtl (P : Prop) (h : P) : P := h

end A3TautScreen

open Lean Meta Elab Command in
run_cmd do
  let env ← getEnv
  let targets : List Name := [``A3TautScreen.a3TautCtl, %NAMES%]
  let mut checked : Nat := 0
  let mut flags : Nat := 0
  for t in targets do
    match env.find? t with
    | none => logError m!"A3TAUT-MISSING: {t}"
    | some ci =>
      let v? := match ci with
        | .thmInfo v => some v.value
        | .defnInfo v => some v.value
        | _ => none
      match v? with
      | none => pure ()
      | some v =>
        checked := checked + 1
        let (typeRes, idxs) ← liftTermElabM do
          let ty ← instantiateMVars ci.type
          forallTelescopeReducing ty fun xs concl => do
            let mut res : Array String := #[]
            let mut idxs : Array Nat := #[]
            let concl ← instantiateMVars concl
            if ← isDefEq concl (mkConst ``True) then
              res := res.push "conclusion-defeq-True"
            for h : i in [0:xs.size] do
              let d ← instantiateMVars (← xs[i].fvarId!.getType)
              if ← isDefEq d concl then
                idxs := idxs.push i
                let n ← xs[i].fvarId!.getUserName
                res := res.push s!"hypothesis-eq-conclusion:{n}"
            return (res, idxs)
        let bodyRes ← liftTermElabM do
          lambdaTelescope v fun ys body => do
            let mut out : Array String := #[]
            let body ← instantiateMVars body
            let head := body.getAppFn
            if let .fvar fid := head then
              if body.getAppArgs.all (fun a => a.isFVar) then
                for i in idxs do
                  if h : i < ys.size then
                    if ys[i].fvarId! == fid then
                      let n ← ys[i].fvarId!.getUserName
                      out := out.push s!"proof-is-hypothesis:{n}"
            return out
        let outs := typeRes ++ bodyRes
        if outs.size > 0 then
          flags := flags + 1
          logInfo m!"A3TAUT-FLAG: {t} {outs.toList}"
  logInfo m!"A3TAUT: checked {checked}, flags {flags}"
'''


def gen(card):
    pkg = os.path.join(PKGS, card)
    meta = json.load(open(os.path.join(pkg, "A3Meta.json")))
    names = []
    for entry in meta.get("resolved", []):
        fq = entry.get("fq") or entry.get("declared")
        if fq and fq not in names:
            names.append(fq)
    imports = []
    full = os.path.join(pkg, "A3UnusedHypFull.lean")
    if os.path.exists(full):
        for line in open(full):
            if line.startswith("import "):
                imports.append(line.rstrip("\n"))
    if not imports:
        imports = ["import Mathlib"]
    name_list = ", ".join("``" + n for n in names)
    text = ("-- A3 round-9 kernel assumption-as-conclusion screen for %s\n"
            "-- generated by audit360/gen_taut_screen.py; do not edit\n" % card)
    text += "\n".join(imports) + "\n" + BODY.replace("%NAMES%", name_list)
    out = os.path.join(pkg, "A3TautScreen.lean")
    open(out, "w").write(text)
    return out, len(names)


def main():
    cards = sys.argv[1:] or CARDS
    for card in cards:
        out, n = gen(card)
        print("generated", out, "targets", n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
