#!/usr/bin/env python3
"""Generate an `A3UnusedHyp.lean` module for each available card.

The module analyses the *proof term* of every declaration the card claims: it
telescopes the leading lambdas of the value and the leading foralls of the type,
then reports any leading binder whose de Bruijn position does not occur in the
proof body.  An explicit hypothesis that the proof never touches is a redundant
(overstrong) hypothesis -- precisely the defect family the D12-plan acceptance
criterion forbids ("no assumption equivalent to the conclusion", and no
hypothesis that the mathematics does not need).

Conservative by construction: if the number of leading lambdas differs from the
number of leading foralls (proofs written as a constant, wrappers, etc.) the
declaration is skipped, not flagged.  Instance/implicit binders are reported but
tagged separately from explicit ones, because an unused `[Fintype ι]` can be a
benign interface artifact while an unused explicit hypothesis is a real defect.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
WT = os.path.dirname(HERE)
CARDS = [
    "D12-connection-curvature", "D12-volume-ibp", "D12-spectral-sobolev",
    "D12-semantic-ledger", "D12-comparison-geodesics", "D12-geometric-compactness",
    "D12-surgery-recognition",
]

ANALYSIS = r'''
open Lean Elab Command

namespace A3Unused

partial def usedBinders (e : Expr) : Std.HashSet Nat :=
  go e 0 {}
where
  go (e : Expr) (depth : Nat) (acc : Std.HashSet Nat) : Std.HashSet Nat :=
    match e with
    | .bvar i => if i < depth then acc.insert (depth - 1 - i) else acc
    | .lam _ d b _ => go b (depth + 1) (go d depth acc)
    | .forallE _ d b _ => go b (depth + 1) (go d depth acc)
    | .app f a => go a depth (go f depth acc)
    | .letE _ t v b _ => go b (depth + 1) (go v depth (go t depth acc))
    | .mdata _ b => go b depth acc
    | .proj _ _ b => go b depth acc
    | _ => acc

partial def leadingLams (e : Expr) : Nat :=
  match e with
  | .lam _ _ b _ => leadingLams b + 1
  | _ => 0

partial def leadingForalls (e : Expr) : Nat :=
  match e with
  | .forallE _ _ b _ => leadingForalls b + 1
  | _ => 0

partial def binderInfos (e : Expr) : List (Name × Expr × BinderInfo) :=
  match e with
  | .forallE n d b bi => (n, d, bi) :: binderInfos b
  | _ => []

def binderTag (bi : BinderInfo) : String :=
  if bi == BinderInfo.instImplicit then "instance"
  else if bi == BinderInfo.implicit then "implicit"
  else if bi == BinderInfo.strictImplicit then "strictImplicit"
  else "explicit"

end A3Unused

run_cmd do
  let env ← getEnv
  let targets : List Name := __TARGETS__
  let mut flagged : Nat := 0
  let mut explicitFlagged : Nat := 0
  let mut checked : Nat := 0
  let mut skipped : Nat := 0
  for t in targets do
    match env.find? t with
    | none => logError m!"A3UNUSED: missing {t}"
    | some ci =>
      let v? := match ci with
        | .thmInfo v => some v.value
        | .defnInfo v => some v.value
        | _ => none
      match v? with
      | none => skipped := skipped + 1
      | some v =>
        let nv := A3Unused.leadingLams v
        let nt := A3Unused.leadingForalls ci.type
        if nv == nt && nv > 0 then
          checked := checked + 1
          let used := A3Unused.usedBinders v
          let infos := A3Unused.binderInfos ci.type
          for i in List.range nv do
            if !used.contains i then
              let (n, d, bi) := infos[i]!
              flagged := flagged + 1
              let tag := A3Unused.binderTag bi
              if tag == "explicit" then explicitFlagged := explicitFlagged + 1
              logInfo m!"A3UNUSED-FLAG: {t} binder#{i} ({n} : {d}) [{tag}]"
        else
          skipped := skipped + 1
  logInfo m!"A3UNUSED: checked {checked}, skipped {skipped}, flags {flagged}, explicit flags {explicitFlagged}"
'''


def imports_of(card):
    p = os.path.join(HERE, "pkgs", card, "A3FullAudit.lean")
    out = []
    for line in open(p, encoding="utf-8"):
        line = line.strip()
        if line.startswith("import "):
            out.append(line)
    return out


def targets_of(card):
    p = os.path.join(HERE, "pkgs", card, "A3Meta.json")
    meta = json.load(open(p))
    names = []
    seen = set()
    for r in meta.get("resolved", []):
        fq = r.get("fq")
        if fq and fq not in seen:
            seen.add(fq)
            names.append(fq)
    return names


def main():
    for card in CARDS:
        imports = imports_of(card)
        names = targets_of(card)
        lst = "[" + ", ".join("``" + n for n in names) + "]"
        text = ("-- A3 unused-hypothesis screen for " + card + "\n"
                + "-- generated by audit360/gen_unused_hyp.py; do not edit\n"
                + "\n".join(imports) + "\n"
                + ANALYSIS.replace("__TARGETS__", lst))
        outp = os.path.join(HERE, "pkgs", card, "A3UnusedHyp.lean")
        with open(outp, "w") as fh:
            fh.write(text)
        print(card, "targets", len(names), "->", outp)


if __name__ == "__main__":
    main()
