#!/usr/bin/env python3
"""Generate a kernel declaration-kind audit module for each rebuilt package.

Adversarial question: the cards classify their `proved_declarations` as proved
theorems.  `#check` + `#print axioms` does not distinguish a theorem (a proof
term) from a `def` (data), an `inductive` (a type/structure), a constructor or a
projection.  This module asks the kernel for the `ConstantInfo` variant of every
name the card lists, so the "proved theorem" classification is machine-checked
rather than assumed.

Output lines have the form `A3KIND\t<fully-qualified-name>\t<kind>`.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PKGS = os.path.join(HERE, "pkgs")
CARDS = [
    "D12-connection-curvature",
    "D12-volume-ibp",
    "D12-spectral-sobolev",
    "D12-semantic-ledger",
    "D12-comparison-geodesics",
    "D12-geometric-compactness",
    "D12-surgery-recognition",
]

BODY = r'''
open Lean Elab Command

def a3KindNames : List Name := [
%NAMES%
]

run_cmd do
  let mut counts : Std.HashMap String Nat := {}
  for n in a3KindNames do
    let ci ← getConstInfo n
    let k : String ← match ci with
      | .axiomInfo _  => pure "axiom"
      | .defnInfo _   => pure "def"
      | .thmInfo _    => pure "theorem"
      | .opaqueInfo _ => pure "opaque"
      | .quotInfo _   => pure "quot"
      | .inductInfo _ => pure "inductive"
      | .ctorInfo _   => pure "ctor"
      | .recInfo _    => pure "rec"
    let res ← liftTermElabM <| Lean.Meta.forallTelescopeReducing ci.type fun _ body => do
      if ← Lean.Meta.isProp body then pure "PropResult"
      else match body with
        | .sort l => pure (match l with | .zero => "PropFormer" | _ => "TypeFormer")
        | _ => pure "DataResult"
    counts := counts.insert (k ++ ":" ++ res) (counts.getD (k ++ ":" ++ res) 0 + 1)
    logInfo m!"A3KIND\t{n}\t{k}\t{res}"
  logInfo m!"A3KIND-SUMMARY\t{toString counts.toList}"
'''


def probe_names(card):
    path = os.path.join(PKGS, card, "A3Probe.lean")
    names, imports = [], []
    with open(path) as f:
        for line in f:
            s = line.strip()
            if s.startswith("#check "):
                names.append(s[len("#check "):].strip())
            elif s.startswith("import "):
                imports.append(s)
    return names, imports


def main():
    for card in CARDS:
        names, imports = probe_names(card)
        body = BODY.replace("%NAMES%", ",\n".join("  `" + n for n in names))
        lines = ["-- A3 declaration-kind audit for " + card,
                 "-- generated by D13-cross-audit-360-cards; do not edit",
                 ""]
        lines += imports
        lines += ["", "set_option maxHeartbeats 400000", "", body]
        out = os.path.join(PKGS, card, "A3KindAudit.lean")
        with open(out, "w") as f:
            f.write("\n".join(lines) + "\n")
        print(card, len(names), "names")


if __name__ == "__main__":
    main()
