import Poincare.D13.IntegratedAudit.SnapshotRoot

#print axioms HatcherLib.CoveredLoop
#print axioms HatcherLib.CoveredPathChain
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.boundary
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.homotopic
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.mk.congr_simp
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.mk.sizeOf_spec
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.recOn
#print axioms HatcherLib.CoveredPathChain.brecOn
#print axioms HatcherLib.CoveredPathChain.carrierSets._f
#print axioms HatcherLib.CoveredPathChain.carrierSets.eq_2
#print axioms HatcherLib.CoveredPathChain.ctorElimType
#print axioms HatcherLib.CoveredPathChain.decompose_loop_with_carrierSets
#print axioms HatcherLib.CoveredPathChain.decompose_of_endpoint_eq_with_carrierSets
#print axioms HatcherLib.CoveredPathChain.extend.inj
#print axioms HatcherLib.CoveredPathChain.loop_decomposition_of_covered_chain
#print axioms HatcherLib.CoveredPathChain.prefixDecomposition
#print axioms HatcherLib.CoveredPathChain.prefixDecomposition._proof_4
#print axioms HatcherLib.CoveredPathChain.prefix_loops_mem_carrierSets._simp_1_10
#print axioms HatcherLib.CoveredPathChain.recOn
#print axioms HatcherLib.CoveredPathChain.single.inj
#print axioms HatcherLib.CoveredPathChain.toPath
#print axioms HatcherLib.CoveredPathChain.toPath.match_1
#print axioms HatcherLib.CoveredSubdivisionPrefix.carrierSets_subset
#print axioms HatcherLib.CoveredSubdivisionPrefix.homotopic
#print axioms HatcherLib.CoveredSubdivisionPrefix.mk.injEq
#print axioms HatcherLib.CoveredSubdivisionPrefix.noConfusionType
#print axioms HatcherLib.FreeGroupOn
#print axioms HatcherLib.Loop
#print axioms HatcherLib.Path.HomotopyClass
#print axioms HatcherLib.PathConnectedOpenCover.base_mem
#print axioms HatcherLib.PathConnectedOpenCover.ctorIdx
#print axioms HatcherLib.PathConnectedOpenCover.mk._flat_ctor
#print axioms HatcherLib.PathConnectedOpenCover.mk.sizeOf_spec
#print axioms HatcherLib.PathConnectedOpenCover.rec
#print axioms HatcherLib.PiOne
#print axioms HatcherLib.VanKampenFactor
#print axioms HatcherLib.VanKampenRectangularSubdivision._sizeOf_inst
#print axioms HatcherLib.VanKampenRectangularSubdivision.ctorIdx
#print axioms HatcherLib.VanKampenRectangularSubdivision.horizontalCut_one
#print axioms HatcherLib.VanKampenRectangularSubdivision.mk.inj
#print axioms HatcherLib.VanKampenRectangularSubdivision.noConfusion
#print axioms HatcherLib.VanKampenRectangularSubdivision.verticalCells
#print axioms HatcherLib.VanKampenRectangularSubdivision.verticalCut_zero
#print axioms HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent._f
#print axioms HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent.eq_2
#print axioms HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent.match_1
#print axioms HatcherLib.VanKampenSquareGrid.cell
#print axioms HatcherLib.VanKampenSquareGrid.cellBoundaryRelation
#print axioms HatcherLib.VanKampenSquareGrid.cellConvexHomotopy._proof_3
#print axioms HatcherLib.VanKampenSquareGrid.cellConvexHomotopy._proof_7
#print axioms HatcherLib.VanKampenSquareGrid.cellMap
#print axioms HatcherLib.VanKampenSquareGrid.cellSweepStep
#print axioms HatcherLib.VanKampenSquareGrid.continuous_coordinateLine
#print axioms HatcherLib.VanKampenSquareGrid.coordinateLine_mem_Icc
#print axioms HatcherLib.VanKampenSquareGrid.ctorIdx
#print axioms HatcherLib.VanKampenSquareGrid.horizontalBasedEdgeInCell
#print axioms HatcherLib.VanKampenSquareGrid.horizontalCut
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdge
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeFactor
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeInCell
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeInCell.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeLoop_in_incidentCell
#print axioms HatcherLib.VanKampenSquareGrid.horizontalFrontierWord.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.horizontalParameterEdge._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.horizontalParameterEdgeInCell._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.horizontalSlice._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.mk._flat_ctor
#print axioms HatcherLib.VanKampenSquareGrid.mk.sizeOf_spec
#print axioms HatcherLib.VanKampenSquareGrid.recOn
#print axioms HatcherLib.VanKampenSquareGrid.rowCellsForIndices.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.rowSweep
#print axioms HatcherLib.VanKampenSquareGrid.sweepCell._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.sweepCell.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.vertexConnector._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.vertexConnectorInCell.congr_simp
#print axioms HatcherLib.VanKampenSquareGrid.vertexLabels
#print axioms HatcherLib.VanKampenSquareGrid.verticalBasedEdgeInCell.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.verticalCut_mono
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeClassInCell
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeFactor.congr_simp
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeInCell._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeLoop
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdge_in_incidentCell
#print axioms HatcherLib.VanKampenSquareGrid.verticalParameterEdge._proof_3
#print axioms HatcherLib.VanKampenSquareGrid.verticalParameterEdge_in_cell
#print axioms HatcherLib.VanKampenSquareGrid.verticalSlice._proof_3
#print axioms HatcherLib.VanKampenSweepCell.Composable._sunfold
#print axioms HatcherLib.VanKampenSweepCell.bottom
#print axioms HatcherLib.VanKampenSweepCell.firstRightWord
#print axioms HatcherLib.VanKampenSweepCell.inputWord.eq_1
#print axioms HatcherLib.VanKampenSweepCell.lastLeftWord
#print axioms HatcherLib.VanKampenSweepCell.lastLeftWord.eq_1
#print axioms HatcherLib.VanKampenSweepCell.left
#print axioms HatcherLib.VanKampenSweepCell.mk.inj
#print axioms HatcherLib.VanKampenSweepCell.noConfusion
#print axioms HatcherLib.VanKampenSweepCell.outputWord._sunfold
#print axioms HatcherLib.VanKampenSweepCell.outputWord.eq_3
#print axioms HatcherLib.VanKampenSweepCell.rec
#print axioms HatcherLib.VanKampenSweepCell.top
#print axioms HatcherLib.VanKampenSweepRow.Composable._sunfold
#print axioms HatcherLib.VanKampenSweepRow.bottom
#print axioms HatcherLib.VanKampenSweepRow.equivalent_rectangleInput_rectangleOutput
#print axioms HatcherLib.VanKampenSweepRow.mk.inj
#print axioms HatcherLib.VanKampenSweepRow.noConfusion
#print axioms HatcherLib.VanKampenSweepRow.rectangleInput
#print axioms HatcherLib.VanKampenSweepRow.rectangleOutput._f
#print axioms HatcherLib.VanKampenSweepRow.rectangleOutput.eq_2
#print axioms HatcherLib.VanKampenSweepRow.right
#print axioms HatcherLib.VanKampenSweepRow.rightBoundary._unsafe_rec
#print axioms HatcherLib.VanKampenSweepRow.rightBoundary.match_1
#print axioms HatcherLib.VanKampenSweepStage.Composable
#print axioms HatcherLib.VanKampenSweepStage._sizeOf_1
#print axioms HatcherLib.VanKampenSweepStage.chainInput.eq_1
#print axioms HatcherLib.VanKampenSweepStage.chainOutput._f
#print axioms HatcherLib.VanKampenSweepStage.chainOutput.eq_2
#print axioms HatcherLib.VanKampenSweepStage.ctorIdx
#print axioms HatcherLib.VanKampenSweepStage.mk
#print axioms HatcherLib.VanKampenSweepStage.mk.noConfusion
#print axioms HatcherLib.VanKampenSweepStage.output
#print axioms HatcherLib.VanKampenTripleIntersectionsPathConnected
#print axioms HatcherLib.VanKampenWordEquivalent.append_right
#print axioms HatcherLib.VanKampenWordEquivalent.of_move
#print axioms HatcherLib.VanKampenWordMove.casesOn
#print axioms HatcherLib.VanKampenWordMove.rec
#print axioms HatcherLib.affinePathHomotopy._proof_2
#print axioms HatcherLib.affine_paths_homotopic
#print axioms HatcherLib.coverInclusion
#print axioms HatcherLib.coverIntersectionInclusionLeft._proof_2
#print axioms HatcherLib.coverIntersectionInclusionRight._proof_2
#print axioms HatcherLib.coverIntersectionToRight
#print axioms HatcherLib.coveredLoopProduct
#print axioms HatcherLib.coveredLoopProduct.match_1
#print axioms HatcherLib.coveredSubdivisionPrefix
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_12
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_3
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_7
#print axioms HatcherLib.coveredSubdivisionPrefix._simp_8
#print axioms HatcherLib.exists_vanKampenSquareGrid._proof_1_14
#print axioms HatcherLib.exists_vanKampenSquareGrid._proof_1_5
#print axioms HatcherLib.freeBasisIndexEquivGenerators
#print axioms HatcherLib.freeProductInclusion
#print axioms HatcherLib.freeProductLift_comp_inclusion
#print axioms HatcherLib.fundamentalGroupProdMulEquiv._proof_2
#print axioms HatcherLib.inducedPiOne
#print axioms HatcherLib.mulOppositeProdMulEquiv
#print axioms HatcherLib.pathHomotopic_equivalence
#print axioms HatcherLib.pathInSubtype._proof_3
#print axioms HatcherLib.pathInSubtype.congr_simp
#print axioms HatcherLib.pathInSubtypeBetween._proof_3
#print axioms HatcherLib.pathInSubtypeBetween_map
#print axioms HatcherLib.pathIn_trans_left
#print axioms HatcherLib.path_connector_insertion
#print axioms HatcherLib.simplyConnected_iff_unique_path_class
#print axioms HatcherLib.vanKampenClassOfLoopIn
#print axioms HatcherLib.vanKampenClassOfLoopInIntersection.congr_simp
#print axioms HatcherLib.vanKampenFactorLoop._proof_1
#print axioms HatcherLib.vanKampenFactorRepresentative._proof_2
#print axioms HatcherLib.vanKampenMap.eq_1
#print axioms HatcherLib.vanKampenMap_wordLoop
#print axioms HatcherLib.vanKampenQuotientMap
#print axioms HatcherLib.vanKampenQuotientMulEquivOfKerEq
#print axioms HatcherLib.vanKampenRelator
#print axioms HatcherLib.vanKampenThreefoldIntersection._proof_1
#print axioms HatcherLib.vanKampenWordEquivalent_changeCover_of_loop
#print axioms HatcherLib.vanKampenWordEvaluation
#print axioms HatcherLib.vanKampenWordEvaluation_mem_normalSubgroup_of_equivalent_nil
#print axioms HatcherLib.vanKampenWordLoop._sunfold
#print axioms HatcherLib.vanKampenWordLoop.match_1
#print axioms HatcherLib.vanKampenWordLoop_singleton
#print axioms HatcherLib.vanKampenWordQuotientEvaluation_eq_mk
#print axioms Poincare.D10.jacobiSolFlat.eq_1
#print axioms Poincare.D11.BochnerManifold.deriv_abs_deriv_eq_of_neg
#print axioms Poincare.D11.BochnerManifold.deriv_deriv_gradSq
#print axioms Poincare.D11.BochnerManifold.differentiableAt_of_contDiff_one
#print axioms Poincare.D11.BochnerManifold.euclidean_bochner_identity_restated
#print axioms Poincare.D11.BochnerManifold.flatCertificateWitness._proof_1
#print axioms Poincare.D11.BochnerManifold.flatCertificateWitness_oneFormLaplacian
#print axioms Poincare.D11.BochnerManifold.frame_hess_norm_sq_sum
#print axioms Poincare.D11.BochnerManifold.gradSq.eq_1
#print axioms Poincare.D11.BochnerManifold.hasDerivAt_jacobiMeanCurvature
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature.eq_1
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_deriv_eq._simp_1_3
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_deriv_eq._simp_1_7
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_riccati
#print axioms Poincare.D11.BochnerManifold.jacobiSol_second_deriv_div._simp_1_3
#print axioms Poincare.D11.BochnerManifold.jacobiSol_second_deriv_div._simp_1_7
#print axioms Poincare.D11.BochnerManifold.modelBochnerCertificate
#print axioms Poincare.D11.BochnerManifold.modelFlatBochnerCertificate
#print axioms Poincare.D11.BochnerManifold.modelGradLapVec
#print axioms Poincare.D11.BochnerManifold.modelGradientCertificate
#print axioms Poincare.D11.BochnerManifold.modelHessSq
#print axioms Poincare.D11.BochnerManifold.modelRicciTerm
#print axioms Poincare.D11.BochnerManifold.model_bochner_certificate_bochner
#print axioms Poincare.D11.BochnerManifold.model_bochner_weitzenbock_unfolded
#print axioms Poincare.D11.BochnerManifold.model_gradient_certificate_hess_norm_sq
#print axioms Poincare.D11.BochnerManifold.model_ricci_pairing_eq_ricciTerm
#print axioms Poincare.D11.BochnerManifold.radial_ricci_of_model
#print axioms Poincare.D11.BochnerManifold.subharmonic_energy_density_of_nonneg_ricci
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.C_up
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.WeakInitialCondition.of_full
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.c_lo_pos
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.ctorIdx
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.dist_self
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.gaussianUpperBound
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.laplacian
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.mk.injEq
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.noConfusionType
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.semigroup
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.toHeatKernelData
#print axioms Poincare.D11.HeatKernelBridge.contDiffTwoSet._proof_1
#print axioms Poincare.D11.HeatKernelBridge.contDiffTwoSubmodule._proof_3
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_1
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_13
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_2
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_6
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_C_lo
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_dim
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_gaussianUpperBound
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_normalization
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_weakInitialCondition_apply
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelData_zero_volume
#print axioms Poincare.D11.HeatKernelBridge.flatKernel_nonneg
#print axioms Poincare.D11.HeatKernelBridge.flatKernel_tendsto_integral
#print axioms Poincare.D11.HeatKernelBridge.integrable_exp_neg_mul_norm_sq
#print axioms Poincare.D11.HeatKernelBridge.laplacianLinearMap._proof_3
#print axioms Poincare.D11.HeatKernelBridge.laplacian_comp_sub
#print axioms Poincare.D11.HeatKernelBridge.setIntegral_compl_ball_gaussianKernel_le
#print axioms Poincare.D11.HeatKernelBridge.tendsto_exp_neg_div
#print axioms Poincare.D11.HeatKernelBridge.tendsto_setIntegral_compl_ball_gaussianKernel
#print axioms Poincare.D11.MaximumPrincipleTensor.ConeInvariantUnderReaction._proof_1
#print axioms Poincare.D11.MaximumPrincipleTensor.PositivityPreserving.add
#print axioms Poincare.D11.MaximumPrincipleTensor.PositivityPreserving.id
#print axioms Poincare.D11.MaximumPrincipleTensor.boundaryOnlyReaction._proof_1
#print axioms Poincare.D11.MaximumPrincipleTensor.boundary_condition_strictly_weaker
#print axioms Poincare.D11.MaximumPrincipleTensor.eulerIterate_succ
#print axioms Poincare.D11.MaximumPrincipleTensor.eulerStep_mono
#print axioms Poincare.D11.MaximumPrincipleTensor.hasDerivAt_negSquare
#print axioms Poincare.D11.MaximumPrincipleTensor.mem_psdCone
#print axioms Poincare.D11.MaximumPrincipleTensor.nonneg_of_posSemidef
#print axioms Poincare.D11.MaximumPrincipleTensor.oneByOne.eq_1
#print axioms Poincare.D11.MaximumPrincipleTensor.oneByOne_injective
#print axioms Poincare.D11.MaximumPrincipleTensor.positivityPreserving_const_smul_add_sq
#print axioms Poincare.D11.MaximumPrincipleTensor.psdCone_convex
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm_eulerStep_nonneg_of_boundary
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm_nonneg
#print axioms Poincare.D11.MaximumPrincipleTensor.scalar_forward_invariance_of_global_reaction
#print axioms Poincare.D11.MaximumPrincipleTensor.sqrtNegReaction.eq_1
#print axioms Poincare.D11.MaximumPrincipleTensor.tensor_maximum_principle_ode
#print axioms Poincare.D11.ReducedVolume.IsLMinimizer_of_eq_straightRay._simp_1_1
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface._sizeOf_1
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.dimension
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.mk.inj
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.noConfusion
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.reducedDistance
#print axioms Poincare.D11.ReducedVolume.euclideanFlow
#print axioms Poincare.D11.ReducedVolume.euclideanJacobianComparisonInterface
#print axioms Poincare.D11.ReducedVolume.euclideanJacobianComparisonInterface_jacobian
#print axioms Poincare.D11.ReducedVolume.euclideanManifoldReducedVolumeInterface_reducedDistance
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolumeCertificate
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolumeCertificate_antitoneOn
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolume_eq_one
#print axioms Poincare.D11.ReducedVolume.euclidean_manifold_LMinimizerExistence
#print axioms Poincare.D11.ReducedVolume.flatDeficit_integral
#print axioms Poincare.D11.ReducedVolume.flatLExponential._proof_2
#print axioms Poincare.D11.ReducedVolume.flatLlength_eq_LlengthAlong
#print axioms Poincare.D11.ReducedVolume.generalMonotonicityMissingDependencies
#print axioms Poincare.D11.ReducedVolume.heatKernelReducedDistance
#print axioms Poincare.D11.ReducedVolume.heatKernelReducedDistance_eq_straightRayReducedLength
#print axioms Poincare.D11.ReducedVolume.integral_reducedVolumeIntegrandUnnormalized
#print axioms Poincare.D11.ReducedVolume.reducedVolume._proof_1
#print axioms Poincare.D11.ReducedVolume.reducedVolumeIntegrand._proof_2
#print axioms Poincare.D11.ReducedVolume.reducedVolumeIntegrand_eq_gaussianKernel
#print axioms Poincare.D11.ReducedVolume.straightRay
#print axioms Poincare.D11.ReducedVolume.straightRayVelocity
#print axioms Poincare.D11.ReducedVolume.straightRay_hasDerivAt
#print axioms Poincare.D11.ReducedVolume.straightRay_tau
#print axioms Poincare.D11.SpectralTorus.Torus
#print axioms Poincare.D11.SpectralTorus.circleRep_sub_witness
#print axioms Poincare.D11.SpectralTorus.coordProj._proof_3
#print axioms Poincare.D11.SpectralTorus.dirDeriv2_fourierMode
#print axioms Poincare.D11.SpectralTorus.finConsEquiv._proof_1
#print axioms Poincare.D11.SpectralTorus.fourierMode
#print axioms Poincare.D11.SpectralTorus.fourierMode_eq_mFourier_lift
#print axioms Poincare.D11.SpectralTorus.gradNorm.eq_1
#print axioms Poincare.D11.SpectralTorus.hasFDerivAt_innerForm
#print axioms Poincare.D11.SpectralTorus.innerForm._proof_3
#print axioms Poincare.D11.SpectralTorus.intVec._proof_1
#print axioms Poincare.D11.SpectralTorus.integral_mFourier
#print axioms Poincare.D11.SpectralTorus.laplacian_fourierMode
#print axioms Poincare.D11.SpectralTorus.lattice
#print axioms Poincare.D11.SpectralTorus.normSq
#print axioms Poincare.D11.SpectralTorus.normSq_nonneg
#print axioms Poincare.D11.SpectralTorus.ofRealClm._proof_2
#print axioms Poincare.D11.SpectralTorus.one_add_normSq_inv_le_prod
#print axioms Poincare.D11.SpectralTorus.one_add_normSq_inv_le_prod._simp_1_4
#print axioms Poincare.D11.SpectralTorus.one_le_normSq_of_ne_zero
#print axioms Poincare.D11.SpectralTorus.parsevalUnitAddCircleIsAddHaarMeasure._proof_1
#print axioms Poincare.D11.SpectralTorus.poincareUnitAddCircleIsAddHaarMeasure
#print axioms Poincare.D11.SpectralTorus.poincareUnitAddCircleMeasureSpace
#print axioms Poincare.D11.SpectralTorus.sobolevEmbeddingConstant.eq_1
#print axioms Poincare.D11.SpectralTorus.sobolevUnitAddCircleIsAddHaarMeasure
#print axioms Poincare.D11.SpectralTorus.sobolevUnitAddCircleMeasureSpace
#print axioms Poincare.D11.SpectralTorus.sobolevWeightHalf._proof_1
#print axioms Poincare.D11.SpectralTorus.stdVec.eq_1
#print axioms Poincare.D11.SpectralTorus.summable_sobolevWeight_inv._simp_1_2
#print axioms Poincare.D11.SpectralTorus.summable_sobolevWeight_inv._simp_1_6
#print axioms Poincare.D11.SpectralTorus.summable_weight_nat
#print axioms Poincare.D11.SpectralTorus.torusEquivUnitAddTorus
#print axioms Poincare.D11.SpectralTorus.torusFourier_abs_eq_one
#print axioms Poincare.D11.SpectralTorus.torusQuot
#print axioms Poincare.D11.SpectralTorus.torusQuotHom._proof_2
#print axioms Poincare.D11.SpectralTorus.torusQuot_periodic
#print axioms Poincare.D11.SpectralTorus.trigCoeff
#print axioms Poincare.D11.SpectralTorus.trigPolyDeriv
#print axioms Poincare.D11.SpectralTorus.trigPolyDerivL2._proof_2
#print axioms Poincare.D11.SpectralTorus.trigPolyDerivL2._proof_6
#print axioms Poincare.D11.SpectralTorus.trigPolyL2
#print axioms Poincare.D11.SpectralTorus.trigPolyL2._proof_4
#print axioms Poincare.D11.SpectralTorus.trigPolyL2_inner_self
#print axioms Poincare.D11.SpectralTorus.trigPoly_mean_zero_iff
#print axioms Poincare.D11.SpectralTorus.twoPiI
#print axioms Poincare.D11.SpectralTorus.twoPiI_sq
#print axioms Poincare.D11.WarpedProductModel.casesOn
#print axioms Poincare.D11.WarpedProductModel.mk._flat_ctor
#print axioms Poincare.D11.WarpedProductModel.solves_ode
#print axioms Poincare.D11.ballVolume_pos
#print axioms Poincare.D11.bishopGromov_volume_comparison_of_nonpos
#print axioms Poincare.D11.continuous_jacobiSol_pow
#print axioms Poincare.D11.differentiable_jacobiSol_pow
#print axioms Poincare.D11.divergenceLaplacian_eq_radialLaplacian._proof_1_1
#print axioms Poincare.D11.jacobiSol_div_antitoneOn
#print axioms Poincare.D11.jacobiSol_pos_of_le
#print axioms Poincare.D11.modelFlatMetric
#print axioms Poincare.D11.modelHyperbolicMetric_posDef
#print axioms Poincare.D11.modelSphereMetric_symm
#print axioms Poincare.D11.polarMetric_add_right
#print axioms Poincare.D11.polarMetric_smul_left
#print axioms Poincare.D11.radialLaplacian_id
#print axioms Poincare.D11.warpedProductModel_jacobiSolFlat
#print axioms Poincare.D11.wronskian.eq_1
#print axioms Poincare.D12.ComparisonGeodesics.HasDerivAtR
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.continuousOn_du
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.hasDerivAt_u
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.rec
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiEqOn.continuousOn_m
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiEqOn.mk._flat_ctor
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiLeOn
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiLeOn.ineq
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiLeOn.recOn
#print axioms Poincare.D12.ComparisonGeodesics.areaRatio_hasDerivAt._simp_1_2
#print axioms Poincare.D12.ComparisonGeodesics.areaRatio_hasDerivAt._simp_1_6
#print axioms Poincare.D12.ComparisonGeodesics.bishopGromov_volume_le._simp_1_1
#print axioms Poincare.D12.ComparisonGeodesics.bishopGromov_volume_le._simp_1_5
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelA
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelA_logDeriv._proof_1_1
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelM
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelM_riccati
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_volume
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_volume._simp_1_4
#print axioms Poincare.D12.ComparisonGeodesics.euclideanNormalizedOn_not_continuousOn_zero
#print axioms Poincare.D12.ComparisonGeodesics.hasDerivAtR_pow
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_hasDerivAt._simp_1_1
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_hasDerivAt._simp_1_5
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_le_of_le._simp_1_1
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_le_of_le._simp_1_5
#print axioms Poincare.D12.ComparisonGeodesics.nonneg_of_continuousOn_of_posOn_Ioo
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume_numerator_le_zero._simp_1_1
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume_numerator_le_zero._simp_1_5
#print axioms Poincare.D12.ComparisonGeodesics.riccati_delta_ge_exp
#print axioms Poincare.D12.ComparisonGeodesics.riccati_le_of_initial
#print axioms Poincare.D12.ComparisonGeodesics.solution_le_of_initial._simp_1_2
#print axioms Poincare.D12.ComparisonGeodesics.solution_le_of_initial._simp_1_6
#print axioms Poincare.D12.ComparisonGeodesics.sturm_zero_comparison
#print axioms Poincare.D12.ComparisonGeodesics.wronskian.eq_1
#print axioms Poincare.D12.ComparisonGeodesics.wronskian_differentiableOn
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients._sizeOf_inst
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.christoffelLower
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.christoffel_raised_contraction._simp_1_2
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.ctorIdx
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.gInv
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.gram_christoffel_contraction._simp_1_2
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.metricDerivative_christoffel
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.mk.congr_simp
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.mk.sizeOf_spec
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.recOn
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D._proof_3
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_christoffel
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_christoffel._simp_1_6
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_christoffel_ne_zero
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.chartCoefficients
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.christoffelFamily_metricDerivative
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.dFamily
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.formField
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.gInv
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.g_component_smooth
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.lieBracket
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.mk.inj
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.nabla
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.nabla_metricCompatible
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.noConfusion
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.cross_e0_e1
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3._proof_3
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3._proof_7
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3Lie
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3Metric
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3Metric._proof_4
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3_bracketInvariant
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3_ricci_e00
#print axioms Poincare.D12.ConnectionCurvature.adTranspose._proof_1
#print axioms Poincare.D12.ConnectionCurvature.adTranspose._proof_5
#print axioms Poincare.D12.ConnectionCurvature.adTranspose.eq_1
#print axioms Poincare.D12.ConnectionCurvature.chartAbstractConnection
#print axioms Poincare.D12.ConnectionCurvature.chartCurvatureOperator
#print axioms Poincare.D12.ConnectionCurvature.chartTorsionFree_form
#print axioms Poincare.D12.ConnectionCurvature.conformalG.eq_1
#print axioms Poincare.D12.ConnectionCurvature.conformalG_smooth
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma.eq_3
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma.eq_7
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma_origin_zero
#print axioms Poincare.D12.ConnectionCurvature.conformalPointwise._proof_3
#print axioms Poincare.D12.ConnectionCurvature.conformalPointwise.eq_1
#print axioms Poincare.D12.ConnectionCurvature.conformal_denom_pos
#print axioms Poincare.D12.ConnectionCurvature.curvatureEndo._proof_2
#print axioms Poincare.D12.ConnectionCurvature.curvature_skew_adjoint._abel_1_1
#print axioms Poincare.D12.ConnectionCurvature.fderiv_mul_mul_apply
#print axioms Poincare.D12.ConnectionCurvature.formOf._proof_3
#print axioms Poincare.D12.ConnectionCurvature.formOf._proof_7
#print axioms Poincare.D12.ConnectionCurvature.form_basis_apply_of_orthonormal
#print axioms Poincare.D12.ConnectionCurvature.linMap_apply_eq_sum_single
#print axioms Poincare.D12.ConnectionCurvature.milnorAbstractConnection
#print axioms Poincare.D12.ConnectionCurvature.milnorConnection._proof_3
#print axioms Poincare.D12.ConnectionCurvature.milnorConnection_isLeviCivita
#print axioms Poincare.D12.ConnectionCurvature.milnor_ricci_symm
#print axioms Poincare.D12.ConnectionCurvature.nablaOf._proof_3
#print axioms Poincare.D12.ConnectionCurvature.nablaOf._proof_7
#print axioms Poincare.D12.ConnectionCurvature.ricci_contraction_eq_sum_basis
#print axioms Poincare.D12.ConnectionCurvature.sum_add_split
#print axioms Poincare.D12.ConnectionCurvature.sum_three_reorder
#print axioms Poincare.D12.EntropyVariation.FDissipationCorrected._proof_1
#print axioms Poincare.D12.EntropyVariation.derivative_sign_distinction
#print axioms Poincare.D12.EntropyVariation.fDerivativeStatement_of_corrected_of_idempotent
#print axioms Poincare.D12.EntropyVariation.fflowEntropyData._proof_3
#print axioms Poincare.D12.EntropyVariation.fflowEntropyData.eq_1
#print axioms Poincare.D12.EntropyVariation.fflowGradSqVariation
#print axioms Poincare.D12.EntropyVariation.fflowRiccHess
#print axioms Poincare.D12.EntropyVariation.fflowScaleInv_pos
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipationCorrected_value._simp_1_5
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipationCorrected_value._simp_1_9
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipation_value._simp_1_4
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipation_value._simp_1_8
#print axioms Poincare.D12.EntropyVariation.fflow_F_hasDerivAt_closedForm
#print axioms Poincare.D12.EntropyVariation.fflow_F_strictMonoOn._simp_1_2
#print axioms Poincare.D12.EntropyVariation.fflow_F_strictMonoOn._simp_1_6
#print axioms Poincare.D12.EntropyVariation.fflow_F_value._simp_1_3
#print axioms Poincare.D12.EntropyVariation.fflow_F_value._simp_1_7
#print axioms Poincare.D12.EntropyVariation.fflow_idempotency_holds_zero_dim
#print axioms Poincare.D12.EntropyVariation.fflow_literal_FDerivativeStatement_zero_dim
#print axioms Poincare.D12.EntropyVariation.fflow_riccHess_eq_scaleInvSq_mul_shrinkerRiccHess
#print axioms Poincare.D12.EntropyVariation.fflow_variation_eq_two_riccHess_iff
#print axioms Poincare.D12.EntropyVariation.fflow_variation_eq_two_riccHess_of_normSq_eq._simp_1_3
#print axioms Poincare.D12.EntropyVariation.fflow_variation_eq_two_riccHess_of_normSq_eq._simp_1_7
#print axioms Poincare.D12.EntropyVariation.fflow_variation_integral._simp_1_3
#print axioms Poincare.D12.EntropyVariation.fflow_variation_integral._simp_1_7
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_fflowGradSq._simp_1_1
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_fflowGradSq._simp_1_5
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_fflowScaleInv
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_weightedIntegral_constWeight
#print axioms Poincare.D12.EntropyVariation.integrable_normSq_mul_exp_neg_mul
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_exp_neg_mul._simp_1_1
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_exp_neg_mul._simp_1_5
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_gaussianKernel._simp_1_1
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_gaussianKernel._simp_1_5
#print axioms Poincare.D12.EntropyVariation.normSq_exp_neg_mul_le
#print axioms Poincare.D12.EntropyVariation.normSq_exp_neg_mul_le._simp_1_4
#print axioms Poincare.D12.EntropyVariation.perelmanFFlow_increasing_toy_nonincreasing
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData._proof_3
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData.eq_1
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipationCorrected_value._simp_1_5
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipationCorrected_value._simp_1_9
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipation_value._simp_1_4
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipation_value._simp_1_8
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_F_value._simp_1_3
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_F_value._simp_1_7
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_secondMoment
#print axioms Poincare.D12.EntropyVariation.shrinkerGradSq._proof_1
#print axioms Poincare.D12.EntropyVariation.shrinkerWDissipation
#print axioms Poincare.D12.EntropyVariation.shrinkerWDissipation_zero
#print axioms Poincare.D12.EntropyVariation.shrinkerWOfTau_eq_zero
#print axioms Poincare.D12.EntropyVariation.shrinker_riccHess_justified
#print axioms Poincare.D12.EntropyVariation.shrinker_riccHess_justified._simp_1_4
#print axioms Poincare.D12.EntropyVariation.shrinker_w_dissipation_density_zero
#print axioms Poincare.D12.GeometricCompactness.bishopGromovVolumeComparison
#print axioms Poincare.D12.GeometricCompactness.closure_isCompact_of_totallyBounded
#print axioms Poincare.D12.GeometricCompactness.cover_transfer_of_isometry
#print axioms Poincare.D12.GeometricCompactness.diam_transfer_of_ghDist
#print axioms Poincare.D12.GeometricCompactness.gh_subseq_of_compact
#print axioms Poincare.D12.GeometricCompactness.gridFamily_infinite
#print axioms Poincare.D12.GeometricCompactness.gridGH_injective
#print axioms Poincare.D12.GeometricCompactness.gridSpace
#print axioms Poincare.D12.GeometricCompactness.gridVertices
#print axioms Poincare.D12.GeometricCompactness.harmonicCoordinatesExistence
#print axioms Poincare.D12.GeometricCompactness.instGridSpaceMetricSpace
#print axioms Poincare.D12.GeometricCompactness.instSquareSpaceNonempty
#print axioms Poincare.D12.GeometricCompactness.mk2._proof_1
#print axioms Poincare.D12.GeometricCompactness.mk2_ofLp_zero
#print axioms Poincare.D12.GeometricCompactness.square_grid_dense._simp_1_1
#print axioms Poincare.D12.GeometricCompactness.square_grid_dense._simp_1_5
#print axioms Poincare.D12.GeometricCompactness.totallyBounded_iff_uniformCovers
#print axioms Poincare.D12.GeometricCompactness.zero_mem_unitSquare
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.casesOn
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.continuousCompactSupportClass
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.continuousIntegrableClass
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.ctorIdx
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.mk.injEq
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.noConfusionType
#print axioms Poincare.D12.HeatDomain.WeakInitialConditionFor
#print axioms Poincare.D12.HeatDomain.bump_continuous
#print axioms Poincare.D12.HeatDomain.bump_support_subset_closedBall
#print axioms Poincare.D12.HeatDomain.ccClass_cls_iff_continuous_of_compactSpace
#print axioms Poincare.D12.HeatDomain.fastFunction_nonneg
#print axioms Poincare.D12.HeatDomain.flatHeatKernelCore_weakInitialConditionFor_integrableClass'
#print axioms Poincare.D12.HeatDomain.integral_fast_times_kernel_eq_zero
#print axioms Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel
#print axioms Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel._simp_1_4
#print axioms Poincare.D12.HeatDomain.not_exists_heatKernelData_flat_of_pos
#print axioms Poincare.D12.HeatDomain.ofLp_image_halfspace
#print axioms Poincare.D12.HeatDomain.toHeatKernelData_of_weak_compact_finiteMeasure._proof_1
#print axioms Poincare.D12.HeatDomain.volume_halfspace_eq_top
#print axioms Poincare.D12.HeatDomain.weakInitialConditionFor_integrableClass_iff_full_of_compact_finiteMeasure
#print axioms Poincare.D12.HeatSemigroup.CompactManifoldLinfContractionObligation
#print axioms Poincare.D12.HeatSemigroup.CompactManifoldSmoothingObligation._proof_2
#print axioms Poincare.D12.HeatSemigroup.continuous_gaussianKernelFDerivCLM
#print axioms Poincare.D12.HeatSemigroup.fderiv_heatOperator
#print axioms Poincare.D12.HeatSemigroup.gaussianKernelFDerivCLM._proof_3
#print axioms Poincare.D12.HeatSemigroup.gaussianKernel_interval_bound
#print axioms Poincare.D12.HeatSemigroup.hasFDerivAt_heatOperator
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_apply
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_apply._simp_1_4
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_bound_ball
#print axioms Poincare.D12.HeatSemigroup.heatOperator
#print axioms Poincare.D12.HeatSemigroup.heatOperatorBCF
#print axioms Poincare.D12.HeatSemigroup.heatOperatorBCF_apply
#print axioms Poincare.D12.HeatSemigroup.heatOperator_abs_le_of_forall_abs_le
#print axioms Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator_integral_norm_eq_zero
#print axioms Poincare.D12.HeatSemigroup.heatOperator_enorm_le_lintegral_enorm
#print axioms Poincare.D12.HeatSemigroup.heatOperator_gaussianKernel
#print axioms Poincare.D12.HeatSemigroup.heatOperator_gaussianKernel_integral
#print axioms Poincare.D12.HeatSemigroup.heatOperator_integral_eq_integral
#print axioms Poincare.D12.HeatSemigroup.heatOperator_norm_le_of_forall_norm_le
#print axioms Poincare.D12.HeatSemigroup.heatOperator_tendsto_nhdsGT_zero_conv
#print axioms Poincare.D12.HeatSemigroup.heatSmoothingBoundConst
#print axioms Poincare.D12.HeatSemigroup.integrable_gaussianKernel_sub
#print axioms Poincare.D12.HeatSemigroup.integral_gaussianKernel_sub_left
#print axioms Poincare.D12.HeatSemigroup.norm_sub_sq_ge_half
#print axioms Poincare.D12.HeatSemigroup.one_add_norm_sq_mul_exp_neg_le._simp_1_3
#print axioms Poincare.D12.HeatSemigroup.one_add_norm_sq_mul_exp_neg_le._simp_1_7
#print axioms Poincare.D12.KappaVariational.ClosureRecord._sizeOf_1
#print axioms Poincare.D12.KappaVariational.ClosureRecord.ctorIdx
#print axioms Poincare.D12.KappaVariational.ClosureRecord.mk._flat_ctor
#print axioms Poincare.D12.KappaVariational.ClosureRecord.mk.noConfusion
#print axioms Poincare.D12.KappaVariational.ClosureRecord.proof
#print axioms Poincare.D12.KappaVariational.ballVolumeComparisonExists
#print axioms Poincare.D12.KappaVariational.constantCurvatureFlow._proof_3
#print axioms Poincare.D12.KappaVariational.constantCurvatureFlow_metric
#print axioms Poincare.D12.KappaVariational.constantCurvatureLPath._proof_1
#print axioms Poincare.D12.KappaVariational.constantCurvatureLPath._proof_5
#print axioms Poincare.D12.KappaVariational.constantCurvatureLPath.eq_1
#print axioms Poincare.D12.KappaVariational.constantCurvature_LlengthAlong
#print axioms Poincare.D12.KappaVariational.constantCurvature_reducedLength_le
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolume
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeCertificate
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeCertificate_antitoneOn
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeDensity.eq_1
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeDensity_shape
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeViaL
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolume_def
#print axioms Poincare.D12.KappaVariational.gaussianUniformReducedVolumeLowerBound_integral
#print axioms Poincare.D12.KappaVariational.gaussianVecTauNormalized._proof_1
#print axioms Poincare.D12.KappaVariational.gaussianVecTau_eq_exp_neg_sum_sq
#print axioms Poincare.D12.KappaVariational.integral_gaussianVecTau
#print axioms Poincare.D12.KappaVariational.integral_sqrt
#print axioms Poincare.D12.KappaVariational.kappaVariationalClosures_nonempty
#print axioms Poincare.D12.KappaVariational.kappaVariationalRemainingDependencies_length
#print axioms Poincare.D12.KappaVariational.rlv10Closure
#print axioms Poincare.D12.KappaVariational.rlv1ModelClosure.eq_1
#print axioms Poincare.D12.KappaVariational.toGaussianPath._proof_1
#print axioms Poincare.D12.KappaVariational.toGaussianPath._proof_5
#print axioms Poincare.D12.ParabolicLocal.BCFn
#print axioms Poincare.D12.ParabolicLocal.BUCf.casesOn
#print axioms Poincare.D12.ParabolicLocal.BUCf.dist_eq_dist_val
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddBUCn._proof_1
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_11
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_4
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_8
#print axioms Poincare.D12.ParabolicLocal.BUCf.instCompleteSpaceBUCn
#print axioms Poincare.D12.ParabolicLocal.BUCf.instModuleRealBUCn._proof_3
#print axioms Poincare.D12.ParabolicLocal.BUCf.instNegBUCn
#print axioms Poincare.D12.ParabolicLocal.BUCf.instNormedAddCommGroupBUCn._proof_2
#print axioms Poincare.D12.ParabolicLocal.BUCf.instNormedSpaceRealBUCn._proof_1
#print axioms Poincare.D12.ParabolicLocal.BUCf.instZeroBUCn._proof_1
#print axioms Poincare.D12.ParabolicLocal.BUCf.mk.inj
#print axioms Poincare.D12.ParabolicLocal.BUCf.noConfusion
#print axioms Poincare.D12.ParabolicLocal.BUCf.norm_val
#print axioms Poincare.D12.ParabolicLocal.BUCf.uniformContinuous_of_tendsto_uniform
#print axioms Poincare.D12.ParabolicLocal.BUCf.val_apply
#print axioms Poincare.D12.ParabolicLocal.BUCf.val_zero
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.F_lipschitz
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup._sizeOf_1
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.clamp.eq_1
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.clamp_eq_self
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.contractionConstant_eq
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.duhamelMap._proof_1
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.duhamelMap_apply
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.extendToInterval
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.extendToInterval_norm_le
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mildSolution_continuous
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mildSolution_unique
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mk.inj
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.noConfusion
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.smap_continuous
#print axioms Poincare.D12.ParabolicLocal.Vn
#print axioms Poincare.D12.ParabolicLocal.arctanBCF._proof_1
#print axioms Poincare.D12.ParabolicLocal.arctanF.eq_1
#print axioms Poincare.D12.ParabolicLocal.bucConst
#print axioms Poincare.D12.ParabolicLocal.bucHeatOperator._proof_1
#print axioms Poincare.D12.ParabolicLocal.bucHeatOperator._proof_5
#print axioms Poincare.D12.ParabolicLocal.continuous_parametric_intervalIntegral
#print axioms Poincare.D12.ParabolicLocal.coordCLM._proof_2
#print axioms Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds
#print axioms Poincare.D12.ParabolicLocal.domBound._proof_1
#print axioms Poincare.D12.ParabolicLocal.domBound_integrable
#print axioms Poincare.D12.ParabolicLocal.gaussianKernel_hasFDerivAt
#print axioms Poincare.D12.ParabolicLocal.gaussianKernel_sub_le_quarter
#print axioms Poincare.D12.ParabolicLocal.gaussianS.eq_1
#print axioms Poincare.D12.ParabolicLocal.gaussianS_norm_le
#print axioms Poincare.D12.ParabolicLocal.gaussianS_semigroup'
#print axioms Poincare.D12.ParabolicLocal.gaussianSetup
#print axioms Poincare.D12.ParabolicLocal.gaussianSmap_continuous
#print axioms Poincare.D12.ParabolicLocal.heatConvPoint
#print axioms Poincare.D12.ParabolicLocal.heatConvPoint_hasFDerivAt_zero
#print axioms Poincare.D12.ParabolicLocal.heatConvPos._proof_2
#print axioms Poincare.D12.ParabolicLocal.heatConv_apply
#print axioms Poincare.D12.ParabolicLocal.heatConv_fderiv_zero_apply
#print axioms Poincare.D12.ParabolicLocal.heatConv_norm_le'
#print axioms Poincare.D12.ParabolicLocal.heatConv_tendsto_self_BUC
#print axioms Poincare.D12.ParabolicLocal.heatMildSolution
#print axioms Poincare.D12.ParabolicLocal.heatMildSolution_initial
#print axioms Poincare.D12.ParabolicLocal.heatOperator._proof_4
#print axioms Poincare.D12.ParabolicLocal.heatOperatorCLM_norm_le
#print axioms Poincare.D12.ParabolicLocal.intervalIntegral_exp_mul_eq
#print axioms Poincare.D12.ParabolicLocal.jointContinuous_of_absSemigroup._abel_1_3
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv._proof_4
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv_norm_le_domBound
#print axioms Poincare.D12.ParabolicLocal.kernelMoment_const
#print axioms Poincare.D12.ParabolicLocal.linearCandidateSolution._proof_1
#print axioms Poincare.D12.ParabolicLocal.linearCandidate_continuous
#print axioms Poincare.D12.ParabolicLocal.linearCandidate_isFixedPt._simp_1_5
#print axioms Poincare.D12.ParabolicLocal.linearCandidate_isFixedPt._simp_1_9
#print axioms Poincare.D12.ParabolicLocal.linearSmulF
#print axioms Poincare.D12.ParabolicLocal.mildToClassicalBridge._proof_1
#print axioms Poincare.D12.ParabolicLocal.normSq_mul_exp_neg_mul_normSq_le
#print axioms Poincare.D12.ParabolicLocal.quasilinearRicciDeTurckBarrier._proof_2
#print axioms Poincare.D12.ParabolicLocal.squareF._proof_1
#print axioms Poincare.D12.ParabolicLocal.squareF_not_lipschitz
#print axioms Poincare.D12.ParabolicLocal.testF_contDiff
#print axioms Poincare.D12.ParabolicLocal.valCLM._proof_2
#print axioms Poincare.D12.SemanticLedger.R
#print axioms Poincare.D12.SemanticLedger.gaussianKernelXY
#print axioms Poincare.D12.SemanticLedger.integrand
#print axioms Poincare.D12.SemanticLedger.integrand_lintegral_eq_top
#print axioms Poincare.D12.SemanticLedger.lowerConstant
#print axioms Poincare.D12.SemanticLedger.not_initialCondition_gaussian_quantified
#print axioms Poincare.D12.SemanticLedger.testFunction_continuous
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic._simp_1_1
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic._simp_1_5
#print axioms Poincare.D12.SpectralSobolev.fourierCoeff_heatEvolve
#print axioms Poincare.D12.SpectralSobolev.heatCoeffsL2._proof_1
#print axioms Poincare.D12.SpectralSobolev.heatEvolve._proof_1
#print axioms Poincare.D12.SpectralSobolev.heatEvolve_fourierLp
#print axioms Poincare.D12.SpectralSobolev.heatSeries_hasSum
#print axioms Poincare.D12.SpectralSobolev.heatWeight_abs_le_one
#print axioms Poincare.D12.SpectralSobolev.heatWeight_pos
#print axioms Poincare.D12.SpectralSobolev.integral_cos_sq_period
#print axioms Poincare.D12.SpectralSobolev.norm_sin_le_one
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger._simp_1_2
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger._simp_1_6
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger_sine_saturates
#print axioms Poincare.D12.SpectralSobolev.sq_norm_eigenvalue
#print axioms Poincare.D12.SpectralSobolev.sq_norm_eigenvalue._simp_1_4
#print axioms Poincare.D12.SpectralSobolev.sq_norm_eigenvalue._simp_1_8
#print axioms Poincare.D12.SurgeryRecognition.Ball3
#print axioms Poincare.D12.SurgeryRecognition.ConnectedSumDecompositionV2.casesOn
#print axioms Poincare.D12.SurgeryRecognition.ConnectedSumDecompositionV2.rec
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.ctorIdx
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.mk._flat_ctor
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.mk.sizeOf_spec
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.rec
#print axioms Poincare.D12.SurgeryRecognition.OpenBall3
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses._sizeOf_1
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.mk
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.mk.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.pieceRecognition
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.coveringTrivial
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.mk.inj
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.spaceForm
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3._sizeOf_1
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.mk
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.mk.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.rec
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.toRemainingV2
#print axioms Poincare.D12.SurgeryRecognition.S3
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel._sizeOf_1
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.coveringQuotient
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.instFintype
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.mk._flat_ctor
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.mk.sizeOf_spec
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.rec
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceFormProjection_covering
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.Γ
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.casesOn
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.mk.inj
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.sum
#print axioms Poincare.D12.SurgeryRecognition.antipodal.eq_1
#print axioms Poincare.D12.SurgeryRecognition.antipodalModel._proof_1
#print axioms Poincare.D12.SurgeryRecognition.antipodalQuotientCovering
#print axioms Poincare.D12.SurgeryRecognition.antipodal_disjoint_ball
#print axioms Poincare.D12.SurgeryRecognition.antipodal_of_ne_one
#print axioms Poincare.D12.SurgeryRecognition.ballEquator
#print axioms Poincare.D12.SurgeryRecognition.connectSumCongr
#print axioms Poincare.D12.SurgeryRecognition.connectSumRel_equiv
#print axioms Poincare.D12.SurgeryRecognition.consVec3
#print axioms Poincare.D12.SurgeryRecognition.consVec3_self_tail
#print axioms Poincare.D12.SurgeryRecognition.down._proof_1
#print axioms Poincare.D12.SurgeryRecognition.downPoint_mem
#print axioms Poincare.D12.SurgeryRecognition.downS3_injective
#print axioms Poincare.D12.SurgeryRecognition.down_southBall
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_2
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_6
#print axioms Poincare.D12.SurgeryRecognition.equator_both_copies
#print axioms Poincare.D12.SurgeryRecognition.glueRel.eq_1
#print axioms Poincare.D12.SurgeryRecognition.glueRel.match_1
#print axioms Poincare.D12.SurgeryRecognition.height_continuous
#print axioms Poincare.D12.SurgeryRecognition.hemiGlueRel
#print axioms Poincare.D12.SurgeryRecognition.hemiQuot_homeo_DoubleBall
#print axioms Poincare.D12.SurgeryRecognition.instMulActionAntipodalGroupS3._proof_1
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum._f
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum._proof_4
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum._sunfold
#print axioms Poincare.D12.SurgeryRecognition.mem_downS3_openBall_iff
#print axioms Poincare.D12.SurgeryRecognition.northBall_injective
#print axioms Poincare.D12.SurgeryRecognition.northHemisphere._proof_1
#print axioms Poincare.D12.SurgeryRecognition.northHemisphereHomeo._proof_3
#print axioms Poincare.D12.SurgeryRecognition.north_south_inter_eq_equator
#print axioms Poincare.D12.SurgeryRecognition.ofSphere_toSphere
#print axioms Poincare.D12.SurgeryRecognition.puncturedHomeo._proof_1
#print axioms Poincare.D12.SurgeryRecognition.puncturedHomeo._proof_5
#print axioms Poincare.D12.SurgeryRecognition.puncturedHomeo.eq_1
#print axioms Poincare.D12.SurgeryRecognition.quotientHomeoOfSubsingleton._proof_2
#print axioms Poincare.D12.SurgeryRecognition.quotientMapHomeo
#print axioms Poincare.D12.SurgeryRecognition.quotientMapHomeo._proof_4
#print axioms Poincare.D12.SurgeryRecognition.quotientMapHomeo._proof_8
#print axioms Poincare.D12.SurgeryRecognition.southBall_down
#print axioms Poincare.D12.SurgeryRecognition.southHemisphereHomeo._proof_2
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo._proof_4
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo._proof_8
#print axioms Poincare.D12.SurgeryRecognition.sphere2ToBall._proof_1
#print axioms Poincare.D12.SurgeryRecognition.sphere2_norm_eq_one
#print axioms Poincare.D12.SurgeryRecognition.sphereBallPart._proof_1
#print axioms Poincare.D12.SurgeryRecognition.sphereConnectSum_homeo_hemiQuot
#print axioms Poincare.D12.SurgeryRecognition.sphereThree_pathConnectedSpace
#print axioms Poincare.D12.SurgeryRecognition.sphericalPieceRecognition_of._proof_1
#print axioms Poincare.D12.SurgeryRecognition.stage6Target_of_v3hypotheses
#print axioms Poincare.D12.SurgeryRecognition.tailVec_norm_eq_one_of_norm_eq_one_and_fst_eq_zero
#print axioms Poincare.D12.SurgeryRecognition.toSpherePre
#print axioms Poincare.D12.SurgeryRecognition.toSphere_ofSphere
#print axioms Poincare.D12.SurgeryRecognition.transportedSouthDisk.eq_1
#print axioms Poincare.D12.SurgeryRecognition.upPoint
#print axioms Poincare.D12.SurgeryRecognition.upPoint_mem
#print axioms Poincare.D12.SurgeryRecognition.up_northBall
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_hamilton_field_kernel_tangent_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_matrix_example_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_so3_lap_X0_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_so3_metric_posSemidef_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.discrete_max_principle_is_scalar
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_comm_u
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_gradSq._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_second_comm_apply
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_second_comm_diag
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData._sizeOf_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.ctorIdx
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.mk.inj
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.noConfusion
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.H
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.K_antisym
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.VecField
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.cG.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.cG_self
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.double_sum_distrib
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.eq_zero_of_eq_neg_self
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.fieldInner_fieldLaplacian_expand
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gamma
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gammaX
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gamma_swap
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gradInner.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gradSq.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.hessian_symm._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_grad_hessian._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_nablaField_grad_H
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.ricciContraction
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.ricciForm_eq_sum_gamma
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.sum_swap_apply
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.w_du_coeff_fixed_j._abel_1_2
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitz_coefficient
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitz_coefficient._abel_1_5
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitzenboeck_expand._abel_1_2
#print axioms Poincare.D12.TensorMaximumBochner.KernelTangent
#print axioms Poincare.D12.TensorMaximumBochner.LeviCivitaIdentities.ricci_eq_sum_curvatureForm
#print axioms Poincare.D12.TensorMaximumBochner.So3.crossBracket._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.So3.crossLeviCivita._proof_2
#print axioms Poincare.D12.TensorMaximumBochner.So3.ricci_eq_half_metric
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric._proof_10
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric._proof_5
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric._proof_9
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.D._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.D_generator
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.Dfun.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.Dfun_smul_f
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.Poly3
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.bochner_inequality_so3
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.bracket_generator
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.dot_polyVec_basis_self
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.evalAt_X
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.gA_half_mul_two
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.lap_X0
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.nabla_self
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.polyVec._proof_2
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.rotVec
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.rotVec_expand
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.so3e1_two
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.sum_rotVec_pderiv_mul
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.dotProduct_mulVec_metricMatrix
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.idMatrix
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricForm._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricForm_apply
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_differentiableAt
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_posDef
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_zero
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.ricciFlow_equation
#print axioms Poincare.D12.TensorMaximumBochner.adjugate_posSemidef
#print axioms Poincare.D12.TensorMaximumBochner.counterexampleA_isHermitian
#print axioms Poincare.D12.TensorMaximumBochner.counterexample_kernelTangent
#print axioms Poincare.D12.TensorMaximumBochner.dotProduct_mulVec_sq
#print axioms Poincare.D12.TensorMaximumBochner.hamiltonField_kernelTangent
#print axioms Poincare.D12.TensorMaximumBochner.hasDerivAt_lambdaInv._simp_1_1
#print axioms Poincare.D12.TensorMaximumBochner.hasDerivAt_lambdaInv._simp_1_5
#print axioms Poincare.D12.TensorMaximumBochner.kernelTangent_of_feasibleDirection
#print axioms Poincare.D12.TensorMaximumBochner.lambdaInv_sq_sub
#print axioms Poincare.D12.TensorMaximumBochner.quadSelfPath
#print axioms Poincare.D12.TensorMaximumBochner.quadSelfPath_solves
#print axioms Poincare.D12.TensorMaximumBochner.staysPosSemidef_of_field
#print axioms Poincare.D12.TriangulationTopology.ConeQuot
#print axioms Poincare.D12.TriangulationTopology.DoubleDiskQuot
#print axioms Poincare.D12.TriangulationTopology.RealProjective
#print axioms Poincare.D12.TriangulationTopology.SimplexFn
#print axioms Poincare.D12.TriangulationTopology.UpperHemisphere
#print axioms Poincare.D12.TriangulationTopology.alexanderHomeo._proof_3
#print axioms Poincare.D12.TriangulationTopology.alexanderHomeo_sphereToDisk
#print axioms Poincare.D12.TriangulationTopology.antipodalIsCancelSMul
#print axioms Poincare.D12.TriangulationTopology.antipodalQuotientCovering
#print axioms Poincare.D12.TriangulationTopology.antipodalSmul_one
#print axioms Poincare.D12.TriangulationTopology.antipodal_smul_one_eq
#print axioms Poincare.D12.TriangulationTopology.clampedMap_clamp_idem
#print axioms Poincare.D12.TriangulationTopology.coneMap
#print axioms Poincare.D12.TriangulationTopology.coneMapQuot_injective
#print axioms Poincare.D12.TriangulationTopology.coneOverSphere2HomeoDisk3
#print axioms Poincare.D12.TriangulationTopology.coneQuotHomeoDisk._proof_3
#print axioms Poincare.D12.TriangulationTopology.continuousOn_diskDirection
#print axioms Poincare.D12.TriangulationTopology.continuous_coneMapQuot
#print axioms Poincare.D12.TriangulationTopology.continuous_doubleDiskMap
#print axioms Poincare.D12.TriangulationTopology.continuous_radialExtend
#print axioms Poincare.D12.TriangulationTopology.continuous_simplexConeMap
#print axioms Poincare.D12.TriangulationTopology.continuous_simplexMin
#print axioms Poincare.D12.TriangulationTopology.continuous_sphere_simplexLambda
#print axioms Poincare.D12.TriangulationTopology.continuous_upperHemisphereToDisk
#print axioms Poincare.D12.TriangulationTopology.coveringOfSimplyConnectedIsHomeo
#print axioms Poincare.D12.TriangulationTopology.diskCompactSpace
#print axioms Poincare.D12.TriangulationTopology.diskDirection._proof_1
#print axioms Poincare.D12.TriangulationTopology.diskGlueQuotCompactSpace
#print axioms Poincare.D12.TriangulationTopology.diskGlueQuotNonempty
#print axioms Poincare.D12.TriangulationTopology.diskGlueRel_transport
#print axioms Poincare.D12.TriangulationTopology.diskGlueSumHomeo_inr
#print axioms Poincare.D12.TriangulationTopology.diskToLowerHemisphere._proof_1
#print axioms Poincare.D12.TriangulationTopology.diskToUpperHemisphere
#print axioms Poincare.D12.TriangulationTopology.diskToUpperHemisphere_upperHemisphereToDisk
#print axioms Poincare.D12.TriangulationTopology.dist_subdiv_succ_le
#print axioms Poincare.D12.TriangulationTopology.doubleDiskMapQuot.eq_1
#print axioms Poincare.D12.TriangulationTopology.doubleDiskMap_mem_pos
#print axioms Poincare.D12.TriangulationTopology.doubleDiskQuotHomeoSphere._proof_2
#print axioms Poincare.D12.TriangulationTopology.eq_neg_self_of_sqrt_eq_neg_sqrt
#print axioms Poincare.D12.TriangulationTopology.esnoc'.eq_1
#print axioms Poincare.D12.TriangulationTopology.esnoc._proof_1
#print axioms Poincare.D12.TriangulationTopology.esnoc_last
#print axioms Poincare.D12.TriangulationTopology.exists_not_mem_finset_submodule_union._proof_1_2
#print axioms Poincare.D12.TriangulationTopology.hemisphere_charts_agree
#print axioms Poincare.D12.TriangulationTopology.homotopic_of_dist_le
#print axioms Poincare.D12.TriangulationTopology.idChain_one
#print axioms Poincare.D12.TriangulationTopology.interp_ne_zero
#print axioms Poincare.D12.TriangulationTopology.linePoints_le_one_of_not_mem'
#print axioms Poincare.D12.TriangulationTopology.longrun_missingSphereThreePiOneTrivial
#print axioms Poincare.D12.TriangulationTopology.loop_homotopic_segChain
#print axioms Poincare.D12.TriangulationTopology.lowerHemisphereHomeoDisk
#print axioms Poincare.D12.TriangulationTopology.lowerHemisphereToDisk._proof_1
#print axioms Poincare.D12.TriangulationTopology.lowerHemisphere_isClosed
#print axioms Poincare.D12.TriangulationTopology.norm_eq_one_iff_norm_sq_eq_one
#print axioms Poincare.D12.TriangulationTopology.norm_segment_sub_left_le
#print axioms Poincare.D12.TriangulationTopology.norm_segment_sub_left_le_two_thirds
#print axioms Poincare.D12.TriangulationTopology.one_ne_ofAdd_one
#print axioms Poincare.D12.TriangulationTopology.quotMapHomeo._proof_3
#print axioms Poincare.D12.TriangulationTopology.quotMapHomeo_mk
#print axioms Poincare.D12.TriangulationTopology.radialExtend_comp
#print axioms Poincare.D12.TriangulationTopology.range_weights_eq_simplex
#print axioms Poincare.D12.TriangulationTopology.restrictionChain._proof_2
#print axioms Poincare.D12.TriangulationTopology.restrictionChain._sunfold
#print axioms Poincare.D12.TriangulationTopology.restrictionChain.eq_def
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_homotopic_segChain
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_source._proof_1_2
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_target._proof_1_2
#print axioms Poincare.D12.TriangulationTopology.restrictionPiece._proof_3
#print axioms Poincare.D12.TriangulationTopology.restrictionPiece_id_apply
#print axioms Poincare.D12.TriangulationTopology.rpPathConnectedSpace_of_pos
#print axioms Poincare.D12.TriangulationTopology.segChain._proof_1
#print axioms Poincare.D12.TriangulationTopology.segChain._sunfold
#print axioms Poincare.D12.TriangulationTopology.segChain.eq_2
#print axioms Poincare.D12.TriangulationTopology.segChain_mem_iUnion_spans._proof_1_2
#print axioms Poincare.D12.TriangulationTopology.segPiece._proof_2
#print axioms Poincare.D12.TriangulationTopology.segmentPath
#print axioms Poincare.D12.TriangulationTopology.segmentPath._proof_3
#print axioms Poincare.D12.TriangulationTopology.segmentPath_sub_left_le_two_thirds
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeHomeoSimplex
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeMap
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeMapQuot.eq_1
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeMap_respects
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeT2Space
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryHomeoBoundaryFn._proof_1
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_eq_of_radial_repr
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_eq_of_radial_repr._simp_1_4
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_mem_of_ne_center
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_mem_of_ne_center._simp_1_4
#print axioms Poincare.D12.TriangulationTopology.simplexBoundarySet
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryToSphere_sphereToSimplexBoundary
#print axioms Poincare.D12.TriangulationTopology.simplexCenter_total
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot._proof_1
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot_injective._simp_1_3
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot_injective._simp_1_7
#print axioms Poincare.D12.TriangulationTopology.simplexConeMap_respects
#print axioms Poincare.D12.TriangulationTopology.simplexDir_last
#print axioms Poincare.D12.TriangulationTopology.simplexFnNonempty
#print axioms Poincare.D12.TriangulationTopology.simplexHomeoConeQuot
#print axioms Poincare.D12.TriangulationTopology.simplexHomeoStdSimplexFn._proof_2
#print axioms Poincare.D12.TriangulationTopology.simplexMin_attains
#print axioms Poincare.D12.TriangulationTopology.simplexMin_lt_center_of_ne_center
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_eq_of_radial_repr
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_eq_of_radial_repr._simp_1_4
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_le_one
#print axioms Poincare.D12.TriangulationTopology.simplexVertexZero
#print axioms Poincare.D12.TriangulationTopology.simplex_point_eq_center_add_norm_mul_dir
#print axioms Poincare.D12.TriangulationTopology.span_pair_ne_top
#print axioms Poincare.D12.TriangulationTopology.sphereConeHomeoSimplex
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_12
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_5
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_9
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks_hemisphere_instance._proof_2
#print axioms Poincare.D12.TriangulationTopology.spherePathConnectedSpace_of_pos._proof_1_1
#print axioms Poincare.D12.TriangulationTopology.sphereThreeSuspension
#print axioms Poincare.D12.TriangulationTopology.sphereThree_eq_sphere3
#print axioms Poincare.D12.TriangulationTopology.sphereToDisk
#print axioms Poincare.D12.TriangulationTopology.sphereToSimplexBoundary.eq_1
#print axioms Poincare.D12.TriangulationTopology.sphere_cover_isHomeo
#print axioms Poincare.D12.TriangulationTopology.sphericalSpaceFormRecognition
#print axioms Poincare.D12.TriangulationTopology.stage6Sphere_eq_sphereThree
#print axioms Poincare.D12.TriangulationTopology.subdiv.eq_1
#print axioms Poincare.D12.TriangulationTopology.subdivSpans_proper._proof_1_1
#print axioms Poincare.D12.TriangulationTopology.suspMap
#print axioms Poincare.D12.TriangulationTopology.suspMapQuot_injective
#print axioms Poincare.D12.TriangulationTopology.suspQuotHomeoSphere
#print axioms Poincare.D12.TriangulationTopology.suspQuotHomeoTopCatSphere
#print axioms Poincare.D12.TriangulationTopology.trivialization_id
#print axioms Poincare.D12.TriangulationTopology.trivialization_id._proof_4
#print axioms Poincare.D12.TriangulationTopology.trivialization_id._proof_8
#print axioms Poincare.D12.TriangulationTopology.truncToCenter_ne_zero._simp_1_1
#print axioms Poincare.D12.TriangulationTopology.upperHemisphereCompactSpace
#print axioms Poincare.D12.TriangulationTopology.upperHemisphereToDisk
#print axioms Poincare.D12.TriangulationTopology.upperHemisphere_isClosed
#print axioms Poincare.D12.TriangulationTopology.zmod2_eq_zero_or_one._proof_1_1
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.casesOn
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.mk
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.mk.noConfusion
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.rec
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.ψ
#print axioms Poincare.D12.VolumeIBP.ChartMetric.adjugate_entry_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.chart_ibp_laplacian
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density
#print axioms Poincare.D12.VolumeIBP.ChartMetric.densityNNReal_aemeasurable
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_ne_zero
#print axioms Poincare.D12.VolumeIBP.ChartMetric.det_continuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.divergence
#print axioms Poincare.D12.VolumeIBP.ChartMetric.driftLaplacian
#print axioms Poincare.D12.VolumeIBP.ChartMetric.euclideanChartMetric
#print axioms Poincare.D12.VolumeIBP.ChartMetric.euclideanChartMetric_density_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.expMetricOne._proof_3
#print axioms Poincare.D12.VolumeIBP.ChartMetric.g
#print axioms Poincare.D12.VolumeIBP.ChartMetric.grad.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse_continuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.hasCompactSupport_of_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.inner_comm
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix_mul_matrix_mul_invMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.jacobianMatrix_det
#print axioms Poincare.D12.VolumeIBP.ChartMetric.laplacian.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.matrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.matrix_mul_invMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.mk
#print axioms Poincare.D12.VolumeIBP.ChartMetric.mk.injEq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.noConfusionType
#print axioms Poincare.D12.VolumeIBP.ChartMetric.posDef
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullbackMetric
#print axioms Poincare.D12.VolumeIBP.ChartMetric.rec
#print axioms Poincare.D12.VolumeIBP.ChartMetric.riemannianMeasure_def
#print axioms Poincare.D12.VolumeIBP.ChartMetric.smooth_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.weighted_divergence_mul_exp_grad
#print axioms Poincare.D12.VolumeIBP.chartWeightedIBPStatementRestricted._proof_1
#print axioms Poincare.D12.VolumeIBP.exists_pi_Ioo_supset_compact
#print axioms Poincare.D7.HeatKernel.HeatKernelData.toCore
#print axioms Set.Icc.addNSMul.congr_simp
#print axioms _private.Poincare.D12.ComparisonGeodesics.SingularRiccati.0.Poincare.D12.ComparisonGeodesics.exp_neg_integral_le_of_normalization
#print axioms _private.Poincare.D12.ComparisonGeodesics.SingularRiccati.0.Poincare.D12.ComparisonGeodesics.exp_neg_integral_le_of_normalization._simp_1_4
#print axioms _private.Poincare.D12.ConnectionCurvature.ConformalChartModel.0.Poincare.D12.ConnectionCurvature.conformalGamma.match_1.eq_1
#print axioms _private.Poincare.D12.ConnectionCurvature.ConformalChartModel.0.Poincare.D12.ConnectionCurvature.conformalGamma.match_1.eq_5
#print axioms _private.Poincare.D12.ConnectionCurvature.ConformalChartModel.0.Poincare.D12.ConnectionCurvature.conformalGamma.match_1.splitter
#print axioms _private.Poincare.D12.HeatSemigroup.AxiomAudit.0.Poincare.D12.HeatSemigroup.AxiomAudit.heatSemigroupAuditedDeclarations
#print axioms _private.Poincare.D12.HeatSemigroup.Semigroup.0.Poincare.D12.HeatSemigroup.truncation_aestronglyMeasurable
#print axioms _private.Poincare.D12.HeatSemigroup.Semigroup.0.Poincare.D12.HeatSemigroup.truncation_tendsto
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds._simp_1_3
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds._simp_1_7
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.domBound_integrable._simp_1_4
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.fderiv_heatConv_testF_coord._simp_1_1
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.fderiv_heatConv_testF_coord._simp_1_5
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.gaussianKernel_sub_le_quarter._abel_1_2
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.sq_mul_exp_neg_mul_sq_le._simp_1_4
#print axioms _private.Poincare.D12.ParabolicLocal.Duhamel.0.Poincare.D12.ParabolicLocal.DuhamelSetup.duhamelMap_pointwise_lipschitz._abel_1_1
#print axioms _private.Poincare.D12.SurgeryRecognition.BallGluing.0.Poincare.D12.SurgeryRecognition.glueRel.match_1.eq_2
#print axioms _private.Poincare.D12.TriangulationTopology.SpherePolygonal.0.Poincare.D12.TriangulationTopology.restrictionChain.match_1.eq_1
#print axioms _private.Poincare.D12.TriangulationTopology.SphereSimplyConnected.0.Poincare.D12.TriangulationTopology.restrictionChain.match_1.eq_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampen.0.HatcherLib.CoveredPathChain.toPath.match_1.splitter
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_adjacent_collision
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_adjacent_collision._proof_1_4
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_eq_of_parity_change._proof_1_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.domino_rect_subset_ball
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.incident_cell_eq_left_or_right._proof_1_3
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.leftCell._proof_3
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.lowerCell
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.rightCell._proof_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.rightCell_touches
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.rightCell_val_eq_or_succ._proof_1_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent.match_1.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepCell.inputWord.match_1.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepCell.outputWord.match_1.eq_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepRow.rectangleOutput.match_1.eq_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepRow.rightBoundary.match_1.eq_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepStage.chainInput.match_1.splitter
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepStage.chainOutput.match_1.splitter
