import Poincare.D13.IntegratedAudit.SnapshotRoot

#print axioms HatcherLib.CoverIntersectionFundamentalGroup
#print axioms HatcherLib.CoveredLoop.path.eq_1
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition._sizeOf_1
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.casesOn
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.mk
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.mk.injEq
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.noConfusionType
#print axioms HatcherLib.CoveredPathChain._sizeOf_inst
#print axioms HatcherLib.CoveredPathChain.brecOn.go
#print axioms HatcherLib.CoveredPathChain.carrierSets._unsafe_rec
#print axioms HatcherLib.CoveredPathChain.casesOn
#print axioms HatcherLib.CoveredPathChain.current_mem_carrierSets
#print axioms HatcherLib.CoveredPathChain.decompose_loop_with_carrierSets._simp_1_2
#print axioms HatcherLib.CoveredPathChain.extend.congr_simp
#print axioms HatcherLib.CoveredPathChain.extend.noConfusion
#print axioms HatcherLib.CoveredPathChain.noConfusion
#print axioms HatcherLib.CoveredPathChain.prefixDecomposition._proof_2
#print axioms HatcherLib.CoveredPathChain.prefixDecomposition.eq_1
#print axioms HatcherLib.CoveredPathChain.prefix_loops_mem_carrierSets._simp_1_5
#print axioms HatcherLib.CoveredPathChain.single.congr_simp
#print axioms HatcherLib.CoveredPathChain.single.noConfusion
#print axioms HatcherLib.CoveredPathChain.toPath._sunfold
#print axioms HatcherLib.CoveredSubdivisionPrefix._sizeOf_1
#print axioms HatcherLib.CoveredSubdivisionPrefix.chain
#print axioms HatcherLib.CoveredSubdivisionPrefix.mk._flat_ctor
#print axioms HatcherLib.CoveredSubdivisionPrefix.mk.sizeOf_spec
#print axioms HatcherLib.CoveredSubdivisionPrefix.recOn
#print axioms HatcherLib.FreeProductWord
#print axioms HatcherLib.Path.Homotopic
#print axioms HatcherLib.PathConnectedOpenCover._sizeOf_1
#print axioms HatcherLib.PathConnectedOpenCover.casesOn
#print axioms HatcherLib.PathConnectedOpenCover.isOpen
#print axioms HatcherLib.PathConnectedOpenCover.mk.injEq
#print axioms HatcherLib.PathConnectedOpenCover.noConfusionType
#print axioms HatcherLib.PathIn
#print axioms HatcherLib.SimplyConnected
#print axioms HatcherLib.VanKampenRectangularSubdivision
#print axioms HatcherLib.VanKampenRectangularSubdivision.cellLabel
#print axioms HatcherLib.VanKampenRectangularSubdivision.horizontalCut
#print axioms HatcherLib.VanKampenRectangularSubdivision.mk
#print axioms HatcherLib.VanKampenRectangularSubdivision.mk.noConfusion
#print axioms HatcherLib.VanKampenRectangularSubdivision.rec
#print axioms HatcherLib.VanKampenRectangularSubdivision.verticalCut_mono
#print axioms HatcherLib.VanKampenSquareGrid.CellBoundaryRelation
#print axioms HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent._unsafe_rec
#print axioms HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent.eq_def
#print axioms HatcherLib.VanKampenSquareGrid._sizeOf_inst
#print axioms HatcherLib.VanKampenSquareGrid.cellBoundaryHomotopy
#print axioms HatcherLib.VanKampenSquareGrid.cellConvexHomotopy._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.cellConvexHomotopy._proof_5
#print axioms HatcherLib.VanKampenSquareGrid.cellConvexHomotopy._proof_9
#print axioms HatcherLib.VanKampenSquareGrid.cellMap._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.cellVertex
#print axioms HatcherLib.VanKampenSquareGrid.coordinateLine._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.coordinateLine_self
#print axioms HatcherLib.VanKampenSquareGrid.descendingFin.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.horizontalBasedEdgeInCell_map
#print axioms HatcherLib.VanKampenSquareGrid.horizontalCut_one
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeClassInCell.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeFactor.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeInCell._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeLoop
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdge_in_incidentCell
#print axioms HatcherLib.VanKampenSquareGrid.horizontalParameterEdge
#print axioms HatcherLib.VanKampenSquareGrid.horizontalParameterEdgeInCell
#print axioms HatcherLib.VanKampenSquareGrid.horizontalSlice
#print axioms HatcherLib.VanKampenSquareGrid.incident_label
#print axioms HatcherLib.VanKampenSquareGrid.mk.injEq
#print axioms HatcherLib.VanKampenSquareGrid.noConfusionType
#print axioms HatcherLib.VanKampenSquareGrid.rowCells
#print axioms HatcherLib.VanKampenSquareGrid.rowStage
#print axioms HatcherLib.VanKampenSquareGrid.sweepCell
#print axioms HatcherLib.VanKampenSquareGrid.sweepCell._proof_4
#print axioms HatcherLib.VanKampenSquareGrid.vertex.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.vertexConnectorInCell._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.vertexConnector_in
#print axioms HatcherLib.VanKampenSquareGrid.vertex_mem_cell
#print axioms HatcherLib.VanKampenSquareGrid.verticalCells
#print axioms HatcherLib.VanKampenSquareGrid.verticalCut_zero
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeClassInCell_eq_based
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeFactor_changeCell
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeInCell.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeLoop_in_incidentCell
#print axioms HatcherLib.VanKampenSquareGrid.verticalParameterEdge._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.verticalParameterEdgeInCell._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.verticalSlice._proof_1
#print axioms HatcherLib.VanKampenSweepCell.Composable
#print axioms HatcherLib.VanKampenSweepCell._sizeOf_1
#print axioms HatcherLib.VanKampenSweepCell.ctorIdx
#print axioms HatcherLib.VanKampenSweepCell.firstRightWord.eq_2
#print axioms HatcherLib.VanKampenSweepCell.inputWord.match_1
#print axioms HatcherLib.VanKampenSweepCell.lastLeftWord._sunfold
#print axioms HatcherLib.VanKampenSweepCell.lastLeftWord.eq_3
#print axioms HatcherLib.VanKampenSweepCell.mk._flat_ctor
#print axioms HatcherLib.VanKampenSweepCell.mk.noConfusion
#print axioms HatcherLib.VanKampenSweepCell.outputWord
#print axioms HatcherLib.VanKampenSweepCell.outputWord.eq_1
#print axioms HatcherLib.VanKampenSweepCell.outputWord.match_1
#print axioms HatcherLib.VanKampenSweepCell.right
#print axioms HatcherLib.VanKampenSweepRow.Composable
#print axioms HatcherLib.VanKampenSweepRow._sizeOf_1
#print axioms HatcherLib.VanKampenSweepRow.ctorIdx
#print axioms HatcherLib.VanKampenSweepRow.mk
#print axioms HatcherLib.VanKampenSweepRow.mk.noConfusion
#print axioms HatcherLib.VanKampenSweepRow.rec
#print axioms HatcherLib.VanKampenSweepRow.rectangleInput.eq_2
#print axioms HatcherLib.VanKampenSweepRow.rectangleOutput._unsafe_rec
#print axioms HatcherLib.VanKampenSweepRow.rectangleOutput.eq_def
#print axioms HatcherLib.VanKampenSweepRow.rightBoundary._f
#print axioms HatcherLib.VanKampenSweepRow.rightBoundary.eq_2
#print axioms HatcherLib.VanKampenSweepRow.top
#print axioms HatcherLib.VanKampenSweepStage.Composable._sunfold
#print axioms HatcherLib.VanKampenSweepStage.casesOn
#print axioms HatcherLib.VanKampenSweepStage.chainInput.match_1
#print axioms HatcherLib.VanKampenSweepStage.chainOutput._unsafe_rec
#print axioms HatcherLib.VanKampenSweepStage.chainOutput.eq_def
#print axioms HatcherLib.VanKampenSweepStage.equivalent_of_boundary_links
#print axioms HatcherLib.VanKampenSweepStage.mk.inj
#print axioms HatcherLib.VanKampenSweepStage.noConfusion
#print axioms HatcherLib.VanKampenSweepStage.recOn
#print axioms HatcherLib.VanKampenWordEquivalent.append
#print axioms HatcherLib.VanKampenWordEquivalent.insert_one
#print axioms HatcherLib.VanKampenWordMove.append_left
#print axioms HatcherLib.VanKampenWordMove.eraseOne
#print axioms HatcherLib.affinePathHomotopy
#print axioms HatcherLib.affinePathHomotopy._proof_4
#print axioms HatcherLib.changeBasepoint_bijective
#print axioms HatcherLib.coverIntersectionInclusionLeft
#print axioms HatcherLib.coverIntersectionInclusionRight
#print axioms HatcherLib.coverIntersectionToLeft
#print axioms HatcherLib.coverIntersection_maps_agree
#print axioms HatcherLib.coveredLoopProduct._sunfold
#print axioms HatcherLib.coveredLoopProduct_append_single
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_10
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_14
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_5
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_9
#print axioms HatcherLib.exists_vanKampenSquareGrid
#print axioms HatcherLib.exists_vanKampenSquareGrid._proof_1_2
#print axioms HatcherLib.exists_vanKampenSquareGrid._proof_1_7
#print axioms HatcherLib.freeGroupAbelianizationBasis
#print axioms HatcherLib.freeProductLift
#print axioms HatcherLib.fundamentalGroupProdMulEquiv
#print axioms HatcherLib.fundamentalGroup_mapOfEq_rfl
#print axioms HatcherLib.loop_decomposition_of_pathConnectedOpenCover
#print axioms HatcherLib.mulOppositeProdMulEquiv._proof_2
#print axioms HatcherLib.pathInSubtype._proof_1
#print axioms HatcherLib.pathInSubtype._proof_5
#print axioms HatcherLib.pathInSubtypeBetween._proof_1
#print axioms HatcherLib.pathInSubtypeBetween._proof_5
#print axioms HatcherLib.pathIn_subpath_of_Icc_subset
#print axioms HatcherLib.pathProduct_homotopic
#print axioms HatcherLib.piOneClass_pathProduct
#print axioms HatcherLib.subgroup_of_free_is_free
#print axioms HatcherLib.vanKampenClassOfLoopInIntersection
#print axioms HatcherLib.vanKampenFactorCoveredLoop.eq_1
#print axioms HatcherLib.vanKampenFactorRepresentative
#print axioms HatcherLib.vanKampenFactor_pathInSubtype
#print axioms HatcherLib.vanKampenMap_factorRepresentative
#print axioms HatcherLib.vanKampenNormalSubgroup_le_ker
#print axioms HatcherLib.vanKampenQuotientMap_wordEvaluation
#print axioms HatcherLib.vanKampenQuotientMulEquivOfKerEq._proof_2
#print axioms HatcherLib.vanKampenRelator_mem_ker
#print axioms HatcherLib.vanKampenWordEquivalent_cellBoundary
#print axioms HatcherLib.vanKampenWordEquivalent_map_singletons
#print axioms HatcherLib.vanKampenWordEvaluation.eq_1
#print axioms HatcherLib.vanKampenWordLoop
#print axioms HatcherLib.vanKampenWordLoop.eq_2
#print axioms HatcherLib.vanKampenWordLoop_homotopic_of_equivalent
#print axioms HatcherLib.vanKampenWordQuotientEvaluation
#print axioms HatcherLib.vanKampen_ker_le_normalSubgroup_of_factorizationsConnected
#print axioms Poincare.D11.BochnerManifold.d7_gradient_estimate_gives_model_subharmonic
#print axioms Poincare.D11.BochnerManifold.deriv_deriv_abs_deriv_eq_of_neg
#print axioms Poincare.D11.BochnerManifold.deriv_lapG
#print axioms Poincare.D11.BochnerManifold.differentiable_deriv_of_contDiff
#print axioms Poincare.D11.BochnerManifold.euclidean_radial_bochner
#print axioms Poincare.D11.BochnerManifold.flatCertificateWitness._proof_3
#print axioms Poincare.D11.BochnerManifold.flatCertificateWitness_roughLaplacian
#print axioms Poincare.D11.BochnerManifold.gradDot
#print axioms Poincare.D11.BochnerManifold.gradient_estimate_inequality
#print axioms Poincare.D11.BochnerManifold.hessSq.eq_1
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_deriv_eq._simp_1_1
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_deriv_eq._simp_1_5
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_of_pos
#print axioms Poincare.D11.BochnerManifold.jacobiSol_second_deriv_div._simp_1_1
#print axioms Poincare.D11.BochnerManifold.jacobiSol_second_deriv_div._simp_1_5
#print axioms Poincare.D11.BochnerManifold.lapG.eq_1
#print axioms Poincare.D11.BochnerManifold.modelBochnerCertificate._proof_2
#print axioms Poincare.D11.BochnerManifold.modelFlatBochnerCertificate._proof_2
#print axioms Poincare.D11.BochnerManifold.modelGradVec
#print axioms Poincare.D11.BochnerManifold.modelGradientCertificate._proof_2
#print axioms Poincare.D11.BochnerManifold.modelLap
#print axioms Poincare.D11.BochnerManifold.modelRicciTerm_eq
#print axioms Poincare.D11.BochnerManifold.model_bochner_weitzenbock
#print axioms Poincare.D11.BochnerManifold.model_flat_certificate_identity
#print axioms Poincare.D11.BochnerManifold.model_hess_norm_sq_eq_hessSq
#print axioms Poincare.D11.BochnerManifold.radial_bochner_identity
#print axioms Poincare.D11.BochnerManifold.ricTerm.eq_1
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.C_lo
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.FullInitialCondition
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore._sizeOf_inst
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.c_up_pos
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.dist
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.exists_toCore_eq_iff
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.kernel
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.mk._flat_ctor
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.mk.sizeOf_spec
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.rec
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.toCore_gaussianUpperBound
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.volume
#print axioms Poincare.D11.HeatKernelBridge.contDiffTwoSubmodule._proof_1
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_11
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_15
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_4
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_8
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_c_lo
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_fullInitialCondition_zero
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_kernel
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_volume
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelData_zero_kernel
#print axioms Poincare.D11.HeatKernelBridge.flatKernel.eq_1
#print axioms Poincare.D11.HeatKernelBridge.flatKernel_of_pos
#print axioms Poincare.D11.HeatKernelBridge.flat_exists_heatKernelData_iff
#print axioms Poincare.D11.HeatKernelBridge.laplacianLinearMap._proof_1
#print axioms Poincare.D11.HeatKernelBridge.laplacianLinearMap_apply_of_contDiff
#print axioms Poincare.D11.HeatKernelBridge.mem_contDiffTwoSubmodule._simp_1
#print axioms Poincare.D11.HeatKernelBridge.tendstoUniformlyOn_gaussianKernel_compl
#print axioms Poincare.D11.HeatKernelBridge.tendsto_rpow_neg_mul_exp_neg_div
#print axioms Poincare.D11.MaximumPrincipleTensor.BoundaryPositivityPreserving
#print axioms Poincare.D11.MaximumPrincipleTensor.Mat
#print axioms Poincare.D11.MaximumPrincipleTensor.PositivityPreserving.comp
#print axioms Poincare.D11.MaximumPrincipleTensor.PositivityPreserving.zero
#print axioms Poincare.D11.MaximumPrincipleTensor.boundaryOnlyReaction_boundary
#print axioms Poincare.D11.MaximumPrincipleTensor.eulerIterate
#print axioms Poincare.D11.MaximumPrincipleTensor.eulerStep
#print axioms Poincare.D11.MaximumPrincipleTensor.exp_shift_forward_invariance
#print axioms Poincare.D11.MaximumPrincipleTensor.le_iff_sub_posSemidef
#print axioms Poincare.D11.MaximumPrincipleTensor.negSquare.eq_1
#print axioms Poincare.D11.MaximumPrincipleTensor.not_positivityPreserving_neg
#print axioms Poincare.D11.MaximumPrincipleTensor.oneByOne_eq_zero_iff
#print axioms Poincare.D11.MaximumPrincipleTensor.posSemidef_iff_quadForm_nonneg
#print axioms Poincare.D11.MaximumPrincipleTensor.psdCone_add_mem
#print axioms Poincare.D11.MaximumPrincipleTensor.psdCone_smul_mem
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm_add
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm_eulerStep_of_nullVector
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm_smul
#print axioms Poincare.D11.MaximumPrincipleTensor.sqrtNegReaction
#print axioms Poincare.D11.MaximumPrincipleTensor.sqrtNegReaction_negSquare._simp_1_3
#print axioms Poincare.D11.ReducedVolume.EuclideanReducedVolumeAnchor._proof_1
#print axioms Poincare.D11.ReducedVolume.LMinimizer_eq_straightRay
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.casesOn
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.mk
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.mk.noConfusion
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.rec
#print axioms Poincare.D11.ReducedVolume.ReducedVolumeMonotonicityTheorem
#print axioms Poincare.D11.ReducedVolume.euclideanFlow_metric
#print axioms Poincare.D11.ReducedVolume.euclideanJacobianComparisonInterface._proof_2
#print axioms Poincare.D11.ReducedVolume.euclideanManifoldReducedVolumeInterface_dimension
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolume
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolumeCertificate._proof_2
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolumeCertificate_flow
#print axioms Poincare.D11.ReducedVolume.euclidean_jacobianComparison
#print axioms Poincare.D11.ReducedVolume.flatDeficit
#print axioms Poincare.D11.ReducedVolume.flatLExponential
#print axioms Poincare.D11.ReducedVolume.flatLIntegrand
#print axioms Poincare.D11.ReducedVolume.flatReducedLength._proof_1
#print axioms Poincare.D11.ReducedVolume.generalMonotonicityMissingDependencies_length
#print axioms Poincare.D11.ReducedVolume.heatKernelReducedDistance_eq
#print axioms Poincare.D11.ReducedVolume.heatKernelReducedDistance_zero
#print axioms Poincare.D11.ReducedVolume.minimizer_iff_eq_straightRay
#print axioms Poincare.D11.ReducedVolume.reducedVolumeIntegrand
#print axioms Poincare.D11.ReducedVolume.reducedVolumeIntegrandUnnormalized_eq
#print axioms Poincare.D11.ReducedVolume.reducedVolume_eq_one
#print axioms Poincare.D11.ReducedVolume.straightRayLPath
#print axioms Poincare.D11.ReducedVolume.straightRayVelocity_eq_gaussianVelocity
#print axioms Poincare.D11.ReducedVolume.straightRay_length
#print axioms Poincare.D11.SpectralTorus.Sobolev
#print axioms Poincare.D11.SpectralTorus.circleRep._proof_1
#print axioms Poincare.D11.SpectralTorus.coordProj._proof_1
#print axioms Poincare.D11.SpectralTorus.dirDeriv
#print axioms Poincare.D11.SpectralTorus.fact_zero_lt_one
#print axioms Poincare.D11.SpectralTorus.finConsEquiv._proof_3
#print axioms Poincare.D11.SpectralTorus.fourierMode_abs_eq_one
#print axioms Poincare.D11.SpectralTorus.fourierMode_periodic
#print axioms Poincare.D11.SpectralTorus.gradNormSq.eq_1
#print axioms Poincare.D11.SpectralTorus.innerForm._proof_1
#print axioms Poincare.D11.SpectralTorus.innerForm_stdVec
#print axioms Poincare.D11.SpectralTorus.intVec_apply
#print axioms Poincare.D11.SpectralTorus.laplacian
#print axioms Poincare.D11.SpectralTorus.laplacian_fourierMode._simp_1_2
#print axioms Poincare.D11.SpectralTorus.mFourier_ne_zero
#print axioms Poincare.D11.SpectralTorus.normSq_eq_zero_iff
#print axioms Poincare.D11.SpectralTorus.ofRealClm
#print axioms Poincare.D11.SpectralTorus.ofReal_prod
#print axioms Poincare.D11.SpectralTorus.one_add_normSq_inv_le_prod._simp_1_2
#print axioms Poincare.D11.SpectralTorus.one_add_normSq_inv_le_prod._simp_1_6
#print axioms Poincare.D11.SpectralTorus.orthonormal_mFourier_finset_sum_normSq
#print axioms Poincare.D11.SpectralTorus.parsevalUnitAddCircleIsProbabilityMeasure._proof_1
#print axioms Poincare.D11.SpectralTorus.poincareUnitAddCircleIsProbabilityMeasure
#print axioms Poincare.D11.SpectralTorus.rpow_prod_univ
#print axioms Poincare.D11.SpectralTorus.sobolevNorm.eq_1
#print axioms Poincare.D11.SpectralTorus.sobolevUnitAddCircleIsProbabilityMeasure
#print axioms Poincare.D11.SpectralTorus.sobolevWeight.eq_1
#print axioms Poincare.D11.SpectralTorus.sobolev_embedding_trigPoly
#print axioms Poincare.D11.SpectralTorus.summable_sobolevWeight_inv
#print axioms Poincare.D11.SpectralTorus.summable_sobolevWeight_inv._simp_1_4
#print axioms Poincare.D11.SpectralTorus.summable_weight_int
#print axioms Poincare.D11.SpectralTorus.torusDeriv_mFourier
#print axioms Poincare.D11.SpectralTorus.torusFourier._abel_1
#print axioms Poincare.D11.SpectralTorus.torusLaplacian
#print axioms Poincare.D11.SpectralTorus.torusQuotHom
#print axioms Poincare.D11.SpectralTorus.torusQuotHom_apply
#print axioms Poincare.D11.SpectralTorus.torusToUnit._proof_1
#print axioms Poincare.D11.SpectralTorus.trigPoly._proof_1
#print axioms Poincare.D11.SpectralTorus.trigPolyDerivL2
#print axioms Poincare.D11.SpectralTorus.trigPolyDerivL2._proof_4
#print axioms Poincare.D11.SpectralTorus.trigPolyDerivL2.eq_1
#print axioms Poincare.D11.SpectralTorus.trigPolyL2._proof_2
#print axioms Poincare.D11.SpectralTorus.trigPolyL2._proof_6
#print axioms Poincare.D11.SpectralTorus.trigPoly_gradNormSq
#print axioms Poincare.D11.SpectralTorus.trigPoly_pointwise_le
#print axioms Poincare.D11.SpectralTorus.twoPiI.eq_1
#print axioms Poincare.D11.SpectralTorus.unitToTorus_torusToUnit
#print axioms Poincare.D11.WarpedProductModel.jacobi_ode
#print axioms Poincare.D11.WarpedProductModel.rec
#print axioms Poincare.D11.ballVolume.eq_1
#print axioms Poincare.D11.ballVolume_ratio_deriv_nonpos
#print axioms Poincare.D11.continuousOn_ballVolume
#print axioms Poincare.D11.differentiableOn_ballVolume
#print axioms Poincare.D11.divergenceLaplacian
#print axioms Poincare.D11.divergenceLaplacian_id_jacobiSol
#print axioms Poincare.D11.jacobiSol_nonneg_of_le
#print axioms Poincare.D11.laplacianComparison_jacobiDeriv
#print axioms Poincare.D11.modelFlatMetric_symm
#print axioms Poincare.D11.modelSphereMetric
#print axioms Poincare.D11.polarMetric._proof_1
#print axioms Poincare.D11.polarMetric_nonneg
#print axioms Poincare.D11.polarMetric_symm
#print axioms Poincare.D11.radialLaplacian_id_le_of_le
#print axioms Poincare.D11.warpedProductModel_jacobiSolSphere
#print axioms Poincare.D11.wronskian_le_zero
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.eq_secondDeriv
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.mk._flat_ctor
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiEqOn
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiEqOn.hasDerivAt_m
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiEqOn.recOn
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiLeOn.continuousOn_m
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiLeOn.mk._flat_ctor
#print axioms Poincare.D12.ComparisonGeodesics.areaRatio_hasDerivAt
#print axioms Poincare.D12.ComparisonGeodesics.areaRatio_hasDerivAt._simp_1_4
#print axioms Poincare.D12.ComparisonGeodesics.bishopGromovVolumeRatio
#print axioms Poincare.D12.ComparisonGeodesics.bishopGromov_volume_le._simp_1_3
#print axioms Poincare.D12.ComparisonGeodesics.bishopGromov_volume_le._simp_1_7
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelA_hasDerivAt
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelA_zero
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelM_hasDerivAt
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_singular_comparison
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_volume._simp_1_2
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_volume._simp_1_6
#print axioms Poincare.D12.ComparisonGeodesics.hasDerivAtR_id
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv.eq_1
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_hasDerivAt._simp_1_3
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_hasDerivAt._simp_1_7
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_le_of_le._simp_1_3
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_le_of_le._simp_1_7
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume_hasDerivAt
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume_numerator_le_zero._simp_1_3
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume_numerator_le_zero._simp_1_7
#print axioms Poincare.D12.ComparisonGeodesics.riccati_ge_of_initial
#print axioms Poincare.D12.ComparisonGeodesics.sign_constant_of_no_zero
#print axioms Poincare.D12.ComparisonGeodesics.solution_le_of_initial._simp_1_4
#print axioms Poincare.D12.ComparisonGeodesics.solution_le_of_initial._simp_1_8
#print axioms Poincare.D12.ComparisonGeodesics.volumeRatio_antitone
#print axioms Poincare.D12.ComparisonGeodesics.wronskian_continuousOn
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.christoffel
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.christoffelLower.eq_1
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.christoffel_raised_contraction_first._simp_1_2
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.d_symm
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.g_symm
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.gram_mul_gInv_delta_first
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.mk
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.mk.injEq
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.noConfusionType
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D._proof_1
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D._proof_5
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_christoffel._simp_1_4
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_christoffel._simp_1_8
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_metricCompatible
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData._sizeOf_inst
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.christoffelFamily
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.christoffelFamily_symm
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.dFamily_smooth
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.formField.eq_1
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.gInv_smooth
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.g_symm
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.mk
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.mk.noConfusion
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.nabla_apply
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.nabla_smul
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.rec
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.cross_e2_e0
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3._proof_10
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3._proof_5
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3._proof_9
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3Lie._proof_2
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3Metric._proof_2
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3Metric.eq_1
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3_curvature_nonzero
#print axioms Poincare.D12.ConnectionCurvature.VectorField
#print axioms Poincare.D12.ConnectionCurvature.adTranspose._proof_3
#print axioms Poincare.D12.ConnectionCurvature.adTranspose._proof_7
#print axioms Poincare.D12.ConnectionCurvature.adTranspose_apply_form_swap
#print axioms Poincare.D12.ConnectionCurvature.chartAbstractConnection._proof_2
#print axioms Poincare.D12.ConnectionCurvature.chartCurvatureOperator_apply
#print axioms Poincare.D12.ConnectionCurvature.conformalG
#print axioms Poincare.D12.ConnectionCurvature.conformalGInv.eq_1
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma.eq_1
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma.eq_5
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma.match_1
#print axioms Poincare.D12.ConnectionCurvature.conformalPointwise._proof_1
#print axioms Poincare.D12.ConnectionCurvature.conformalPointwise._proof_5
#print axioms Poincare.D12.ConnectionCurvature.conformal_curvature_nonzero
#print axioms Poincare.D12.ConnectionCurvature.curvatureEndo
#print axioms Poincare.D12.ConnectionCurvature.curvatureEndo._proof_4
#print axioms Poincare.D12.ConnectionCurvature.dFormOf.eq_1
#print axioms Poincare.D12.ConnectionCurvature.formOf._proof_1
#print axioms Poincare.D12.ConnectionCurvature.formOf._proof_5
#print axioms Poincare.D12.ConnectionCurvature.formOf._proof_9
#print axioms Poincare.D12.ConnectionCurvature.form_nabla_second_eq_sum
#print axioms Poincare.D12.ConnectionCurvature.meanLeviCivitaData._proof_1
#print axioms Poincare.D12.ConnectionCurvature.milnorConnection._proof_1
#print axioms Poincare.D12.ConnectionCurvature.milnorConnection_apply
#print axioms Poincare.D12.ConnectionCurvature.milnorConnection_torsionFree
#print axioms Poincare.D12.ConnectionCurvature.nablaOf._proof_1
#print axioms Poincare.D12.ConnectionCurvature.nablaOf._proof_5
#print axioms Poincare.D12.ConnectionCurvature.nablaOf._proof_9
#print axioms Poincare.D12.ConnectionCurvature.riemannComp
#print axioms Poincare.D12.ConnectionCurvature.sum_four_reorder
#print axioms Poincare.D12.EntropyVariation.Euc
#print axioms Poincare.D12.EntropyVariation.FDissipationCorrected_nonneg
#print axioms Poincare.D12.EntropyVariation.fDerivativeCorrected_at_of_pointwise
#print axioms Poincare.D12.EntropyVariation.fflowEntropyData._proof_1
#print axioms Poincare.D12.EntropyVariation.fflowEntropyData._proof_5
#print axioms Poincare.D12.EntropyVariation.fflowGradSq._proof_1
#print axioms Poincare.D12.EntropyVariation.fflowMetricFlow_consistency
#print axioms Poincare.D12.EntropyVariation.fflowScaleInv
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipationCorrected_value._simp_1_3
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipationCorrected_value._simp_1_7
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipation_value
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipation_value._simp_1_6
#print axioms Poincare.D12.EntropyVariation.fflow_F_deriv_pos
#print axioms Poincare.D12.EntropyVariation.fflow_F_strictMonoOn
#print axioms Poincare.D12.EntropyVariation.fflow_F_strictMonoOn._simp_1_4
#print axioms Poincare.D12.EntropyVariation.fflow_F_value
#print axioms Poincare.D12.EntropyVariation.fflow_F_value._simp_1_5
#print axioms Poincare.D12.EntropyVariation.fflow_corrected_FDerivative_on_domain
#print axioms Poincare.D12.EntropyVariation.fflow_integrated_variation_eq_dissipation
#print axioms Poincare.D12.EntropyVariation.fflow_rho_deriv_zero
#print axioms Poincare.D12.EntropyVariation.fflow_riccHess_justified
#print axioms Poincare.D12.EntropyVariation.fflow_variation_eq_two_riccHess_of_normSq_eq._simp_1_1
#print axioms Poincare.D12.EntropyVariation.fflow_variation_eq_two_riccHess_of_normSq_eq._simp_1_5
#print axioms Poincare.D12.EntropyVariation.fflow_variation_integral._simp_1_1
#print axioms Poincare.D12.EntropyVariation.fflow_variation_integral._simp_1_5
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_F_of_pointwise
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_fflowGradSq._simp_1_3
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_fflowGradSq._simp_1_7
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_neg_mul_const
#print axioms Poincare.D12.EntropyVariation.integrable_exp_neg_mul_normSq
#print axioms Poincare.D12.EntropyVariation.integrable_shrinkerWDissipationDensity_mul
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_exp_neg_mul._simp_1_3
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_exp_neg_mul._simp_1_7
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_gaussianKernel._simp_1_3
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_gaussianKernel._simp_1_7
#print axioms Poincare.D12.EntropyVariation.normSq_exp_neg_mul_le._simp_1_2
#print axioms Poincare.D12.EntropyVariation.normSq_exp_neg_mul_le._simp_1_6
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData._proof_1
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData._proof_5
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipationCorrected_value._simp_1_10
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipationCorrected_value._simp_1_7
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipation_value
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipation_value._simp_1_6
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_F_value
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_F_value._simp_1_5
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_W_value
#print axioms Poincare.D12.EntropyVariation.shrinkerFpot.eq_1
#print axioms Poincare.D12.EntropyVariation.shrinkerRiccHess
#print axioms Poincare.D12.EntropyVariation.shrinkerWDissipationDensity._proof_1
#print axioms Poincare.D12.EntropyVariation.shrinkerWOfTau._proof_1
#print axioms Poincare.D12.EntropyVariation.shrinker_W_derivative_identity
#print axioms Poincare.D12.EntropyVariation.shrinker_riccHess_justified._simp_1_2
#print axioms Poincare.D12.EntropyVariation.shrinker_riccHess_justified._simp_1_6
#print axioms Poincare.D12.GeometricCompactness.E2
#print axioms Poincare.D12.GeometricCompactness.canonicalNeighborhoodFrontier_iff
#print axioms Poincare.D12.GeometricCompactness.cover_transfer_of_ghDist
#print axioms Poincare.D12.GeometricCompactness.curvatureBoundImpliesUniformCovers_iff
#print axioms Poincare.D12.GeometricCompactness.ghDist_congr_left
#print axioms Poincare.D12.GeometricCompactness.gh_subseq_of_uniformCovers
#print axioms Poincare.D12.GeometricCompactness.gridFamily_totallyBounded
#print axioms Poincare.D12.GeometricCompactness.gridSet
#print axioms Poincare.D12.GeometricCompactness.gridSpace_diam_le
#print axioms Poincare.D12.GeometricCompactness.grid_gh_tendsto_square
#print axioms Poincare.D12.GeometricCompactness.instGridSpaceCompactSpace
#print axioms Poincare.D12.GeometricCompactness.instSquareSpaceCompactSpace
#print axioms Poincare.D12.GeometricCompactness.isCompact_unitSquare
#print axioms Poincare.D12.GeometricCompactness.mk2.eq_1
#print axioms Poincare.D12.GeometricCompactness.squareSpace
#print axioms Poincare.D12.GeometricCompactness.square_grid_dense._simp_1_3
#print axioms Poincare.D12.GeometricCompactness.square_grid_dense._simp_1_7
#print axioms Poincare.D12.GeometricCompactness.unitSquare
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass._sizeOf_1
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.cls_continuous
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.continuousCompactSupportClass._proof_2
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.continuousIntegrableClass._proof_2
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.mk._flat_ctor
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.mk.sizeOf_spec
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.recOn
#print axioms Poincare.D12.HeatDomain.WeakInitialConditionFor.of_integrableClass_of_ccClass
#print axioms Poincare.D12.HeatDomain.bump_mem_ccClass
#print axioms Poincare.D12.HeatDomain.bump_weakInitialConditionFor_ccClass
#print axioms Poincare.D12.HeatDomain.fastFunction
#print axioms Poincare.D12.HeatDomain.flatHeatKernelCore_weakInitialConditionFor_ccClass
#print axioms Poincare.D12.HeatDomain.halfspace_eq_box
#print axioms Poincare.D12.HeatDomain.measurableSet_halfspace_fn
#print axioms Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel._simp_1_2
#print axioms Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel._simp_1_6
#print axioms Poincare.D12.HeatDomain.not_fullInitialCondition_flat_of_pos
#print axioms Poincare.D12.HeatDomain.punitHeatKernelData_toCore_weakInitialCondition
#print axioms Poincare.D12.HeatDomain.toHeatKernelData_of_weak_compact_finiteMeasure_toCore
#print axioms Poincare.D12.HeatDomain.volume_set_norm_ge_eq_top
#print axioms Poincare.D12.HeatSemigroup.CompactManifoldHeatKernelCoreObligation
#print axioms Poincare.D12.HeatSemigroup.CompactManifoldSmoothingObligation
#print axioms Poincare.D12.HeatSemigroup.StrongContinuityBoundedContinuousObligation
#print axioms Poincare.D12.HeatSemigroup.differentiable_heatOperator
#print axioms Poincare.D12.HeatSemigroup.gaussianKernelFDerivCLM._proof_1
#print axioms Poincare.D12.HeatSemigroup.gaussianKernelFDerivCLM_apply
#print axioms Poincare.D12.HeatSemigroup.gaussianKernel_sub_le_prefactor
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM._proof_1
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_apply._simp_1_2
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_apply._simp_1_6
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_norm_le
#print axioms Poincare.D12.HeatSemigroup.heatOperator._proof_2
#print axioms Poincare.D12.HeatSemigroup.heatOperatorBCF._proof_2
#print axioms Poincare.D12.HeatSemigroup.heatOperatorBCF_comp_swap
#print axioms Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator
#print axioms Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator_of_bounded_fun
#print axioms Poincare.D12.HeatSemigroup.heatOperator_eq_integral_sub
#print axioms Poincare.D12.HeatSemigroup.heatOperator_gaussianKernel_L1
#print axioms Poincare.D12.HeatSemigroup.heatOperator_gaussianKernel_pos
#print axioms Poincare.D12.HeatSemigroup.heatOperator_lintegral_enorm_le
#print axioms Poincare.D12.HeatSemigroup.heatOperator_smul
#print axioms Poincare.D12.HeatSemigroup.heatOperator_zero
#print axioms Poincare.D12.HeatSemigroup.heatSmoothingBoundConst._proof_2
#print axioms Poincare.D12.HeatSemigroup.integrable_heatSmoothingBound
#print axioms Poincare.D12.HeatSemigroup.lintegral_enorm_heatKernelProduct_le
#print axioms Poincare.D12.HeatSemigroup.one_add_norm_sq_mul_exp_neg_le._simp_1_1
#print axioms Poincare.D12.HeatSemigroup.one_add_norm_sq_mul_exp_neg_le._simp_1_5
#print axioms Poincare.D12.HeatSemigroup.tendsto_integral_abs_gaussianKernel_sub_of_seq._simp_1_1
#print axioms Poincare.D12.KappaVariational.ClosureRecord.casesOn
#print axioms Poincare.D12.KappaVariational.ClosureRecord.downstreamUseDecl
#print axioms Poincare.D12.KappaVariational.ClosureRecord.mk.inj
#print axioms Poincare.D12.KappaVariational.ClosureRecord.noConfusion
#print axioms Poincare.D12.KappaVariational.ClosureRecord.recOn
#print axioms Poincare.D12.KappaVariational.constantCurvatureFlow._proof_1
#print axioms Poincare.D12.KappaVariational.constantCurvatureFlow._proof_5
#print axioms Poincare.D12.KappaVariational.constantCurvatureLMinimizerExistence
#print axioms Poincare.D12.KappaVariational.constantCurvatureLPath._proof_3
#print axioms Poincare.D12.KappaVariational.constantCurvatureLPath._proof_7
#print axioms Poincare.D12.KappaVariational.constantCurvatureReducedLengthData.eq_1
#print axioms Poincare.D12.KappaVariational.constantCurvature_length_le
#print axioms Poincare.D12.KappaVariational.gaussianKappaNoncollapsing_of_ballVolumeComparison
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolume._proof_2
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeCertificate._proof_2
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeCertificate_volume
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeDensity_ne_zero
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeDensity_two_half_zero
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeViaL_eq_gaussianReducedVolume
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolume_monotoneOn_and_antitoneOn
#print axioms Poincare.D12.KappaVariational.gaussianVecTau._proof_1
#print axioms Poincare.D12.KappaVariational.gaussianVecTau_def
#print axioms Poincare.D12.KappaVariational.integral_gaussianKernel_tau
#print axioms Poincare.D12.KappaVariational.integral_gaussianVecTau_eq_rpow
#print axioms Poincare.D12.KappaVariational.kappaVariationalClosures
#print axioms Poincare.D12.KappaVariational.kappaVariationalRemainingDependencies.eq_1
#print axioms Poincare.D12.KappaVariational.ncf12ModelClosure.eq_1
#print axioms Poincare.D12.KappaVariational.rlv10Statement
#print axioms Poincare.D12.KappaVariational.rpow_three_halves_eq_mul_sqrt
#print axioms Poincare.D12.KappaVariational.toGaussianPath._proof_3
#print axioms Poincare.D12.KappaVariational.toGaussianPath._proof_7
#print axioms Poincare.D12.ParabolicLocal.BUCf._sizeOf_1
#print axioms Poincare.D12.ParabolicLocal.BUCf.ctorIdx
#print axioms Poincare.D12.ParabolicLocal.BUCf.ext_iff
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_2
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_6
#print axioms Poincare.D12.ParabolicLocal.BUCf.instCoeBUCnBCFn
#print axioms Poincare.D12.ParabolicLocal.BUCf.instModuleRealBUCn._proof_1
#print axioms Poincare.D12.ParabolicLocal.BUCf.instModuleRealBUCn._proof_5
#print axioms Poincare.D12.ParabolicLocal.BUCf.instNormedAddCommGroupBUCn
#print axioms Poincare.D12.ParabolicLocal.BUCf.instNormedAddCommGroupBUCn._proof_4
#print axioms Poincare.D12.ParabolicLocal.BUCf.instSMulRealBUCn._proof_1
#print axioms Poincare.D12.ParabolicLocal.BUCf.mk._flat_ctor
#print axioms Poincare.D12.ParabolicLocal.BUCf.mk.noConfusion
#print axioms Poincare.D12.ParabolicLocal.BUCf.norm_coe_le_norm
#print axioms Poincare.D12.ParabolicLocal.BUCf.rec
#print axioms Poincare.D12.ParabolicLocal.BUCf.val
#print axioms Poincare.D12.ParabolicLocal.BUCf.val_smul
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.S
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.casesOn
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.clampSubtype._proof_1
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.contractionConstant
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.duhamelIntegrand_continuous
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.duhamelMap.congr_simp
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.duhamelMap_pointwise_lipschitz
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.extendToInterval_apply
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mildSolution
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mildSolution_initial
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mk._flat_ctor
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mk.noConfusion
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.rec
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.solutionSpace_nonempty
#print axioms Poincare.D12.ParabolicLocal.abs_mul_exp_neg_mul_sq_le
#print axioms Poincare.D12.ParabolicLocal.arctanF
#print axioms Poincare.D12.ParabolicLocal.arctanF_not_additive
#print axioms Poincare.D12.ParabolicLocal.bucConst.eq_1
#print axioms Poincare.D12.ParabolicLocal.bucHeatOperator._proof_3
#print axioms Poincare.D12.ParabolicLocal.bucHeatOperator.eq_1
#print axioms Poincare.D12.ParabolicLocal.coordCLM
#print axioms Poincare.D12.ParabolicLocal.derivativeLossBarrier
#print axioms Poincare.D12.ParabolicLocal.deturckSymbol_quadratic
#print axioms Poincare.D12.ParabolicLocal.domBound.congr_simp
#print axioms Poincare.D12.ParabolicLocal.existsUnique_heatMildSolution
#print axioms Poincare.D12.ParabolicLocal.gaussianKernel_sub_hasFDerivAt
#print axioms Poincare.D12.ParabolicLocal.gaussianS._proof_1
#print axioms Poincare.D12.ParabolicLocal.gaussianS_add
#print axioms Poincare.D12.ParabolicLocal.gaussianS_of_zero
#print axioms Poincare.D12.ParabolicLocal.gaussianS_val_of_ne_zero
#print axioms Poincare.D12.ParabolicLocal.gaussianSetup.congr_simp
#print axioms Poincare.D12.ParabolicLocal.heatConv.eq_1
#print axioms Poincare.D12.ParabolicLocal.heatConvPoint._proof_2
#print axioms Poincare.D12.ParabolicLocal.heatConvPos
#print axioms Poincare.D12.ParabolicLocal.heatConvPos.eq_1
#print axioms Poincare.D12.ParabolicLocal.heatConv_apply_translated._abel_1_1
#print axioms Poincare.D12.ParabolicLocal.heatConv_nonneg
#print axioms Poincare.D12.ParabolicLocal.heatConv_of_pos
#print axioms Poincare.D12.ParabolicLocal.heatConv_uniformContinuous
#print axioms Poincare.D12.ParabolicLocal.heatMildSolution_duhamel_eq
#print axioms Poincare.D12.ParabolicLocal.heatOperator
#print axioms Poincare.D12.ParabolicLocal.heatOperatorCLM
#print axioms Poincare.D12.ParabolicLocal.integrable_exp_neg_mul_normSq
#print axioms Poincare.D12.ParabolicLocal.jointContinuous_of_absSemigroup._abel_1_1
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrand
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv._proof_2
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv._proof_6
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv_zero_integrable
#print axioms Poincare.D12.ParabolicLocal.linearCandidate.eq_1
#print axioms Poincare.D12.ParabolicLocal.linearCandidateSolution._proof_3
#print axioms Poincare.D12.ParabolicLocal.linearCandidate_isFixedPt._simp_1_3
#print axioms Poincare.D12.ParabolicLocal.linearCandidate_isFixedPt._simp_1_7
#print axioms Poincare.D12.ParabolicLocal.linearHeat_example
#print axioms Poincare.D12.ParabolicLocal.lipschitzWith_arctan
#print axioms Poincare.D12.ParabolicLocal.mildToClassicalBridge._proof_3
#print axioms Poincare.D12.ParabolicLocal.quasilinearRicciDeTurckBarrier
#print axioms Poincare.D12.ParabolicLocal.sq_mul_exp_neg_mul_sq_le
#print axioms Poincare.D12.ParabolicLocal.squareF._proof_3
#print axioms Poincare.D12.ParabolicLocal.testF._proof_1
#print axioms Poincare.D12.ParabolicLocal.valCLM
#print axioms Poincare.D12.ParabolicLocal.valCLM._proof_4
#print axioms Poincare.D12.SemanticLedger.R_sq
#print axioms Poincare.D12.SemanticLedger.gaussianKernelXY._proof_2
#print axioms Poincare.D12.SemanticLedger.integrand_continuous
#print axioms Poincare.D12.SemanticLedger.integrand_not_integrable
#print axioms Poincare.D12.SemanticLedger.lowerConstant_pos
#print axioms Poincare.D12.SemanticLedger.tendsto_testFunction_atTop
#print axioms Poincare.D12.SemanticLedger.testFunction_zero
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic._simp_1_3
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic._simp_1_7
#print axioms Poincare.D12.SpectralSobolev.heatCoeffs._proof_1
#print axioms Poincare.D12.SpectralSobolev.heatCoeffs_apply
#print axioms Poincare.D12.SpectralSobolev.heatEvolve.eq_1
#print axioms Poincare.D12.SpectralSobolev.heatEvolve_tendsto_self
#print axioms Poincare.D12.SpectralSobolev.heatWeight._proof_1
#print axioms Poincare.D12.SpectralSobolev.heatWeight_lt_one_of_pos
#print axioms Poincare.D12.SpectralSobolev.heatWeight_zero
#print axioms Poincare.D12.SpectralSobolev.norm_cos_le_one
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger._simp_1_4
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger._simp_1_8
#print axioms Poincare.D12.SpectralSobolev.sq_eigenvalue_pos
#print axioms Poincare.D12.SpectralSobolev.sq_norm_eigenvalue._simp_1_2
#print axioms Poincare.D12.SpectralSobolev.sq_norm_eigenvalue._simp_1_6
#print axioms Poincare.D12.SpectralSobolev.summable_sq_heatCoeff
#print axioms Poincare.D12.SurgeryRecognition.ConnectedSumDecomposition.mkV2._proof_1
#print axioms Poincare.D12.SurgeryRecognition.ConnectedSumDecompositionV2.mk._flat_ctor
#print axioms Poincare.D12.SurgeryRecognition.ConnectedSumDecompositionV2.sumHomeo
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition._sizeOf_inst
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.finiteExtinction
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.mk.injEq
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.surgeryExistence
#print axioms Poincare.D12.SurgeryRecognition.R4
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.casesOn
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.mk.inj
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.recOn
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2._sizeOf_inst
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.mk
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.mk.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.rec
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.vanKampen
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.casesOn
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.mk.inj
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.spaceForm
#print axioms Poincare.D12.SurgeryRecognition.S2
#print axioms Poincare.D12.SurgeryRecognition.S3Set_eq
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.casesOn
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.free
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.instMulAction
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.mk.injEq
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.noConfusionType
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceFormFiberEquivGroup
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceForm_monodromy_transitive
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum._sizeOf_1
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.mk
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.mk.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.rec
#print axioms Poincare.D12.SurgeryRecognition.antipodal
#print axioms Poincare.D12.SurgeryRecognition.antipodalGroup_card
#print axioms Poincare.D12.SurgeryRecognition.antipodalModel_nontrivial
#print axioms Poincare.D12.SurgeryRecognition.antipodalVec.eq_1
#print axioms Poincare.D12.SurgeryRecognition.antipodal_fiber_equiv
#print axioms Poincare.D12.SurgeryRecognition.antipodal_two_sheets
#print axioms Poincare.D12.SurgeryRecognition.ballOrigin
#print axioms Poincare.D12.SurgeryRecognition.connectSumRel
#print axioms Poincare.D12.SurgeryRecognition.connectedSum
#print axioms Poincare.D12.SurgeryRecognition.consVec3_continuous
#print axioms Poincare.D12.SurgeryRecognition.doubleBallHomeoSphere
#print axioms Poincare.D12.SurgeryRecognition.downPoint_continuous
#print axioms Poincare.D12.SurgeryRecognition.downS3
#print axioms Poincare.D12.SurgeryRecognition.down_continuous
#print axioms Poincare.D12.SurgeryRecognition.equator
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_10
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_4
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_8
#print axioms Poincare.D12.SurgeryRecognition.finiteFreeOrbit_isQuotientCoveringMap
#print axioms Poincare.D12.SurgeryRecognition.glueRel.eq_3
#print axioms Poincare.D12.SurgeryRecognition.glue_eq
#print axioms Poincare.D12.SurgeryRecognition.height_sphereBallPart_eq_neg_fst_of_nonpos
#print axioms Poincare.D12.SurgeryRecognition.hemiGlueRel_equiv
#print axioms Poincare.D12.SurgeryRecognition.instContinuousConstSMulAntipodalGroupS3
#print axioms Poincare.D12.SurgeryRecognition.instSMulAntipodalGroupS3
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum._proof_2
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum._proof_6
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum.match_1
#print axioms Poincare.D12.SurgeryRecognition.northBall
#print axioms Poincare.D12.SurgeryRecognition.northBall_up
#print axioms Poincare.D12.SurgeryRecognition.northHemisphereHomeo._proof_1
#print axioms Poincare.D12.SurgeryRecognition.northPole
#print axioms Poincare.D12.SurgeryRecognition.ofSphere_continuous
#print axioms Poincare.D12.SurgeryRecognition.openBallInBall.eq_1
#print axioms Poincare.D12.SurgeryRecognition.puncturedHomeo._proof_3
#print axioms Poincare.D12.SurgeryRecognition.puncturedHomeo._proof_7
#print axioms Poincare.D12.SurgeryRecognition.quotientHomeoOfSubsingleton
#print axioms Poincare.D12.SurgeryRecognition.quotientHomeoOfSubsingleton._proof_4
#print axioms Poincare.D12.SurgeryRecognition.quotientMapHomeo._proof_2
#print axioms Poincare.D12.SurgeryRecognition.quotientMapHomeo._proof_6
#print axioms Poincare.D12.SurgeryRecognition.southBall
#print axioms Poincare.D12.SurgeryRecognition.southHemisphereHomeo
#print axioms Poincare.D12.SurgeryRecognition.southPole._proof_1
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo._proof_2
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo._proof_6
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo.eq_1
#print axioms Poincare.D12.SurgeryRecognition.sphere2ToBall_continuous
#print axioms Poincare.D12.SurgeryRecognition.sphere2_norm_eq_one_of_mem._simp_1_1
#print axioms Poincare.D12.SurgeryRecognition.sphereBallPart_continuous
#print axioms Poincare.D12.SurgeryRecognition.sphereConnectSum_transported
#print axioms Poincare.D12.SurgeryRecognition.sphericalPieceRecognition_expanded
#print axioms Poincare.D12.SurgeryRecognition.stage6Target_of_v2decomposition
#print axioms Poincare.D12.SurgeryRecognition.tailVec_consVec3
#print axioms Poincare.D12.SurgeryRecognition.toSphere
#print axioms Poincare.D12.SurgeryRecognition.toSpherePre_respects
#print axioms Poincare.D12.SurgeryRecognition.toSphere_origin_second
#print axioms Poincare.D12.SurgeryRecognition.up
#print axioms Poincare.D12.SurgeryRecognition.upPoint_continuous
#print axioms Poincare.D12.SurgeryRecognition.up_injective
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_adjugate_posSemidef_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_kernel_tangent_necessary_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_so3_bochner_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_so3_metric_extinction_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_so3_ricci_term_audited
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_H_expand
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_expand
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_one
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_second_comm_apply._abel_1_2
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.bracket_deriv
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.mk
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.mk.noConfusion
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.rec
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.H_expand
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.K_antisym._abel_1_2
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.bochner_metric_half
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.cG_antisym._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.curvatureForm_as_gamma
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.eField.congr_simp
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.fieldInner.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.fieldLaplacian
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gamma._proof_2
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gammaX_swap
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gradField.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gradLapField.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.hessSq.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.lap
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_grad_coeff
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_metric._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_nabla_grad_H._abel_1_2
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.ricciForm
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.sum_gammaX_bilin_pair._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.ui._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.w_du_pair_fixed_j
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitz_coefficient._abel_1_2
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitzenboeck_expand
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitzenboeck_half._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.LeviCivitaIdentities.curvatureForm_last_pair_skew
#print axioms Poincare.D12.TensorMaximumBochner.So3.Vec3
#print axioms Poincare.D12.TensorMaximumBochner.So3.crossLeviCivita
#print axioms Poincare.D12.TensorMaximumBochner.So3.crossMetricSkew
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric._proof_3
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric._proof_7
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric_form
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.D._proof_3
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.D_rotVec
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.Dfun_add_f
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.Dlin
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.bochner_identity_so3_curvature
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.bochner_strict_at_e1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.crossDerivation._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.evalAt
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.evalAt_hessSq_nonneg
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.gradSq_X0_at_e1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.laplacian_gradSq_nonneg_of_harmonic
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.polyVec
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.ricciContraction_so3
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.rotVec.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.so3e1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.stdMetric_basis_apply
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.xVec
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.dotProduct_mulVec_smul_one
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.idMatrix_as_matrix
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricForm._proof_3
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricForm_nonneg
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_at_one
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_isHermitian
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_posSemidef_zero
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.negIdMatrix.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.StrictKernelTangent
#print axioms Poincare.D12.TensorMaximumBochner.counterexampleA
#print axioms Poincare.D12.TensorMaximumBochner.counterexampleN
#print axioms Poincare.D12.TensorMaximumBochner.counterexample_not_feasible
#print axioms Poincare.D12.TensorMaximumBochner.hamiltonField
#print axioms Poincare.D12.TensorMaximumBochner.hamiltonField_not_strengthened
#print axioms Poincare.D12.TensorMaximumBochner.hasDerivAt_lambdaInv._simp_1_3
#print axioms Poincare.D12.TensorMaximumBochner.hasDerivAt_lambdaInv._simp_1_7
#print axioms Poincare.D12.TensorMaximumBochner.lambdaInv
#print axioms Poincare.D12.TensorMaximumBochner.nonneg_of_nonneg_init_of_deriv_nonneg_on_nonpos
#print axioms Poincare.D12.TensorMaximumBochner.quadSelfPath_hermitian
#print axioms Poincare.D12.TensorMaximumBochner.quadSelfSquareSub
#print axioms Poincare.D12.TensorMaximumBochner.staysPosSemidef_of_tangent_Icc
#print axioms Poincare.D12.TriangulationTopology.DiskGlueQuot
#print axioms Poincare.D12.TriangulationTopology.LowerHemisphere
#print axioms Poincare.D12.TriangulationTopology.SimplexBoundaryCone
#print axioms Poincare.D12.TriangulationTopology.SuspCyl
#print axioms Poincare.D12.TriangulationTopology.alexanderHomeo._proof_1
#print axioms Poincare.D12.TriangulationTopology.alexanderHomeo_eq_refl_iff
#print axioms Poincare.D12.TriangulationTopology.alexanderHomeo_zero
#print axioms Poincare.D12.TriangulationTopology.antipodalMulAction._proof_1
#print axioms Poincare.D12.TriangulationTopology.antipodalSmul.eq_1
#print axioms Poincare.D12.TriangulationTopology.antipodal_mul_self
#print axioms Poincare.D12.TriangulationTopology.clampedMap._proof_1
#print axioms Poincare.D12.TriangulationTopology.clampedMap_of_mem_Icc
#print axioms Poincare.D12.TriangulationTopology.coneMapQuot
#print axioms Poincare.D12.TriangulationTopology.coneMap_mem
#print axioms Poincare.D12.TriangulationTopology.coneQuotHomeoDisk._proof_1
#print axioms Poincare.D12.TriangulationTopology.coneQuotNonempty
#print axioms Poincare.D12.TriangulationTopology.continuous_clampedMap
#print axioms Poincare.D12.TriangulationTopology.continuous_diskToLowerHemisphere
#print axioms Poincare.D12.TriangulationTopology.continuous_esnoc'
#print axioms Poincare.D12.TriangulationTopology.continuous_simplexBoundaryConeMapQuot
#print axioms Poincare.D12.TriangulationTopology.continuous_simplexDir
#print axioms Poincare.D12.TriangulationTopology.continuous_sphereToSimplexBoundaryFn
#print axioms Poincare.D12.TriangulationTopology.continuous_suspMapQuot
#print axioms Poincare.D12.TriangulationTopology.coveringMap_injective_of_simplyConnected
#print axioms Poincare.D12.TriangulationTopology.coveringOfSimplyConnectedIsHomeo_of_nonempty
#print axioms Poincare.D12.TriangulationTopology.diskCoverPipeline
#print axioms Poincare.D12.TriangulationTopology.diskDirection_radialExtend
#print axioms Poincare.D12.TriangulationTopology.diskGlueQuotHomeoSphere.eq_1
#print axioms Poincare.D12.TriangulationTopology.diskGlueRel
#print axioms Poincare.D12.TriangulationTopology.diskGlueSumHomeo.eq_1
#print axioms Poincare.D12.TriangulationTopology.diskSimplyConnected
#print axioms Poincare.D12.TriangulationTopology.diskToLowerHemisphere.eq_1
#print axioms Poincare.D12.TriangulationTopology.diskToUpperHemisphere._proof_2
#print axioms Poincare.D12.TriangulationTopology.dist_restrictionPiece_left
#print axioms Poincare.D12.TriangulationTopology.doubleDiskMap.eq_1
#print axioms Poincare.D12.TriangulationTopology.doubleDiskMapQuot_surjective
#print axioms Poincare.D12.TriangulationTopology.doubleDiskQuotHomeoSphere
#print axioms Poincare.D12.TriangulationTopology.doubleDiskQuotNonempty
#print axioms Poincare.D12.TriangulationTopology.esnoc'
#print axioms Poincare.D12.TriangulationTopology.esnoc'_last
#print axioms Poincare.D12.TriangulationTopology.esnoc_castSucc
#print axioms Poincare.D12.TriangulationTopology.exists_not_mem_finset_submodule_union
#print axioms Poincare.D12.TriangulationTopology.exists_unit_notMem_segChain._proof_1_1
#print axioms Poincare.D12.TriangulationTopology.hemisphere_cover._simp_1_1
#print axioms Poincare.D12.TriangulationTopology.idChain
#print axioms Poincare.D12.TriangulationTopology.idChain_zero_apply
#print axioms Poincare.D12.TriangulationTopology.le_simplexMin
#print axioms Poincare.D12.TriangulationTopology.linePoints_le_one_of_not_mem._abel_1_1
#print axioms Poincare.D12.TriangulationTopology.loop_cast_source
#print axioms Poincare.D12.TriangulationTopology.loop_nullhomotopic_of_forall_ne
#print axioms Poincare.D12.TriangulationTopology.lowerHemisphereT2Space
#print axioms Poincare.D12.TriangulationTopology.lowerHemisphereToDisk_diskToLowerHemisphere
#print axioms Poincare.D12.TriangulationTopology.lowerTrunc.eq_1
#print axioms Poincare.D12.TriangulationTopology.norm_radialExtend
#print axioms Poincare.D12.TriangulationTopology.norm_segment_sub_left_le._abel_1_2
#print axioms Poincare.D12.TriangulationTopology.norm_sq_esnoc'
#print axioms Poincare.D12.TriangulationTopology.quotMapHomeo._proof_1
#print axioms Poincare.D12.TriangulationTopology.quotMapHomeo._proof_5
#print axioms Poincare.D12.TriangulationTopology.radialExtend._proof_1
#print axioms Poincare.D12.TriangulationTopology.radialExtend_sphereToDisk
#print axioms Poincare.D12.TriangulationTopology.restrictionChain._f
#print axioms Poincare.D12.TriangulationTopology.restrictionChain._proof_4
#print axioms Poincare.D12.TriangulationTopology.restrictionChain.eq_1
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_apply_eq_clampedMap_idChain
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_homotopic_segChain._proof_1_2
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_succ_apply._proof_1
#print axioms Poincare.D12.TriangulationTopology.restrictionPiece._proof_1
#print axioms Poincare.D12.TriangulationTopology.restrictionPiece_extend_two_mul
#print axioms Poincare.D12.TriangulationTopology.rpCompactSpace
#print axioms Poincare.D12.TriangulationTopology.segChain
#print axioms Poincare.D12.TriangulationTopology.segChain._proof_3
#print axioms Poincare.D12.TriangulationTopology.segChain.congr_simp
#print axioms Poincare.D12.TriangulationTopology.segChain_mem_iUnion_spans
#print axioms Poincare.D12.TriangulationTopology.segPiece
#print axioms Poincare.D12.TriangulationTopology.segPiece.eq_1
#print axioms Poincare.D12.TriangulationTopology.segmentPath._proof_1
#print axioms Poincare.D12.TriangulationTopology.segmentPath.congr_simp
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryCompactSpace
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeHomeoSimplex._proof_2
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeMapQuot
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeMapQuot_surjective
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeRel
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryFnHomeoSphere
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryNonempty
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_eq_of_radial_repr._simp_1_2
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_eq_of_radial_repr._simp_1_6
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_mem_of_ne_center._simp_1_2
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_mem_of_ne_center._simp_1_6
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryToSphere
#print axioms Poincare.D12.TriangulationTopology.simplexCenter.eq_1
#print axioms Poincare.D12.TriangulationTopology.simplexConeMap.eq_1
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot_injective
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot_injective._simp_1_5
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot_surjective
#print axioms Poincare.D12.TriangulationTopology.simplexDir.eq_1
#print axioms Poincare.D12.TriangulationTopology.simplexDir_sum
#print axioms Poincare.D12.TriangulationTopology.simplexHomeoBoundaryCone
#print axioms Poincare.D12.TriangulationTopology.simplexHomeoStdSimplexFn
#print axioms Poincare.D12.TriangulationTopology.simplexLambda_pos_of_unit
#print axioms Poincare.D12.TriangulationTopology.simplexMin_le
#print axioms Poincare.D12.TriangulationTopology.simplexMin_of_simplexBoundaryToSphere
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_eq_of_radial_repr._simp_1_2
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_eq_of_radial_repr._simp_1_6
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_pos_of_ne_center
#print axioms Poincare.D12.TriangulationTopology.simplexVertexZero.eq_1
#print axioms Poincare.D12.TriangulationTopology.simplyConnectedSpace_sphere._proof_1_1
#print axioms Poincare.D12.TriangulationTopology.sphereBase
#print axioms Poincare.D12.TriangulationTopology.sphereConeHomeoSimplex._proof_2
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_10
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_3
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_7
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks_hemisphere_instance
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks_hemisphere_instance._proof_4
#print axioms Poincare.D12.TriangulationTopology.sphereThreeGluedDisks
#print axioms Poincare.D12.TriangulationTopology.sphereThreeTarget_homeo_sphereThree
#print axioms Poincare.D12.TriangulationTopology.sphereThree_identityCover
#print axioms Poincare.D12.TriangulationTopology.sphereToDisk_coe
#print axioms Poincare.D12.TriangulationTopology.sphereToSimplexBoundary_mem
#print axioms Poincare.D12.TriangulationTopology.sphere_pi1_subsingleton
#print axioms Poincare.D12.TriangulationTopology.sqrt_one_sub_trunc_norm_sq_eq_last
#print axioms Poincare.D12.TriangulationTopology.stage6_sphereThreeSimplyConnected
#print axioms Poincare.D12.TriangulationTopology.subdivSpans
#print axioms Poincare.D12.TriangulationTopology.subdiv_not_antipodal_all
#print axioms Poincare.D12.TriangulationTopology.suspMapQuot
#print axioms Poincare.D12.TriangulationTopology.suspMap_mem
#print axioms Poincare.D12.TriangulationTopology.suspQuotHomeoSphere._proof_2
#print axioms Poincare.D12.TriangulationTopology.suspRel
#print axioms Poincare.D12.TriangulationTopology.trivialization_id._proof_2
#print axioms Poincare.D12.TriangulationTopology.trivialization_id._proof_6
#print axioms Poincare.D12.TriangulationTopology.truncToCenter._proof_1
#print axioms Poincare.D12.TriangulationTopology.truncToCenter_sphereToSimplexBoundary
#print axioms Poincare.D12.TriangulationTopology.upperHemisphereNonempty
#print axioms Poincare.D12.TriangulationTopology.upperHemisphereToDisk.eq_1
#print axioms Poincare.D12.TriangulationTopology.zmod2Mul_eq_ofAdd_one_or_one
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism._sizeOf_1
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.fderiv_injective
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.mk.inj
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.noConfusion
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.smooth
#print axioms Poincare.D12.VolumeIBP.ChartMetric._sizeOf_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.chart_ibp
#print axioms Poincare.D12.VolumeIBP.ChartMetric.chart_weighted_ibp
#print axioms Poincare.D12.VolumeIBP.ChartMetric.densityNNReal
#print axioms Poincare.D12.VolumeIBP.ChartMetric.densityNNReal_measurable
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_continuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_pos
#print axioms Poincare.D12.VolumeIBP.ChartMetric.det_pos
#print axioms Poincare.D12.VolumeIBP.ChartMetric.divergence_integral_eq_zero
#print axioms Poincare.D12.VolumeIBP.ChartMetric.driftLaplacian_continuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.euclideanChartMetric._proof_2
#print axioms Poincare.D12.VolumeIBP.ChartMetric.expMetricOne._proof_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.expMetricOne_density_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.g_symm
#print axioms Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.grad_contDiff_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.inner
#print axioms Poincare.D12.VolumeIBP.ChartMetric.inner_pos_of_ne_zero
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix_entry_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.jacobianMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.jentry_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.laplacian_continuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.matrix_apply
#print axioms Poincare.D12.VolumeIBP.ChartMetric.metricInnerInverse
#print axioms Poincare.D12.VolumeIBP.ChartMetric.mk.congr_simp
#print axioms Poincare.D12.VolumeIBP.ChartMetric.mk.sizeOf_spec
#print axioms Poincare.D12.VolumeIBP.ChartMetric.partialDeriv.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullbackMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullbackMetric._proof_2
#print axioms Poincare.D12.VolumeIBP.ChartMetric.riemannianMeasure
#print axioms Poincare.D12.VolumeIBP.ChartMetric.setIntegral_riemannianMeasure_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.weightedDivergence.eq_1
#print axioms Poincare.D12.VolumeIBP.Vec
#print axioms Poincare.D12.VolumeIBP.closedManifoldEntropyIdentity
#print axioms Poincare.D12.VolumeIBP.manifoldRiemannianMeasureExists
#print axioms Poincare.Longrun.Entropy.EntropyData.extra.eq_1
#print axioms _private.Poincare.D11.HeatKernelBridge.AxiomAudit.0.bridgeAuditedDeclarations
#print axioms _private.Poincare.D12.ComparisonGeodesics.SingularRiccati.0.Poincare.D12.ComparisonGeodesics.exp_neg_integral_le_of_normalization._simp_1_2
#print axioms _private.Poincare.D12.ComparisonGeodesics.SingularRiccati.0.Poincare.D12.ComparisonGeodesics.exp_neg_integral_le_of_normalization._simp_1_6
#print axioms _private.Poincare.D12.ConnectionCurvature.ConformalChartModel.0.Poincare.D12.ConnectionCurvature.conformalGamma.match_1.eq_3
#print axioms _private.Poincare.D12.ConnectionCurvature.ConformalChartModel.0.Poincare.D12.ConnectionCurvature.conformalGamma.match_1.eq_7
#print axioms _private.Poincare.D12.HeatDomain.AxiomAudit.0.heatDomainAuditedDeclarations
#print axioms _private.Poincare.D12.HeatSemigroup.Semigroup.0.Poincare.D12.HeatSemigroup.truncation
#print axioms _private.Poincare.D12.HeatSemigroup.Semigroup.0.Poincare.D12.HeatSemigroup.truncation_norm_le
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds._simp_1_1
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds._simp_1_5
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.domBound_integrable._simp_1_2
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.domBound_integrable._simp_1_6
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.fderiv_heatConv_testF_coord._simp_1_3
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.fderiv_heatConv_testF_coord._simp_1_7
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.sq_mul_exp_neg_mul_sq_le._simp_1_2
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.sq_mul_exp_neg_mul_sq_le._simp_1_6
#print axioms _private.Poincare.D12.SemanticLedger.AxiomAudit.0.Poincare.D12.SemanticLedger.d12AuditedDeclarations
#print axioms _private.Poincare.D12.SurgeryRecognition.BallGluing.0.Poincare.D12.SurgeryRecognition.glueRel.match_1.eq_4
#print axioms _private.Poincare.D12.TriangulationTopology.SpherePolygonal.0.Poincare.D12.TriangulationTopology.restrictionChain.match_1.splitter
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampen.0.HatcherLib.CoveredPathChain.toPath.match_1.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.cell_touches_vertex_left_right
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_adjacent_collision._proof_1_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_eq_of_parity_change
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_le_or_succ._proof_1_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.incident_cell_eq_left_or_right._proof_1_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.leftCell._proof_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.leftCell_touches
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.lowerCell.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.rightCell._proof_3
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.rightCell_val_eq_or_succ
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.upperCell.congr_simp
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent.match_1.eq_3
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepCell.inputWord.match_1.splitter
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepCell.outputWord.match_1.splitter
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepRow.rectangleOutput.match_1.splitter
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepStage.chainInput.match_1.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepStage.chainOutput.match_1.eq_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGrid.0.HatcherLib.vanKampenWordLoop.match_1.eq_2
