-- A3 declaration-kind audit for D12-semantic-ledger
-- generated by D13-cross-audit-360-cards; do not edit

import Poincare.D12.SemanticLedger.Defect

set_option maxHeartbeats 400000


open Lean Elab Command

def a3KindNames : List Name := [
  `Poincare.D12.SemanticLedger.not_initialCondition_gaussian,
  `Poincare.D12.SemanticLedger.not_initialCondition_gaussian_quantified,
  `Poincare.D12.SemanticLedger.integrand_not_integrable,
  `Poincare.D12.SemanticLedger.integrand_lintegral_eq_top,
  `Poincare.D12.SemanticLedger.tendsto_testFunction_atTop,
  `Poincare.D12.SemanticLedger.quartic_dominates,
  `Poincare.D12.SemanticLedger.lowerConstant_le_integrand
]

run_cmd do
  let mut counts : Std.HashMap String Nat := {}
  for n in a3KindNames do
    let ci ← getConstInfo n
    let k : String ← match ci with
      | .axiomInfo _  => pure "axiom"
      | .defnInfo _   => pure "def"
      | .thmInfo _    => pure "theorem"
      | .opaqueInfo _ => pure "opaque"
      | .quotInfo _   => pure "quot"
      | .inductInfo _ => pure "inductive"
      | .ctorInfo _   => pure "ctor"
      | .recInfo _    => pure "rec"
    let res ← liftTermElabM <| Lean.Meta.forallTelescopeReducing ci.type fun _ body => do
      if ← Lean.Meta.isProp body then pure "PropResult"
      else match body with
        | .sort l => pure (match l with | .zero => "PropFormer" | _ => "TypeFormer")
        | _ => pure "DataResult"
    counts := counts.insert (k ++ ":" ++ res) (counts.getD (k ++ ":" ++ res) 0 + 1)
    logInfo m!"A3KIND\t{n}\t{k}\t{res}"
  logInfo m!"A3KIND-SUMMARY\t{toString counts.toList}"

