-- A3 independent probe for D12-semantic-ledger
-- generated by D13-cross-audit-360-cards; do not edit

import Poincare.D12.SemanticLedger.Defect

set_option maxHeartbeats 200000

#check Poincare.D12.SemanticLedger.not_initialCondition_gaussian
#check Poincare.D12.SemanticLedger.not_initialCondition_gaussian_quantified
#check Poincare.D12.SemanticLedger.integrand_not_integrable
#check Poincare.D12.SemanticLedger.integrand_lintegral_eq_top
#check Poincare.D12.SemanticLedger.tendsto_testFunction_atTop
#check Poincare.D12.SemanticLedger.quartic_dominates
#check Poincare.D12.SemanticLedger.lowerConstant_le_integrand

#print axioms Poincare.D12.SemanticLedger.not_initialCondition_gaussian
#print axioms Poincare.D12.SemanticLedger.not_initialCondition_gaussian_quantified
#print axioms Poincare.D12.SemanticLedger.integrand_not_integrable
#print axioms Poincare.D12.SemanticLedger.integrand_lintegral_eq_top
#print axioms Poincare.D12.SemanticLedger.tendsto_testFunction_atTop
#print axioms Poincare.D12.SemanticLedger.quartic_dominates
#print axioms Poincare.D12.SemanticLedger.lowerConstant_le_integrand
