-- A3 independent probe for D12-volume-ibp
-- generated by D13-cross-audit-360-cards; do not edit

import Poincare.D12.VolumeIBP.Basic
import Poincare.D12.VolumeIBP.Blocked
import Poincare.D12.VolumeIBP.ChangeOfVariables
import Poincare.D12.VolumeIBP.Divergence
import Poincare.D12.VolumeIBP.Example
import Poincare.D12.VolumeIBP.IBP
import Poincare.D12.VolumeIBP.Regularity

set_option maxHeartbeats 200000

#check Poincare.D12.VolumeIBP.ChartMetric.matrix
#check Poincare.D12.VolumeIBP.ChartMetric.g_symm
#check Poincare.D12.VolumeIBP.ChartMetric.det_pos
#check Poincare.D12.VolumeIBP.ChartMetric.density
#check Poincare.D12.VolumeIBP.ChartMetric.density_pos
#check Poincare.D12.VolumeIBP.ChartMetric.density_ne_zero
#check Poincare.D12.VolumeIBP.ChartMetric.inner
#check Poincare.D12.VolumeIBP.ChartMetric.inner_comm
#check Poincare.D12.VolumeIBP.ChartMetric.inner_pos_of_ne_zero
#check Poincare.D12.VolumeIBP.ChartMetric.invMatrix
#check Poincare.D12.VolumeIBP.ChartMetric.invMatrix_mul
#check Poincare.D12.VolumeIBP.ChartMetric.matrix_mul_invMatrix
#check Poincare.D12.VolumeIBP.ChartMetric.invMatrix_symm
#check Poincare.D12.VolumeIBP.ChartMetric.riemannianMeasure
#check Poincare.D12.VolumeIBP.ChartMetric.densityNNReal
#check Poincare.D12.VolumeIBP.ChartMetric.euclideanChartMetric
#check Poincare.D12.VolumeIBP.contDiff_if_const
#check Poincare.D12.VolumeIBP.ChartMetric.entry_contDiff
#check Poincare.D12.VolumeIBP.ChartMetric.det_contDiff
#check Poincare.D12.VolumeIBP.ChartMetric.adjugate_entry_contDiff
#check Poincare.D12.VolumeIBP.ChartMetric.invMatrix_entry_contDiff
#check Poincare.D12.VolumeIBP.ChartMetric.density_contDiff
#check Poincare.D12.VolumeIBP.ChartMetric.density_continuous
#check Poincare.D12.VolumeIBP.ChartMetric.density_measurable
#check Poincare.D12.VolumeIBP.ChartMetric.density_aemeasurable
#check Poincare.D12.VolumeIBP.ChartMetric.densityNNReal_measurable
#check Poincare.D12.VolumeIBP.ChartMetric.densityNNReal_eq
#check Poincare.D12.VolumeIBP.ChartMetric.integral_riemannianMeasure_eq
#check Poincare.D12.VolumeIBP.ChartMetric.setIntegral_riemannianMeasure_eq
#check Poincare.D12.VolumeIBP.ChartMetric.riemannianMeasure_absolutelyContinuous
#check Poincare.D12.VolumeIBP.ChartMetric.riemannianMeasure_univ
#check Poincare.D12.VolumeIBP.exists_pi_Ioo_supset_compact
#check Poincare.D12.VolumeIBP.ChartMetric.partialDeriv
#check Poincare.D12.VolumeIBP.ChartMetric.weightedDivergence
#check Poincare.D12.VolumeIBP.ChartMetric.divergence
#check Poincare.D12.VolumeIBP.ChartMetric.weighted_divergence_integral_eq_zero
#check Poincare.D12.VolumeIBP.ChartMetric.divergence_integral_eq_zero
#check Poincare.D12.VolumeIBP.ChartMetric.divergence_integral_eq_zero_density
#check Poincare.D12.VolumeIBP.ChartMetric.grad
#check Poincare.D12.VolumeIBP.ChartMetric.laplacian
#check Poincare.D12.VolumeIBP.ChartMetric.metricInnerInverse
#check Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse
#check Poincare.D12.VolumeIBP.ChartMetric.driftLaplacian
#check Poincare.D12.VolumeIBP.ChartMetric.partialDeriv_contDiff_one
#check Poincare.D12.VolumeIBP.ChartMetric.grad_contDiff_one
#check Poincare.D12.VolumeIBP.ChartMetric.grad_hasCompactSupport
#check Poincare.D12.VolumeIBP.ChartMetric.hasCompactSupport_partialDeriv
#check Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse_eq_sum
#check Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse_continuous
#check Poincare.D12.VolumeIBP.ChartMetric.laplacian_continuous
#check Poincare.D12.VolumeIBP.ChartMetric.laplacian_contDiff_two
#check Poincare.D12.VolumeIBP.ChartMetric.weighted_divergence_mul_grad
#check Poincare.D12.VolumeIBP.ChartMetric.chart_ibp
#check Poincare.D12.VolumeIBP.ChartMetric.chart_ibp_self
#check Poincare.D12.VolumeIBP.ChartMetric.laplacian_integral_eq_zero
#check Poincare.D12.VolumeIBP.ChartMetric.chart_ibp_laplacian
#check Poincare.D12.VolumeIBP.ChartMetric.exp_neg_contDiff_one
#check Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse_comm
#check Poincare.D12.VolumeIBP.ChartMetric.weighted_divergence_mul_exp_grad
#check Poincare.D12.VolumeIBP.ChartMetric.chart_weighted_ibp
#check Poincare.D12.VolumeIBP.ChartMetric.driftLaplacian_continuous
#check Poincare.D12.VolumeIBP.ChartDiffeomorphism
#check Poincare.D12.VolumeIBP.ChartMetric.jacobianMatrix
#check Poincare.D12.VolumeIBP.ChartMetric.pullbackMatrix
#check Poincare.D12.VolumeIBP.ChartMetric.jacobianMatrix_det
#check Poincare.D12.VolumeIBP.ChartMetric.det_pullbackMatrix
#check Poincare.D12.VolumeIBP.ChartMetric.jentry_contDiff
#check Poincare.D12.VolumeIBP.ChartMetric.jacobianMatrix_mulVec_eq_fderiv
#check Poincare.D12.VolumeIBP.ChartMetric.invMatrix_mul_matrix_mul_invMatrix
#check Poincare.D12.VolumeIBP.ChartMetric.inner_grad_eq_gradInnerInverse
#check Poincare.D12.VolumeIBP.ChartMetric.pullbackMetric
#check Poincare.D12.VolumeIBP.ChartMetric.pullbackDensity_eq
#check Poincare.D12.VolumeIBP.ChartMetric.pullback_measure_naturality
#check Poincare.D12.VolumeIBP.ChartMetric.euclideanChartMetric_density_one
#check Poincare.D12.VolumeIBP.ChartMetric.expMetricOne
#check Poincare.D12.VolumeIBP.ChartMetric.expMetricOne_density_eq
#check Poincare.D12.VolumeIBP.ChartMetric.chart_ibp_euclidean_one
#check Poincare.D12.VolumeIBP.chartWeightedIBPStatementRestricted_holds

#print axioms Poincare.D12.VolumeIBP.ChartMetric.matrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.g_symm
#print axioms Poincare.D12.VolumeIBP.ChartMetric.det_pos
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_pos
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_ne_zero
#print axioms Poincare.D12.VolumeIBP.ChartMetric.inner
#print axioms Poincare.D12.VolumeIBP.ChartMetric.inner_comm
#print axioms Poincare.D12.VolumeIBP.ChartMetric.inner_pos_of_ne_zero
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix_mul
#print axioms Poincare.D12.VolumeIBP.ChartMetric.matrix_mul_invMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix_symm
#print axioms Poincare.D12.VolumeIBP.ChartMetric.riemannianMeasure
#print axioms Poincare.D12.VolumeIBP.ChartMetric.densityNNReal
#print axioms Poincare.D12.VolumeIBP.ChartMetric.euclideanChartMetric
#print axioms Poincare.D12.VolumeIBP.contDiff_if_const
#print axioms Poincare.D12.VolumeIBP.ChartMetric.entry_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.det_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.adjugate_entry_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix_entry_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_continuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_measurable
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_aemeasurable
#print axioms Poincare.D12.VolumeIBP.ChartMetric.densityNNReal_measurable
#print axioms Poincare.D12.VolumeIBP.ChartMetric.densityNNReal_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.integral_riemannianMeasure_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.setIntegral_riemannianMeasure_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.riemannianMeasure_absolutelyContinuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.riemannianMeasure_univ
#print axioms Poincare.D12.VolumeIBP.exists_pi_Ioo_supset_compact
#print axioms Poincare.D12.VolumeIBP.ChartMetric.partialDeriv
#print axioms Poincare.D12.VolumeIBP.ChartMetric.weightedDivergence
#print axioms Poincare.D12.VolumeIBP.ChartMetric.divergence
#print axioms Poincare.D12.VolumeIBP.ChartMetric.weighted_divergence_integral_eq_zero
#print axioms Poincare.D12.VolumeIBP.ChartMetric.divergence_integral_eq_zero
#print axioms Poincare.D12.VolumeIBP.ChartMetric.divergence_integral_eq_zero_density
#print axioms Poincare.D12.VolumeIBP.ChartMetric.grad
#print axioms Poincare.D12.VolumeIBP.ChartMetric.laplacian
#print axioms Poincare.D12.VolumeIBP.ChartMetric.metricInnerInverse
#print axioms Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse
#print axioms Poincare.D12.VolumeIBP.ChartMetric.driftLaplacian
#print axioms Poincare.D12.VolumeIBP.ChartMetric.partialDeriv_contDiff_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.grad_contDiff_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.grad_hasCompactSupport
#print axioms Poincare.D12.VolumeIBP.ChartMetric.hasCompactSupport_partialDeriv
#print axioms Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse_eq_sum
#print axioms Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse_continuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.laplacian_continuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.laplacian_contDiff_two
#print axioms Poincare.D12.VolumeIBP.ChartMetric.weighted_divergence_mul_grad
#print axioms Poincare.D12.VolumeIBP.ChartMetric.chart_ibp
#print axioms Poincare.D12.VolumeIBP.ChartMetric.chart_ibp_self
#print axioms Poincare.D12.VolumeIBP.ChartMetric.laplacian_integral_eq_zero
#print axioms Poincare.D12.VolumeIBP.ChartMetric.chart_ibp_laplacian
#print axioms Poincare.D12.VolumeIBP.ChartMetric.exp_neg_contDiff_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse_comm
#print axioms Poincare.D12.VolumeIBP.ChartMetric.weighted_divergence_mul_exp_grad
#print axioms Poincare.D12.VolumeIBP.ChartMetric.chart_weighted_ibp
#print axioms Poincare.D12.VolumeIBP.ChartMetric.driftLaplacian_continuous
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism
#print axioms Poincare.D12.VolumeIBP.ChartMetric.jacobianMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullbackMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.jacobianMatrix_det
#print axioms Poincare.D12.VolumeIBP.ChartMetric.det_pullbackMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.jentry_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.jacobianMatrix_mulVec_eq_fderiv
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix_mul_matrix_mul_invMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.inner_grad_eq_gradInnerInverse
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullbackMetric
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullbackDensity_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullback_measure_naturality
#print axioms Poincare.D12.VolumeIBP.ChartMetric.euclideanChartMetric_density_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.expMetricOne
#print axioms Poincare.D12.VolumeIBP.ChartMetric.expMetricOne_density_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.chart_ibp_euclidean_one
#print axioms Poincare.D12.VolumeIBP.chartWeightedIBPStatementRestricted_holds
