import Poincare.L4.Compactness.RicciToDoubling
import Poincare.L4.Compactness.RicciToDoublingHyperbolic
import Poincare.L4.Compactness.RicciToDoublingHyperbolicClosedForm
set_option pp.universes false
#check @Poincare.L4.Compactness.euclidModel_volumeRatio_closedForm
#check @Poincare.L4.Compactness.euclidModel_volume_doubling_closedForm
#check @Poincare.L4.Compactness.euclid_volume_ratio_le_of_ricci_nonneg
#check @Poincare.L4.Compactness.euclid_volumeRatio_div_le_of_ricci_nonneg
#check @Poincare.L4.Compactness.euclid_volume_doubling_of_ricci_nonneg
#check @Poincare.L4.Compactness.euclidModel_hypotheses_witness
#check @Poincare.L4.Compactness.radialVolume_euclidModel_one_doubling_witness
#check @Poincare.L4.Compactness.radialVolume_euclidModel_one_value_witness
#check @Poincare.L4.Compactness.IsRadialBallMeasure
#check @Poincare.L4.Compactness.isRadialBallMeasure_real_witness
#check @Poincare.L4.Compactness.coveringNumber_le_measure_ratio_of_radialBallMeasure
#check @Poincare.L4.Compactness.coveringNumber_le_of_radialBallMeasure_doubling
#check @Poincare.L4.Compactness.coveringNumber_le_of_ricci_nonneg_radialBallMeasure
#check @Poincare.L4.Compactness.hypModelK
#check @Poincare.L4.Compactness.hypModelA
#check @Poincare.L4.Compactness.hypModelM
#check @Poincare.L4.Compactness.hypModelDm
#check @Poincare.L4.Compactness.hypModelDA
#check @Poincare.L4.Compactness.coth_sub_inv_abs_le_one
#check @Poincare.L4.Compactness.hypModelM_hasDerivAt
#check @Poincare.L4.Compactness.hypModelM_riccati
#check @Poincare.L4.Compactness.hypModelM_contOn
#check @Poincare.L4.Compactness.hypModelM_normalized
#check @Poincare.L4.Compactness.hypModelA_hasDerivAt
#check @Poincare.L4.Compactness.hypModelA_contOn
#check @Poincare.L4.Compactness.hypModelA_pos
#check @Poincare.L4.Compactness.hypModelA_zero
#check @Poincare.L4.Compactness.hypModelA_logDeriv
#check @Poincare.L4.Compactness.hyp_volume_ratio_le_of_ricci_ge
#check @Poincare.L4.Compactness.hyp_volume_doubling_of_ricci_ge
#check @Poincare.L4.Compactness.hypModel_doubling_witness
#check @Poincare.L4.Compactness.hypModelA_one_one_volume
#check @Poincare.L4.Compactness.hypModelA_one_one_doubling
#check @Poincare.L4.Compactness.hyp_volume_doubling_d1_k1
#check @Poincare.L4.Compactness.sinhPowIntegral
#check @Poincare.L4.Compactness.sinhPowIntegral_zero
#check @Poincare.L4.Compactness.sinhPowIntegral_one
#check @Poincare.L4.Compactness.sinhPowIntegral_add_two
#check @Poincare.L4.Compactness.sinhPowIntegral_apply_zero
#check @Poincare.L4.Compactness.sinhPowIntegral_hasDerivAt
#check @Poincare.L4.Compactness.sinhPowIntegral_integral
#check @Poincare.L4.Compactness.sinhPowIntegral_two
#check @Poincare.L4.Compactness.sinhPowIntegral_three
#check @Poincare.L4.Compactness.hypModelA_volume_closedForm
#check @Poincare.L4.Compactness.hypModel_volumeRatio_closedForm
#check @Poincare.L4.Compactness.hypModelA_one_one_volume_closedForm
#check @Poincare.L4.Compactness.hypModel_volumeRatio_d2_closedForm
#check @Poincare.L4.Compactness.hyp_volume_ratio_le_of_ricci_ge_closedForm
#check @Poincare.L4.Compactness.hyp_volume_doubling_closedForm
