import Poincare.D13.IntegratedAudit.SnapshotRoot

#print axioms HatcherLib.CoverIntersectionFundamentalGroup._proof_1
#print axioms HatcherLib.CoveredLoop.path_in
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition._sizeOf_inst
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.ctorIdx
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.mk._flat_ctor
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.mk.noConfusion
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.rec
#print axioms HatcherLib.CoveredPathChain.below
#print axioms HatcherLib.CoveredPathChain.carrierSets
#print axioms HatcherLib.CoveredPathChain.carrierSets.eq_1
#print axioms HatcherLib.CoveredPathChain.ctorElim
#print axioms HatcherLib.CoveredPathChain.decompose_loop
#print axioms HatcherLib.CoveredPathChain.decompose_loop_with_membership
#print axioms HatcherLib.CoveredPathChain.extend.elim
#print axioms HatcherLib.CoveredPathChain.extend.sizeOf_spec
#print axioms HatcherLib.CoveredPathChain.noConfusionType
#print axioms HatcherLib.CoveredPathChain.prefixDecomposition._proof_3
#print axioms HatcherLib.CoveredPathChain.prefix_loops_mem_carrierSets
#print axioms HatcherLib.CoveredPathChain.rec
#print axioms HatcherLib.CoveredPathChain.single.elim
#print axioms HatcherLib.CoveredPathChain.single.sizeOf_spec
#print axioms HatcherLib.CoveredPathChain.toPath._unsafe_rec
#print axioms HatcherLib.CoveredSubdivisionPrefix._sizeOf_inst
#print axioms HatcherLib.CoveredSubdivisionPrefix.ctorIdx
#print axioms HatcherLib.CoveredSubdivisionPrefix.mk.inj
#print axioms HatcherLib.CoveredSubdivisionPrefix.noConfusion
#print axioms HatcherLib.FreeBasis
#print axioms HatcherLib.IsFree
#print axioms HatcherLib.Path.Homotopy
#print axioms HatcherLib.PathConnectedOpenCover._sizeOf_inst
#print axioms HatcherLib.PathConnectedOpenCover.cover
#print axioms HatcherLib.PathConnectedOpenCover.mk
#print axioms HatcherLib.PathConnectedOpenCover.mk.noConfusion
#print axioms HatcherLib.PathConnectedOpenCover.pathConnected
#print axioms HatcherLib.PathIn.eq_1
#print axioms HatcherLib.VanKampenCellTouchesVertex
#print axioms HatcherLib.VanKampenRectangularSubdivision._sizeOf_1
#print axioms HatcherLib.VanKampenRectangularSubdivision.cell_subordinate
#print axioms HatcherLib.VanKampenRectangularSubdivision.horizontalCut_mono
#print axioms HatcherLib.VanKampenRectangularSubdivision.mk._flat_ctor
#print axioms HatcherLib.VanKampenRectangularSubdivision.mk.sizeOf_spec
#print axioms HatcherLib.VanKampenRectangularSubdivision.recOn
#print axioms HatcherLib.VanKampenRectangularSubdivision.verticalCut_one
#print axioms HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent
#print axioms HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent.map_castSucc
#print axioms HatcherLib.VanKampenSquareGrid.casesOn
#print axioms HatcherLib.VanKampenSquareGrid.cellBoundaryHomotopy._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.cellConvexHomotopy._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.cellConvexHomotopy._proof_6
#print axioms HatcherLib.VanKampenSquareGrid.cellIndex
#print axioms HatcherLib.VanKampenSquareGrid.cellMap._proof_3
#print axioms HatcherLib.VanKampenSquareGrid.cell_subordinate
#print axioms HatcherLib.VanKampenSquareGrid.coordinateLine.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.coordinateLine_zero
#print axioms HatcherLib.VanKampenSquareGrid.descendingFin_succ
#print axioms HatcherLib.VanKampenSquareGrid.horizontalCells
#print axioms HatcherLib.VanKampenSquareGrid.horizontalCut_zero
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeClassInCell_eq_based
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeFactor_changeCell
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeInCell._proof_3
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeLoop.congr_simp
#print axioms HatcherLib.VanKampenSquareGrid.horizontalFrontierWord
#print axioms HatcherLib.VanKampenSquareGrid.horizontalParameterEdge._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.horizontalParameterEdgeInCell._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.horizontalSlice._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.mk
#print axioms HatcherLib.VanKampenSquareGrid.mk.noConfusion
#print axioms HatcherLib.VanKampenSquareGrid.rec
#print axioms HatcherLib.VanKampenSquareGrid.rowCellsForIndices
#print axioms HatcherLib.VanKampenSquareGrid.rowStage._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.sweepCell._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.sweepCell._proof_5
#print axioms HatcherLib.VanKampenSquareGrid.vertexConnector
#print axioms HatcherLib.VanKampenSquareGrid.vertexConnectorInCell._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.vertexConnector_in_incidentCell
#print axioms HatcherLib.VanKampenSquareGrid.verticalBasedEdgeInCell
#print axioms HatcherLib.VanKampenSquareGrid.verticalCut
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdge
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeFactor
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeInCell
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeInCell_map
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeLoop_in_incidentCells
#print axioms HatcherLib.VanKampenSquareGrid.verticalParameterEdge._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.verticalParameterEdgeInCell._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.verticalSlice._proof_2
#print axioms HatcherLib.VanKampenSweepCell.Composable._f
#print axioms HatcherLib.VanKampenSweepCell._sizeOf_inst
#print axioms HatcherLib.VanKampenSweepCell.equivalent_input_output
#print axioms HatcherLib.VanKampenSweepCell.inputWord
#print axioms HatcherLib.VanKampenSweepCell.inputWord_eq_firstRight_bottoms
#print axioms HatcherLib.VanKampenSweepCell.lastLeftWord._unsafe_rec
#print axioms HatcherLib.VanKampenSweepCell.lastLeftWord.eq_def
#print axioms HatcherLib.VanKampenSweepCell.mk.congr_simp
#print axioms HatcherLib.VanKampenSweepCell.mk.sizeOf_spec
#print axioms HatcherLib.VanKampenSweepCell.outputWord._f
#print axioms HatcherLib.VanKampenSweepCell.outputWord.eq_2
#print axioms HatcherLib.VanKampenSweepCell.outputWord_eq_tops_lastLeft
#print axioms HatcherLib.VanKampenSweepCell.step
#print axioms HatcherLib.VanKampenSweepRow.Composable._f
#print axioms HatcherLib.VanKampenSweepRow._sizeOf_inst
#print axioms HatcherLib.VanKampenSweepRow.equivalent_of_outerBoundary_links
#print axioms HatcherLib.VanKampenSweepRow.mk._flat_ctor
#print axioms HatcherLib.VanKampenSweepRow.mk.sizeOf_spec
#print axioms HatcherLib.VanKampenSweepRow.recOn
#print axioms HatcherLib.VanKampenSweepRow.rectangleOutput
#print axioms HatcherLib.VanKampenSweepRow.rectangleOutput.eq_1
#print axioms HatcherLib.VanKampenSweepRow.rectangleOutput.match_1
#print axioms HatcherLib.VanKampenSweepRow.rightBoundary._sunfold
#print axioms HatcherLib.VanKampenSweepRow.rightBoundary.eq_def
#print axioms HatcherLib.VanKampenSweepStage
#print axioms HatcherLib.VanKampenSweepStage.Composable._unsafe_rec
#print axioms HatcherLib.VanKampenSweepStage.chainInput
#print axioms HatcherLib.VanKampenSweepStage.chainOutput
#print axioms HatcherLib.VanKampenSweepStage.chainOutput.eq_1
#print axioms HatcherLib.VanKampenSweepStage.chainOutput.match_1
#print axioms HatcherLib.VanKampenSweepStage.input
#print axioms HatcherLib.VanKampenSweepStage.mk.injEq
#print axioms HatcherLib.VanKampenSweepStage.noConfusionType
#print axioms HatcherLib.VanKampenSweepStage.step
#print axioms HatcherLib.VanKampenWordEquivalent.append_left
#print axioms HatcherLib.VanKampenWordEquivalent.multiply
#print axioms HatcherLib.VanKampenWordMove.append_right
#print axioms HatcherLib.VanKampenWordMove.multiply
#print axioms HatcherLib.affinePathHomotopy._proof_1
#print axioms HatcherLib.affinePathHomotopy._proof_5
#print axioms HatcherLib.chosenFreeBasis
#print axioms HatcherLib.coverIntersectionInclusionLeft._proof_1
#print axioms HatcherLib.coverIntersectionInclusionRight._proof_1
#print axioms HatcherLib.coverIntersectionToLeft_classOfLoop
#print axioms HatcherLib.coverIntersection_maps_agree._simp_1_1
#print axioms HatcherLib.coveredLoopProduct._unsafe_rec
#print axioms HatcherLib.coveredLoopProduct_mem_vanKampenMap_range
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_11
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_2
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_6
#print axioms HatcherLib.coveredSubdivisionPrefix._simp_7
#print axioms HatcherLib.exists_vanKampenSquareGrid._proof_1_1
#print axioms HatcherLib.exists_vanKampenSquareGrid._proof_1_4
#print axioms HatcherLib.exists_vanKampenWordEvaluation_eq
#print axioms HatcherLib.freeGroupRank
#print axioms HatcherLib.freeProductLift.eq_1
#print axioms HatcherLib.fundamentalGroupProdMulEquiv._proof_1
#print axioms HatcherLib.fundamentalTheoremOfAlgebra
#print axioms HatcherLib.loop_decomposition_two
#print axioms HatcherLib.mulOppositeProdMulEquiv._proof_3
#print axioms HatcherLib.pathInSubtype._proof_2
#print axioms HatcherLib.pathInSubtype._proof_6
#print axioms HatcherLib.pathInSubtypeBetween._proof_2
#print axioms HatcherLib.pathInSubtypeBetween._proof_6
#print axioms HatcherLib.pathIn_symm
#print axioms HatcherLib.pathReverse
#print axioms HatcherLib.piOneProdMulEquiv
#print axioms HatcherLib.subtypePath_ext
#print axioms HatcherLib.vanKampenClassOfLoopInIntersection._proof_1
#print axioms HatcherLib.vanKampenFactorLoop
#print axioms HatcherLib.vanKampenFactorRepresentative._proof_1
#print axioms HatcherLib.vanKampenMap
#print axioms HatcherLib.vanKampenMap_surjective
#print axioms HatcherLib.vanKampenNormalSubgroup_normal
#print axioms HatcherLib.vanKampenQuotientMulEquivOfFactorizationsConnected
#print axioms HatcherLib.vanKampenRelations
#print axioms HatcherLib.vanKampenThreefoldIntersection
#print axioms HatcherLib.vanKampenWordEquivalent_cellSweepStep
#print axioms HatcherLib.vanKampenWordEquivalent_quotient_eq
#print axioms HatcherLib.vanKampenWordEvaluation_append
#print axioms HatcherLib.vanKampenWordLoop._f
#print axioms HatcherLib.vanKampenWordLoop.eq_def
#print axioms HatcherLib.vanKampenWordLoop_homotopic_of_map_eq
#print axioms HatcherLib.vanKampenWordQuotientEvaluation.eq_1
#print axioms Poincare.D10.HeatKernelEuclidean.gaussianKernel.eq_1
#print axioms Poincare.D11.BochnerManifold.d7_gradient_estimate_implies_model_subharmonic_nonneg
#print axioms Poincare.D11.BochnerManifold.deriv_deriv_abs_deriv_eq_of_pos
#print axioms Poincare.D11.BochnerManifold.differentiableAt_deriv_deriv_of_contDiff
#print axioms Poincare.D11.BochnerManifold.euclidean_bochner_identity_components_restated
#print axioms Poincare.D11.BochnerManifold.flatCertificateWitness
#print axioms Poincare.D11.BochnerManifold.flatCertificateWitness_bochner
#print axioms Poincare.D11.BochnerManifold.frame_grad_lap_dot_sum
#print axioms Poincare.D11.BochnerManifold.gradSq
#print axioms Poincare.D11.BochnerManifold.gradient_estimate_of_norm
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_deriv_eq._simp_1_2
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_deriv_eq._simp_1_6
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_of_zero
#print axioms Poincare.D11.BochnerManifold.jacobiSol_second_deriv_div._simp_1_2
#print axioms Poincare.D11.BochnerManifold.jacobiSol_second_deriv_div._simp_1_6
#print axioms Poincare.D11.BochnerManifold.lap_gradSq_split
#print axioms Poincare.D11.BochnerManifold.modelBochnerCertificate._proof_3
#print axioms Poincare.D11.BochnerManifold.modelGradDot
#print axioms Poincare.D11.BochnerManifold.modelGradVec._proof_1
#print axioms Poincare.D11.BochnerManifold.modelHessMat
#print axioms Poincare.D11.BochnerManifold.modelRicMat
#print axioms Poincare.D11.BochnerManifold.modelRicciTerm_nonneg_of_nonneg
#print axioms Poincare.D11.BochnerManifold.model_bochner_weitzenbock_harmonic
#print axioms Poincare.D11.BochnerManifold.model_grad_lap_dot_eq_gradDot
#print axioms Poincare.D11.BochnerManifold.model_kato
#print axioms Poincare.D11.BochnerManifold.radial_bochner_identity_dim_zero
#print axioms Poincare.D11.BochnerManifold.subharmonic_energy_density_of_harmonic
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.C_lo_nonneg
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.WeakInitialCondition
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.c_lo
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.casesOn
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.dist_nonneg
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.gaussianLowerBound
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.kernel_nonneg
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.mk.inj
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.noConfusion
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.recOn
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.toCore_toHeatKernelData
#print axioms Poincare.D11.HeatKernelBridge.contDiffTwoSet
#print axioms Poincare.D11.HeatKernelBridge.contDiffTwoSubmodule._proof_2
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._abel_2
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_12
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_16
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_5
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_9
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_c_up
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_gaussianLowerBound
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_laplacian
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_weakInitialCondition
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelData_zero_toCore
#print axioms Poincare.D11.HeatKernelBridge.flatKernel_eq
#print axioms Poincare.D11.HeatKernelBridge.flatKernel_pos
#print axioms Poincare.D11.HeatKernelBridge.integrable_euclideanSpace_fin_zero
#print axioms Poincare.D11.HeatKernelBridge.laplacianLinearMap._proof_2
#print axioms Poincare.D11.HeatKernelBridge.laplacianLinearMap_flatKernel
#print axioms Poincare.D11.HeatKernelBridge.prefactor_mul_eight
#print axioms Poincare.D11.HeatKernelBridge.tendstoUniformlyOn_gaussianKernel_compl._simp_1_1
#print axioms Poincare.D11.HeatKernelBridge.tendsto_setIntegral_ball_gaussianKernel
#print axioms Poincare.D11.MaximumPrincipleTensor.ConeInvariantUnderReaction
#print axioms Poincare.D11.MaximumPrincipleTensor.PositivityPreserving
#print axioms Poincare.D11.MaximumPrincipleTensor.PositivityPreserving.const_smul
#print axioms Poincare.D11.MaximumPrincipleTensor.boundaryOnlyReaction
#print axioms Poincare.D11.MaximumPrincipleTensor.boundaryOnlyReaction_not_positivityPreserving
#print axioms Poincare.D11.MaximumPrincipleTensor.eulerIterate_posSemidef
#print axioms Poincare.D11.MaximumPrincipleTensor.eulerStep.eq_1
#print axioms Poincare.D11.MaximumPrincipleTensor.exp_smul_posSemidef
#print axioms Poincare.D11.MaximumPrincipleTensor.mat_one_eq_oneByOne
#print axioms Poincare.D11.MaximumPrincipleTensor.nonneg_iff_posSemidef
#print axioms Poincare.D11.MaximumPrincipleTensor.oneByOne
#print axioms Poincare.D11.MaximumPrincipleTensor.oneByOne_forward_invariance
#print axioms Poincare.D11.MaximumPrincipleTensor.posSemidef_of_nonneg
#print axioms Poincare.D11.MaximumPrincipleTensor.psdCone_closed
#print axioms Poincare.D11.MaximumPrincipleTensor.psdCone_zero_mem
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm_eq_zero_iff_mulVec_eq_zero
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm_monotone_of_reaction_posSemidef
#print axioms Poincare.D11.MaximumPrincipleTensor.scalar_forward_invariance
#print axioms Poincare.D11.MaximumPrincipleTensor.sqrtNegReaction._proof_1
#print axioms Poincare.D11.MaximumPrincipleTensor.sqrtNegReaction_nonneg
#print axioms Poincare.D11.ReducedVolume.IsLMinimizer_of_eq_straightRay
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.ctorIdx
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.mk._flat_ctor
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.mk.sizeOf_spec
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.recOn
#print axioms Poincare.D11.ReducedVolume.ae_velocity_eq_of_deficit_integral_zero
#print axioms Poincare.D11.ReducedVolume.euclideanFlow_scalarCurvature
#print axioms Poincare.D11.ReducedVolume.euclideanJacobianComparisonInterface_comparison
#print axioms Poincare.D11.ReducedVolume.euclideanManifoldReducedVolumeInterface_flow
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolumeAnchor
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolumeCertificate._proof_3
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolumeCertificate_volume
#print axioms Poincare.D11.ReducedVolume.euclidean_manifoldReducedVolumeMonotonicity
#print axioms Poincare.D11.ReducedVolume.flatDeficit_eq_normSq
#print axioms Poincare.D11.ReducedVolume.flatLExponential._proof_1
#print axioms Poincare.D11.ReducedVolume.flatLlength
#print axioms Poincare.D11.ReducedVolume.flatReducedLength_eq_reducedLength
#print axioms Poincare.D11.ReducedVolume.generalMonotonicityMissingDependencies_ne_nil
#print axioms Poincare.D11.ReducedVolume.heatKernelReducedDistance_eq_reducedLength
#print axioms Poincare.D11.ReducedVolume.heatKernel_asymptotics
#print axioms Poincare.D11.ReducedVolume.reducedVolume
#print axioms Poincare.D11.ReducedVolume.reducedVolumeIntegrand._proof_1
#print axioms Poincare.D11.ReducedVolume.reducedVolumeIntegrandUnnormalized_eq_gaussianKernel
#print axioms Poincare.D11.ReducedVolume.reducedVolume_nonneg
#print axioms Poincare.D11.ReducedVolume.straightRayLPath.congr_simp
#print axioms Poincare.D11.ReducedVolume.straightRay_eq_gaussianPath
#print axioms Poincare.D11.ReducedVolume.straightRay_reducedLength
#print axioms Poincare.D11.SpectralTorus.Sobolev._proof_1
#print axioms Poincare.D11.SpectralTorus.circleRep_coe
#print axioms Poincare.D11.SpectralTorus.coordProj._proof_2
#print axioms Poincare.D11.SpectralTorus.dirDeriv.eq_1
#print axioms Poincare.D11.SpectralTorus.finConsEquiv
#print axioms Poincare.D11.SpectralTorus.finConsEquiv_apply
#print axioms Poincare.D11.SpectralTorus.fourierMode_eq_exp_sum
#print axioms Poincare.D11.SpectralTorus.gradNorm
#print axioms Poincare.D11.SpectralTorus.hasFDerivAt_expArg
#print axioms Poincare.D11.SpectralTorus.innerForm._proof_2
#print axioms Poincare.D11.SpectralTorus.intVec
#print axioms Poincare.D11.SpectralTorus.integrable_mFourier
#print axioms Poincare.D11.SpectralTorus.laplacian.eq_1
#print axioms Poincare.D11.SpectralTorus.laplacian_periodic
#print axioms Poincare.D11.SpectralTorus.nnreal_coe_ennreal_eq
#print axioms Poincare.D11.SpectralTorus.normSq_eq_zero_iff._simp_1
#print axioms Poincare.D11.SpectralTorus.ofRealClm._proof_1
#print axioms Poincare.D11.SpectralTorus.one_add_normSq_ge_geomMean
#print axioms Poincare.D11.SpectralTorus.one_add_normSq_inv_le_prod._simp_1_3
#print axioms Poincare.D11.SpectralTorus.one_add_normSq_inv_le_prod._simp_1_7
#print axioms Poincare.D11.SpectralTorus.parsevalUnitAddCircleIsAddHaarMeasure
#print axioms Poincare.D11.SpectralTorus.parsevalUnitAddCircleMeasureSpace
#print axioms Poincare.D11.SpectralTorus.poincareUnitAddCircleIsProbabilityMeasure._proof_1
#print axioms Poincare.D11.SpectralTorus.sobolevEmbeddingConstant
#print axioms Poincare.D11.SpectralTorus.sobolevNormSq
#print axioms Poincare.D11.SpectralTorus.sobolevUnitAddCircleIsProbabilityMeasure._proof_1
#print axioms Poincare.D11.SpectralTorus.sobolevWeightHalf
#print axioms Poincare.D11.SpectralTorus.stdVec
#print axioms Poincare.D11.SpectralTorus.summable_sobolevWeight_inv._simp_1_1
#print axioms Poincare.D11.SpectralTorus.summable_sobolevWeight_inv._simp_1_5
#print axioms Poincare.D11.SpectralTorus.summable_weight_int_ennreal
#print axioms Poincare.D11.SpectralTorus.torusDeriv_trigPoly
#print axioms Poincare.D11.SpectralTorus.torusFourier._proof_1
#print axioms Poincare.D11.SpectralTorus.torusLaplacian_mFourier
#print axioms Poincare.D11.SpectralTorus.torusQuotHom._proof_1
#print axioms Poincare.D11.SpectralTorus.torusQuotHom_ker
#print axioms Poincare.D11.SpectralTorus.torusToUnit_unitToTorus
#print axioms Poincare.D11.SpectralTorus.trigPoly.eq_1
#print axioms Poincare.D11.SpectralTorus.trigPolyDerivL2._proof_1
#print axioms Poincare.D11.SpectralTorus.trigPolyDerivL2._proof_5
#print axioms Poincare.D11.SpectralTorus.trigPolyDerivL2_normSq
#print axioms Poincare.D11.SpectralTorus.trigPolyL2._proof_3
#print axioms Poincare.D11.SpectralTorus.trigPolyL2.eq_1
#print axioms Poincare.D11.SpectralTorus.trigPoly_integral
#print axioms Poincare.D11.SpectralTorus.tsum_piFin_product
#print axioms Poincare.D11.SpectralTorus.twoPiI_norm
#print axioms Poincare.D11.WarpedProductModel
#print axioms Poincare.D11.WarpedProductModel.mk
#print axioms Poincare.D11.WarpedProductModel.recOn
#print axioms Poincare.D11.ballVolume_ge_jacobiSol_pow
#print axioms Poincare.D11.bishopGromov_volume_comparison
#print axioms Poincare.D11.continuous_jacobiDeriv
#print axioms Poincare.D11.differentiable_jacobiDeriv
#print axioms Poincare.D11.divergenceLaplacian_eq_radialLaplacian
#print axioms Poincare.D11.firstZero_le_firstZero
#print axioms Poincare.D11.jacobiSol_pos
#print axioms Poincare.D11.laplacianComparison_model
#print axioms Poincare.D11.modelHyperbolicMetric
#print axioms Poincare.D11.modelSphereMetric_posDef
#print axioms Poincare.D11.polarMetric_add_left
#print axioms Poincare.D11.polarMetric_pos_of_pos
#print axioms Poincare.D11.radialLaplacian
#print axioms Poincare.D11.warpedProductModel_jacobiSol
#print axioms Poincare.D11.wronskian
#print axioms Poincare.D12.ComparisonGeodesics.EuclideanNormalizedOn
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.casesOn
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.hasDerivAt_du
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.neg
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiEqOn.casesOn
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiEqOn.mk
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiEqOn.toLe
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiLeOn.hasDerivAt_m
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiLeOn.rec
#print axioms Poincare.D12.ComparisonGeodesics.areaRatio_hasDerivAt._simp_1_1
#print axioms Poincare.D12.ComparisonGeodesics.areaRatio_hasDerivAt._simp_1_5
#print axioms Poincare.D12.ComparisonGeodesics.bishopGromov_volume_le
#print axioms Poincare.D12.ComparisonGeodesics.bishopGromov_volume_le._simp_1_4
#print axioms Poincare.D12.ComparisonGeodesics.deriv_nonpos_of_posOn_Ioo_of_eq_at_right
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelA_logDeriv
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelDm
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelM_normalized
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_singular_comparison_ge
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_volume._simp_1_3
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_volume._simp_1_7
#print axioms Poincare.D12.ComparisonGeodesics.hasDerivAtR_inv
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_hasDerivAt
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_hasDerivAt._simp_1_4
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_le_of_le
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_le_of_le._simp_1_4
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_riccati
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume_numerator_le_zero
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume_numerator_le_zero._simp_1_4
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume_pos_of_pos
#print axioms Poincare.D12.ComparisonGeodesics.riccati_ge_of_singular_normalization
#print axioms Poincare.D12.ComparisonGeodesics.solution_le_of_initial
#print axioms Poincare.D12.ComparisonGeodesics.solution_le_of_initial._simp_1_5
#print axioms Poincare.D12.ComparisonGeodesics.solution_le_of_same_initial
#print axioms Poincare.D12.ComparisonGeodesics.wronskian
#print axioms Poincare.D12.ComparisonGeodesics.wronskian_deriv
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients._sizeOf_1
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.christoffel.eq_1
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.christoffel_raised_contraction
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.christoffel_symm
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.g
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.gram_christoffel_contraction
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.inv_mul
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.mk._flat_ctor
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.mk.noConfusion
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.rec
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D._proof_2
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D.eq_1
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_christoffel._simp_1_5
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_christoffel._simp_1_9
#print axioms Poincare.D12.ConnectionCurvature.ChartPoint
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.casesOn
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.christoffelFamily.eq_1
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.ctorIdx
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.dFamily_symm
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.g
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.gInv_symm
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.inv_mul
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.mk._flat_ctor
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.mk.sizeOf_spec
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.nabla_const_apply
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.nabla_torsionFree
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.recOn
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.cross_e2_e1
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3._proof_2
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3._proof_6
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3_apply
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3MeanLeviCivita
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3Metric._proof_3
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3_basis_eq_single
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3_milnor_eq_mean
#print axioms Poincare.D12.ConnectionCurvature.adTranspose
#print axioms Poincare.D12.ConnectionCurvature.adTranspose._proof_4
#print axioms Poincare.D12.ConnectionCurvature.adTranspose._proof_8
#print axioms Poincare.D12.ConnectionCurvature.bracketInvariant
#print axioms Poincare.D12.ConnectionCurvature.chartAbstractConnection.eq_1
#print axioms Poincare.D12.ConnectionCurvature.chartMetricCompatible_form
#print axioms Poincare.D12.ConnectionCurvature.conformalG._proof_1
#print axioms Poincare.D12.ConnectionCurvature.conformalGInv_smooth
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma.eq_2
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma.eq_6
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma_101_zero
#print axioms Poincare.D12.ConnectionCurvature.conformalPointwise._proof_2
#print axioms Poincare.D12.ConnectionCurvature.conformalPointwise._simp_3
#print axioms Poincare.D12.ConnectionCurvature.conformal_denom_ne_zero
#print axioms Poincare.D12.ConnectionCurvature.curvatureEndo._proof_1
#print axioms Poincare.D12.ConnectionCurvature.curvature_skew_adjoint
#print axioms Poincare.D12.ConnectionCurvature.fderiv_apply_eq_sum_single
#print axioms Poincare.D12.ConnectionCurvature.formOf._proof_2
#print axioms Poincare.D12.ConnectionCurvature.formOf._proof_6
#print axioms Poincare.D12.ConnectionCurvature.formOf_apply
#print axioms Poincare.D12.ConnectionCurvature.leviCivitaExists
#print axioms Poincare.D12.ConnectionCurvature.meanLeviCivitaData._proof_2
#print axioms Poincare.D12.ConnectionCurvature.milnorConnection._proof_2
#print axioms Poincare.D12.ConnectionCurvature.milnorConnection_eq_mean_iff
#print axioms Poincare.D12.ConnectionCurvature.milnorLeviCivitaData
#print axioms Poincare.D12.ConnectionCurvature.nablaOf._proof_2
#print axioms Poincare.D12.ConnectionCurvature.nablaOf._proof_6
#print axioms Poincare.D12.ConnectionCurvature.nablaOf_apply
#print axioms Poincare.D12.ConnectionCurvature.scalarCurvature_eq_sum_ricci_basis
#print axioms Poincare.D12.ConnectionCurvature.sum_three_cycle
#print axioms Poincare.D12.EntropyVariation.FDissipationCorrected
#print axioms Poincare.D12.EntropyVariation.FDissipation_eq_corrected_of_idempotent
#print axioms Poincare.D12.EntropyVariation.fDerivativeCorrected_of_pointwise
#print axioms Poincare.D12.EntropyVariation.fflowEntropyData._proof_2
#print axioms Poincare.D12.EntropyVariation.fflowEntropyData.congr_simp
#print axioms Poincare.D12.EntropyVariation.fflowGradSq.eq_1
#print axioms Poincare.D12.EntropyVariation.fflowMetricScale
#print axioms Poincare.D12.EntropyVariation.fflowScaleInv_eq_inv_metricScale
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipationCorrected_value._simp_1_4
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipationCorrected_value._simp_1_8
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipation_value._simp_1_3
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipation_value._simp_1_7
#print axioms Poincare.D12.EntropyVariation.fflow_F_hasDerivAt
#print axioms Poincare.D12.EntropyVariation.fflow_F_strictMonoOn._simp_1_1
#print axioms Poincare.D12.EntropyVariation.fflow_F_strictMonoOn._simp_1_5
#print axioms Poincare.D12.EntropyVariation.fflow_F_value._simp_1_2
#print axioms Poincare.D12.EntropyVariation.fflow_F_value._simp_1_6
#print axioms Poincare.D12.EntropyVariation.fflow_idempotency_forces_zero_dim
#print axioms Poincare.D12.EntropyVariation.fflow_literal_FDerivativeStatement_of_idempotent
#print axioms Poincare.D12.EntropyVariation.fflow_rho_timeIndep
#print axioms Poincare.D12.EntropyVariation.fflow_two_riccHess_pos
#print axioms Poincare.D12.EntropyVariation.fflow_variation_eq_two_riccHess_of_normSq_eq._simp_1_2
#print axioms Poincare.D12.EntropyVariation.fflow_variation_eq_two_riccHess_of_normSq_eq._simp_1_6
#print axioms Poincare.D12.EntropyVariation.fflow_variation_integral._simp_1_2
#print axioms Poincare.D12.EntropyVariation.fflow_variation_integral._simp_1_6
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_fflowGradSq
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_fflowGradSq._simp_1_4
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_fflowMetricScale
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_weightedIntegral
#print axioms Poincare.D12.EntropyVariation.integrable_gaussianKernel
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_exp_neg_mul
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_exp_neg_mul._simp_1_4
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_gaussianKernel
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_gaussianKernel._simp_1_4
#print axioms Poincare.D12.EntropyVariation.iteratedFDeriv_two_shrinkerFpot
#print axioms Poincare.D12.EntropyVariation.normSq_exp_neg_mul_le._simp_1_3
#print axioms Poincare.D12.EntropyVariation.normSq_exp_neg_mul_le._simp_1_7
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData._proof_2
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData.congr_simp
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipationCorrected_value._simp_1_4
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipationCorrected_value._simp_1_8
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipation_value._simp_1_3
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipation_value._simp_1_7
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_F_value._simp_1_2
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_F_value._simp_1_6
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_mass
#print axioms Poincare.D12.EntropyVariation.shrinkerGradSq
#print axioms Poincare.D12.EntropyVariation.shrinkerRiccHess.eq_1
#print axioms Poincare.D12.EntropyVariation.shrinkerWDissipationDensity_zero
#print axioms Poincare.D12.EntropyVariation.shrinkerWOfTau._proof_2
#print axioms Poincare.D12.EntropyVariation.shrinker_hessian_eq_metricOverTwoTau
#print axioms Poincare.D12.EntropyVariation.shrinker_riccHess_justified._simp_1_3
#print axioms Poincare.D12.EntropyVariation.shrinker_riccHess_justified._simp_1_7
#print axioms Poincare.D12.GeometricCompactness.ancientKappaCompactnessFrontier
#print axioms Poincare.D12.GeometricCompactness.cheegerGromovCompactness
#print axioms Poincare.D12.GeometricCompactness.cover_transfer_of_hausdorffDist_lt
#print axioms Poincare.D12.GeometricCompactness.diam_rep_of_toGHSpace
#print axioms Poincare.D12.GeometricCompactness.ghDist_congr_right
#print axioms Poincare.D12.GeometricCompactness.gridFamily_closure_isCompact
#print axioms Poincare.D12.GeometricCompactness.gridGH
#print axioms Poincare.D12.GeometricCompactness.gridSet.eq_1
#print axioms Poincare.D12.GeometricCompactness.gridUniformCover
#print axioms Poincare.D12.GeometricCompactness.gromovCriterion
#print axioms Poincare.D12.GeometricCompactness.instGridSpaceFintype
#print axioms Poincare.D12.GeometricCompactness.instSquareSpaceMetricSpace
#print axioms Poincare.D12.GeometricCompactness.mk2
#print axioms Poincare.D12.GeometricCompactness.mk2_ofLp_one
#print axioms Poincare.D12.GeometricCompactness.square_grid_dense
#print axioms Poincare.D12.GeometricCompactness.square_grid_dense._simp_1_4
#print axioms Poincare.D12.GeometricCompactness.toGHSpace_rep_isometryEquiv
#print axioms Poincare.D12.GeometricCompactness.zero_mem_gridSet
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass._sizeOf_inst
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.cls_integrable
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.continuousCompactSupportClass_subset_continuousIntegrableClass
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.continuousIntegrableClass_inhabited
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.mk.inj
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.noConfusion
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.v1
#print axioms Poincare.D12.HeatDomain.bump
#print axioms Poincare.D12.HeatDomain.bump_nontrivial
#print axioms Poincare.D12.HeatDomain.bump_zero
#print axioms Poincare.D12.HeatDomain.fastFunction_continuous
#print axioms Poincare.D12.HeatDomain.flatHeatKernelCore_weakInitialConditionFor_integrableClass
#print axioms Poincare.D12.HeatDomain.halfspace_eq_box._simp_1_1
#print axioms Poincare.D12.HeatDomain.measurableSet_norm_ge
#print axioms Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel._simp_1_3
#print axioms Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel._simp_1_7
#print axioms Poincare.D12.HeatDomain.not_fullInitialCondition_flat_one
#print axioms Poincare.D12.HeatDomain.toHeatKernelData_of_weak_compact_finiteMeasure
#print axioms Poincare.D12.HeatDomain.volume_eq_volume_pi_image_ofLp
#print axioms Poincare.D12.HeatDomain.weakInitialConditionFor_ccClass_iff_full_of_compact_finiteMeasure
#print axioms Poincare.D12.HeatSemigroup.CompactManifoldL1ContractionObligation
#print axioms Poincare.D12.HeatSemigroup.CompactManifoldSmoothingObligation._proof_1
#print axioms Poincare.D12.HeatSemigroup.continuousAt_gaussianKernel_time
#print axioms Poincare.D12.HeatSemigroup.enorm_mul_of_nonneg_left
#print axioms Poincare.D12.HeatSemigroup.gaussianKernelFDerivCLM._proof_2
#print axioms Poincare.D12.HeatSemigroup.gaussianKernelFDerivCLM_norm_le
#print axioms Poincare.D12.HeatSemigroup.hasFDerivAt_gaussianKernel_mul
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM._proof_2
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_apply._simp_1_3
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_apply._simp_1_7
#print axioms Poincare.D12.HeatSemigroup.heatKernelProduct_integrable
#print axioms Poincare.D12.HeatSemigroup.heatOperator.eq_1
#print axioms Poincare.D12.HeatSemigroup.heatOperatorBCF.congr_simp
#print axioms Poincare.D12.HeatSemigroup.heatOperatorBCF_norm_le
#print axioms Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator_fun
#print axioms Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator_swap
#print axioms Poincare.D12.HeatSemigroup.heatOperator_eq_integral_sub._abel_1_1
#print axioms Poincare.D12.HeatSemigroup.heatOperator_gaussianKernel_L1_tendsto_seq
#print axioms Poincare.D12.HeatSemigroup.heatOperator_integrable
#print axioms Poincare.D12.HeatSemigroup.heatOperator_nonneg
#print axioms Poincare.D12.HeatSemigroup.heatOperator_tendsto_nhdsGT_zero
#print axioms Poincare.D12.HeatSemigroup.heatSemigroupKernelProduct_integrable
#print axioms Poincare.D12.HeatSemigroup.heatSmoothingBoundConst_nonneg
#print axioms Poincare.D12.HeatSemigroup.integral_gaussianKernel_sub
#print axioms Poincare.D12.HeatSemigroup.norm_le_one_add_norm_sq
#print axioms Poincare.D12.HeatSemigroup.one_add_norm_sq_mul_exp_neg_le._simp_1_2
#print axioms Poincare.D12.HeatSemigroup.one_add_norm_sq_mul_exp_neg_le._simp_1_6
#print axioms Poincare.D12.KappaVariational.ClosureRecord
#print axioms Poincare.D12.KappaVariational.ClosureRecord.constructorDecl
#print axioms Poincare.D12.KappaVariational.ClosureRecord.mk
#print axioms Poincare.D12.KappaVariational.ClosureRecord.mk.injEq
#print axioms Poincare.D12.KappaVariational.ClosureRecord.noConfusionType
#print axioms Poincare.D12.KappaVariational.ClosureRecord.statement
#print axioms Poincare.D12.KappaVariational.constantCurvatureFlow._proof_2
#print axioms Poincare.D12.KappaVariational.constantCurvatureFlow.eq_1
#print axioms Poincare.D12.KappaVariational.constantCurvatureLPath
#print axioms Poincare.D12.KappaVariational.constantCurvatureLPath._proof_4
#print axioms Poincare.D12.KappaVariational.constantCurvatureLPath.congr_simp
#print axioms Poincare.D12.KappaVariational.constantCurvatureReducedLengthData_reducedLength
#print axioms Poincare.D12.KappaVariational.constantCurvature_reducedLength
#print axioms Poincare.D12.KappaVariational.gaussianKernel_tau_eq
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolume.eq_1
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeCertificate._proof_3
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeDensity
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeDensity_pos
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeDensity_two_half_zero_ne_one
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeViaL_eq_one
#print axioms Poincare.D12.KappaVariational.gaussianUniformReducedVolumeLowerBound
#print axioms Poincare.D12.KappaVariational.gaussianVecTauNormalized
#print axioms Poincare.D12.KappaVariational.gaussianVecTau_eq_exp_neg_normSq_div
#print axioms Poincare.D12.KappaVariational.integral_gaussianReducedVolumeDensity
#print axioms Poincare.D12.KappaVariational.integral_gaussianVecTau_fubini
#print axioms Poincare.D12.KappaVariational.kappaVariationalClosures.eq_1
#print axioms Poincare.D12.KappaVariational.kappaVariationalRemainingDependencies_all_named
#print axioms Poincare.D12.KappaVariational.ncf12ModelStatement
#print axioms Poincare.D12.KappaVariational.rlv1ModelClosure
#print axioms Poincare.D12.KappaVariational.toGaussianPath
#print axioms Poincare.D12.KappaVariational.toGaussianPath._proof_4
#print axioms Poincare.D12.KappaVariational.toGaussianPath.eq_1
#print axioms Poincare.D12.ParabolicLocal.BUCf._sizeOf_inst
#print axioms Poincare.D12.ParabolicLocal.BUCf.dist_coe_le_dist
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddBUCn
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_1
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_3
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_7
#print axioms Poincare.D12.ParabolicLocal.BUCf.instCoeFunBUCnForallEuclideanSpaceRealFin
#print axioms Poincare.D12.ParabolicLocal.BUCf.instModuleRealBUCn._proof_2
#print axioms Poincare.D12.ParabolicLocal.BUCf.instModuleRealBUCn._proof_6
#print axioms Poincare.D12.ParabolicLocal.BUCf.instNormedAddCommGroupBUCn._proof_1
#print axioms Poincare.D12.ParabolicLocal.BUCf.instNormedSpaceRealBUCn
#print axioms Poincare.D12.ParabolicLocal.BUCf.instZeroBUCn
#print axioms Poincare.D12.ParabolicLocal.BUCf.mk.congr_simp
#print axioms Poincare.D12.ParabolicLocal.BUCf.mk.sizeOf_spec
#print axioms Poincare.D12.ParabolicLocal.BUCf.norm_mk
#print axioms Poincare.D12.ParabolicLocal.BUCf.recOn
#print axioms Poincare.D12.ParabolicLocal.BUCf.val_add
#print axioms Poincare.D12.ParabolicLocal.BUCf.val_sub
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.F
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.SolutionSpace
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.clamp
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.clamp_continuous
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.contractionConstant.eq_1
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.duhamelMap
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.duhamelMap.eq_1
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.existsUnique_mildSolution
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.extendToInterval_eq_of_mem
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mildSolution.congr_simp
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mildSolution_isFixedPt
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mk.congr_simp
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mk.sizeOf_spec
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.recOn
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.u₀
#print axioms Poincare.D12.ParabolicLocal.arctanBCF
#print axioms Poincare.D12.ParabolicLocal.arctanF._proof_1
#print axioms Poincare.D12.ParabolicLocal.arctanHeat_example
#print axioms Poincare.D12.ParabolicLocal.bucHeatOperator
#print axioms Poincare.D12.ParabolicLocal.bucHeatOperator._proof_4
#print axioms Poincare.D12.ParabolicLocal.continuous_heatConvPoint
#print axioms Poincare.D12.ParabolicLocal.coordCLM._proof_1
#print axioms Poincare.D12.ParabolicLocal.derivativeLossBarrier_discharged
#print axioms Poincare.D12.ParabolicLocal.domBound
#print axioms Poincare.D12.ParabolicLocal.domBound.eq_1
#print axioms Poincare.D12.ParabolicLocal.fderiv_heatConv_testF_coord
#print axioms Poincare.D12.ParabolicLocal.gaussianKernel_sub_integrable
#print axioms Poincare.D12.ParabolicLocal.gaussianS._proof_2
#print axioms Poincare.D12.ParabolicLocal.gaussianS_apply
#print axioms Poincare.D12.ParabolicLocal.gaussianS_semigroup
#print axioms Poincare.D12.ParabolicLocal.gaussianS_val_of_pos
#print axioms Poincare.D12.ParabolicLocal.gaussianSetup.eq_1
#print axioms Poincare.D12.ParabolicLocal.heatConvIntegrand_integrable
#print axioms Poincare.D12.ParabolicLocal.heatConvPoint.eq_1
#print axioms Poincare.D12.ParabolicLocal.heatConvPos._proof_1
#print axioms Poincare.D12.ParabolicLocal.heatConvPos_apply
#print axioms Poincare.D12.ParabolicLocal.heatConv_const
#print axioms Poincare.D12.ParabolicLocal.heatConv_norm_le
#print axioms Poincare.D12.ParabolicLocal.heatConv_semigroup
#print axioms Poincare.D12.ParabolicLocal.heatConv_uniformContinuous._abel_1_1
#print axioms Poincare.D12.ParabolicLocal.heatMildSolution_duhamel_eq_kernel
#print axioms Poincare.D12.ParabolicLocal.heatOperator._proof_1
#print axioms Poincare.D12.ParabolicLocal.heatOperatorCLM._proof_1
#print axioms Poincare.D12.ParabolicLocal.integral_exp_neg_mul_normSq_sq_coord
#print axioms Poincare.D12.ParabolicLocal.jointContinuous_of_absSemigroup._abel_1_2
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrand.eq_1
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv._proof_3
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv.eq_1
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrand_hasFDerivAt
#print axioms Poincare.D12.ParabolicLocal.linearCandidateSolution
#print axioms Poincare.D12.ParabolicLocal.linearCandidateSolution.congr_simp
#print axioms Poincare.D12.ParabolicLocal.linearCandidate_isFixedPt._simp_1_4
#print axioms Poincare.D12.ParabolicLocal.linearCandidate_isFixedPt._simp_1_8
#print axioms Poincare.D12.ParabolicLocal.linearHeat_example_nontrivial
#print axioms Poincare.D12.ParabolicLocal.mildToClassicalBridge
#print axioms Poincare.D12.ParabolicLocal.mildToClassicalBridge._proof_4
#print axioms Poincare.D12.ParabolicLocal.quasilinearRicciDeTurckBarrier._proof_1
#print axioms Poincare.D12.ParabolicLocal.squareF
#print axioms Poincare.D12.ParabolicLocal.squareF.eq_1
#print axioms Poincare.D12.ParabolicLocal.testF._proof_2
#print axioms Poincare.D12.ParabolicLocal.valCLM._proof_1
#print axioms Poincare.D12.SemanticLedger.D7InitialConditionAt
#print axioms Poincare.D12.SemanticLedger.continuous_gaussianKernelXY_int
#print axioms Poincare.D12.SemanticLedger.integral_undef_zero
#print axioms Poincare.D12.SemanticLedger.integrand_eq
#print axioms Poincare.D12.SemanticLedger.integrand_pos
#print axioms Poincare.D12.SemanticLedger.not_initialCondition_gaussian
#print axioms Poincare.D12.SemanticLedger.testFunction
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic._simp_1_4
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_zero_eq_mean
#print axioms Poincare.D12.SpectralSobolev.heatCoeffsL2
#print axioms Poincare.D12.SpectralSobolev.heatEvolve
#print axioms Poincare.D12.SpectralSobolev.heatEvolve_add
#print axioms Poincare.D12.SpectralSobolev.heatEvolve_zero
#print axioms Poincare.D12.SpectralSobolev.heatWeight.eq_1
#print axioms Poincare.D12.SpectralSobolev.heatWeight_nonneg
#print axioms Poincare.D12.SpectralSobolev.heat_evolution_first_mode_nontrivial
#print axioms Poincare.D12.SpectralSobolev.norm_heatEvolve_fourierLp
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger._simp_1_1
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger._simp_1_5
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger_sine
#print axioms Poincare.D12.SpectralSobolev.sq_eigenvalue_pos._simp_1_1
#print axioms Poincare.D12.SpectralSobolev.sq_norm_eigenvalue._simp_1_3
#print axioms Poincare.D12.SpectralSobolev.sq_norm_eigenvalue._simp_1_7
#print axioms Poincare.D12.SurgeryRecognition.AntipodalGroup
#print axioms Poincare.D12.SurgeryRecognition.ConnectedSumDecompositionV2
#print axioms Poincare.D12.SurgeryRecognition.ConnectedSumDecompositionV2.pieceSphere
#print axioms Poincare.D12.SurgeryRecognition.DoubleBall
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.casesOn
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.mk
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.mk.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.noConfusionType
#print axioms Poincare.D12.SurgeryRecognition.IsSpaceFormModelOf
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.ctorIdx
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.mk.injEq
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.noConfusionType
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.vanKampen
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.casesOn
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.mk._flat_ctor
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.mk.sizeOf_spec
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.recOn
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.ctorIdx
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.mk.injEq
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.noConfusionType
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.toRemaining
#print axioms Poincare.D12.SurgeryRecognition.S2Set
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.covering
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.instContinuous
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.mk
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.mk.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.quotient
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceFormProjection
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceForm_monodromy_trivial
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum._sizeOf_inst
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.mk._flat_ctor
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.mk.sizeOf_spec
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.recOn
#print axioms Poincare.D12.SurgeryRecognition.antipodal._proof_1
#print axioms Poincare.D12.SurgeryRecognition.antipodalModel
#print axioms Poincare.D12.SurgeryRecognition.antipodalQuotient
#print axioms Poincare.D12.SurgeryRecognition.antipodalVec_one
#print axioms Poincare.D12.SurgeryRecognition.antipodal_free
#print axioms Poincare.D12.SurgeryRecognition.ball3_norm_le_one
#print axioms Poincare.D12.SurgeryRecognition.ballOrigin._proof_1
#print axioms Poincare.D12.SurgeryRecognition.connectSumRel.match_1
#print axioms Poincare.D12.SurgeryRecognition.connectedSumDecomposition_expanded
#print axioms Poincare.D12.SurgeryRecognition.consVec3_fst
#print axioms Poincare.D12.SurgeryRecognition.down
#print axioms Poincare.D12.SurgeryRecognition.downPoint_fst
#print axioms Poincare.D12.SurgeryRecognition.downS3_image_S2_eq_equator
#print axioms Poincare.D12.SurgeryRecognition.down_injective
#print axioms Poincare.D12.SurgeryRecognition.equator.eq_1
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_11
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_5
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_9
#print axioms Poincare.D12.SurgeryRecognition.glueRel
#print axioms Poincare.D12.SurgeryRecognition.glueRel.eq_4
#print axioms Poincare.D12.SurgeryRecognition.height
#print axioms Poincare.D12.SurgeryRecognition.height_sq
#print axioms Poincare.D12.SurgeryRecognition.hemiGlueRel_transport
#print axioms Poincare.D12.SurgeryRecognition.instMulActionAntipodalGroupS3
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum._proof_3
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum._proof_7
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum_homeo_sphere
#print axioms Poincare.D12.SurgeryRecognition.northBall_continuous
#print axioms Poincare.D12.SurgeryRecognition.northHemisphere
#print axioms Poincare.D12.SurgeryRecognition.northHemisphereHomeo._proof_2
#print axioms Poincare.D12.SurgeryRecognition.northPole._proof_1
#print axioms Poincare.D12.SurgeryRecognition.ofSphere_continuous._simp_1_2
#print axioms Poincare.D12.SurgeryRecognition.puncturedHomeo
#print axioms Poincare.D12.SurgeryRecognition.puncturedHomeo._proof_4
#print axioms Poincare.D12.SurgeryRecognition.puncturedHomeo._proof_8
#print axioms Poincare.D12.SurgeryRecognition.quotientHomeoOfSubsingleton._proof_1
#print axioms Poincare.D12.SurgeryRecognition.quotientHomeoOfSubsingleton._proof_5
#print axioms Poincare.D12.SurgeryRecognition.quotientMapHomeo._proof_3
#print axioms Poincare.D12.SurgeryRecognition.quotientMapHomeo._proof_7
#print axioms Poincare.D12.SurgeryRecognition.southBall_continuous
#print axioms Poincare.D12.SurgeryRecognition.southHemisphereHomeo._proof_1
#print axioms Poincare.D12.SurgeryRecognition.southPuncture
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo._proof_3
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo._proof_7
#print axioms Poincare.D12.SurgeryRecognition.sphere2ToBall
#print axioms Poincare.D12.SurgeryRecognition.sphere2ToBall_injective
#print axioms Poincare.D12.SurgeryRecognition.sphereBallPart
#print axioms Poincare.D12.SurgeryRecognition.sphereConnectSum
#print axioms Poincare.D12.SurgeryRecognition.sphereSpace
#print axioms Poincare.D12.SurgeryRecognition.sphericalPieceRecognition_of
#print axioms Poincare.D12.SurgeryRecognition.stage6Target_of_v2hypotheses
#print axioms Poincare.D12.SurgeryRecognition.tailVec_continuous
#print axioms Poincare.D12.SurgeryRecognition.toSphere.eq_1
#print axioms Poincare.D12.SurgeryRecognition.toSphere_continuous
#print axioms Poincare.D12.SurgeryRecognition.transportedSouthDisk
#print axioms Poincare.D12.SurgeryRecognition.up._proof_1
#print axioms Poincare.D12.SurgeryRecognition.upPoint_fst
#print axioms Poincare.D12.SurgeryRecognition.up_mem_equator_iff
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_hamilton_field_gap_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_kernel_tangent_not_feasible_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_so3_gradsq_nonvacuous
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_so3_metric_posDef_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_so3_strict_bochner_audited
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_comm_apply
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_gradSq
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_one._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_second_comm_apply._abel_1_3
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.D
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.casesOn
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.mk._flat_ctor
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.mk.sizeOf_spec
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.recOn
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.K
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.K_antisym._abel_1_3
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.cG
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.cG_eq_torsion
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.curvatureForm_as_gamma._simp_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.eField.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.fieldInner_eField
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gA
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gamma.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gamma_self
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gradInner
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gradSq
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.hessian_symm
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.lap.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_grad_hessian
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_metric._abel_1_2
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_nabla_grad_H._simp_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.ricciForm._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.sum_gammaX_quad
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.w_du_coeff_fixed_j
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.w_du_pair_fixed_j._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitz_coefficient._abel_1_4
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitzenboeck_expand._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.FeasibleDirection
#print axioms Poincare.D12.TensorMaximumBochner.LeviCivitaIdentities.curvatureForm_pair_symm
#print axioms Poincare.D12.TensorMaximumBochner.So3.crossBracket
#print axioms Poincare.D12.TensorMaximumBochner.So3.crossLeviCivita._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.So3.curvature_eq_quarter_doubleBracket
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric._proof_4
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric._proof_8
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.D
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.D_apply
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.Dfun
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.Dfun_smul_X
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.H_self_X0
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.bochner_identity_so3_eval
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.bracket_deriv_apply
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.crossDerivation_D
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.evalAt_C
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.evalAt_rotVec_zero
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.gradSq_X0_at_e1_pos
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.laplacian_gradSq_pos_of_harmonic
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.polyVec._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.ricciForm_so3
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.rotVec_add
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.so3e1_one
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.sum_rotVec_mul_pderiv
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.xVec.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.gram_metricMatrix
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricForm
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricForm.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_deriv
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_not_posDef_at_one
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_tangent
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.negIdMatrix_as_matrix
#print axioms Poincare.D12.TensorMaximumBochner.adjugate_eq_det_smul_inv
#print axioms Poincare.D12.TensorMaximumBochner.counterexampleA.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.counterexampleN.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.diagonal_hasDerivAt
#print axioms Poincare.D12.TensorMaximumBochner.hamiltonField.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.hasDerivAt_lambdaInv
#print axioms Poincare.D12.TensorMaximumBochner.hasDerivAt_lambdaInv._simp_1_4
#print axioms Poincare.D12.TensorMaximumBochner.kernelTangent_not_feasible
#print axioms Poincare.D12.TensorMaximumBochner.lambdaInv.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.nonneg_of_nonneg_init_of_deriv_nonneg_on_nonpos_Icc
#print axioms Poincare.D12.TensorMaximumBochner.quadSelfPath_posSemidef
#print axioms Poincare.D12.TensorMaximumBochner.quadSelfSquareSub.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.tangentCondition_selfSq_sub_self
#print axioms Poincare.D12.TriangulationTopology.DoubleDisk
#print axioms Poincare.D12.TriangulationTopology.PuncturedDisk
#print axioms Poincare.D12.TriangulationTopology.SimplexBoundaryFn
#print axioms Poincare.D12.TriangulationTopology.SuspQuot
#print axioms Poincare.D12.TriangulationTopology.alexanderHomeo._proof_2
#print axioms Poincare.D12.TriangulationTopology.alexanderHomeo_refl
#print axioms Poincare.D12.TriangulationTopology.antipodalContinuousConstSMul
#print axioms Poincare.D12.TriangulationTopology.antipodalMulAction._proof_2
#print axioms Poincare.D12.TriangulationTopology.antipodalSmul_ofAdd_one
#print axioms Poincare.D12.TriangulationTopology.antipodal_smul_ofAdd_one_eq
#print axioms Poincare.D12.TriangulationTopology.clampedMap.eq_1
#print axioms Poincare.D12.TriangulationTopology.clampedMap_of_one_le
#print axioms Poincare.D12.TriangulationTopology.coneMapQuot.eq_1
#print axioms Poincare.D12.TriangulationTopology.coneMap_respects
#print axioms Poincare.D12.TriangulationTopology.coneQuotHomeoDisk._proof_2
#print axioms Poincare.D12.TriangulationTopology.coneRel
#print axioms Poincare.D12.TriangulationTopology.continuous_coneMap
#print axioms Poincare.D12.TriangulationTopology.continuous_diskToUpperHemisphere
#print axioms Poincare.D12.TriangulationTopology.continuous_lowerHemisphereToDisk
#print axioms Poincare.D12.TriangulationTopology.continuous_simplexBoundaryToSphere
#print axioms Poincare.D12.TriangulationTopology.continuous_simplexDir_apply
#print axioms Poincare.D12.TriangulationTopology.continuous_sphereToSimplexBoundary_apply
#print axioms Poincare.D12.TriangulationTopology.continuous_truncToCenter
#print axioms Poincare.D12.TriangulationTopology.coveringMap_surjective_of_pathConnected
#print axioms Poincare.D12.TriangulationTopology.disk3_boundary_eq_sphere2
#print axioms Poincare.D12.TriangulationTopology.diskDirection
#print axioms Poincare.D12.TriangulationTopology.diskDirection_sphereToDisk
#print axioms Poincare.D12.TriangulationTopology.diskGlueQuotHomeoSphere_refl_apply
#print axioms Poincare.D12.TriangulationTopology.diskGlueRel_id_iff_doubleDiskRel
#print axioms Poincare.D12.TriangulationTopology.diskGlueSumHomeo_inl
#print axioms Poincare.D12.TriangulationTopology.diskToLowerHemisphere
#print axioms Poincare.D12.TriangulationTopology.diskToLowerHemisphere_lowerHemisphereToDisk
#print axioms Poincare.D12.TriangulationTopology.diskToUpperHemisphere.eq_1
#print axioms Poincare.D12.TriangulationTopology.dist_segPiece_left
#print axioms Poincare.D12.TriangulationTopology.doubleDiskMapQuot
#print axioms Poincare.D12.TriangulationTopology.doubleDiskMap_mem_neg
#print axioms Poincare.D12.TriangulationTopology.doubleDiskQuotHomeoSphere._proof_1
#print axioms Poincare.D12.TriangulationTopology.doubleDiskRel
#print axioms Poincare.D12.TriangulationTopology.esnoc'._proof_1
#print axioms Poincare.D12.TriangulationTopology.esnoc'_lowerTrunc_eq
#print axioms Poincare.D12.TriangulationTopology.esnoc_injective2
#print axioms Poincare.D12.TriangulationTopology.exists_not_mem_finset_submodule_union._proof_1_1
#print axioms Poincare.D12.TriangulationTopology.exists_unit_notMem_segChain._proof_1_2
#print axioms Poincare.D12.TriangulationTopology.hemisphere_cover._simp_1_2
#print axioms Poincare.D12.TriangulationTopology.idChain.eq_1
#print axioms Poincare.D12.TriangulationTopology.image_weights_boundary_eq
#print axioms Poincare.D12.TriangulationTopology.linePoints_le_one_of_not_mem
#print axioms Poincare.D12.TriangulationTopology.locallyCompactSpace_of_compact_t2
#print axioms Poincare.D12.TriangulationTopology.loop_cast_target
#print axioms Poincare.D12.TriangulationTopology.lowerHemisphereCompactSpace
#print axioms Poincare.D12.TriangulationTopology.lowerHemisphereToDisk
#print axioms Poincare.D12.TriangulationTopology.lowerHemisphere_boundary_eq_inter
#print axioms Poincare.D12.TriangulationTopology.moiseWeakenedCW
#print axioms Poincare.D12.TriangulationTopology.norm_segment_sq_lower_bound
#print axioms Poincare.D12.TriangulationTopology.norm_segment_sub_left_le._abel_1_3
#print axioms Poincare.D12.TriangulationTopology.normalize_mem_sphere
#print axioms Poincare.D12.TriangulationTopology.quotMapHomeo._proof_2
#print axioms Poincare.D12.TriangulationTopology.quotMapHomeo._proof_6
#print axioms Poincare.D12.TriangulationTopology.radialExtend_apply
#print axioms Poincare.D12.TriangulationTopology.radialExtend_zero
#print axioms Poincare.D12.TriangulationTopology.restrictionChain._proof_1
#print axioms Poincare.D12.TriangulationTopology.restrictionChain._proof_5
#print axioms Poincare.D12.TriangulationTopology.restrictionChain.eq_2
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_extend_two_mul_sub_one
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_source
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_target
#print axioms Poincare.D12.TriangulationTopology.restrictionPiece._proof_2
#print axioms Poincare.D12.TriangulationTopology.restrictionPiece_homotopic_segPiece
#print axioms Poincare.D12.TriangulationTopology.rpNonempty
#print axioms Poincare.D12.TriangulationTopology.segChain._f
#print axioms Poincare.D12.TriangulationTopology.segChain._proof_4
#print axioms Poincare.D12.TriangulationTopology.segChain.eq_1
#print axioms Poincare.D12.TriangulationTopology.segChain_mem_iUnion_spans._proof_1_1
#print axioms Poincare.D12.TriangulationTopology.segPiece._proof_1
#print axioms Poincare.D12.TriangulationTopology.segPiece_mem_span
#print axioms Poincare.D12.TriangulationTopology.segmentPath._proof_2
#print axioms Poincare.D12.TriangulationTopology.segmentPath.eq_1
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeCompactSpace
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeHomeoSphereCone
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeMapQuot._proof_1
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeMap_mem
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeRel_iff_coneRel
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryHomeoBoundaryFn
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_eq_of_radial_repr._simp_1_3
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_eq_of_radial_repr._simp_1_7
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_mem_of_ne_center._simp_1_3
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_mem_of_ne_center._simp_1_7
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryToSphere._proof_1
#print axioms Poincare.D12.TriangulationTopology.simplexCenter_pos
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot_injective._simp_1_2
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot_injective._simp_1_6
#print axioms Poincare.D12.TriangulationTopology.simplexConeMap_mem
#print axioms Poincare.D12.TriangulationTopology.simplexDir_castSucc
#print axioms Poincare.D12.TriangulationTopology.simplexFnCompactSpace
#print axioms Poincare.D12.TriangulationTopology.simplexHomeoBoundaryConeStd
#print axioms Poincare.D12.TriangulationTopology.simplexHomeoStdSimplexFn._proof_1
#print axioms Poincare.D12.TriangulationTopology.simplexMin
#print axioms Poincare.D12.TriangulationTopology.simplexMin_le_center
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_eq_of_radial_repr._simp_1_3
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_eq_of_radial_repr._simp_1_7
#print axioms Poincare.D12.TriangulationTopology.simplexSet
#print axioms Poincare.D12.TriangulationTopology.simplexVertexZero_mem_boundary
#print axioms Poincare.D12.TriangulationTopology.simplyConnectedSpace_sphereThree
#print axioms Poincare.D12.TriangulationTopology.sphereCompactSpace
#print axioms Poincare.D12.TriangulationTopology.sphereNonempty
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_11
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_4
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_8
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks_hemisphere_instance._proof_1
#print axioms Poincare.D12.TriangulationTopology.spherePathConnectedSpace_of_pos
#print axioms Poincare.D12.TriangulationTopology.sphereThreeSimplyConnectedSpace
#print axioms Poincare.D12.TriangulationTopology.sphereThree_cover_isHomeo
#print axioms Poincare.D12.TriangulationTopology.sphereThree_pi1_subsingleton
#print axioms Poincare.D12.TriangulationTopology.sphereToSimplexBoundary
#print axioms Poincare.D12.TriangulationTopology.sphereToSimplexBoundary_simplexBoundaryToSphere
#print axioms Poincare.D12.TriangulationTopology.sphere_trunc_norm_sq_add_last_sq_eq_one
#print axioms Poincare.D12.TriangulationTopology.sqrt_one_sub_trunc_norm_sq_eq_neg_last
#print axioms Poincare.D12.TriangulationTopology.subdiv
#print axioms Poincare.D12.TriangulationTopology.subdivSpans_proper
#print axioms Poincare.D12.TriangulationTopology.subdiv_not_antipodal_all._proof_1_1
#print axioms Poincare.D12.TriangulationTopology.suspMapQuot.eq_1
#print axioms Poincare.D12.TriangulationTopology.suspMap_respects
#print axioms Poincare.D12.TriangulationTopology.suspQuotHomeoSphere._proof_3
#print axioms Poincare.D12.TriangulationTopology.trans_apply_extend
#print axioms Poincare.D12.TriangulationTopology.trivialization_id._proof_3
#print axioms Poincare.D12.TriangulationTopology.trivialization_id._proof_7
#print axioms Poincare.D12.TriangulationTopology.truncToCenter_ne_zero
#print axioms Poincare.D12.TriangulationTopology.trunc_norm_sq_add_last_sq_eq_one
#print axioms Poincare.D12.TriangulationTopology.upperHemisphereT2Space
#print axioms Poincare.D12.TriangulationTopology.upperHemisphereToDisk_diskToUpperHemisphere
#print axioms Poincare.D12.TriangulationTopology.zmod2_eq_zero_or_one
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism._sizeOf_inst
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.injective
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.mk.injEq
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.noConfusionType
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.surjective
#print axioms Poincare.D12.VolumeIBP.ChartMetric._sizeOf_inst
#print axioms Poincare.D12.VolumeIBP.ChartMetric.chart_ibp_euclidean_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.ctorIdx
#print axioms Poincare.D12.VolumeIBP.ChartMetric.densityNNReal.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_aemeasurable
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_measurable
#print axioms Poincare.D12.VolumeIBP.ChartMetric.det_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.det_pullbackMatrix
#print axioms Poincare.D12.VolumeIBP.ChartMetric.divergence_integral_eq_zero_density
#print axioms Poincare.D12.VolumeIBP.ChartMetric.entry_contDiff
#print axioms Poincare.D12.VolumeIBP.ChartMetric.euclideanChartMetric.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.expMetricOne._proof_2
#print axioms Poincare.D12.VolumeIBP.ChartMetric.exp_neg_contDiff_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.grad
#print axioms Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse_comm
#print axioms Poincare.D12.VolumeIBP.ChartMetric.grad_hasCompactSupport
#print axioms Poincare.D12.VolumeIBP.ChartMetric.inner.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.integral_riemannianMeasure_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix_mul
#print axioms Poincare.D12.VolumeIBP.ChartMetric.jacobianMatrix.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.laplacian
#print axioms Poincare.D12.VolumeIBP.ChartMetric.laplacian_integral_eq_zero
#print axioms Poincare.D12.VolumeIBP.ChartMetric.matrix_continuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.metricInnerInverse.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.mk.inj
#print axioms Poincare.D12.VolumeIBP.ChartMetric.noConfusion
#print axioms Poincare.D12.VolumeIBP.ChartMetric.partialDeriv_contDiff_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullbackMatrix.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullback_measure_naturality
#print axioms Poincare.D12.VolumeIBP.ChartMetric.riemannianMeasure_absolutelyContinuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.smooth
#print axioms Poincare.D12.VolumeIBP.ChartMetric.weighted_divergence_integral_eq_zero
#print axioms Poincare.D12.VolumeIBP.chartWeightedIBPStatementRestricted
#print axioms Poincare.D12.VolumeIBP.contDiff_if_const
#print axioms Poincare.D12.VolumeIBP.manifoldStokesTheorem
#print axioms Poincare.Longrun.Geometry.MetricData.mk.congr_simp
#print axioms _private.Poincare.D12.ComparisonGeodesics.SingularRiccati.0.Poincare.D12.ComparisonGeodesics.abs_sub_le_two_C
#print axioms _private.Poincare.D12.ComparisonGeodesics.SingularRiccati.0.Poincare.D12.ComparisonGeodesics.exp_neg_integral_le_of_normalization._simp_1_3
#print axioms _private.Poincare.D12.ComparisonGeodesics.SingularRiccati.0.Poincare.D12.ComparisonGeodesics.exp_neg_integral_le_of_normalization._simp_1_7
#print axioms _private.Poincare.D12.ConnectionCurvature.ConformalChartModel.0.Poincare.D12.ConnectionCurvature.conformalGamma.match_1.eq_4
#print axioms _private.Poincare.D12.ConnectionCurvature.ConformalChartModel.0.Poincare.D12.ConnectionCurvature.conformalGamma.match_1.eq_8
#print axioms _private.Poincare.D12.HeatSemigroup.AxiomAudit.0.Poincare.D12.HeatSemigroup.AxiomAudit.heatSemigroupApprovedAxioms
#print axioms _private.Poincare.D12.HeatSemigroup.Semigroup.0.Poincare.D12.HeatSemigroup.truncation.eq_1
#print axioms _private.Poincare.D12.HeatSemigroup.Semigroup.0.Poincare.D12.HeatSemigroup.truncation_norm_le_indicator
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds._simp_1_2
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds._simp_1_6
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.domBound_integrable._simp_1_3
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.domBound_integrable._simp_1_7
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.fderiv_heatConv_testF_coord._simp_1_4
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.gaussianKernel_sub_le_quarter._abel_1_1
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.sq_mul_exp_neg_mul_sq_le._simp_1_3
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.sq_mul_exp_neg_mul_sq_le._simp_1_7
#print axioms _private.Poincare.D12.SurgeryRecognition.BallGluing.0.Poincare.D12.SurgeryRecognition.glueRel.match_1.eq_1
#print axioms _private.Poincare.D12.SurgeryRecognition.BallGluing.0.Poincare.D12.SurgeryRecognition.glueRel.match_1.splitter
#print axioms _private.Poincare.D12.TriangulationTopology.SphereSimplyConnected.0.Poincare.D12.TriangulationTopology.restrictionChain.match_1.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampen.0.HatcherLib.CoveredPathChain.toPath.match_1.eq_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_adjacent_collision._proof_1_3
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_eq_of_parity_change._proof_1_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_le_or_succ._proof_1_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.incident_cell_eq_left_or_right._proof_1_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.leftCell._proof_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.leftCell_touches._proof_1_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.rightCell
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.rightCell.congr_simp
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.rightCell_val_eq_or_succ._proof_1_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.upperCell.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent.match_1.splitter
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepCell.outputWord.match_1.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepRow.rectangleOutput.match_1.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepRow.rightBoundary.match_1.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepStage.chainInput.match_1.eq_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepStage.chainOutput.match_1.eq_3
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGrid.0.HatcherLib.vanKampenWordLoop.match_1.splitter
