import Poincare.D13.IntegratedAudit.SnapshotRoot

#print axioms HatcherLib.CoverFundamentalGroup
#print axioms HatcherLib.CoveredLoop.path
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.boundary_in
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.loops
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.mk.inj
#print axioms HatcherLib.CoveredPathChain.PrefixDecomposition.noConfusion
#print axioms HatcherLib.CoveredPathChain._sizeOf_1
#print axioms HatcherLib.CoveredPathChain.brecOn.eq
#print axioms HatcherLib.CoveredPathChain.carrierSets._sunfold
#print axioms HatcherLib.CoveredPathChain.carrierSets.eq_def
#print axioms HatcherLib.CoveredPathChain.ctorIdx
#print axioms HatcherLib.CoveredPathChain.decompose_loop_with_carrierSets._simp_1_1
#print axioms HatcherLib.CoveredPathChain.extend
#print axioms HatcherLib.CoveredPathChain.extend.injEq
#print axioms HatcherLib.CoveredPathChain.loop_decomposition_of_covered_chain_with_membership
#print axioms HatcherLib.CoveredPathChain.prefixDecomposition._proof_1
#print axioms HatcherLib.CoveredPathChain.prefixDecomposition._proof_5
#print axioms HatcherLib.CoveredPathChain.prefix_loops_mem_carrierSets._simp_1_4
#print axioms HatcherLib.CoveredPathChain.single
#print axioms HatcherLib.CoveredPathChain.single.injEq
#print axioms HatcherLib.CoveredPathChain.toPath._f
#print axioms HatcherLib.CoveredSubdivisionPrefix
#print axioms HatcherLib.CoveredSubdivisionPrefix.casesOn
#print axioms HatcherLib.CoveredSubdivisionPrefix.mk
#print axioms HatcherLib.CoveredSubdivisionPrefix.mk.noConfusion
#print axioms HatcherLib.CoveredSubdivisionPrefix.rec
#print axioms HatcherLib.FreeProduct
#print axioms HatcherLib.Path
#print axioms HatcherLib.PathConnectedOpenCover
#print axioms HatcherLib.PathConnectedOpenCover.carrier
#print axioms HatcherLib.PathConnectedOpenCover.interPathConnected
#print axioms HatcherLib.PathConnectedOpenCover.mk.inj
#print axioms HatcherLib.PathConnectedOpenCover.noConfusion
#print axioms HatcherLib.PathConnectedOpenCover.recOn
#print axioms HatcherLib.PiOneSet
#print axioms HatcherLib.VanKampenFactorizationsConnected
#print axioms HatcherLib.VanKampenRectangularSubdivision.casesOn
#print axioms HatcherLib.VanKampenRectangularSubdivision.horizontalCells
#print axioms HatcherLib.VanKampenRectangularSubdivision.horizontalCut_zero
#print axioms HatcherLib.VanKampenRectangularSubdivision.mk.injEq
#print axioms HatcherLib.VanKampenRectangularSubdivision.noConfusionType
#print axioms HatcherLib.VanKampenRectangularSubdivision.verticalCut
#print axioms HatcherLib.VanKampenSquareGrid
#print axioms HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent._sunfold
#print axioms HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent.eq_3
#print axioms HatcherLib.VanKampenSquareGrid._sizeOf_1
#print axioms HatcherLib.VanKampenSquareGrid.cell.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.cellConvexHomotopy
#print axioms HatcherLib.VanKampenSquareGrid.cellConvexHomotopy._proof_4
#print axioms HatcherLib.VanKampenSquareGrid.cellConvexHomotopy._proof_8
#print axioms HatcherLib.VanKampenSquareGrid.cellMap._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.cellSweepStep_of_grid
#print axioms HatcherLib.VanKampenSquareGrid.coordinateLine
#print axioms HatcherLib.VanKampenSquareGrid.coordinateLine_one
#print axioms HatcherLib.VanKampenSquareGrid.descendingFin
#print axioms HatcherLib.VanKampenSquareGrid.horizontalBasedEdgeInCell.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.horizontalCut_mono
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeClassInCell
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeFactor.congr_simp
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeInCell._proof_1
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeInCell_map
#print axioms HatcherLib.VanKampenSquareGrid.horizontalEdgeLoop_in_incidentCells
#print axioms HatcherLib.VanKampenSquareGrid.horizontalFrontierWord_changeRow
#print axioms HatcherLib.VanKampenSquareGrid.horizontalParameterEdge._proof_3
#print axioms HatcherLib.VanKampenSquareGrid.horizontalParameterEdge_in_cell
#print axioms HatcherLib.VanKampenSquareGrid.horizontalSlice._proof_3
#print axioms HatcherLib.VanKampenSquareGrid.mk.inj
#print axioms HatcherLib.VanKampenSquareGrid.noConfusion
#print axioms HatcherLib.VanKampenSquareGrid.rightToLeftAdjacent_descendingFin
#print axioms HatcherLib.VanKampenSquareGrid.rowCellsForIndices_composable
#print axioms HatcherLib.VanKampenSquareGrid.rowSweepForIndices
#print axioms HatcherLib.VanKampenSquareGrid.sweepCell._proof_3
#print axioms HatcherLib.VanKampenSquareGrid.vertex
#print axioms HatcherLib.VanKampenSquareGrid.vertexConnectorInCell
#print axioms HatcherLib.VanKampenSquareGrid.vertexConnectorInCell_map
#print axioms HatcherLib.VanKampenSquareGrid.vertex_image_mem
#print axioms HatcherLib.VanKampenSquareGrid.verticalBasedEdgeInCell_map
#print axioms HatcherLib.VanKampenSquareGrid.verticalCut_one
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeClassInCell.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeFactor.eq_1
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeInCell._proof_2
#print axioms HatcherLib.VanKampenSquareGrid.verticalEdgeLoop.congr_simp
#print axioms HatcherLib.VanKampenSquareGrid.verticalParameterEdge
#print axioms HatcherLib.VanKampenSquareGrid.verticalParameterEdgeInCell
#print axioms HatcherLib.VanKampenSquareGrid.verticalSlice
#print axioms HatcherLib.VanKampenSweepCell
#print axioms HatcherLib.VanKampenSweepCell.Composable._unsafe_rec
#print axioms HatcherLib.VanKampenSweepCell.casesOn
#print axioms HatcherLib.VanKampenSweepCell.firstRightWord.eq_1
#print axioms HatcherLib.VanKampenSweepCell.inputWord.eq_2
#print axioms HatcherLib.VanKampenSweepCell.lastLeftWord._f
#print axioms HatcherLib.VanKampenSweepCell.lastLeftWord.eq_2
#print axioms HatcherLib.VanKampenSweepCell.mk
#print axioms HatcherLib.VanKampenSweepCell.mk.injEq
#print axioms HatcherLib.VanKampenSweepCell.noConfusionType
#print axioms HatcherLib.VanKampenSweepCell.outputWord._unsafe_rec
#print axioms HatcherLib.VanKampenSweepCell.outputWord.eq_def
#print axioms HatcherLib.VanKampenSweepCell.recOn
#print axioms HatcherLib.VanKampenSweepRow
#print axioms HatcherLib.VanKampenSweepRow.Composable._unsafe_rec
#print axioms HatcherLib.VanKampenSweepRow.casesOn
#print axioms HatcherLib.VanKampenSweepRow.left
#print axioms HatcherLib.VanKampenSweepRow.mk.injEq
#print axioms HatcherLib.VanKampenSweepRow.noConfusionType
#print axioms HatcherLib.VanKampenSweepRow.rectangleInput.eq_1
#print axioms HatcherLib.VanKampenSweepRow.rectangleOutput._sunfold
#print axioms HatcherLib.VanKampenSweepRow.rectangleOutput.eq_3
#print axioms HatcherLib.VanKampenSweepRow.rightBoundary
#print axioms HatcherLib.VanKampenSweepRow.rightBoundary.eq_1
#print axioms HatcherLib.VanKampenSweepRow.step
#print axioms HatcherLib.VanKampenSweepStage.Composable._f
#print axioms HatcherLib.VanKampenSweepStage._sizeOf_inst
#print axioms HatcherLib.VanKampenSweepStage.chainInput.eq_2
#print axioms HatcherLib.VanKampenSweepStage.chainOutput._sunfold
#print axioms HatcherLib.VanKampenSweepStage.chainOutput.eq_3
#print axioms HatcherLib.VanKampenSweepStage.equivalent_chainInput_chainOutput
#print axioms HatcherLib.VanKampenSweepStage.mk._flat_ctor
#print axioms HatcherLib.VanKampenSweepStage.mk.sizeOf_spec
#print axioms HatcherLib.VanKampenSweepStage.rec
#print axioms HatcherLib.VanKampenWordEquivalent
#print axioms HatcherLib.VanKampenWordEquivalent.change_cover
#print axioms HatcherLib.VanKampenWordMove
#print axioms HatcherLib.VanKampenWordMove.changeCover
#print axioms HatcherLib.VanKampenWordMove.recOn
#print axioms HatcherLib.affinePathHomotopy._proof_3
#print axioms HatcherLib.changeBasepoint
#print axioms HatcherLib.coverInclusion._proof_1
#print axioms HatcherLib.coverIntersectionInclusionLeft._proof_3
#print axioms HatcherLib.coverIntersectionInclusionRight._proof_3
#print axioms HatcherLib.coverIntersectionToRight_classOfLoop
#print axioms HatcherLib.coveredLoopProduct._f
#print axioms HatcherLib.coveredLoopProduct_append
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_1
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_13
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_4
#print axioms HatcherLib.coveredSubdivisionPrefix._proof_8
#print axioms HatcherLib.exists_vanKampenRectangularSubdivision
#print axioms HatcherLib.exists_vanKampenSquareGrid._proof_1_15
#print axioms HatcherLib.exists_vanKampenSquareGrid._proof_1_6
#print axioms HatcherLib.freeBasis_cardinalMk_eq_rank
#print axioms HatcherLib.freeProductInclusion.eq_1
#print axioms HatcherLib.freeProductLift_unique
#print axioms HatcherLib.fundamentalGroup_connectorSquare
#print axioms HatcherLib.inducedPiOneOfEq
#print axioms HatcherLib.mulOppositeProdMulEquiv._proof_1
#print axioms HatcherLib.pathInSubtype
#print axioms HatcherLib.pathInSubtype._proof_4
#print axioms HatcherLib.pathInSubtypeBetween
#print axioms HatcherLib.pathInSubtypeBetween._proof_4
#print axioms HatcherLib.pathInSubtype_map
#print axioms HatcherLib.pathProduct
#print axioms HatcherLib.piOneClass
#print axioms HatcherLib.simplyConnected_paths_homotopic
#print axioms HatcherLib.vanKampenClassOfLoopIn.congr_simp
#print axioms HatcherLib.vanKampenFactorCoveredLoop
#print axioms HatcherLib.vanKampenFactorLoop_in
#print axioms HatcherLib.vanKampenFactorRepresentative_mk
#print axioms HatcherLib.vanKampenMap_factor
#print axioms HatcherLib.vanKampenNormalSubgroup
#print axioms HatcherLib.vanKampenQuotientMap_surjective
#print axioms HatcherLib.vanKampenQuotientMulEquivOfKerEq._proof_1
#print axioms HatcherLib.vanKampenRelator.eq_1
#print axioms HatcherLib.vanKampenThreefoldIntersection_subset
#print axioms HatcherLib.vanKampenWordEquivalent_map_eq
#print axioms HatcherLib.vanKampenWordEvaluation._proof_1
#print axioms HatcherLib.vanKampenWordHomotopyOfMapEq
#print axioms HatcherLib.vanKampenWordLoop.eq_1
#print axioms HatcherLib.vanKampenWordLoop_append
#print axioms HatcherLib.vanKampenWordMove_quotient_eq
#print axioms HatcherLib.vanKampen_ker_eq_normalSubgroup_of_factorizationsConnected
#print axioms Poincare.D11.BochnerManifold.d7_estimate_iff_ricci_nonneg
#print axioms Poincare.D11.BochnerManifold.deriv_abs_deriv_eq_of_pos
#print axioms Poincare.D11.BochnerManifold.deriv_gradSq
#print axioms Poincare.D11.BochnerManifold.differentiable_deriv_deriv_of_contDiff
#print axioms Poincare.D11.BochnerManifold.euclidean_harmonic_subharmonic_restated
#print axioms Poincare.D11.BochnerManifold.flatCertificateWitness._proof_2
#print axioms Poincare.D11.BochnerManifold.flatCertificateWitness_ricci_zero
#print axioms Poincare.D11.BochnerManifold.frame_ricci_pairing_sum
#print axioms Poincare.D11.BochnerManifold.gradient_estimate_eq_iff_ricci_zero
#print axioms Poincare.D11.BochnerManifold.hessSq
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_deriv_eq
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_deriv_eq._simp_1_4
#print axioms Poincare.D11.BochnerManifold.jacobiMeanCurvature_of_neg
#print axioms Poincare.D11.BochnerManifold.jacobiSol_second_deriv_div
#print axioms Poincare.D11.BochnerManifold.jacobiSol_second_deriv_div._simp_1_4
#print axioms Poincare.D11.BochnerManifold.lapG
#print axioms Poincare.D11.BochnerManifold.modelBochnerCertificate._proof_1
#print axioms Poincare.D11.BochnerManifold.modelFlatBochnerCertificate._proof_1
#print axioms Poincare.D11.BochnerManifold.modelGradSq
#print axioms Poincare.D11.BochnerManifold.modelGradientCertificate._proof_1
#print axioms Poincare.D11.BochnerManifold.modelHessSq_nonneg
#print axioms Poincare.D11.BochnerManifold.modelRicciTerm.eq_1
#print axioms Poincare.D11.BochnerManifold.model_bochner_inequality_of_nonneg_ricci
#print axioms Poincare.D11.BochnerManifold.model_flat_bochner
#print axioms Poincare.D11.BochnerManifold.model_gradient_certificate_laplacian_grad_norm_sq
#print axioms Poincare.D11.BochnerManifold.radial_bochner_defect
#print axioms Poincare.D11.BochnerManifold.ricTerm
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.C_up_nonneg
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore._sizeOf_1
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.c_up
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.dim
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.dist_symm
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.heatEquation
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.mk
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.mk.noConfusion
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.normalization
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.symmetry
#print axioms Poincare.D11.HeatKernelBridge.HeatKernelCore.toHeatKernelData_toCore
#print axioms Poincare.D11.HeatKernelBridge.contDiffTwoSubmodule
#print axioms Poincare.D11.HeatKernelBridge.contDiff_gaussianKernel_translate
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_10
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_14
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_3
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore._proof_7
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_C_up
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_dist
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_heatEquation
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelCore_semigroup
#print axioms Poincare.D11.HeatKernelBridge.flatHeatKernelData_zero
#print axioms Poincare.D11.HeatKernelBridge.flatKernel
#print axioms Poincare.D11.HeatKernelBridge.flatKernel_of_nonpos
#print axioms Poincare.D11.HeatKernelBridge.flatKernel_tendsto_integral_of_hasCompactSupport
#print axioms Poincare.D11.HeatKernelBridge.laplacianLinearMap
#print axioms Poincare.D11.HeatKernelBridge.laplacianLinearMap._proof_4
#print axioms Poincare.D11.HeatKernelBridge.mem_contDiffTwoSubmodule
#print axioms Poincare.D11.HeatKernelBridge.setIntegral_compl_ball_gaussianKernel_le._simp_1_1
#print axioms Poincare.D11.HeatKernelBridge.tendsto_prefactor_mul_exp_neg_div
#print axioms Poincare.D11.HeatKernelBridge.volume_euclideanSpace_fin_zero
#print axioms Poincare.D11.MaximumPrincipleTensor.IsNullVector
#print axioms Poincare.D11.MaximumPrincipleTensor.PositivityPreserving.boundary
#print axioms Poincare.D11.MaximumPrincipleTensor.PositivityPreserving.sq
#print axioms Poincare.D11.MaximumPrincipleTensor.boundaryOnlyReaction.eq_1
#print axioms Poincare.D11.MaximumPrincipleTensor.coneInvariantUnderReaction_oneByOne
#print axioms Poincare.D11.MaximumPrincipleTensor.eulerIterate_zero
#print axioms Poincare.D11.MaximumPrincipleTensor.eulerStep_posSemidef
#print axioms Poincare.D11.MaximumPrincipleTensor.hasDerivAt_quadForm
#print axioms Poincare.D11.MaximumPrincipleTensor.negSquare
#print axioms Poincare.D11.MaximumPrincipleTensor.not_posSemidef_eulerStep_of_nullVector
#print axioms Poincare.D11.MaximumPrincipleTensor.oneByOne_apply
#print axioms Poincare.D11.MaximumPrincipleTensor.oneByOne_posSemidef_iff
#print axioms Poincare.D11.MaximumPrincipleTensor.psdCone
#print axioms Poincare.D11.MaximumPrincipleTensor.psdCone_oneByOne_iff
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm.eq_1
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm_eulerStep_nonneg_of_nullVector
#print axioms Poincare.D11.MaximumPrincipleTensor.quadForm_pos
#print axioms Poincare.D11.MaximumPrincipleTensor.scalar_invariance_oneSided_false
#print axioms Poincare.D11.MaximumPrincipleTensor.sqrtNegReaction_negSquare
#print axioms Poincare.D11.ReducedVolume.EuclideanReducedVolumeAnchor
#print axioms Poincare.D11.ReducedVolume.IsLMinimizer_of_eq_straightRay._simp_1_2
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface._sizeOf_inst
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.flow
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.mk.injEq
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.noConfusionType
#print axioms Poincare.D11.ReducedVolume.ManifoldReducedVolumeInterface.reducedVolume
#print axioms Poincare.D11.ReducedVolume.euclideanFlow.eq_1
#print axioms Poincare.D11.ReducedVolume.euclideanJacobianComparisonInterface._proof_1
#print axioms Poincare.D11.ReducedVolume.euclideanManifoldReducedVolumeInterface
#print axioms Poincare.D11.ReducedVolume.euclideanManifoldReducedVolumeInterface_reducedVolume
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolumeCertificate._proof_1
#print axioms Poincare.D11.ReducedVolume.euclideanReducedVolumeCertificate_derivative
#print axioms Poincare.D11.ReducedVolume.euclidean_LMinimizerExistence
#print axioms Poincare.D11.ReducedVolume.euclidean_reducedVolumeMonotonicity
#print axioms Poincare.D11.ReducedVolume.flatDeficit_nonneg
#print axioms Poincare.D11.ReducedVolume.flatLExponential_det
#print axioms Poincare.D11.ReducedVolume.flatReducedLength
#print axioms Poincare.D11.ReducedVolume.generalMonotonicityMissingDependencies.eq_1
#print axioms Poincare.D11.ReducedVolume.heatKernelReducedDistance._proof_1
#print axioms Poincare.D11.ReducedVolume.heatKernelReducedDistance_nonneg
#print axioms Poincare.D11.ReducedVolume.integral_reducedVolumeIntegrandUnnormalized_constant
#print axioms Poincare.D11.ReducedVolume.reducedVolume._proof_2
#print axioms Poincare.D11.ReducedVolume.reducedVolumeIntegrandUnnormalized
#print axioms Poincare.D11.ReducedVolume.reducedVolume_constant
#print axioms Poincare.D11.ReducedVolume.straightRay.eq_1
#print axioms Poincare.D11.ReducedVolume.straightRayVelocity._proof_1
#print axioms Poincare.D11.ReducedVolume.straightRay_isLMinimizer
#print axioms Poincare.D11.ReducedVolume.straightRay_zero
#print axioms Poincare.D11.SpectralTorus.circleRep
#print axioms Poincare.D11.SpectralTorus.coordProj
#print axioms Poincare.D11.SpectralTorus.differentiableAt_fourierMode
#print axioms Poincare.D11.SpectralTorus.dirDeriv_fourierMode
#print axioms Poincare.D11.SpectralTorus.finConsEquiv._proof_2
#print axioms Poincare.D11.SpectralTorus.fourierMode.eq_1
#print axioms Poincare.D11.SpectralTorus.fourierMode_hasFDerivAt
#print axioms Poincare.D11.SpectralTorus.gradNormSq
#print axioms Poincare.D11.SpectralTorus.innerForm
#print axioms Poincare.D11.SpectralTorus.innerForm_apply
#print axioms Poincare.D11.SpectralTorus.intVec._proof_2
#print axioms Poincare.D11.SpectralTorus.integral_mFourier._simp_1_1
#print axioms Poincare.D11.SpectralTorus.laplacian_fourierMode._simp_1_1
#print axioms Poincare.D11.SpectralTorus.mFourier_isEigenfunction
#print axioms Poincare.D11.SpectralTorus.normSq.eq_1
#print axioms Poincare.D11.SpectralTorus.normSq_nonneg._simp_1
#print axioms Poincare.D11.SpectralTorus.ofRealClm._proof_3
#print axioms Poincare.D11.SpectralTorus.one_add_normSq_inv_le_prod._simp_1_1
#print axioms Poincare.D11.SpectralTorus.one_add_normSq_inv_le_prod._simp_1_5
#print axioms Poincare.D11.SpectralTorus.one_le_normSq_of_ne_zero._proof_1_1
#print axioms Poincare.D11.SpectralTorus.parsevalUnitAddCircleIsProbabilityMeasure
#print axioms Poincare.D11.SpectralTorus.poincareUnitAddCircleIsAddHaarMeasure._proof_1
#print axioms Poincare.D11.SpectralTorus.poincare_trigPoly
#print axioms Poincare.D11.SpectralTorus.sobolevNorm
#print axioms Poincare.D11.SpectralTorus.sobolevUnitAddCircleIsAddHaarMeasure._proof_1
#print axioms Poincare.D11.SpectralTorus.sobolevWeight
#print axioms Poincare.D11.SpectralTorus.sobolevWeightHalf.eq_1
#print axioms Poincare.D11.SpectralTorus.summable_sobolevWeightHalf_inv
#print axioms Poincare.D11.SpectralTorus.summable_sobolevWeight_inv._simp_1_3
#print axioms Poincare.D11.SpectralTorus.summable_sobolevWeight_inv._simp_1_7
#print axioms Poincare.D11.SpectralTorus.torusDeriv
#print axioms Poincare.D11.SpectralTorus.torusFourier
#print axioms Poincare.D11.SpectralTorus.torusFourier_compat
#print axioms Poincare.D11.SpectralTorus.torusQuot.eq_1
#print axioms Poincare.D11.SpectralTorus.torusQuotHom._proof_3
#print axioms Poincare.D11.SpectralTorus.torusToUnit
#print axioms Poincare.D11.SpectralTorus.trigPoly
#print axioms Poincare.D11.SpectralTorus.trigPolyDeriv._proof_1
#print axioms Poincare.D11.SpectralTorus.trigPolyDerivL2._proof_3
#print axioms Poincare.D11.SpectralTorus.trigPolyDerivL2._proof_7
#print axioms Poincare.D11.SpectralTorus.trigPolyL2._proof_1
#print axioms Poincare.D11.SpectralTorus.trigPolyL2._proof_5
#print axioms Poincare.D11.SpectralTorus.trigPoly_apply
#print axioms Poincare.D11.SpectralTorus.trigPoly_parseval
#print axioms Poincare.D11.SpectralTorus.twoPiI._proof_1
#print axioms Poincare.D11.SpectralTorus.unitToTorus
#print axioms Poincare.D11.WarpedProductModel.initial
#print axioms Poincare.D11.WarpedProductModel.normalized_initial
#print axioms Poincare.D11.ballVolume
#print axioms Poincare.D11.ballVolume_ratio_antitoneOn
#print axioms Poincare.D11.bishopGromov_volume_comparison_sphere
#print axioms Poincare.D11.continuous_wronskian
#print axioms Poincare.D11.differentiable_wronskian
#print axioms Poincare.D11.divergenceLaplacian_eq_radialLaplacian._proof_1_2
#print axioms Poincare.D11.jacobiSol_mul_le_mul_of_le
#print axioms Poincare.D11.jacobiSol_pos_of_nonpos
#print axioms Poincare.D11.modelFlatMetric_posDef
#print axioms Poincare.D11.modelHyperbolicMetric_symm
#print axioms Poincare.D11.polarMetric
#print axioms Poincare.D11.polarMetric_jacobiSol_posDef
#print axioms Poincare.D11.polarMetric_smul_right
#print axioms Poincare.D11.radialLaplacian_id_jacobiSol
#print axioms Poincare.D11.warpedProductModel_jacobiSolHyperbolic
#print axioms Poincare.D11.wronskian_deriv
#print axioms Poincare.D12.ComparisonGeodesics.HasDerivAtR._proof_1
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.continuousOn_u
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.mk
#print axioms Poincare.D12.ComparisonGeodesics.JacobiSolutionOn.recOn
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiEqOn.eq
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiEqOn.rec
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiLeOn.casesOn
#print axioms Poincare.D12.ComparisonGeodesics.RiccatiLeOn.mk
#print axioms Poincare.D12.ComparisonGeodesics.areaRatio_antitone_of_logDeriv_le
#print axioms Poincare.D12.ComparisonGeodesics.areaRatio_hasDerivAt._simp_1_3
#print axioms Poincare.D12.ComparisonGeodesics.areaRatio_hasDerivAt._simp_1_7
#print axioms Poincare.D12.ComparisonGeodesics.bishopGromov_volume_le._simp_1_2
#print axioms Poincare.D12.ComparisonGeodesics.bishopGromov_volume_le._simp_1_6
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelA_contOn
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelA_pos
#print axioms Poincare.D12.ComparisonGeodesics.euclidModelM_contOn
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_bishopGromov
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_volume._simp_1_1
#print axioms Poincare.D12.ComparisonGeodesics.euclidModel_volume._simp_1_5
#print axioms Poincare.D12.ComparisonGeodesics.hasDerivAtR_const
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_hasDerivAt._simp_1_2
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_hasDerivAt._simp_1_6
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_le_of_le._simp_1_2
#print axioms Poincare.D12.ComparisonGeodesics.logDeriv_le_of_le._simp_1_6
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume_numerator_le_zero._simp_1_2
#print axioms Poincare.D12.ComparisonGeodesics.radialVolume_numerator_le_zero._simp_1_6
#print axioms Poincare.D12.ComparisonGeodesics.riccati_delta_le_exp
#print axioms Poincare.D12.ComparisonGeodesics.riccati_le_of_singular_normalization
#print axioms Poincare.D12.ComparisonGeodesics.solution_le_of_initial._simp_1_3
#print axioms Poincare.D12.ComparisonGeodesics.solution_le_of_initial._simp_1_7
#print axioms Poincare.D12.ComparisonGeodesics.sturm_zero_comparison_of_pos
#print axioms Poincare.D12.ComparisonGeodesics.wronskian_antitoneOn_of_le
#print axioms Poincare.D12.ComparisonGeodesics.wronskian_hasDerivAt
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.casesOn
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.christoffelLower._proof_1
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.christoffel_raised_contraction_first
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.d
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.gInv_symm
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.gram_mul_gInv_delta
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.metricDerivative_christoffel'
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.mk.inj
#print axioms Poincare.D12.ConnectionCurvature.ChartMetricCoefficients.noConfusion
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D._proof_4
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_christoffel._simp_1_3
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_christoffel._simp_1_7
#print axioms Poincare.D12.ConnectionCurvature.ChartModel1D.chart1D_curvature_zero
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData._sizeOf_1
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.chartCoefficients.eq_1
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.christoffelFamily_smooth
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.dFamily.eq_1
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.formField._proof_1
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.gInv_component_smooth
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.g_smooth
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.lieBracket_smooth
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.mk.injEq
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.nabla.eq_1
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.nabla_smooth
#print axioms Poincare.D12.ConnectionCurvature.SmoothChartData.noConfusionType
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.cross_e1_e0
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3._proof_1
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3._proof_4
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.dot3._proof_8
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3Lie._proof_1
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3Metric._proof_1
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3Metric._proof_5
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3_curvature_basis
#print axioms Poincare.D12.ConnectionCurvature.SoThreeModel.so3_ricci_symm
#print axioms Poincare.D12.ConnectionCurvature.adTranspose._proof_2
#print axioms Poincare.D12.ConnectionCurvature.adTranspose._proof_6
#print axioms Poincare.D12.ConnectionCurvature.adTranspose_apply_form
#print axioms Poincare.D12.ConnectionCurvature.chartAbstractConnection._proof_1
#print axioms Poincare.D12.ConnectionCurvature.chartCurvatureOperator.eq_1
#print axioms Poincare.D12.ConnectionCurvature.christoffel_pointwise_conformal
#print axioms Poincare.D12.ConnectionCurvature.conformalGInv
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma.eq_4
#print axioms Poincare.D12.ConnectionCurvature.conformalGamma.eq_8
#print axioms Poincare.D12.ConnectionCurvature.conformalPointwise
#print axioms Poincare.D12.ConnectionCurvature.conformalPointwise._proof_4
#print axioms Poincare.D12.ConnectionCurvature.conformal_contDiff_proj
#print axioms Poincare.D12.ConnectionCurvature.conformal_riemann_1212_origin
#print axioms Poincare.D12.ConnectionCurvature.curvatureEndo._proof_3
#print axioms Poincare.D12.ConnectionCurvature.dFormOf
#print axioms Poincare.D12.ConnectionCurvature.formOf
#print axioms Poincare.D12.ConnectionCurvature.formOf._proof_4
#print axioms Poincare.D12.ConnectionCurvature.formOf._proof_8
#print axioms Poincare.D12.ConnectionCurvature.form_nabla_eq_sum
#print axioms Poincare.D12.ConnectionCurvature.meanLeviCivitaData
#print axioms Poincare.D12.ConnectionCurvature.milnorConnection
#print axioms Poincare.D12.ConnectionCurvature.milnorConnection.eq_1
#print axioms Poincare.D12.ConnectionCurvature.milnorConnection_metricCompatible
#print axioms Poincare.D12.ConnectionCurvature.nablaOf
#print axioms Poincare.D12.ConnectionCurvature.nablaOf._proof_4
#print axioms Poincare.D12.ConnectionCurvature.nablaOf._proof_8
#print axioms Poincare.D12.ConnectionCurvature.ricci_symm
#print axioms Poincare.D12.ConnectionCurvature.sum_cycle_first_to_last
#print axioms Poincare.D12.ConnectionCurvature.trace_skew_adjoint_zero
#print axioms Poincare.D12.EntropyVariation.FDissipationCorrected.eq_1
#print axioms Poincare.D12.EntropyVariation.eventually_of_forall
#print axioms Poincare.D12.EntropyVariation.fflowEntropyData
#print axioms Poincare.D12.EntropyVariation.fflowEntropyData._proof_4
#print axioms Poincare.D12.EntropyVariation.fflowGradSq
#print axioms Poincare.D12.EntropyVariation.fflowGradSqVariation.eq_1
#print axioms Poincare.D12.EntropyVariation.fflowRiccHess.eq_1
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipationCorrected_value
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipationCorrected_value._simp_1_6
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipation_ne_corrected_one
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipation_value._simp_1_5
#print axioms Poincare.D12.EntropyVariation.fflow_FDissipation_value._simp_1_9
#print axioms Poincare.D12.EntropyVariation.fflow_F_increasing_on_Iio
#print axioms Poincare.D12.EntropyVariation.fflow_F_strictMonoOn._simp_1_3
#print axioms Poincare.D12.EntropyVariation.fflow_F_strictMonoOn._simp_1_7
#print axioms Poincare.D12.EntropyVariation.fflow_F_value._simp_1_4
#print axioms Poincare.D12.EntropyVariation.fflow_F_value._simp_1_8
#print axioms Poincare.D12.EntropyVariation.fflow_idempotency_iff_zero_dim
#print axioms Poincare.D12.EntropyVariation.fflow_literal_FDerivative_inconsistent
#print axioms Poincare.D12.EntropyVariation.fflow_riccHess_eq_zero_of_zero_dim
#print axioms Poincare.D12.EntropyVariation.fflow_variation_eq_two_riccHess_of_normSq_eq
#print axioms Poincare.D12.EntropyVariation.fflow_variation_eq_two_riccHess_of_normSq_eq._simp_1_4
#print axioms Poincare.D12.EntropyVariation.fflow_variation_integral
#print axioms Poincare.D12.EntropyVariation.fflow_variation_integral._simp_1_4
#print axioms Poincare.D12.EntropyVariation.fflow_variation_ne_two_riccHess_at_zero
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_fflowGradSq._simp_1_2
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_fflowGradSq._simp_1_6
#print axioms Poincare.D12.EntropyVariation.hasDerivAt_integral_param
#print axioms Poincare.D12.EntropyVariation.hasFDerivAt_shrinkerFpot
#print axioms Poincare.D12.EntropyVariation.integrable_normSq_mul_gaussianKernel
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_exp_neg_mul._simp_1_2
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_exp_neg_mul._simp_1_6
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_gaussianKernel._simp_1_2
#print axioms Poincare.D12.EntropyVariation.integral_normSq_mul_gaussianKernel._simp_1_6
#print axioms Poincare.D12.EntropyVariation.normSq_exp_neg_mul_le._simp_1_1
#print axioms Poincare.D12.EntropyVariation.normSq_exp_neg_mul_le._simp_1_5
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData._proof_4
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipationCorrected_value
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipationCorrected_value._simp_1_6
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipation_ne_corrected_one
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipation_value._simp_1_5
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_FDissipation_value._simp_1_9
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_F_value._simp_1_4
#print axioms Poincare.D12.EntropyVariation.shrinkerEntropyData_F_value._simp_1_8
#print axioms Poincare.D12.EntropyVariation.shrinkerFpot
#print axioms Poincare.D12.EntropyVariation.shrinkerGradSq.eq_1
#print axioms Poincare.D12.EntropyVariation.shrinkerWDissipationDensity
#print axioms Poincare.D12.EntropyVariation.shrinkerWOfTau
#print axioms Poincare.D12.EntropyVariation.shrinkerWOfTau_hasDerivAt
#print axioms Poincare.D12.EntropyVariation.shrinker_riccHess_justified._simp_1_1
#print axioms Poincare.D12.EntropyVariation.shrinker_riccHess_justified._simp_1_5
#print axioms Poincare.D12.EntropyVariation.toy_heatEnergy_nonincreasing
#print axioms Poincare.D12.GeometricCompactness.canonicalNeighborhoodFrontier
#print axioms Poincare.D12.GeometricCompactness.coordBounds
#print axioms Poincare.D12.GeometricCompactness.curvatureBoundImpliesUniformCovers
#print axioms Poincare.D12.GeometricCompactness.diam_transfer_of_hausdorffDist_lt
#print axioms Poincare.D12.GeometricCompactness.gh_subseq_of_familyBounds
#print axioms Poincare.D12.GeometricCompactness.gridFamily_subseq
#print axioms Poincare.D12.GeometricCompactness.gridPoint_coord
#print axioms Poincare.D12.GeometricCompactness.gridSpace_card
#print axioms Poincare.D12.GeometricCompactness.gridVertices.eq_1
#print axioms Poincare.D12.GeometricCompactness.hausdorffDist_grid_square_le
#print axioms Poincare.D12.GeometricCompactness.instGridSpaceNonempty
#print axioms Poincare.D12.GeometricCompactness.isCompact_of_uniformCovers
#print axioms Poincare.D12.GeometricCompactness.mk2._proof_2
#print axioms Poincare.D12.GeometricCompactness.squareGH
#print axioms Poincare.D12.GeometricCompactness.square_grid_dense._simp_1_2
#print axioms Poincare.D12.GeometricCompactness.square_grid_dense._simp_1_6
#print axioms Poincare.D12.GeometricCompactness.uniformCovers_of_totallyBounded
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.cls
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.continuousCompactSupportClass._proof_1
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.continuousIntegrableClass._proof_1
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.mk
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.mk.noConfusion
#print axioms Poincare.D12.HeatDomain.AdmissibleTestClass.rec
#print axioms Poincare.D12.HeatDomain.WeakInitialConditionFor.iff_integrableClass
#print axioms Poincare.D12.HeatDomain.bump_hasCompactSupport
#print axioms Poincare.D12.HeatDomain.bump_weakInitialCondition
#print axioms Poincare.D12.HeatDomain.continuous_integrable_of_compactSpace_finiteMeasure
#print axioms Poincare.D12.HeatDomain.fastFunction_zero
#print axioms Poincare.D12.HeatDomain.flat_positive_dimension_weak_not_full
#print axioms Poincare.D12.HeatDomain.measurableSet_halfspace
#print axioms Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel._simp_1_1
#print axioms Poincare.D12.HeatDomain.notIntegrable_fast_times_kernel._simp_1_5
#print axioms Poincare.D12.HeatDomain.not_exists_heatKernelData_flat_one
#print axioms Poincare.D12.HeatDomain.punitHeatKernelData_core_weak_iff_full
#print axioms Poincare.D12.HeatDomain.toHeatKernelData_of_weak_compact_finiteMeasure_initialCondition
#print axioms Poincare.D12.HeatDomain.volume_halfspace_eq_top._simp_1_1
#print axioms Poincare.D12.HeatDomain.weakInitialCondition_iff_full_of_compact_finiteMeasure
#print axioms Poincare.D12.HeatSemigroup.CompactManifoldSemigroupObligation
#print axioms Poincare.D12.HeatSemigroup.CompactManifoldStrongContinuityObligation
#print axioms Poincare.D12.HeatSemigroup.continuous_heatOperator
#print axioms Poincare.D12.HeatSemigroup.gaussianKernelFDerivCLM
#print axioms Poincare.D12.HeatSemigroup.gaussianKernelFDerivCLM._proof_4
#print axioms Poincare.D12.HeatSemigroup.gaussianKernel_interval_bound_le
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_apply._simp_1_1
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_apply._simp_1_5
#print axioms Poincare.D12.HeatSemigroup.heatKernelMulFDerivCLM_bound_ball._abel_1_1
#print axioms Poincare.D12.HeatSemigroup.heatOperator._proof_1
#print axioms Poincare.D12.HeatSemigroup.heatOperatorBCF._proof_1
#print axioms Poincare.D12.HeatSemigroup.heatOperatorBCF_comp
#print axioms Poincare.D12.HeatSemigroup.heatOperator_add_of_integrable
#print axioms Poincare.D12.HeatSemigroup.heatOperator_comp_heatOperator_of_bounded
#print axioms Poincare.D12.HeatSemigroup.heatOperator_eq_integral_flatKernel
#print axioms Poincare.D12.HeatSemigroup.heatOperator_gaussianKernel._abel_1_1
#print axioms Poincare.D12.HeatSemigroup.heatOperator_gaussianKernel_norm_le
#print axioms Poincare.D12.HeatSemigroup.heatOperator_integral_norm_le
#print axioms Poincare.D12.HeatSemigroup.heatOperator_norm_le_of_forall_norm_le'
#print axioms Poincare.D12.HeatSemigroup.heatOperator_tendsto_nhdsGT_zero_of_hasCompactSupport
#print axioms Poincare.D12.HeatSemigroup.heatSmoothingBoundConst._proof_1
#print axioms Poincare.D12.HeatSemigroup.integrable_gaussianKernel_sub_left
#print axioms Poincare.D12.HeatSemigroup.lintegral_enorm_gaussianKernel_sub_left
#print axioms Poincare.D12.HeatSemigroup.one_add_norm_sq_mul_exp_neg_le
#print axioms Poincare.D12.HeatSemigroup.one_add_norm_sq_mul_exp_neg_le._simp_1_4
#print axioms Poincare.D12.HeatSemigroup.tendsto_integral_abs_gaussianKernel_sub_of_seq
#print axioms Poincare.D12.KappaVariational.ClosureRecord._sizeOf_inst
#print axioms Poincare.D12.KappaVariational.ClosureRecord.dependencyName
#print axioms Poincare.D12.KappaVariational.ClosureRecord.mk.congr_simp
#print axioms Poincare.D12.KappaVariational.ClosureRecord.mk.sizeOf_spec
#print axioms Poincare.D12.KappaVariational.ClosureRecord.rec
#print axioms Poincare.D12.KappaVariational.constantCurvatureFlow
#print axioms Poincare.D12.KappaVariational.constantCurvatureFlow._proof_4
#print axioms Poincare.D12.KappaVariational.constantCurvatureFlow_scalarCurvature
#print axioms Poincare.D12.KappaVariational.constantCurvatureLPath._proof_2
#print axioms Poincare.D12.KappaVariational.constantCurvatureLPath._proof_6
#print axioms Poincare.D12.KappaVariational.constantCurvatureReducedLengthData
#print axioms Poincare.D12.KappaVariational.constantCurvature_isLMinimizer
#print axioms Poincare.D12.KappaVariational.constantCurvature_reducedLength_mono_in_R0
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolume._proof_1
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeCertificate._proof_1
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeCertificate_constant_one
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeDensity_def
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeDensity_shape_integral
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolumeViaL.eq_1
#print axioms Poincare.D12.KappaVariational.gaussianReducedVolume_eq_one
#print axioms Poincare.D12.KappaVariational.gaussianVecTau
#print axioms Poincare.D12.KappaVariational.gaussianVecTauNormalized_def
#print axioms Poincare.D12.KappaVariational.integral_exp_neg_normSq_div
#print axioms Poincare.D12.KappaVariational.integral_gaussianVecTauNormalized
#print axioms Poincare.D12.KappaVariational.intervalIntegrable_sqrt
#print axioms Poincare.D12.KappaVariational.kappaVariationalRemainingDependencies
#print axioms Poincare.D12.KappaVariational.ncf12ModelClosure
#print axioms Poincare.D12.KappaVariational.rlv10Closure.eq_1
#print axioms Poincare.D12.KappaVariational.rlv1ModelStatement
#print axioms Poincare.D12.KappaVariational.toGaussianPath._proof_2
#print axioms Poincare.D12.KappaVariational.toGaussianPath._proof_6
#print axioms Poincare.D12.ParabolicLocal.BUCf
#print axioms Poincare.D12.ParabolicLocal.BUCf.coe_apply
#print axioms Poincare.D12.ParabolicLocal.BUCf.ext
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddBUCn._proof_2
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_12
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_5
#print axioms Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._proof_9
#print axioms Poincare.D12.ParabolicLocal.BUCf.instModuleRealBUCn
#print axioms Poincare.D12.ParabolicLocal.BUCf.instModuleRealBUCn._proof_4
#print axioms Poincare.D12.ParabolicLocal.BUCf.instNegBUCn._proof_1
#print axioms Poincare.D12.ParabolicLocal.BUCf.instNormedAddCommGroupBUCn._proof_3
#print axioms Poincare.D12.ParabolicLocal.BUCf.instSMulRealBUCn
#print axioms Poincare.D12.ParabolicLocal.BUCf.mk
#print axioms Poincare.D12.ParabolicLocal.BUCf.mk.injEq
#print axioms Poincare.D12.ParabolicLocal.BUCf.noConfusionType
#print axioms Poincare.D12.ParabolicLocal.BUCf.norm_val'
#print axioms Poincare.D12.ParabolicLocal.BUCf.uniformContinuous_val
#print axioms Poincare.D12.ParabolicLocal.BUCf.val_neg
#print axioms Poincare.D12.ParabolicLocal.BUCn
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.M
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup._sizeOf_inst
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.clampSubtype
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.clamp_mem
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.ctorIdx
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.duhamelMap._proof_2
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.duhamelMap_lipschitzWith
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.extendToInterval.congr_simp
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.hM
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mildSolution_duhamel_eq
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mk
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.mk.injEq
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.noConfusionType
#print axioms Poincare.D12.ParabolicLocal.DuhamelSetup.smap_norm_le
#print axioms Poincare.D12.ParabolicLocal.abs_arctan_le_pi_div_two
#print axioms Poincare.D12.ParabolicLocal.arctanBCF._proof_2
#print axioms Poincare.D12.ParabolicLocal.arctanF_lipschitz
#print axioms Poincare.D12.ParabolicLocal.bucConst._proof_1
#print axioms Poincare.D12.ParabolicLocal.bucHeatOperator._proof_2
#print axioms Poincare.D12.ParabolicLocal.bucHeatOperator.congr_simp
#print axioms Poincare.D12.ParabolicLocal.continuous_parametric_intervalIntegral_of_base
#print axioms Poincare.D12.ParabolicLocal.coordCLM._proof_3
#print axioms Poincare.D12.ParabolicLocal.deturckFlowSymbol_eq_negativeLaplacian
#print axioms Poincare.D12.ParabolicLocal.domBound._proof_2
#print axioms Poincare.D12.ParabolicLocal.existsUnique_arctanHeatMildSolution
#print axioms Poincare.D12.ParabolicLocal.gaussianKernel_integrable
#print axioms Poincare.D12.ParabolicLocal.gaussianS
#print axioms Poincare.D12.ParabolicLocal.gaussianS_abs
#print axioms Poincare.D12.ParabolicLocal.gaussianS_of_pos
#print axioms Poincare.D12.ParabolicLocal.gaussianS_tendsto_self
#print axioms Poincare.D12.ParabolicLocal.gaussianSetup._proof_1
#print axioms Poincare.D12.ParabolicLocal.heatConv
#print axioms Poincare.D12.ParabolicLocal.heatConvPoint._proof_1
#print axioms Poincare.D12.ParabolicLocal.heatConvPoint_le_norm
#print axioms Poincare.D12.ParabolicLocal.heatConvPos.congr_simp
#print axioms Poincare.D12.ParabolicLocal.heatConv_apply_translated
#print axioms Poincare.D12.ParabolicLocal.heatConv_hasFDerivAt_zero
#print axioms Poincare.D12.ParabolicLocal.heatConv_of_nonpos
#print axioms Poincare.D12.ParabolicLocal.heatConv_tendsto_self_BUC._abel_1_1
#print axioms Poincare.D12.ParabolicLocal.heatMildSolution.eq_1
#print axioms Poincare.D12.ParabolicLocal.heatMildSolution_linear_eq
#print axioms Poincare.D12.ParabolicLocal.heatOperator._proof_5
#print axioms Poincare.D12.ParabolicLocal.heatOperator_apply
#print axioms Poincare.D12.ParabolicLocal.jointContinuous_of_absSemigroup
#print axioms Poincare.D12.ParabolicLocal.jointContinuous_of_absSemigroup._abel_1_4
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv._proof_1
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv._proof_5
#print axioms Poincare.D12.ParabolicLocal.kernelIntegrandFderiv_zero_aestronglyMeasurable
#print axioms Poincare.D12.ParabolicLocal.linearCandidate
#print axioms Poincare.D12.ParabolicLocal.linearCandidateSolution._proof_2
#print axioms Poincare.D12.ParabolicLocal.linearCandidate_isFixedPt
#print axioms Poincare.D12.ParabolicLocal.linearCandidate_isFixedPt._simp_1_6
#print axioms Poincare.D12.ParabolicLocal.linearCandidate_norm_le
#print axioms Poincare.D12.ParabolicLocal.linearSmulF_lipschitz
#print axioms Poincare.D12.ParabolicLocal.mildToClassicalBridge._proof_2
#print axioms Poincare.D12.ParabolicLocal.not_lipschitz_of_homogeneous_two
#print axioms Poincare.D12.ParabolicLocal.quasilinearRicciDeTurckBarrier_discharged
#print axioms Poincare.D12.ParabolicLocal.squareF._proof_2
#print axioms Poincare.D12.ParabolicLocal.testF
#print axioms Poincare.D12.ParabolicLocal.testF_norm_le
#print axioms Poincare.D12.ParabolicLocal.valCLM._proof_3
#print axioms Poincare.D12.SemanticLedger.R_nonneg
#print axioms Poincare.D12.SemanticLedger.gaussianKernelXY._proof_1
#print axioms Poincare.D12.SemanticLedger.integrand.eq_1
#print axioms Poincare.D12.SemanticLedger.integrand_nonneg
#print axioms Poincare.D12.SemanticLedger.lowerConstant_le_integrand
#print axioms Poincare.D12.SemanticLedger.quartic_dominates
#print axioms Poincare.D12.SemanticLedger.testFunction_pos
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic._simp_1_2
#print axioms Poincare.D12.SpectralSobolev.fourierCoeffOn_deriv_periodic._simp_1_6
#print axioms Poincare.D12.SpectralSobolev.heatCoeffs
#print axioms Poincare.D12.SpectralSobolev.heatCoeffsL2.eq_1
#print axioms Poincare.D12.SpectralSobolev.heatEvolve._proof_2
#print axioms Poincare.D12.SpectralSobolev.heatEvolve_norm_le
#print axioms Poincare.D12.SpectralSobolev.heatWeight
#print axioms Poincare.D12.SpectralSobolev.heatWeight_le_one
#print axioms Poincare.D12.SpectralSobolev.heatWeight_tendsto_one
#print axioms Poincare.D12.SpectralSobolev.integral_sin_sq_period
#print axioms Poincare.D12.SpectralSobolev.poincare_constant_sharp
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger._simp_1_3
#print axioms Poincare.D12.SpectralSobolev.poincare_wirtinger._simp_1_7
#print axioms Poincare.D12.SpectralSobolev.sine_wave_hypotheses
#print axioms Poincare.D12.SpectralSobolev.sq_norm_eigenvalue._simp_1_1
#print axioms Poincare.D12.SpectralSobolev.sq_norm_eigenvalue._simp_1_5
#print axioms Poincare.D12.SpectralSobolev.sq_norm_fourierCoeffOn_deriv_periodic
#print axioms Poincare.D12.SurgeryRecognition.ConnectedSumDecomposition.mkV2
#print axioms Poincare.D12.SurgeryRecognition.ConnectedSumDecompositionV2.mk
#print axioms Poincare.D12.SurgeryRecognition.ConnectedSumDecompositionV2.recOn
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition._sizeOf_1
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.finalTopology
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.mk.inj
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.neckEstimates
#print axioms Poincare.D12.SurgeryRecognition.EndGameDecomposition.recOn
#print axioms Poincare.D12.SurgeryRecognition.R3
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses._sizeOf_inst
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.mk._flat_ctor
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.mk.sizeOf_spec
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypotheses.rec
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2._sizeOf_1
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.ctorIdx
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.mk.injEq
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.noConfusionType
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV2.toRemaining
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3._sizeOf_inst
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.mk._flat_ctor
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.mk.sizeOf_spec
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.recOn
#print axioms Poincare.D12.SurgeryRecognition.RemainingRecognitionHypothesesV3.vanKampen
#print axioms Poincare.D12.SurgeryRecognition.S3Set
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel._sizeOf_inst
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.ctorIdx
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.instGroup
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.mk.inj
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.noConfusion
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.recOn
#print axioms Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceForm_fiber_subsingleton
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.ctorIdx
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.mk.injEq
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.noConfusionType
#print axioms Poincare.D12.SurgeryRecognition.SphericalSum.sumHomeo
#print axioms Poincare.D12.SurgeryRecognition.antipodalCoveringMap
#print axioms Poincare.D12.SurgeryRecognition.antipodalModel._proof_2
#print axioms Poincare.D12.SurgeryRecognition.antipodalVec
#print axioms Poincare.D12.SurgeryRecognition.antipodal_fiber_card_two
#print axioms Poincare.D12.SurgeryRecognition.antipodal_one
#print axioms Poincare.D12.SurgeryRecognition.ballEquator._proof_1
#print axioms Poincare.D12.SurgeryRecognition.connectSumCongr._proof_1
#print axioms Poincare.D12.SurgeryRecognition.connectSumRel_transport
#print axioms Poincare.D12.SurgeryRecognition.consVec3._proof_1
#print axioms Poincare.D12.SurgeryRecognition.deckTrivial_of_simplyConnected_quotient
#print axioms Poincare.D12.SurgeryRecognition.downPoint
#print axioms Poincare.D12.SurgeryRecognition.downPoint_sphereBallPart_eq_of_nonpos
#print axioms Poincare.D12.SurgeryRecognition.downS3_sphereBallPart_eq_of_eq_zero
#print axioms Poincare.D12.SurgeryRecognition.endGame_finalTopology
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_1
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_3
#print axioms Poincare.D12.SurgeryRecognition.equatorHomeoS2._proof_7
#print axioms Poincare.D12.SurgeryRecognition.extinctionCertificate_expanded
#print axioms Poincare.D12.SurgeryRecognition.glueRel.eq_2
#print axioms Poincare.D12.SurgeryRecognition.glueRel_equiv
#print axioms Poincare.D12.SurgeryRecognition.height_sphereBallPart_eq_fst_of_nonneg
#print axioms Poincare.D12.SurgeryRecognition.hemiGlueRel.match_1
#print axioms Poincare.D12.SurgeryRecognition.hemisphere_cover
#print axioms Poincare.D12.SurgeryRecognition.instMulActionAntipodalGroupS3._proof_2
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum._proof_1
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum._proof_5
#print axioms Poincare.D12.SurgeryRecognition.iteratedSphereSum._unsafe_rec
#print axioms Poincare.D12.SurgeryRecognition.norm_sq_consVec3
#print axioms Poincare.D12.SurgeryRecognition.northBall_mem_S2_iff
#print axioms Poincare.D12.SurgeryRecognition.northHemisphereHomeo
#print axioms Poincare.D12.SurgeryRecognition.northHemisphereHomeo_symm_apply
#print axioms Poincare.D12.SurgeryRecognition.ofSphere
#print axioms Poincare.D12.SurgeryRecognition.openBallInBall
#print axioms Poincare.D12.SurgeryRecognition.puncturedHomeo._proof_2
#print axioms Poincare.D12.SurgeryRecognition.puncturedHomeo._proof_6
#print axioms Poincare.D12.SurgeryRecognition.puncturedOfDisk
#print axioms Poincare.D12.SurgeryRecognition.quotientHomeoOfSubsingleton._proof_3
#print axioms Poincare.D12.SurgeryRecognition.quotientMapHomeo._proof_1
#print axioms Poincare.D12.SurgeryRecognition.quotientMapHomeo._proof_5
#print axioms Poincare.D12.SurgeryRecognition.recognitionHypotheses_expanded
#print axioms Poincare.D12.SurgeryRecognition.southHemisphere
#print axioms Poincare.D12.SurgeryRecognition.southPole
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo._proof_1
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo._proof_5
#print axioms Poincare.D12.SurgeryRecognition.southPunctureHomeo._proof_9
#print axioms Poincare.D12.SurgeryRecognition.sphere2ToBall.eq_1
#print axioms Poincare.D12.SurgeryRecognition.sphere2_norm_eq_one_of_mem
#print axioms Poincare.D12.SurgeryRecognition.sphereBallPart.eq_1
#print axioms Poincare.D12.SurgeryRecognition.sphereConnectSum_homeo_sphere
#print axioms Poincare.D12.SurgeryRecognition.sphere_norm_eq_one
#print axioms Poincare.D12.SurgeryRecognition.sphericalPieceRecognition_of_spaceForm
#print axioms Poincare.D12.SurgeryRecognition.tailVec
#print axioms Poincare.D12.SurgeryRecognition.tailVec_norm_le_one_of_norm_eq_one
#print axioms Poincare.D12.SurgeryRecognition.toSpherePre.eq_1
#print axioms Poincare.D12.SurgeryRecognition.toSphere_origin_first
#print axioms Poincare.D12.SurgeryRecognition.transportedSouthDisk_injective
#print axioms Poincare.D12.SurgeryRecognition.upPoint.eq_1
#print axioms Poincare.D12.SurgeryRecognition.up_continuous
#print axioms Poincare.D12.TensorMaximumBochner.Audit.bochnerStatement_is_statement_only
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_horizon_max_principle_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_pair_symm_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_so3_laplacian_nondegenerate
#print axioms Poincare.D12.TensorMaximumBochner.Audit.d12_so3_ricci_flow_audited
#print axioms Poincare.D12.TensorMaximumBochner.Audit.zero_bridge_is_zero_calculus
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_const
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_nabla
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_second_comm_apply._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.D_second_comm_diag._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData._sizeOf_inst
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.leibniz
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.mk.injEq
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.DerivationData.noConfusionType
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.H.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.K_antisym._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.bochner_identity
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.cG_antisym
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.cG_self._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.eField
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.fieldInner
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.fieldInner_gradLapField_expand
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gamma._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gammaX.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gradField
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.gradLapField
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.hessSq
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.hessian_symm._abel_1_2
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_eField
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_metric
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.nablaField_nabla_grad_H
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.ricciContraction.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.sum_gammaX_bilin_pair
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.ui
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.w_du_coeff_fixed_j._simp_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitz_coefficient._abel_1_1
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitz_coefficient._simp_1_3
#print axioms Poincare.D12.TensorMaximumBochner.Bochner.weitzenboeck_half
#print axioms Poincare.D12.TensorMaximumBochner.LeviCivitaIdentities.curvatureForm_add_last_pair
#print axioms Poincare.D12.TensorMaximumBochner.LeviCivitaIdentities.ricci_symm
#print axioms Poincare.D12.TensorMaximumBochner.So3.crossBracket._proof_2
#print axioms Poincare.D12.TensorMaximumBochner.So3.crossLeviCivita._proof_3
#print axioms Poincare.D12.TensorMaximumBochner.So3.sectional_nonflat
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric._proof_2
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric._proof_6
#print axioms Poincare.D12.TensorMaximumBochner.So3.stdMetric.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.D._proof_2
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.D_leibniz
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.Dfun_add_X
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.Dfun_zero
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.bochner_identity_so3
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.bochner_inequality_so3_strict
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.crossDerivation
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.dot_xVec_polyVec_basis
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.evalAt_gradSq_nonneg
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.gradSq_X0
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.lap_X0_ne_zero
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.pderiv_rotVec
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.polyVec.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.rotVec._proof_1
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.rotVec_smul
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.so3e1_zero
#print axioms Poincare.D12.TensorMaximumBochner.So3Polynomial.ui_X0
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.dotProduct_mulVec_negIdMatrix
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.idMatrix.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricForm._proof_2
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricForm_at_zero_nonvacuous
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_as_matrix
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_hasDerivAt
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.metricMatrix_posSemidef
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.negIdMatrix
#print axioms Poincare.D12.TensorMaximumBochner.So3RicciFlow.stdMetric_basis_eq
#print axioms Poincare.D12.TensorMaximumBochner.continuous_dotProduct_mulVec
#print axioms Poincare.D12.TensorMaximumBochner.counterexampleA_posSemidef
#print axioms Poincare.D12.TensorMaximumBochner.counterexample_nondegenerate
#print axioms Poincare.D12.TensorMaximumBochner.exists_first_zero
#print axioms Poincare.D12.TensorMaximumBochner.hamiltonField_kernel_witness
#print axioms Poincare.D12.TensorMaximumBochner.hasDerivAt_lambdaInv._simp_1_2
#print axioms Poincare.D12.TensorMaximumBochner.hasDerivAt_lambdaInv._simp_1_6
#print axioms Poincare.D12.TensorMaximumBochner.kernelTangent_of_posSemidef_path
#print axioms Poincare.D12.TensorMaximumBochner.negSqrtCounterexample
#print axioms Poincare.D12.TensorMaximumBochner.quadSelfPath.eq_1
#print axioms Poincare.D12.TensorMaximumBochner.quadSelfPath_stays_posSemidef
#print axioms Poincare.D12.TensorMaximumBochner.staysPosSemidef_of_tangent
#print axioms Poincare.D12.TriangulationTopology.Disk
#print axioms Poincare.D12.TriangulationTopology.LocallyEuclideanOfDimension
#print axioms Poincare.D12.TriangulationTopology.SimplexBoundary
#print axioms Poincare.D12.TriangulationTopology.Sphere
#print axioms Poincare.D12.TriangulationTopology.alexanderHomeo
#print axioms Poincare.D12.TriangulationTopology.alexanderHomeo._proof_4
#print axioms Poincare.D12.TriangulationTopology.alexanderHomeo_symm_sphereToDisk
#print axioms Poincare.D12.TriangulationTopology.antipodalMulAction
#print axioms Poincare.D12.TriangulationTopology.antipodalSmul
#print axioms Poincare.D12.TriangulationTopology.antipodalSmul_one._simp_1_2
#print axioms Poincare.D12.TriangulationTopology.clampedMap
#print axioms Poincare.D12.TriangulationTopology.clampedMap_coe
#print axioms Poincare.D12.TriangulationTopology.coneMap.eq_1
#print axioms Poincare.D12.TriangulationTopology.coneMapQuot_surjective
#print axioms Poincare.D12.TriangulationTopology.coneQuotHomeoDisk
#print axioms Poincare.D12.TriangulationTopology.coneQuotHomeoTopCatDisk
#print axioms Poincare.D12.TriangulationTopology.continuous_antipodal_ofAdd_one
#print axioms Poincare.D12.TriangulationTopology.continuous_diskDirection_punctured
#print axioms Poincare.D12.TriangulationTopology.continuous_doubleDiskMapQuot
#print axioms Poincare.D12.TriangulationTopology.continuous_simplexBoundaryConeMap
#print axioms Poincare.D12.TriangulationTopology.continuous_simplexConeMapQuot
#print axioms Poincare.D12.TriangulationTopology.continuous_sphereToSimplexBoundary
#print axioms Poincare.D12.TriangulationTopology.continuous_suspMap
#print axioms Poincare.D12.TriangulationTopology.contractibleSpace_puncturedSphere
#print axioms Poincare.D12.TriangulationTopology.coveringOfSimplyConnectedIsHomeo_bijective
#print axioms Poincare.D12.TriangulationTopology.diskContractible
#print axioms Poincare.D12.TriangulationTopology.diskDirection_of_ne
#print axioms Poincare.D12.TriangulationTopology.diskGlueQuotHomeoSphere
#print axioms Poincare.D12.TriangulationTopology.diskGlueQuotT2Space
#print axioms Poincare.D12.TriangulationTopology.diskGlueSumHomeo
#print axioms Poincare.D12.TriangulationTopology.diskNonempty
#print axioms Poincare.D12.TriangulationTopology.diskToLowerHemisphere._proof_2
#print axioms Poincare.D12.TriangulationTopology.diskToUpperHemisphere._proof_1
#print axioms Poincare.D12.TriangulationTopology.disk_boundary_eq_sphere
#print axioms Poincare.D12.TriangulationTopology.doubleDiskMap
#print axioms Poincare.D12.TriangulationTopology.doubleDiskMapQuot_injective
#print axioms Poincare.D12.TriangulationTopology.doubleDiskMap_respects
#print axioms Poincare.D12.TriangulationTopology.doubleDiskQuotHomeoTopCatSphere
#print axioms Poincare.D12.TriangulationTopology.esnoc
#print axioms Poincare.D12.TriangulationTopology.esnoc'_castSucc
#print axioms Poincare.D12.TriangulationTopology.esnoc.eq_1
#print axioms Poincare.D12.TriangulationTopology.exists_fine_subdivision
#print axioms Poincare.D12.TriangulationTopology.exists_unit_notMem_segChain
#print axioms Poincare.D12.TriangulationTopology.hemisphere_cover
#print axioms Poincare.D12.TriangulationTopology.iccCompactSpace
#print axioms Poincare.D12.TriangulationTopology.idChain_zero
#print axioms Poincare.D12.TriangulationTopology.isCoveringMap_id
#print axioms Poincare.D12.TriangulationTopology.linePoints_le_one_of_not_mem'._abel_1_1
#print axioms Poincare.D12.TriangulationTopology.longrun_missingSphereThreeSimplyConnected
#print axioms Poincare.D12.TriangulationTopology.loop_homotopic_segChain._proof_1_1
#print axioms Poincare.D12.TriangulationTopology.lowerHemisphereNonempty
#print axioms Poincare.D12.TriangulationTopology.lowerHemisphereToDisk.eq_1
#print axioms Poincare.D12.TriangulationTopology.lowerTrunc
#print axioms Poincare.D12.TriangulationTopology.norm_esnoc_smul_sqrt_sub_sq_eq_one
#print axioms Poincare.D12.TriangulationTopology.norm_segment_sub_left_le._abel_1_1
#print axioms Poincare.D12.TriangulationTopology.norm_sq_esnoc
#print axioms Poincare.D12.TriangulationTopology.quotMapHomeo
#print axioms Poincare.D12.TriangulationTopology.quotMapHomeo._proof_4
#print axioms Poincare.D12.TriangulationTopology.radialExtend
#print axioms Poincare.D12.TriangulationTopology.radialExtend_id
#print axioms Poincare.D12.TriangulationTopology.restrictionChain
#print axioms Poincare.D12.TriangulationTopology.restrictionChain._proof_3
#print axioms Poincare.D12.TriangulationTopology.restrictionChain._unsafe_rec
#print axioms Poincare.D12.TriangulationTopology.restrictionChain.match_1
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_homotopic_segChain._proof_1_1
#print axioms Poincare.D12.TriangulationTopology.restrictionChain_succ_apply
#print axioms Poincare.D12.TriangulationTopology.restrictionPiece
#print axioms Poincare.D12.TriangulationTopology.restrictionPiece_apply
#print axioms Poincare.D12.TriangulationTopology.restrictionPiece_id_extend_two_mul
#print axioms Poincare.D12.TriangulationTopology.rpT2Space
#print axioms Poincare.D12.TriangulationTopology.segChain._proof_2
#print axioms Poincare.D12.TriangulationTopology.segChain._unsafe_rec
#print axioms Poincare.D12.TriangulationTopology.segChain.eq_def
#print axioms Poincare.D12.TriangulationTopology.segChain_mem_iUnion_spans._proof_1_3
#print axioms Poincare.D12.TriangulationTopology.segPiece.congr_simp
#print axioms Poincare.D12.TriangulationTopology.segmentPath._abel_1
#print axioms Poincare.D12.TriangulationTopology.segmentPath._proof_4
#print axioms Poincare.D12.TriangulationTopology.segment_ne_zero
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeHomeoSimplex._proof_1
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeMap.eq_1
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeMapQuot_injective
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryConeNonempty
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryFnCompactSpace
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryHomeoSphere
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_eq_of_radial_repr._simp_1_1
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_eq_of_radial_repr._simp_1_5
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_mem_of_ne_center._simp_1_1
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryPoint_mem_of_ne_center._simp_1_5
#print axioms Poincare.D12.TriangulationTopology.simplexBoundaryT2Space
#print axioms Poincare.D12.TriangulationTopology.simplexCenter
#print axioms Poincare.D12.TriangulationTopology.simplexConeMap
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot.eq_1
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot_injective._simp_1_4
#print axioms Poincare.D12.TriangulationTopology.simplexConeMapQuot_injective._simp_1_8
#print axioms Poincare.D12.TriangulationTopology.simplexDir
#print axioms Poincare.D12.TriangulationTopology.simplexDir_of_simplexBoundaryToSphere
#print axioms Poincare.D12.TriangulationTopology.simplexFnT2Space
#print axioms Poincare.D12.TriangulationTopology.simplexHomeoDisk
#print axioms Poincare.D12.TriangulationTopology.simplexLambda
#print axioms Poincare.D12.TriangulationTopology.simplexMin_eq_zero_of_mem_boundary
#print axioms Poincare.D12.TriangulationTopology.simplexMin_neg_of_unit
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_eq_of_radial_repr._simp_1_1
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_eq_of_radial_repr._simp_1_5
#print axioms Poincare.D12.TriangulationTopology.simplexRadialTime_nonneg
#print axioms Poincare.D12.TriangulationTopology.simplexVertexZero._proof_1
#print axioms Poincare.D12.TriangulationTopology.simplyConnectedSpace_sphere
#print axioms Poincare.D12.TriangulationTopology.span_pair_ne_top._proof_1_1
#print axioms Poincare.D12.TriangulationTopology.sphereConeHomeoSimplex._proof_1
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_1
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_2
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks._proof_6
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks.match_1
#print axioms Poincare.D12.TriangulationTopology.sphereOfTwoDisks_hemisphere_instance._proof_3
#print axioms Poincare.D12.TriangulationTopology.sphereSimplyConnectedSpaceOfFact
#print axioms Poincare.D12.TriangulationTopology.sphereThreeTarget_cover_isHomeo
#print axioms Poincare.D12.TriangulationTopology.sphereThree_fundamentalGroup_subsingleton
#print axioms Poincare.D12.TriangulationTopology.sphereToDisk._proof_1
#print axioms Poincare.D12.TriangulationTopology.sphereToSimplexBoundaryFn
#print axioms Poincare.D12.TriangulationTopology.sphere_eq_neg_self_impossible
#print axioms Poincare.D12.TriangulationTopology.sqrt_one_sub_sq_eq_norm_of_norm_sq_add_sq_eq_one
#print axioms Poincare.D12.TriangulationTopology.stage6_sphereThreePiOneTrivial
#print axioms Poincare.D12.TriangulationTopology.subdivPoint
#print axioms Poincare.D12.TriangulationTopology.subdiv_not_antipodal
#print axioms Poincare.D12.TriangulationTopology.suspMap.eq_1
#print axioms Poincare.D12.TriangulationTopology.suspMapQuot_surjective
#print axioms Poincare.D12.TriangulationTopology.suspQuotHomeoSphere._proof_1
#print axioms Poincare.D12.TriangulationTopology.suspQuotNonempty
#print axioms Poincare.D12.TriangulationTopology.trivialization_id._proof_1
#print axioms Poincare.D12.TriangulationTopology.trivialization_id._proof_5
#print axioms Poincare.D12.TriangulationTopology.truncToCenter
#print axioms Poincare.D12.TriangulationTopology.truncToCenter_simplexConeMap
#print axioms Poincare.D12.TriangulationTopology.upperHemisphereHomeoDisk
#print axioms Poincare.D12.TriangulationTopology.upperHemisphereToDisk._proof_1
#print axioms Poincare.D12.TriangulationTopology.vanKampenSimplyConnectedCover
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.ctorIdx
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.mk._flat_ctor
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.mk.sizeOf_spec
#print axioms Poincare.D12.VolumeIBP.ChartDiffeomorphism.recOn
#print axioms Poincare.D12.VolumeIBP.ChartMetric
#print axioms Poincare.D12.VolumeIBP.ChartMetric.casesOn
#print axioms Poincare.D12.VolumeIBP.ChartMetric.chart_ibp_self
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.densityNNReal_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_contDiff_one
#print axioms Poincare.D12.VolumeIBP.ChartMetric.density_nonneg
#print axioms Poincare.D12.VolumeIBP.ChartMetric.det_ne_zero
#print axioms Poincare.D12.VolumeIBP.ChartMetric.divergence.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.driftLaplacian.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.euclideanChartMetric._proof_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.expMetricOne
#print axioms Poincare.D12.VolumeIBP.ChartMetric.expMetricOne._proof_4
#print axioms Poincare.D12.VolumeIBP.ChartMetric.g_continuous
#print axioms Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse
#print axioms Poincare.D12.VolumeIBP.ChartMetric.gradInnerInverse_eq_sum
#print axioms Poincare.D12.VolumeIBP.ChartMetric.hasCompactSupport_partialDeriv
#print axioms Poincare.D12.VolumeIBP.ChartMetric.inner_grad_eq_gradInnerInverse
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.invMatrix_symm
#print axioms Poincare.D12.VolumeIBP.ChartMetric.jacobianMatrix_mulVec_eq_fderiv
#print axioms Poincare.D12.VolumeIBP.ChartMetric.laplacian_contDiff_two
#print axioms Poincare.D12.VolumeIBP.ChartMetric.matrix.eq_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.matrix_symm
#print axioms Poincare.D12.VolumeIBP.ChartMetric.mk._flat_ctor
#print axioms Poincare.D12.VolumeIBP.ChartMetric.mk.noConfusion
#print axioms Poincare.D12.VolumeIBP.ChartMetric.partialDeriv
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullbackDensity_eq
#print axioms Poincare.D12.VolumeIBP.ChartMetric.pullbackMetric._proof_1
#print axioms Poincare.D12.VolumeIBP.ChartMetric.recOn
#print axioms Poincare.D12.VolumeIBP.ChartMetric.riemannianMeasure_univ
#print axioms Poincare.D12.VolumeIBP.ChartMetric.weightedDivergence
#print axioms Poincare.D12.VolumeIBP.ChartMetric.weighted_divergence_mul_grad
#print axioms Poincare.D12.VolumeIBP.chartWeightedIBPStatementRestricted_holds
#print axioms Poincare.D12.VolumeIBP.manifoldOrientationVolumeFormCompat
#print axioms Poincare.D7.HeatKernel.HeatKernelData.toCore_fullInitialCondition
#print axioms _private.Poincare.D11.HeatKernelBridge.AxiomAudit.0.bridgeApprovedAxioms
#print axioms _private.Poincare.D12.ComparisonGeodesics.SingularRiccati.0.Poincare.D12.ComparisonGeodesics.exp_neg_integral_le_of_normalization._simp_1_1
#print axioms _private.Poincare.D12.ComparisonGeodesics.SingularRiccati.0.Poincare.D12.ComparisonGeodesics.exp_neg_integral_le_of_normalization._simp_1_5
#print axioms _private.Poincare.D12.ConnectionCurvature.ConformalChartModel.0.Poincare.D12.ConnectionCurvature.conformalGamma.match_1.eq_2
#print axioms _private.Poincare.D12.ConnectionCurvature.ConformalChartModel.0.Poincare.D12.ConnectionCurvature.conformalGamma.match_1.eq_6
#print axioms _private.Poincare.D12.HeatDomain.AxiomAudit.0.heatDomainApprovedAxioms
#print axioms _private.Poincare.D12.HeatSemigroup.Semigroup.0.Poincare.D12.HeatSemigroup.integral_kernel_cross_sub_left
#print axioms _private.Poincare.D12.HeatSemigroup.Semigroup.0.Poincare.D12.HeatSemigroup.truncation_integrable
#print axioms _private.Poincare.D12.ParabolicLocal.BUC.0.Poincare.D12.ParabolicLocal.BUCf.instAddCommGroupBUCn._abel_10
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.derivativeLossBarrier_holds._simp_1_4
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.domBound_integrable._simp_1_1
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.domBound_integrable._simp_1_5
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.fderiv_heatConv_testF_coord._simp_1_2
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.fderiv_heatConv_testF_coord._simp_1_6
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.sq_mul_exp_neg_mul_sq_le._simp_1_1
#print axioms _private.Poincare.D12.ParabolicLocal.DerivativeLoss.0.Poincare.D12.ParabolicLocal.sq_mul_exp_neg_mul_sq_le._simp_1_5
#print axioms _private.Poincare.D12.SemanticLedger.AxiomAudit.0.Poincare.D12.SemanticLedger.d12ApprovedAxioms
#print axioms _private.Poincare.D12.SurgeryRecognition.BallGluing.0.Poincare.D12.SurgeryRecognition.glueRel.match_1.eq_3
#print axioms _private.Poincare.D12.TriangulationTopology.SpherePolygonal.0.Poincare.D12.TriangulationTopology.restrictionChain.match_1.eq_2
#print axioms _private.Poincare.D12.TriangulationTopology.SphereSimplyConnected.0.Poincare.D12.TriangulationTopology.restrictionChain.match_1.splitter
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.abs_sub_addNSMul_le_two
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_adjacent_collision._proof_1_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_adjacent_eq_or_of_bounds
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.dominoAnchor_le_or_succ
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.incident_cell_eq_left_or_right
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.leftCell
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.leftCell.congr_simp
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.lowerCell.congr_simp
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.rightCell._proof_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.rightCell_touches._proof_1_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenAdaptedGrid.0.HatcherLib.upperCell
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSquareGrid.RightToLeftAdjacent.match_1.eq_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepCell.inputWord.match_1.eq_2
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepCell.outputWord.match_1.eq_3
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepRow.rectangleOutput.match_1.eq_3
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepRow.rightBoundary.match_1.splitter
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGlobalSweep.0.HatcherLib.VanKampenSweepStage.chainOutput.match_1.eq_1
#print axioms _private.Poincare.VKPort.HatcherLib.Ch1.VanKampenGrid.0.HatcherLib.vanKampenWordLoop.match_1.eq_1
