/-
Copyright (c) 2026 Poincare Lab. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Poincare Lab (task D11-triangulation-3d)
-/
import Mathlib.Data.Finset.Card
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.GroupTheory.Perm.Sign
import Mathlib.Tactic

/-!
# Face-pairing triangulations of 3-manifolds (generalized triangulations)

This file fixes the combinatorial notion of a **3-dimensional generalized triangulation**
(a.k.a. Δ-complex triangulation, face-pairing description): a finite collection of abstract
tetrahedra together with a partial matching of their boundary triangles, each pair glued by
an affine (corner) identification.  Everything is *unconditional*: there are no postulates,
no holes and no kernel bypasses.  The data are plain finite functions, so every check below
is decidable by computation for a concrete gluing.

## Data

A **corner** is a pair `(t, j)` with `t : Fin N` the tetrahedron and `j : Fin 4` the corner
of that tetrahedron.  The face `(t, i)` of a tetrahedron is the triangle opposite corner `i`.
A gluing of `(t, i)` to `(t', i')` is a bijection `g : Fin 4 ≃ Fin 4` with `g i = i'`; the
corner `(t, j)` (`j ≠ i`) is identified with `(t', g j)`.

* `Consistent`: the pairing is a partial involution (a face is glued at most once, its
  partner is glued back by the inverse map, and no face is glued to itself).
* `OrientationReversing`: each gluing reverses the induced boundary orientations
  (`sign(π) = (-1)^(i + i' + 1)`, where `π` is the permutation of the increasing orders of
  the two faces).  This is exactly the condition that the quotient carries the orientation
  induced by the consistently oriented tetrahedra.
* `Closed`: every face is glued.

## The quotient

The classes of corners, edges and triangles under the identifications generated by the
gluings are computed by the union-find pass `componentsOf`, whose correctness is proved
(`componentsOf_spec`): two elements end up in the same block exactly when they are joined by
a chain of generating identifications.  The **Euler characteristic** is then
`eulerChar3 = V - E + F - T`, computed from the class counts, and `0` for every closed
3-manifold.

## The combinatorial manifold condition

For each vertex class the **link** is the complex whose triangles are the faces opposite the
corners of the class (a link triangle is the set of edge classes of such a face).  The
decidable manifold checks used throughout are:

* `VertexLinkIsSphere`: every link triangle has three distinct edge classes, every pair of
  edge classes lies in exactly two link triangles, the link has `χ = 2` and is connected.
* `VertexLinkIsDisk`: every pair lies in at most two link triangles, the pairs lying in one
  form a single cycle, and `χ = 1` — the link of a boundary vertex.
* `EdgeLinkIsCycle` / `EdgeLinkIsPath`: the face–tetrahedron incidence around each edge
  class is a single cycle / path.

The conjunction `IsCombinatorialManifoldWithBoundary` expresses: consistent pairing,
orientation-reversing gluings, sphere links at interior vertices, disk links at boundary
vertices, cycle/path edge links, and a boundary made of a closed orientable surface with
Euler characteristic `0` (torus conditions in the orientable case).
-/

set_option maxRecDepth 1000000
set_option maxHeartbeats 2000000
-- The composite decidable predicates below (vertex links inside the manifold condition)
-- need a deeper type class search than the default limit of 128.
set_option synthInstance.maxSize 4096

open Finset

namespace Poincare

namespace D11

namespace Triangulation3D

universe u

/-- A **corner** of a tetrahedron: tetrahedron `t` and corner index `j`. -/
structure Corner (N : ℕ) where
  t : Fin N
  j : Fin 4
  deriving DecidableEq, Fintype

def cornerFin (c : Corner N) : Fin (N * 4) := ⟨c.t.val * 4 + c.j.val, by omega⟩

instance (N : ℕ) : Max (Corner N) := ⟨fun a b => if cornerFin a ≤ cornerFin b then b else a⟩
instance (N : ℕ) : Min (Corner N) := ⟨fun a b => if cornerFin a ≤ cornerFin b then a else b⟩

instance (N : ℕ) : LinearOrder (Corner N) :=
  LinearOrder.lift cornerFin (by
    intro a b h
    rcases a with ⟨t1, j1⟩
    rcases b with ⟨t2, j2⟩
    have hv : t1.val * 4 + j1.val = t2.val * 4 + j2.val := congrArg Fin.val h
    have ht : t1 = t2 := Fin.ext (by omega)
    have hj : j1 = j2 := Fin.ext (by omega)
    subst ht
    subst hj
    rfl) (by
    intro x y
    by_cases h : cornerFin x ≤ cornerFin y
    · have hxy : x ⊔ y = y := by
        change (if cornerFin x ≤ cornerFin y then y else x) = y
        simp [h]
      rw [hxy, max_eq_right h]
    · have hxy : x ⊔ y = x := by
        change (if cornerFin x ≤ cornerFin y then y else x) = x
        simp [h]
      rw [hxy, max_eq_left (a := cornerFin x) (b := cornerFin y) (le_of_not_ge (a := cornerFin x) (b := cornerFin y) h)]) (by
    intro x y
    by_cases h : cornerFin x ≤ cornerFin y
    · have hxy : x ⊓ y = x := by
        change (if cornerFin x ≤ cornerFin y then x else y) = x
        simp [h]
      rw [hxy, min_eq_left h]
    · have hxy : x ⊓ y = y := by
        change (if cornerFin x ≤ cornerFin y then x else y) = y
        simp [h]
      rw [hxy, min_eq_right (a := cornerFin x) (b := cornerFin y) (le_of_not_ge (a := cornerFin x) (b := cornerFin y) h)])

/-- A **face** of a tetrahedron: the triangle opposite corner `i`. -/
structure Face (N : ℕ) where
  t : Fin N
  i : Fin 4
  deriving DecidableEq, Fintype

def faceFin (f : Face N) : Fin (N * 4) := ⟨f.t.val * 4 + f.i.val, by omega⟩

instance (N : ℕ) : Max (Face N) := ⟨fun a b => if faceFin a ≤ faceFin b then b else a⟩
instance (N : ℕ) : Min (Face N) := ⟨fun a b => if faceFin a ≤ faceFin b then a else b⟩

instance (N : ℕ) : LinearOrder (Face N) :=
  LinearOrder.lift faceFin (by
    intro a b h
    rcases a with ⟨t1, i1⟩
    rcases b with ⟨t2, i2⟩
    have hv : t1.val * 4 + i1.val = t2.val * 4 + i2.val := congrArg Fin.val h
    have ht : t1 = t2 := Fin.ext (by omega)
    have hi : i1 = i2 := Fin.ext (by omega)
    subst ht
    subst hi
    rfl) (by
    intro x y
    by_cases h : faceFin x ≤ faceFin y
    · have hxy : x ⊔ y = y := by
        change (if faceFin x ≤ faceFin y then y else x) = y
        simp [h]
      rw [hxy, max_eq_right h]
    · have hxy : x ⊔ y = x := by
        change (if faceFin x ≤ faceFin y then y else x) = x
        simp [h]
      rw [hxy, max_eq_left (a := faceFin x) (b := faceFin y) (le_of_not_ge (a := faceFin x) (b := faceFin y) h)]) (by
    intro x y
    by_cases h : faceFin x ≤ faceFin y
    · have hxy : x ⊓ y = x := by
        change (if faceFin x ≤ faceFin y then x else y) = x
        simp [h]
      rw [hxy, min_eq_left h]
    · have hxy : x ⊓ y = y := by
        change (if faceFin x ≤ faceFin y then x else y) = y
        simp [h]
      rw [hxy, min_eq_right (a := faceFin x) (b := faceFin y) (le_of_not_ge (a := faceFin x) (b := faceFin y) h)])

/-! ## A computable `Decidable` instance for bounded universal quantification

The library instance deciding `∀ a ∈ s, p a` for a `Finset` runs through
`Multiset.decidableDforallMultiset`, which builds `s.attach` — a multiset of *subtypes*
carrying one membership proof per element.  For the nested `Finset`-valued classes used
below, kernel reduction of that construction is prohibitively expensive (`decide` on a
single vertex-link check does not terminate in reasonable time), even though the underlying
sets are tiny.

The instance below decides the same proposition by testing whether
`s.filter (fun a => ¬ p a)` is empty, i.e. by one computable pass over the elements with a
`Bool`-valued predicate.  Nothing about the *proposition* changes: `fastForallMem_iff`
proves the two formulations equivalent, and the instance only chooses a different
`Decidable` term. -/

/-- `∀ a ∈ s, p a` is equivalent to the emptiness of the finset of counterexamples. -/
theorem fastForallMem_iff {α : Type*} {s : Finset α} {p : α → Prop} [DecidablePred p] :
    (s.filter (fun a => ¬ p a)).card = 0 ↔ ∀ a ∈ s, p a := by
  rw [Finset.card_eq_zero]
  constructor
  · intro h a ha
    by_contra hp
    have hmem : a ∈ s.filter (fun a => ¬ p a) := Finset.mem_filter.mpr ⟨ha, hp⟩
    rw [h] at hmem
    exact absurd hmem (Finset.notMem_empty a)
  · intro h
    apply Finset.eq_empty_iff_forall_notMem.mpr
    intro a ha
    rw [Finset.mem_filter] at ha
    exact ha.2 (h a ha.1)

/-- A cheap `Decidable` instance for `∀ a ∈ s, p a` over a `Finset`: count the
counterexamples.  It has higher priority than the library instance so that concrete
computations reduce in one pass over the elements. -/
instance (priority := 1100) instFastDecidableForallMemFinset {α : Type*} {s : Finset α}
    {p : α → Prop} [DecidablePred p] : Decidable (∀ a ∈ s, p a) :=
  decidable_of_iff ((s.filter (fun a => ¬ p a)).card = 0) fastForallMem_iff

/-- The corners of the face opposite corner `i`, in increasing order: the `j`-th element
(for `j : Fin 3`) is `j` if `j < i` and `j + 1` otherwise. -/
def faceCorner (i : Fin 4) (j : Fin 3) : Fin 4 :=
  ⟨if j.val < i.val then j.val else j.val + 1, by
    by_cases h : j.val < i.val
    · simp [h]
      omega
    · simp [h]
      omega⟩

theorem faceCorner_ne (i : Fin 4) (j : Fin 3) : faceCorner i j ≠ i := by
  apply Fin.ne_of_val_ne
  by_cases h : j.val < i.val
  · simp [faceCorner, h]
    omega
  · simp [faceCorner, h]
    have hj : j.val ≤ 3 := by omega
    omega

/-- The position of a corner `c ≠ i` in the increasing list of the face opposite `i`. -/
def positionInFace (i : Fin 4) (c : Fin 4) (h : c ≠ i) : Fin 3 :=
  ⟨if c.val < i.val then c.val else c.val - 1, by
    by_cases hc : c.val < i.val
    · simp [hc]
      omega
    · have hi : i.val < c.val := by
        have : c.val ≠ i.val := by
          intro h'; exact h (Fin.ext h')
        omega
      simp [hc]
      omega⟩

@[simp]
theorem positionInFace_apply (i : Fin 4) (j : Fin 3) :
    positionInFace i (faceCorner i j) (faceCorner_ne i j) = j := by
  ext
  by_cases hj : j.val < i.val
  · simp [positionInFace, faceCorner, hj]
  · simp [positionInFace, faceCorner, hj]
    omega

/-- The **sign of the permutation of the three face corners** induced by a corner bijection
`g` on the face opposite `i`: `+1` if the induced permutation of the increasing orders is
even, `-1` otherwise.  Computed by counting inversions. -/
def facePermSign (i : Fin 4) (g : Equiv.Perm (Fin 4)) : ℤ :=
  let p0 := positionInFace (g i) (g (faceCorner i 0)) (by
    intro h; exact faceCorner_ne i 0 (g.injective h))
  let p1 := positionInFace (g i) (g (faceCorner i 1)) (by
    intro h; exact faceCorner_ne i 1 (g.injective h))
  let p2 := positionInFace (g i) (g (faceCorner i 2)) (by
    intro h; exact faceCorner_ne i 2 (g.injective h))
  if ((decide (p1 < p0)).toNat + (decide (p2 < p0)).toNat + (decide (p2 < p1)).toNat) % 2 = 0 then
    1
  else -1

/-- A **face-pairing (generalized triangulation)** of `N` tetrahedra: for each face
`(t, i)` either `none` (a boundary face) or `some (t', g)` (glued to the face `(t', g i)`
by the corner bijection `g`).  No proofs are stored; the validity conditions are the
predicates below, which are decidable for concrete data. -/
structure FacePairing3 (N : ℕ) where
  glue : Fin N → Fin 4 → Option (Fin N × Equiv.Perm (Fin 4))

namespace FacePairing3

local infixr:67 " =>> " => fun l f => List.flatMap f l

/-- A computable enumeration of the faces of `N` tetrahedra (used in place of the
non-computable `Finset.sort`, so that every check below really reduces). -/
def faceEnum (N : ℕ) : List (Face N) :=
  (List.finRange N) =>> fun t => (List.finRange 4).map fun i => (⟨t, i⟩ : Face N)

instance instMaxFinset [LinearOrder α] : Max (Finset α) :=
  ⟨fun a b => if a.sort (· ≤ ·) ≤ b.sort (· ≤ ·) then b else a⟩

instance instMinFinset [LinearOrder α] : Min (Finset α) :=
  ⟨fun a b => if a.sort (· ≤ ·) ≤ b.sort (· ≤ ·) then a else b⟩

/-- The lexicographic linear order on finsets (via the sorted lists), used to keep the
finite enumerations of the link checks computable. -/
instance instLinearOrderFinset [LinearOrder α] : LinearOrder (Finset α) :=
  let f : Finset α → List α := fun s => s.sort (· ≤ ·)
  have inj : Function.Injective f := by
    intro a b h
    ext x
    simpa [f, Finset.mem_sort] using congrArg (fun l => x ∈ l) h
  LinearOrder.lift f inj (by
    intro x y
    by_cases h : f x ≤ f y
    · have hxy : x ⊔ y = y := by
        change (if f x ≤ f y then y else x) = y
        simp [h]
      rw [hxy, max_eq_right h]
    · have hxy : x ⊔ y = x := by
        change (if f x ≤ f y then y else x) = x
        simp [h]
      rw [hxy, max_eq_left (le_of_not_ge h)]) (by
    intro x y
    by_cases h : f x ≤ f y
    · have hxy : x ⊓ y = x := by
        change (if f x ≤ f y then x else y) = x
        simp [h]
      rw [hxy, min_eq_left h]
    · have hxy : x ⊓ y = y := by
        change (if f x ≤ f y then x else y) = y
        simp [h]
      rw [hxy, min_eq_right (le_of_not_ge h)])

variable {N : ℕ}

/-- The pairing is **consistent**: a partial involution, with no face glued to itself.

The condition is written with an explicit existential over the partner pair (rather than a
`match` on the `Option`) so that Lean can synthesise the `Decidable` instance by type class
search; this is what makes the condition checkable by computation for concrete data. -/
@[reducible] def Consistent (T : FacePairing3 N) : Prop :=
  ∀ t i, T.glue t i = none ∨
    ∃ p : Fin N × Equiv.Perm (Fin 4), T.glue t i = some p ∧
      T.glue p.1 (p.2 i) = some (t, p.2.symm) ∧ (p.1, p.2 i) ≠ (t, i)

/-- Every gluing is **orientation-reversing** with respect to the induced boundary
orientations of the ordered tetrahedra: `sign(π) = (-1)^(i + i' + 1)`. -/
@[reducible] def OrientationReversing (T : FacePairing3 N) : Prop :=
  ∀ t i, T.glue t i = none ∨
    ∃ p : Fin N × Equiv.Perm (Fin 4), T.glue t i = some p ∧
      facePermSign i p.2 = (-1 : ℤ) ^ (i.val + (p.2 i).val + 1)

/-- **Closed**: every face is glued. -/
@[reducible] def Closed (T : FacePairing3 N) : Prop :=
  ∀ t i, T.glue t i ≠ none

/-- The **boundary faces**: the unpaired faces. -/
def boundaryFaces (T : FacePairing3 N) : Finset (Face N) :=
  (Finset.univ : Finset (Fin N)).biUnion fun t =>
    (Finset.univ : Finset (Fin 4)).filter (fun i => T.glue t i = none) |>.image
      fun i => (⟨t, i⟩ : Face N)

/-! ## Quotient computation (union–find pass) -/

variable {α : Type*}

/-- Two elements are **pair-connected** if they are joined by a chain of identifications
from the list (in either direction). -/
def PairConnected (pairs : List (α × α)) (a b : α) : Prop :=
  Relation.ReflTransGen (fun x y => (x, y) ∈ pairs ∨ (y, x) ∈ pairs) a b

/-- `PairConnected` is monotone in the list of identifications. -/
theorem PairConnected_mono {l1 l2 : List (α × α)} (h : ∀ p, p ∈ l1 → p ∈ l2) {a b : α} :
    PairConnected l1 a b → PairConnected l2 a b := by
  intro hab
  induction hab with
  | refl => exact Relation.ReflTransGen.refl
  | tail hrec hstep ih =>
      exact Relation.ReflTransGen.tail ih (by
        rcases hstep with hstep | hstep
        · exact Or.inl (h _ hstep)
        · exact Or.inr (h _ hstep))

/-- Splitting a list at an occurrence of an element. -/
theorem mem_split (l : List α) {x : α} (h : x ∈ l) : ∃ l1 l2, l = l1 ++ x :: l2 := by
  induction l with
  | nil => cases h
  | cons y tl ih =>
      rw [List.mem_cons] at h
      rcases h with h | h
      · subst h
        exact ⟨[], tl, rfl⟩
      · rcases ih h with ⟨l1, l2, rfl⟩
        exact ⟨y :: l1, l2, rfl⟩

variable [DecidableEq α]

/-- One union-find step: in a partition `P` of a finite type, merge the blocks of `a` and
`b` (a block is missing if the element has not been seeded). -/
def mergePair (P : Finset (Finset α)) (a b : α) : Finset (Finset α) :=
  let ca := P.biUnion (fun s => if a ∈ s then s else ∅)
  let cb := P.biUnion (fun s => if b ∈ s then s else ∅)
  P.filter (fun s => a ∉ s ∧ b ∉ s) ∪ {ca ∪ cb}

/-- The **connected components** of the graph on the seeded elements with the given list of
edges: a single union-find pass over the edge list. -/
def componentsOf (seed : Finset α) (pairs : List (α × α)) : Finset (Finset α) :=
  pairs.foldl (fun P ab => mergePair P ab.1 ab.2)
    (seed.image fun a => ({a} : Finset α))

/-- Restrict a list of identifications to those whose two endpoints are both seeded.  Only
seeded identifications can merge blocks: an identification with both endpoints outside the
seed would make `mergePair` add a spurious empty block. -/
def pairsOnSeed [DecidableEq α] (seed : Finset α) (pairs : List (α × α)) : List (α × α) :=
  pairs.filter (fun p => p.1 ∈ seed ∧ p.2 ∈ seed)

/-- One union-find step keeps every old block inside some new block. -/
theorem mergePair_grow {P : Finset (Finset α)} {a b : α} :
    ∀ C ∈ P, ∃ C' ∈ mergePair P a b, C ⊆ C' := by
  intro C hC
  by_cases ha : a ∈ C
  · refine ⟨(P.biUnion (fun s => if a ∈ s then s else ∅)) ∪
        (P.biUnion (fun s => if b ∈ s then s else ∅)), ?_, ?_⟩
    · rw [mergePair]
      rw [mem_union]
      right
      simp
    · intro x hx
      rw [mem_union]
      left
      rw [mem_biUnion]
      exact ⟨C, hC, by simpa [ha] using hx⟩
  · by_cases hb : b ∈ C
    · refine ⟨(P.biUnion (fun s => if a ∈ s then s else ∅)) ∪
          (P.biUnion (fun s => if b ∈ s then s else ∅)), ?_, ?_⟩
      · rw [mergePair]
        rw [mem_union]
        right
        simp
      · intro x hx
        rw [mem_union]
        right
        rw [mem_biUnion]
        exact ⟨C, hC, by simpa [hb] using hx⟩
    · refine ⟨C, ?_, by intro x hx; exact hx⟩
      rw [mergePair]
      rw [mem_union]
      left
      simp only [mem_filter]
      exact ⟨hC, ha, hb⟩

/-- Every old block survives inside some block of any further union-find pass. -/
theorem grow_foldl : ∀ P : Finset (Finset α), ∀ l : List (α × α),
    ∀ C ∈ P, ∃ C' ∈ l.foldl (fun P ab => mergePair P ab.1 ab.2) P, C ⊆ C' := by
  intro P l
  induction l generalizing P with
  | nil => intro C hC; exact ⟨C, hC, subset_rfl⟩
  | cons ab tl ih =>
      intro C hC
      rcases mergePair_grow (P := P) (a := ab.1) (b := ab.2) C hC with ⟨C1, hC1, hCC1⟩
      rcases ih (mergePair P ab.1 ab.2) C1 hC1 with ⟨C2, hC2, hC1C2⟩
      exact ⟨C2, by simpa using hC2, fun x hx => hC1C2 (hCC1 hx)⟩

/-- One union-find step maintains connectedness inside every block. -/
theorem mergePair_connected {pairs : List (α × α)} {P : Finset (Finset α)} {a b : α}
    (hP : ∀ C ∈ P, ∀ x ∈ C, ∀ y ∈ C, PairConnected pairs x y) :
    ∀ C ∈ mergePair P a b, ∀ x ∈ C, ∀ y ∈ C,
      PairConnected ((a, b) :: pairs) x y := by
  intro C hC x hx y hy
  rw [mergePair] at hC
  simp only [mem_union, mem_singleton, mem_filter] at hC
  rcases hC with hC | hC
  · exact PairConnected_mono (fun p hp => by simp [hp]) (hP C hC.1 x hx y hy)
  · subst hC
    rw [mem_union] at hx hy
    rcases hx with hx | hx <;> rcases hy with hy | hy
    · rw [mem_biUnion] at hx hy
      rcases hx with ⟨Cx, hCx, hxC⟩
      rcases hy with ⟨Cy, hCy, hyC⟩
      have hx' : x ∈ Cx := by
        by_cases h : a ∈ Cx <;> simp [h] at hxC ⊢
        exact hxC
      have haCx : a ∈ Cx := by
        by_cases h : a ∈ Cx <;> simp [h] at hxC ⊢
      have hy' : y ∈ Cy := by
        by_cases h : a ∈ Cy <;> simp [h] at hyC ⊢
        exact hyC
      have haCy : a ∈ Cy := by
        by_cases h : a ∈ Cy <;> simp [h] at hyC ⊢
      exact PairConnected_mono (fun p hp => by simp [hp])
        (Relation.ReflTransGen.trans (hP Cx hCx x hx' a haCx)
          (hP Cy hCy a haCy y hy'))
    · rw [mem_biUnion] at hx hy
      rcases hx with ⟨Cx, hCx, hxC⟩
      rcases hy with ⟨Cy, hCy, hyC⟩
      have hx' : x ∈ Cx := by
        by_cases h : a ∈ Cx <;> simp [h] at hxC ⊢
        exact hxC
      have haCx : a ∈ Cx := by
        by_cases h : a ∈ Cx <;> simp [h] at hxC ⊢
      have hy' : y ∈ Cy := by
        by_cases h : b ∈ Cy <;> simp [h] at hyC ⊢
        exact hyC
      have hbCy : b ∈ Cy := by
        by_cases h : b ∈ Cy <;> simp [h] at hyC ⊢
      exact Relation.ReflTransGen.trans
        (PairConnected_mono (fun p hp => by simp [hp]) (hP Cx hCx x hx' a haCx))
        (Relation.ReflTransGen.trans (Relation.ReflTransGen.single (Or.inl (by simp)))
          (PairConnected_mono (fun p hp => by simp [hp]) (hP Cy hCy b hbCy y hy')))
    · rw [mem_biUnion] at hx hy
      rcases hx with ⟨Cx, hCx, hxC⟩
      rcases hy with ⟨Cy, hCy, hyC⟩
      have hx' : x ∈ Cx := by
        by_cases h : b ∈ Cx <;> simp [h] at hxC ⊢
        exact hxC
      have hbCx : b ∈ Cx := by
        by_cases h : b ∈ Cx <;> simp [h] at hxC ⊢
      have hy' : y ∈ Cy := by
        by_cases h : a ∈ Cy <;> simp [h] at hyC ⊢
        exact hyC
      have haCy : a ∈ Cy := by
        by_cases h : a ∈ Cy <;> simp [h] at hyC ⊢
      exact Relation.ReflTransGen.trans
        (PairConnected_mono (fun p hp => by simp [hp]) (hP Cx hCx x hx' b hbCx))
        (Relation.ReflTransGen.trans (Relation.ReflTransGen.single (Or.inr (by simp)))
          (PairConnected_mono (fun p hp => by simp [hp]) (hP Cy hCy a haCy y hy')))
    · rw [mem_biUnion] at hx hy
      rcases hx with ⟨Cx, hCx, hxC⟩
      rcases hy with ⟨Cy, hCy, hyC⟩
      have hx' : x ∈ Cx := by
        by_cases h : b ∈ Cx <;> simp [h] at hxC ⊢
        exact hxC
      have hy' : y ∈ Cy := by
        by_cases h : b ∈ Cy <;> simp [h] at hyC ⊢
        exact hyC
      have hbCx : b ∈ Cx := by
        by_cases h : b ∈ Cx <;> simp [h] at hxC ⊢
      have hbCy : b ∈ Cy := by
        by_cases h : b ∈ Cy <;> simp [h] at hyC ⊢
      exact PairConnected_mono (fun p hp => by simp [hp])
        (Relation.ReflTransGen.trans (hP Cx hCx x hx' b hbCx)
          (hP Cy hCy b hbCy y hy'))

/-- One union-find step maintains connectedness inside every block, for the full list of
identifications (the new pair must already be in the list). -/
theorem mergePair_connected_full {l : List (α × α)} {P : Finset (Finset α)} {a b : α}
    (hab : (a, b) ∈ l) (hP : ∀ C ∈ P, ∀ x ∈ C, ∀ y ∈ C, PairConnected l x y) :
    ∀ C ∈ mergePair P a b, ∀ x ∈ C, ∀ y ∈ C, PairConnected l x y := by
  intro C hC x hx y hy
  rw [mergePair] at hC
  simp only [mem_union, mem_singleton, mem_filter] at hC
  rcases hC with hC | hC
  · exact hP C hC.1 x hx y hy
  · subst hC
    rw [mem_union] at hx hy
    rcases hx with hx | hx <;> rcases hy with hy | hy
    · rw [mem_biUnion] at hx hy
      rcases hx with ⟨Cx, hCx, hxC⟩
      rcases hy with ⟨Cy, hCy, hyC⟩
      have hx' : x ∈ Cx := by
        by_cases h : a ∈ Cx <;> simp [h] at hxC ⊢
        exact hxC
      have haCx : a ∈ Cx := by
        by_cases h : a ∈ Cx <;> simp [h] at hxC ⊢
      have hy' : y ∈ Cy := by
        by_cases h : a ∈ Cy <;> simp [h] at hyC ⊢
        exact hyC
      have haCy : a ∈ Cy := by
        by_cases h : a ∈ Cy <;> simp [h] at hyC ⊢
      exact Relation.ReflTransGen.trans (hP Cx hCx x hx' a haCx)
        (hP Cy hCy a haCy y hy')
    · rw [mem_biUnion] at hx hy
      rcases hx with ⟨Cx, hCx, hxC⟩
      rcases hy with ⟨Cy, hCy, hyC⟩
      have hx' : x ∈ Cx := by
        by_cases h : a ∈ Cx <;> simp [h] at hxC ⊢
        exact hxC
      have haCx : a ∈ Cx := by
        by_cases h : a ∈ Cx <;> simp [h] at hxC ⊢
      have hy' : y ∈ Cy := by
        by_cases h : b ∈ Cy <;> simp [h] at hyC ⊢
        exact hyC
      have hbCy : b ∈ Cy := by
        by_cases h : b ∈ Cy <;> simp [h] at hyC ⊢
      exact Relation.ReflTransGen.trans (hP Cx hCx x hx' a haCx)
        (Relation.ReflTransGen.trans (Relation.ReflTransGen.single (Or.inl hab))
          (hP Cy hCy b hbCy y hy'))
    · rw [mem_biUnion] at hx hy
      rcases hx with ⟨Cx, hCx, hxC⟩
      rcases hy with ⟨Cy, hCy, hyC⟩
      have hx' : x ∈ Cx := by
        by_cases h : b ∈ Cx <;> simp [h] at hxC ⊢
        exact hxC
      have hbCx : b ∈ Cx := by
        by_cases h : b ∈ Cx <;> simp [h] at hxC ⊢
      have hy' : y ∈ Cy := by
        by_cases h : a ∈ Cy <;> simp [h] at hyC ⊢
        exact hyC
      have haCy : a ∈ Cy := by
        by_cases h : a ∈ Cy <;> simp [h] at hyC ⊢
      exact Relation.ReflTransGen.trans (hP Cx hCx x hx' b hbCx)
        (Relation.ReflTransGen.trans (Relation.ReflTransGen.single (Or.inr hab))
          (hP Cy hCy a haCy y hy'))
    · rw [mem_biUnion] at hx hy
      rcases hx with ⟨Cx, hCx, hxC⟩
      rcases hy with ⟨Cy, hCy, hyC⟩
      have hx' : x ∈ Cx := by
        by_cases h : b ∈ Cx <;> simp [h] at hxC ⊢
        exact hxC
      have hbCx : b ∈ Cx := by
        by_cases h : b ∈ Cx <;> simp [h] at hxC ⊢
      have hy' : y ∈ Cy := by
        by_cases h : b ∈ Cy <;> simp [h] at hyC ⊢
        exact hyC
      have hbCy : b ∈ Cy := by
        by_cases h : b ∈ Cy <;> simp [h] at hyC ⊢
      exact Relation.ReflTransGen.trans (hP Cx hCx x hx' b hbCx)
        (hP Cy hCy b hbCy y hy')

/-- The foldl over a list of pairs keeps every block pairwise connected, for the full list
of identifications. -/
theorem foldl_connected (l rel : List (α × α)) (P : Finset (Finset α))
    (hsub : ∀ p, p ∈ l → p ∈ rel) :
    (∀ C ∈ P, ∀ x ∈ C, ∀ y ∈ C, PairConnected rel x y) →
    ∀ C ∈ l.foldl (fun P ab => mergePair P ab.1 ab.2) P, ∀ x ∈ C, ∀ y ∈ C,
      PairConnected rel x y := by
  intro hP
  induction l generalizing P with
  | nil => exact hP
  | cons ab tl ih =>
      have hP' : ∀ C ∈ mergePair P ab.1 ab.2, ∀ x ∈ C, ∀ y ∈ C,
          PairConnected rel x y := by
        intro C hC x hx y hy
        exact mergePair_connected_full (l := rel) (a := ab.1) (b := ab.2)
          (hsub (ab.1, ab.2) (by simp)) hP C hC x hx y hy
      have := ih (mergePair P ab.1 ab.2) (fun p hp => hsub p (by simp [hp])) hP'
      simpa using this

/-- Every block of the final union-find partition is pairwise connected via the generating
identifications. -/
theorem componentsOf_blocks_connected (seed : Finset α) (pairs : List (α × α)) :
    ∀ C ∈ componentsOf seed pairs, ∀ x ∈ C, ∀ y ∈ C, PairConnected pairs x y := by
  have h0 : ∀ C ∈ seed.image fun a => ({a} : Finset α), ∀ x ∈ C, ∀ y ∈ C,
      PairConnected pairs x y := by
    intro C hC x hx y hy
    rw [mem_image] at hC
    rcases hC with ⟨z, hz, rfl⟩
    simp at hx hy
    rw [hx, hy]
    exact Relation.ReflTransGen.refl
  simpa [componentsOf] using foldl_connected pairs pairs
    (seed.image fun a => ({a} : Finset α)) (fun _ h => h) h0

/-- The blocks of a union-find partition are pairwise disjoint (invariant). -/
theorem blocks_disjoint : ∀ P : Finset (Finset α), ∀ l : List (α × α),
    (∀ C1 ∈ P, ∀ C2 ∈ P, C1 ≠ C2 → C1 ∩ C2 = ∅) →
    ∀ C1 ∈ l.foldl (fun P ab => mergePair P ab.1 ab.2) P,
    ∀ C2 ∈ l.foldl (fun P ab => mergePair P ab.1 ab.2) P, C1 ≠ C2 → C1 ∩ C2 = ∅ := by
  intro P l
  induction l generalizing P with
  | nil => intro hP; exact hP
  | cons ab tl ih =>
      intro hP
      have hP' : ∀ C1 ∈ mergePair P ab.1 ab.2, ∀ C2 ∈ mergePair P ab.1 ab.2, C1 ≠ C2 →
          C1 ∩ C2 = ∅ := by
        intro C1 hC1 C2 hC2 hne
        rw [eq_empty_iff_forall_notMem]
        intro x hx
        rw [mem_inter] at hx
        rw [mergePair] at hC1 hC2
        simp only [mem_union, mem_singleton, mem_filter] at hC1 hC2
        rcases hC1 with hC1 | hC1 <;> rcases hC2 with hC2 | hC2
        · have hxin : x ∈ C1 ∩ C2 := by
            rw [mem_inter]
            exact hx
          have hempty : C1 ∩ C2 = ∅ := hP C1 hC1.1 C2 hC2.1 hne
          have hmem : x ∈ (∅ : Finset α) := by
            rw [hempty] at hxin
            exact hxin
          simp at hmem
        · subst hC2
          rw [mem_union] at hx
          rcases hx.2 with h | h
          · rw [mem_biUnion] at h
            rcases h with ⟨A, hA, hxA⟩
            have hxA' : ab.1 ∈ A ∧ x ∈ A := by
              by_cases hh : ab.1 ∈ A <;> simp [hh] at hxA
              exact ⟨hh, hxA⟩
            have hne' : C1 ≠ A := by
              intro hh
              exact hC1.2.1 (by simpa [hh] using hxA'.1)
            have hempty : C1 ∩ A = ∅ := hP C1 hC1.1 A hA hne'
            have hxin : x ∈ C1 ∩ A := by
              rw [mem_inter]
              exact ⟨hx.1, hxA'.2⟩
            have hmem : x ∈ (∅ : Finset α) := by
              rw [hempty] at hxin
              exact hxin
            simp at hmem
          · rw [mem_biUnion] at h
            rcases h with ⟨A, hA, hxA⟩
            have hxA' : ab.2 ∈ A ∧ x ∈ A := by
              by_cases hh : ab.2 ∈ A <;> simp [hh] at hxA
              exact ⟨hh, hxA⟩
            have hne' : C1 ≠ A := by
              intro hh
              exact hC1.2.2 (by simpa [hh] using hxA'.1)
            have hempty : C1 ∩ A = ∅ := hP C1 hC1.1 A hA hne'
            have hxin : x ∈ C1 ∩ A := by
              rw [mem_inter]
              exact ⟨hx.1, hxA'.2⟩
            have hmem : x ∈ (∅ : Finset α) := by
              rw [hempty] at hxin
              exact hxin
            simp at hmem
        · subst hC1
          rw [mem_union] at hx
          rcases hx.1 with h | h
          · rw [mem_biUnion] at h
            rcases h with ⟨A, hA, hxA⟩
            have hxA' : ab.1 ∈ A ∧ x ∈ A := by
              by_cases hh : ab.1 ∈ A <;> simp [hh] at hxA
              exact ⟨hh, hxA⟩
            have hne' : A ≠ C2 := by
              intro hh
              exact hC2.2.1 (by simpa [hh] using hxA'.1)
            have hempty : A ∩ C2 = ∅ := hP A hA C2 hC2.1 hne'
            have hxin : x ∈ A ∩ C2 := by
              rw [mem_inter]
              exact ⟨hxA'.2, hx.2⟩
            have hmem : x ∈ (∅ : Finset α) := by
              rw [hempty] at hxin
              exact hxin
            simp at hmem
          · rw [mem_biUnion] at h
            rcases h with ⟨A, hA, hxA⟩
            have hxA' : ab.2 ∈ A ∧ x ∈ A := by
              by_cases hh : ab.2 ∈ A <;> simp [hh] at hxA
              exact ⟨hh, hxA⟩
            have hne' : A ≠ C2 := by
              intro hh
              exact hC2.2.2 (by simpa [hh] using hxA'.1)
            have hempty : A ∩ C2 = ∅ := hP A hA C2 hC2.1 hne'
            have hxin : x ∈ A ∩ C2 := by
              rw [mem_inter]
              exact ⟨hxA'.2, hx.2⟩
            have hmem : x ∈ (∅ : Finset α) := by
              rw [hempty] at hxin
              exact hxin
            simp at hmem
        · subst hC1
          subst hC2
          exact (hne rfl).elim
      exact ih (mergePair P ab.1 ab.2) hP'

theorem blocks_disjoint_foldl (seed : Finset α) (pairs : List (α × α)) :
    ∀ C1 ∈ componentsOf seed pairs, ∀ C2 ∈ componentsOf seed pairs, C1 ≠ C2 →
      C1 ∩ C2 = ∅ := by
  have h0 : ∀ C1 ∈ seed.image fun a => ({a} : Finset α),
      ∀ C2 ∈ seed.image fun a => ({a} : Finset α), C1 ≠ C2 → C1 ∩ C2 = ∅ := by
    intro C1 hC1 C2 hC2 hne
    rw [eq_empty_iff_forall_notMem]
    intro x hx
    rw [mem_inter] at hx
    rw [mem_image] at hC1 hC2
    rcases hC1 with ⟨a, ha, rfl⟩
    rcases hC2 with ⟨b, hb, rfl⟩
    have hxa : x = a := by simpa using hx.1
    have hxb : x = b := by simpa using hx.2
    have : a = b := hxa.symm.trans hxb
    subst this
    exact (hne rfl).elim
  simpa [componentsOf] using blocks_disjoint (seed.image fun a => ({a} : Finset α)) pairs h0

/-- If two elements are in the same block, they remain in the same block after any further
union-find pass. -/
theorem same_block_preserved (P : Finset (Finset α)) (l : List (α × α)) {x y : α} :
    (∃ C ∈ P, x ∈ C ∧ y ∈ C) → ∃ C ∈ l.foldl (fun P ab => mergePair P ab.1 ab.2) P,
      x ∈ C ∧ y ∈ C := by
  intro h
  rcases h with ⟨C, hC, hxC, hyC⟩
  rcases grow_foldl P l C hC with ⟨C', hC', hsub⟩
  exact ⟨C', hC', hsub hxC, hsub hyC⟩

/-- If two elements of the partition are joined by a single generating pair that occurs
somewhere in the edge list, then after the whole union-find pass they lie in a common
block.  Proved by structural induction on the edge list, so that no evaluation of the
concrete partition is ever forced. -/
theorem same_block_of_pair_foldl (P : Finset (Finset α)) (l : List (α × α)) {a b : α}
    (ha : ∃ C ∈ P, a ∈ C) (hb : ∃ C ∈ P, b ∈ C) (hab : (a, b) ∈ l) :
    ∃ C ∈ l.foldl (fun P ab => mergePair P ab.1 ab.2) P, a ∈ C ∧ b ∈ C := by
  induction l generalizing P with
  | nil => exact absurd hab (List.not_mem_nil)
  | cons cd tl ih =>
      rcases cd with ⟨c, d⟩
      rw [List.mem_cons] at hab
      rcases hab with hab | hab
      · -- the pair is the head: merge it, then the block only grows
        rw [Prod.mk.injEq] at hab
        obtain ⟨rfl, rfl⟩ := hab
        have hmerge : ∃ C ∈ mergePair P a b, a ∈ C ∧ b ∈ C := by
          rcases ha with ⟨Ca, hCa, haCa⟩
          rcases hb with ⟨Cb, hCb, hbCb⟩
          refine ⟨(P.biUnion fun s => if a ∈ s then s else ∅) ∪
            (P.biUnion fun s => if b ∈ s then s else ∅), ?_, ?_, ?_⟩
          · rw [mergePair]
            exact mem_union_right _ (by simp)
          · rw [mem_union]
            left
            rw [mem_biUnion]
            exact ⟨Ca, hCa, by simp [haCa]⟩
          · rw [mem_union]
            right
            rw [mem_biUnion]
            exact ⟨Cb, hCb, by simp [hbCb]⟩
        rcases same_block_preserved (mergePair P a b) tl hmerge with ⟨C, hC, haC, hbC⟩
        exact ⟨C, by simpa using hC, haC, hbC⟩
      · -- the pair occurs later: blocks only grow, then apply the induction hypothesis
        have ha' : ∃ C ∈ mergePair P c d, a ∈ C := by
          rcases ha with ⟨Ca, hCa, haCa⟩
          rcases mergePair_grow (P := P) (a := c) (b := d) Ca hCa with ⟨C', hC', hsub⟩
          exact ⟨C', hC', hsub haCa⟩
        have hb' : ∃ C ∈ mergePair P c d, b ∈ C := by
          rcases hb with ⟨Cb, hCb, hbCb⟩
          rcases mergePair_grow (P := P) (a := c) (b := d) Cb hCb with ⟨C', hC', hsub⟩
          exact ⟨C', hC', hsub hbCb⟩
        exact ih (mergePair P c d) ha' hb' hab

/-- If a pair appears in the list of identifications, its two endpoints end up in the
same block (both must be seeded). -/
theorem same_block_of_pair (seed : Finset α) (pairs : List (α × α)) {x y : α}
    (hxy : (x, y) ∈ pairs) (hx : x ∈ seed) (hy : y ∈ seed) :
    ∃ C ∈ componentsOf seed pairs, x ∈ C ∧ y ∈ C := by
  have h := same_block_of_pair_foldl (seed.image fun a => ({a} : Finset α)) pairs
    ⟨{x}, mem_image_of_mem _ hx, by simp⟩
    ⟨{y}, mem_image_of_mem _ hy, by simp⟩ hxy
  simpa [componentsOf] using h

/-! ## Corners, edges, faces, and the Euler characteristic -/

/-- The generating corner identifications: for each gluing `(t,i) ↦ (t', g)`, each corner
`j ≠ i` of the face is identified with `g j`. -/
def cornerPairs (T : FacePairing3 N) : List (Corner N × Corner N) :=
  (List.finRange N) =>> fun t =>
  (List.finRange 4) =>> fun i =>
  (List.finRange 4).filter (fun j => j ≠ i) =>> fun j =>
    match T.glue t i with
    | none => []
    | some (t', g) => [((⟨t, j⟩ : Corner N), (⟨t', g j⟩ : Corner N))]

/-- The seed of all corners. -/
def cornerSeed (N : ℕ) : Finset (Corner N) :=
  (Finset.univ : Finset (Fin N)).biUnion fun t =>
    (Finset.univ : Finset (Fin 4)).image fun j => (⟨t, j⟩ : Corner N)

/-- The **vertex classes** of the quotient: the corner classes under the identifications. -/
def vertexClasses (T : FacePairing3 N) : Finset (Finset (Corner N)) :=
  componentsOf (cornerSeed N) (cornerPairs T)

/-- The seed of all edges: the `6N` edges of the tetrahedra, as 2-element corner sets.
Only the pairs `a < b` are enumerated, so that no degenerate `{a,a}` singleton is
mistaken for an edge. -/
def edgeSeed (N : ℕ) : Finset (Finset (Corner N)) :=
  (Finset.univ : Finset (Fin N)).biUnion fun t =>
    (Finset.univ : Finset (Fin 4)).biUnion fun a =>
      ((Finset.univ : Finset (Fin 4)).filter (fun b => a < b)).image fun b =>
        ({⟨t, a⟩, ⟨t, b⟩} : Finset (Corner N))

/-- The generating edge identifications: each gluing identifies `{t,a} {t,b}` with
`{t', g a} {t', g b}` for each edge of the glued face. -/
def edgePairs (T : FacePairing3 N) : List (Finset (Corner N) × Finset (Corner N)) :=
  (List.finRange N) =>> fun t =>
  (List.finRange 4) =>> fun i =>
  (List.finRange 4) =>> fun a =>
  (List.finRange 4) =>> fun b =>
    match T.glue t i with
    | none => []
    | some (t', g) =>
        if a ≠ i ∧ b ≠ i ∧ a ≠ b then
          [(({⟨t, a⟩, ⟨t, b⟩} : Finset (Corner N)),
            ({⟨t', g a⟩, ⟨t', g b⟩} : Finset (Corner N)))]
        else []

/-- The **edge classes** of the quotient. -/
def edgeClasses (T : FacePairing3 N) : Finset (Finset (Finset (Corner N))) :=
  componentsOf (edgeSeed N) (edgePairs T)

/-- The seed of all faces. -/
def faceSeed (N : ℕ) : Finset (Face N) :=
  (Finset.univ : Finset (Fin N)).biUnion fun t =>
    (Finset.univ : Finset (Fin 4)).image fun i => (⟨t, i⟩ : Face N)

/-- The generating face identifications. -/
def facePairs (T : FacePairing3 N) : List (Face N × Face N) :=
  (List.finRange N) =>> fun t =>
  (List.finRange 4) =>> fun i =>
    match T.glue t i with
    | none => []
    | some (t', g) => [((⟨t, i⟩ : Face N), (⟨t', g i⟩ : Face N))]

/-- The **face (triangle) classes** of the quotient. -/
def faceClasses (T : FacePairing3 N) : Finset (Finset (Face N)) :=
  componentsOf (faceSeed N) (facePairs T)

/-- The **Euler characteristic** `χ = V - E + F - T` of the quotient.  For a closed
3-manifold triangulation this is `0`; for a compact 3-manifold with torus boundary it is
also `0`. -/
def eulerChar3 (T : FacePairing3 N) : ℤ :=
  (T.vertexClasses.card : ℤ) - (T.edgeClasses.card : ℤ)
    + (T.faceClasses.card : ℤ) - (N : ℤ)

/-- The edge class of the edge `{(t,a), (t,b)}`: the (unique) class of edges containing it. -/
def edgeClassOf (T : FacePairing3 N) (t : Fin N) (a b : Fin 4) : Finset (Finset (Corner N)) :=
  (T.edgeClasses.filter (fun E => ({⟨t, a⟩, ⟨t, b⟩} : Finset (Corner N)) ∈ E)).biUnion id

/-- The face class of the face `(t,i)`. -/
def faceClassOf (T : FacePairing3 N) (t : Fin N) (i : Fin 4) : Finset (Face N) :=
  (T.faceClasses.filter (fun F => (⟨t, i⟩ : Face N) ∈ F)).biUnion id

/-- The vertex class of the corner `(t,j)`. -/
def vertexClassOf (T : FacePairing3 N) (t : Fin N) (j : Fin 4) : Finset (Corner N) :=
  (T.vertexClasses.filter (fun C => (⟨t, j⟩ : Corner N) ∈ C)).biUnion id

/-- A **link vertex** of a vertex class: a corner together with one of the three edges
through it (the edge `{corner.j, other}`). -/
abbrev CornerEdge (N : ℕ) := Corner N × Fin 4

/-- A **link edge** of a vertex class: a face together with one of its corners
(the arc of the vertex figure cut by that face). -/
abbrev FaceCorner (N : ℕ) := Face N × Fin 4

/-- A computable enumeration of the face/corner pairs of `N` tetrahedra. -/
def faceCornerEnum (N : ℕ) : List (FaceCorner N) :=
  (List.finRange N) =>> fun t =>
    (List.finRange 4) =>> fun i => (List.finRange 4).map fun c => ((⟨t, i⟩ : Face N), c)

/-- A computable finite index of a `FaceCorner` (for the linear order). -/
def faceCornerFin (fc : FaceCorner N) : Fin (N * 16) :=
  ⟨fc.1.t.val * 16 + fc.1.i.val * 4 + fc.2.val, by omega⟩

instance (N : ℕ) : Max (FaceCorner N) := ⟨fun a b => if faceCornerFin a ≤ faceCornerFin b then b else a⟩
instance (N : ℕ) : Min (FaceCorner N) := ⟨fun a b => if faceCornerFin a ≤ faceCornerFin b then a else b⟩

instance (N : ℕ) : LinearOrder (FaceCorner N) :=
  LinearOrder.lift faceCornerFin (by
    intro a b h
    rcases a with ⟨f1, c1⟩
    rcases b with ⟨f2, c2⟩
    rcases f1 with ⟨t1, i1⟩
    rcases f2 with ⟨t2, i2⟩
    have hv : t1.val * 16 + i1.val * 4 + c1.val = t2.val * 16 + i2.val * 4 + c2.val :=
      congrArg Fin.val h
    have ht : t1 = t2 := Fin.ext (by omega)
    have hi : i1 = i2 := Fin.ext (by omega)
    have hc : c1 = c2 := Fin.ext (by omega)
    subst ht
    subst hi
    subst hc
    rfl) (by
    intro x y
    by_cases h : faceCornerFin x ≤ faceCornerFin y
    · have hxy : x ⊔ y = y := by
        change (if faceCornerFin x ≤ faceCornerFin y then y else x) = y
        simp [h]
      rw [hxy, max_eq_right h]
    · have hxy : x ⊔ y = x := by
        change (if faceCornerFin x ≤ faceCornerFin y then y else x) = x
        simp [h]
      rw [hxy, max_eq_left (le_of_not_ge (a := faceCornerFin x) (b := faceCornerFin y) h)]) (by
    intro x y
    by_cases h : faceCornerFin x ≤ faceCornerFin y
    · have hxy : x ⊓ y = x := by
        change (if faceCornerFin x ≤ faceCornerFin y then x else y) = x
        simp [h]
      rw [hxy, min_eq_left h]
    · have hxy : x ⊓ y = y := by
        change (if faceCornerFin x ≤ faceCornerFin y then x else y) = y
        simp [h]
      rw [hxy, min_eq_right (le_of_not_ge (a := faceCornerFin x) (b := faceCornerFin y) h)])

/-- A **face occurrence** through an edge class: a face together with one of its edges
(the pair `(a, b)` of corner indices of the edge). -/
abbrev FaceOcc (N : ℕ) := Face N × Fin 4 × Fin 4

/-- An **arc occurrence** of an edge class: a tetrahedron together with one of its edges
(the pair `(a, b)` of corner indices). -/
abbrev ArcOcc (N : ℕ) := Fin N × Fin 4 × Fin 4

/-- The corners of the vertex class `C`, as a list. -/
def vertexLinkCorners (T : FacePairing3 N) (C : Finset (Corner N)) : List (Corner N) :=
  List.filter (fun c => c ∈ C)
    ((List.finRange N) =>> fun t => (List.finRange 4).map fun j =>  (⟨t, j⟩ : Corner N))

/-- The link vertices of `C`: the pairs (corner `c ∈ C`, edge `{c.j, k}`). -/
def vertexLinkVertices (T : FacePairing3 N) (C : Finset (Corner N)) : List (CornerEdge N) :=
  List.filter (fun ce => ce.1 ∈ C)
    ((List.finRange N) =>> fun t =>
      (List.finRange 4) =>> fun j =>
        List.map (fun k => ((⟨t, j⟩ : Corner N), k))
          ((List.finRange 4).filter (fun k => k ≠ j)))

/-- The identifications of link vertices induced by face gluings. -/
def vertexLinkVertexPairs (T : FacePairing3 N) : List (CornerEdge N × CornerEdge N) :=
  (List.finRange N) =>> fun t =>
  (List.finRange 4) =>> fun i =>
    match T.glue t i with
    | none => []
    | some (t', g) =>
      (List.finRange 4).filter (fun j => j ≠ i) =>> fun j =>
      List.map (fun k => (((⟨t, j⟩ : Corner N), k), ((⟨t', g j⟩ : Corner N), g k)))
        ((List.finRange 4).filter (fun k => k ≠ i ∧ k ≠ j))

/-- The **vertex classes of the link** of the vertex class `C`. -/
def vertexLinkVertexClasses (T : FacePairing3 N) (C : Finset (Corner N)) :
    Finset (Finset (CornerEdge N)) :=
  componentsOf (vertexLinkVertices T C).toFinset
    (pairsOnSeed (vertexLinkVertices T C).toFinset (vertexLinkVertexPairs T))

/-- The link edges of `C`: the pairs (face `(t,i)`, corner `j ≠ i` of that face) with the
corner `(t,j)` in `C`. -/
def vertexLinkEdges (T : FacePairing3 N) (C : Finset (Corner N)) : List (FaceCorner N) :=
  List.filter (fun fc => ((⟨fc.1.t, fc.2⟩ : Corner N) ∈ C))
    ((List.finRange N) =>> fun t =>
      (List.finRange 4) =>> fun i =>
        List.map (fun j => ((⟨t, i⟩ : Face N), j))
          ((List.finRange 4).filter (fun j => j ≠ i)))

/-- The identifications of link edges induced by face gluings. -/
def vertexLinkEdgePairs (T : FacePairing3 N) : List (FaceCorner N × FaceCorner N) :=
  (List.finRange N) =>> fun t =>
  (List.finRange 4) =>> fun i =>
    match T.glue t i with
    | none => []
    | some (t', g) =>
      List.map (fun j => (((⟨t, i⟩ : Face N), j), ((⟨t', g i⟩ : Face N), g j)))
        ((List.finRange 4).filter (fun j => j ≠ i))

/-- The **edge classes of the link** of the vertex class `C`. -/
def vertexLinkEdgeClasses (T : FacePairing3 N) (C : Finset (Corner N)) :
    Finset (Finset (FaceCorner N)) :=
  componentsOf (vertexLinkEdges T C).toFinset
    (pairsOnSeed (vertexLinkEdges T C).toFinset (vertexLinkEdgePairs T))

/-- The class of a link vertex in the link of `C`. -/
def vertexLinkVertexClassOf (T : FacePairing3 N) (C : Finset (Corner N)) (ce : CornerEdge N) :
    Finset (CornerEdge N) :=
  ((T.vertexLinkVertexClasses C).filter (fun B => ce ∈ B)).biUnion id

/-- The class of a link edge in the link of `C`. -/
def vertexLinkEdgeClassOf (T : FacePairing3 N) (C : Finset (Corner N)) (fc : FaceCorner N) :
    Finset (FaceCorner N) :=
  ((T.vertexLinkEdgeClasses C).filter (fun B => fc ∈ B)).biUnion id

/-- The first endpoint of a link edge ` (⟨t,i⟩, j)`: the link vertex ` (⟨t,j⟩, k)` with `k` the
first of the two corners other than `i` and `j`. -/
def linkEdgeEndpoint1 (fc : FaceCorner N) : CornerEdge N :=
  match (List.finRange 4).filter (fun k => k ≠ fc.1.i ∧ k ≠ fc.2) with
  | k1 :: _ => ⟨⟨fc.1.t, fc.2⟩, k1⟩
  | [] => ⟨⟨fc.1.t, fc.2⟩, fc.1.i⟩

/-- The second endpoint of a link edge. -/
def linkEdgeEndpoint2 (fc : FaceCorner N) : CornerEdge N :=
  match (List.finRange 4).filter (fun k => k ≠ fc.1.i ∧ k ≠ fc.2) with
  | _ :: k2 :: _ => ⟨⟨fc.1.t, fc.2⟩, k2⟩
  | _ => ⟨⟨fc.1.t, fc.2⟩, fc.1.i⟩

/-- The three link edge classes of a corner. -/
def linkFaceEdgeClasses (T : FacePairing3 N) (C : Finset (Corner N)) (c : Corner N) :
    List (Finset (FaceCorner N)) :=
  ((List.finRange 4).filter (fun i => i ≠ c.j)).map fun i =>
    T.vertexLinkEdgeClassOf C ((⟨c.t, i⟩ : Face N), c.j)

/-- The three link vertex classes of a corner. -/
def linkFaceVertexClasses (T : FacePairing3 N) (C : Finset (Corner N)) (c : Corner N) :
    List (Finset (CornerEdge N)) :=
  ((List.finRange 4).filter (fun k => k ≠ c.j)).map fun k =>
    T.vertexLinkVertexClassOf C ((⟨c.t, c.j⟩ : Corner N), k)

/-- The link face of a corner is a genuine triangle: three distinct edge classes and three
distinct vertex classes. -/
@[reducible] def linkFaceIsTriangle (T : FacePairing3 N) (C : Finset (Corner N)) (c : Corner N) : Prop :=
  (linkFaceEdgeClasses T C c).eraseDups.length = 3 ∧
  (linkFaceVertexClasses T C c).eraseDups.length = 3

/-- The number of link faces adjacent to a link edge class. -/
@[reducible] def linkEdgeIncidence (T : FacePairing3 N) (C : Finset (Corner N))
    (ec : Finset (FaceCorner N)) : ℕ :=
  ((vertexLinkCorners T C).filter (fun c =>
    (((List.finRange 4).filter (fun i => i ≠ c.j)).map fun i =>
        (⟨⟨c.t, i⟩, c.j⟩ : FaceCorner N)).any (fun fc => fc ∈ ec))).length

/-- The link of `C` is connected along its edge classes. -/
@[reducible] def vertexLinkConnected (T : FacePairing3 N) (C : Finset (Corner N)) : Prop :=
  let corners := vertexLinkCorners T C
  let pairs : List (Corner N × Corner N) :=
    corners =>> fun c1 =>
    corners =>> fun c2 =>
      if c1 ≠ c2 ∧ (((List.finRange 4).filter (fun i => i ≠ c1.j)).map fun i =>
          (⟨⟨c1.t, i⟩, c1.j⟩ : FaceCorner N)).any (fun fc =>
            (((List.finRange 4).filter (fun i2 => i2 ≠ c2.j)).map fun i2 =>
              (⟨⟨c2.t, i2⟩, c2.j⟩ : FaceCorner N)).any (fun fc2 =>
                T.vertexLinkEdgeClassOf C fc = T.vertexLinkEdgeClassOf C fc2)) then
        [(c1, c2)] else []
  (componentsOf corners.toFinset pairs).card = 1

/-- **The vertex link is a 2-sphere** (the decidable criterion): every link face is a
triangle, every link edge class lies in exactly two link faces, the link is connected and has
Euler characteristic `2`. -/
@[reducible] def VertexLinkIsSphere (T : FacePairing3 N) (C : Finset (Corner N)) : Prop :=
  (∀ c ∈ vertexLinkCorners T C, linkFaceIsTriangle T C c) ∧
  (∀ ec ∈ T.vertexLinkEdgeClasses C, linkEdgeIncidence T C ec = 2) ∧
  vertexLinkConnected T C ∧
  ((T.vertexLinkVertexClasses C).card : ℤ) - ((T.vertexLinkEdgeClasses C).card : ℤ)
    + ((vertexLinkCorners T C).length : ℤ) = 2

/-- The link edge classes of the link of `C` adjacent to exactly one link face. -/
def diskOnes (T : FacePairing3 N) (C : Finset (Corner N)) : Finset (Finset (FaceCorner N)) :=
  (T.vertexLinkEdgeClasses C).filter (fun ec => linkEdgeIncidence T C ec = 1)

/-- The link edge classes of `C`, as a computable list: every link edge is mapped to its
class and the list is de-duplicated. -/
def vertexLinkEdgeClassList (T : FacePairing3 N) (C : Finset (Corner N)) :
    List (Finset (FaceCorner N)) :=
  (((faceCornerEnum N).filter (fun fc => fc ∈ (vertexLinkEdges T C).toFinset)).map
    (fun fc => T.vertexLinkEdgeClassOf C fc)).eraseDups

/-- The link edge classes of the link of `C` adjacent to exactly one link face, as a
computable list. -/
def diskOnesList (T : FacePairing3 N) (C : Finset (Corner N)) : List (Finset (FaceCorner N)) :=
  (T.vertexLinkEdgeClassList C).filter (fun ec => linkEdgeIncidence T C ec = 1)

/-- The endpoints (vertex classes of the link) of the single occurrence of a one-edge. -/
def linkOnesNeighbors (T : FacePairing3 N) (C : Finset (Corner N))
    (ec : Finset (FaceCorner N)) : List (Finset (CornerEdge N) × Finset (CornerEdge N)) :=
  match (faceCornerEnum N).filter (fun fc => fc ∈ ec) with
  | [fc] => [(T.vertexLinkVertexClassOf C (linkEdgeEndpoint1 fc),
              T.vertexLinkVertexClassOf C (linkEdgeEndpoint2 fc))]
  | _ => []

/-- The adjacency pairs of the boundary cycle of a disk link. -/
def diskBoundaryPairs (T : FacePairing3 N) (C : Finset (Corner N)) :
    List (Finset (CornerEdge N) × Finset (CornerEdge N)) :=
  (T.diskOnesList C) =>> fun ec => linkOnesNeighbors T C ec

/-- Whether the link vertex class `vc` is an endpoint of the one-edge class `ec`. -/
@[reducible] def oneEdgeTouches (T : FacePairing3 N) (C : Finset (Corner N))
    (ec : Finset (FaceCorner N)) (vc : Finset (CornerEdge N)) : Prop :=
  ∃ fc ∈ (faceCornerEnum N).filter (fun fc => fc ∈ ec),
    T.vertexLinkVertexClassOf C (linkEdgeEndpoint1 fc) = vc ∨
      T.vertexLinkVertexClassOf C (linkEdgeEndpoint2 fc) = vc

/-- The link vertex classes adjacent to two one-edges. -/
def diskBoundaryVertices (T : FacePairing3 N) (C : Finset (Corner N)) :
    Finset (Finset (CornerEdge N)) :=
  (T.vertexLinkVertexClasses C).filter (fun vc =>
    ((diskOnes T C).filter (fun ec => T.oneEdgeTouches C ec vc)).card = 2)

/-- **The vertex link is a disk** (the decidable criterion for boundary vertices): every
link face is a triangle, every link edge class lies in at most two link faces, the classes
lying in one form a single boundary cycle (each link vertex class adjacent to exactly two of
them, connected), the link is connected and has Euler characteristic `1`. -/
@[reducible] def VertexLinkIsDisk (T : FacePairing3 N) (C : Finset (Corner N)) : Prop :=
  (∀ c ∈ vertexLinkCorners T C, linkFaceIsTriangle T C c) ∧
  (∀ ec ∈ T.vertexLinkEdgeClasses C, linkEdgeIncidence T C ec ≤ 2) ∧
  (diskOnes T C).Nonempty ∧
  (∀ vc ∈ T.vertexLinkVertexClasses C,
    (((diskOnes T C).filter (fun ec => T.oneEdgeTouches C ec vc)).card = 0 ∨
     ((diskOnes T C).filter (fun ec => T.oneEdgeTouches C ec vc)).card = 2)) ∧
  (componentsOf (diskBoundaryVertices T C) (diskBoundaryPairs T C)).card = 1 ∧
  vertexLinkConnected T C ∧
  ((T.vertexLinkVertexClasses C).card : ℤ) - ((T.vertexLinkEdgeClasses C).card : ℤ)
    + ((vertexLinkCorners T C).length : ℤ) = 1

/-- Whether a vertex class lies on the boundary (one of its corners is on a boundary
face). -/
@[reducible] def IsBoundaryVertexClass (T : FacePairing3 N) (C : Finset (Corner N)) : Prop :=
  ∃ f ∈ T.boundaryFaces, ∃ j, j ≠ f.i ∧ (⟨f.t, j⟩ : Corner N) ∈ C

/-- The face occurrences through the edge class `E`: a face together with the (unordered)
edge of that face which lies in `E`, recorded in increasing corner order `a < b`.  The
increasing-order convention is essential: an ordered pair together with its reverse would
represent the same face-arc incidence twice, doubling the vertices of the edge link. -/
def edgeLinkFaceOccs (T : FacePairing3 N) (E : Finset (Finset (Corner N))) : List (FaceOcc N) :=
  (List.finRange N) =>> fun t =>
  (List.finRange 4) =>> fun a =>
  (List.finRange 4).filter (fun b => a < b) =>> fun b =>
    if ({⟨t, a⟩, ⟨t, b⟩} : Finset (Corner N)) ∈ E then
      ((List.finRange 4).filter (fun i => i ≠ a ∧ i ≠ b)).map fun i =>
        ( (⟨t, i⟩ : Face N), a, b)
    else []

/-- The identifications of face occurrences induced by face gluings.  A face occurrence
`((t,i), a, b)` with `a < b` is glued to the occurrence of the image edge `{g a, g b}` in
the face `(t', g i)`, normalized back to increasing corner order. -/
def edgeLinkFaceOccPairs (T : FacePairing3 N) : List (FaceOcc N × FaceOcc N) :=
  (List.finRange N) =>> fun t =>
  (List.finRange 4) =>> fun i =>
    match T.glue t i with
    | none => []
    | some (t', g) =>
      (List.finRange 4).filter (fun a => a ≠ i) =>> fun a =>
      List.map (fun b => (((⟨t, i⟩ : Face N), a, b),
          ((⟨t', g i⟩ : Face N), min (g a) (g b), max (g a) (g b))))
        ((List.finRange 4).filter (fun b => b ≠ i ∧ a < b))

/-- The **face classes through `E`**: the vertices of the edge link. -/
def edgeLinkFaceClasses (T : FacePairing3 N) (E : Finset (Finset (Corner N))) :
    Finset (Finset (FaceOcc N)) :=
  componentsOf (edgeLinkFaceOccs T E).toFinset
    (pairsOnSeed (edgeLinkFaceOccs T E).toFinset (edgeLinkFaceOccPairs T))

/-- The class of a face occurrence in the edge link of `E`. -/
def edgeLinkFaceClassOf (T : FacePairing3 N) (E : Finset (Finset (Corner N))) (fo : FaceOcc N) :
    Finset (FaceOcc N) :=
  ((T.edgeLinkFaceClasses E).filter (fun B => fo ∈ B)).biUnion id

/-- The arc occurrences of the edge class `E` (each edge occurrence, normalized). -/
def edgeLinkArcs (T : FacePairing3 N) (E : Finset (Finset (Corner N))) : List (ArcOcc N) :=
  (List.finRange N) =>> fun t =>
  (List.finRange 4) =>> fun a =>
  ((List.finRange 4).filter (fun b => b ≠ a ∧ a < b)) =>> fun b =>
    if ({⟨t, a⟩, ⟨t, b⟩} : Finset (Corner N)) ∈ E then [(t, a, b)] else []

/-- The identifications of arc occurrences induced by face gluings. -/
def edgeLinkArcPairs (T : FacePairing3 N) : List (ArcOcc N × ArcOcc N) :=
  (List.finRange N) =>> fun t =>
  (List.finRange 4) =>> fun i =>
    match T.glue t i with
    | none => []
    | some (t', g) =>
      (List.finRange 4).filter (fun a => a ≠ i) =>> fun a =>
      ((List.finRange 4).filter (fun b => b ≠ i ∧ b ≠ a ∧ a < b)) =>> fun b =>
        let a' := g a
        let b' := g b
        [((t, a, b), (t', min a' b', max a' b'))]

/-- The degree of a face class in the edge link of `E`: the number of arc ends at it. -/
@[reducible] def edgeLinkDegree (T : FacePairing3 N) (E : Finset (Finset (Corner N)))
    (f : Finset (FaceOcc N)) : ℕ :=
  ((edgeLinkArcs T E).map (fun arc =>
    (((List.finRange 4).filter (fun i => i ≠ arc.2.1 ∧ i ≠ arc.2.2 ∧
      ((⟨arc.1, i⟩ : Face N), arc.2.1, arc.2.2) ∈ f)).length))).sum

/-- The edge link of `E` is connected along its arcs. -/
@[reducible] def edgeLinkConnected (T : FacePairing3 N) (E : Finset (Finset (Corner N))) : Prop :=
  let fcs := T.edgeLinkFaceClasses E
  let pairs : List (Finset (FaceOcc N) × Finset (FaceOcc N)) :=
    (edgeLinkArcs T E) =>> fun arc =>
      match ((List.finRange 4).filter (fun i => i ≠ arc.2.1 ∧ i ≠ arc.2.2)) with
      | [i1, i2] => [(T.edgeLinkFaceClassOf E ((⟨arc.1, i1⟩ : Face N), arc.2.1, arc.2.2),
                      T.edgeLinkFaceClassOf E ((⟨arc.1, i2⟩ : Face N), arc.2.1, arc.2.2))]
      | _ => []
  (componentsOf fcs pairs).card = 1

/-- **The edge link is a cycle** (interior edge): every face class through `E` has exactly
two arc ends, the link is connected and has `V - A = 0`. -/
@[reducible] def EdgeLinkIsCycle (T : FacePairing3 N) (E : Finset (Finset (Corner N))) : Prop :=
  (∀ f ∈ T.edgeLinkFaceClasses E, edgeLinkDegree T E f = 2) ∧
  edgeLinkConnected T E ∧
  ((T.edgeLinkFaceClasses E).card : ℤ) - ((edgeLinkArcs T E).length : ℤ) = 0

/-- **The edge link is a path** (boundary edge): exactly two face classes through `E` have
one arc end and the rest two, the link is connected and has `V - A = 1`. -/
@[reducible] def EdgeLinkIsPath (T : FacePairing3 N) (E : Finset (Finset (Corner N))) : Prop :=
  (∀ f ∈ T.edgeLinkFaceClasses E, edgeLinkDegree T E f = 1 ∨ edgeLinkDegree T E f = 2) ∧
  ((T.edgeLinkFaceClasses E).filter (fun f => edgeLinkDegree T E f = 1)).card = 2 ∧
  edgeLinkConnected T E ∧
  ((T.edgeLinkFaceClasses E).card : ℤ) - ((edgeLinkArcs T E).length : ℤ) = 1

/-- Whether an edge class meets the boundary. -/
@[reducible] def IsBoundaryEdgeClass (T : FacePairing3 N) (E : Finset (Finset (Corner N))) : Prop :=
  ∃ f ∈ T.boundaryFaces, ∃ a, a ≠ f.i ∧ ∃ b, b ≠ f.i ∧ a ≠ b ∧
    ({⟨f.t, a⟩, ⟨f.t, b⟩} : Finset (Corner N)) ∈ E

/-- The boundary faces, as a computable list. -/
def boundaryFacesList (T : FacePairing3 N) : List (Face N) :=
  (faceEnum N).filter (fun f => T.glue f.t f.i = none)

/-- The vertex classes on the boundary, as a list (with repetitions). -/
def boundaryVertexClassesList (T : FacePairing3 N) : List (Finset (Corner N)) :=
  (T.boundaryFacesList) =>> fun f =>
    List.map (fun a => T.vertexClassOf f.t a)
      ((List.finRange 4).filter (fun a => a ≠ f.i))

/-- The edge classes on the boundary, as a list (with repetitions). -/
def boundaryEdgeClassesList (T : FacePairing3 N) : List (Finset (Finset (Corner N))) :=
  (T.boundaryFacesList) =>> fun f =>
    ((List.finRange 4).filter (fun a => a ≠ f.i)) =>> fun a =>
      List.map (fun b => T.edgeClassOf f.t a b)
        ((List.finRange 4).filter (fun b => b ≠ f.i ∧ a ≠ b ∧ a < b))

/-- The **Euler characteristic of the boundary** `V_∂ - E_∂ + F_∂`. -/
def boundaryChi (T : FacePairing3 N) : ℤ :=
  ((boundaryVertexClassesList T).eraseDups).length -
    ((boundaryEdgeClassesList T).eraseDups).length + (T.boundaryFaces.card : ℤ)

/-- The pairs of boundary faces sharing an edge class. -/
def boundaryAdjacencyPairs (T : FacePairing3 N) : List (Face N × Face N) :=
  (T.boundaryFacesList) =>> fun f =>
    (T.boundaryFacesList) =>> fun g =>
      (if f ≠ g ∧ (∃ a, a ≠ f.i ∧ ∃ b, b ≠ f.i ∧ a ≠ b ∧
        ∃ c, c ≠ g.i ∧ ∃ d, d ≠ g.i ∧ c ≠ d ∧
          T.edgeClassOf f.t a b = T.edgeClassOf g.t c d) then
        [(f, g)] else [])

/-- The **boundary is a closed surface**: every boundary face has three distinct edge
classes, every boundary edge class lies in exactly two boundary faces, the boundary is
connected, and its Euler characteristic is `0` (torus) or `2` (sphere). -/
@[reducible] def BoundaryIsClosedSurface (T : FacePairing3 N) : Prop :=
  let bfs := T.boundaryFaces
  (∀ f ∈ bfs, (((List.finRange 4).filter (fun a => a ≠ f.i)) =>> fun a =>
      List.map (fun b => T.edgeClassOf f.t a b)
        ((List.finRange 4).filter (fun b => b ≠ f.i ∧ a ≠ b))).eraseDups.length = 3) ∧
  (∀ f ∈ bfs, ∀ a, a ≠ f.i → ∀ b, b ≠ f.i → a ≠ b →
    (((T.boundaryFacesList).filter (fun g => ∃ c, c ≠ g.i ∧ ∃ d, d ≠ g.i ∧ c ≠ d ∧
      ({⟨g.t, c⟩, ⟨g.t, d⟩} : Finset (Corner N)) ∈ T.edgeClassOf f.t a b)).length = 2)) ∧
  (componentsOf bfs (boundaryAdjacencyPairs T)).card = 1 ∧
  (T.boundaryChi = 0 ∨ T.boundaryChi = 2)

/-- The pairing is **orientable**: there is a choice of orientations of the tetrahedra
making every gluing orientation-reversing between the induced boundary orientations. -/
@[reducible] def Orientable (T : FacePairing3 N) : Prop :=
  ∃ σ : Fin N → Bool, ∀ t i, T.glue t i = none ∨
    ∃ p : Fin N × Equiv.Perm (Fin 4), T.glue t i = some p ∧
      σ t = (if decide (facePermSign i p.2 ≠ (-1 : ℤ) ^ (i.val + (p.2 i).val + 1)) then
        !(σ p.1) else σ t)

/-- The tetrahedra are connected through the gluings. -/
@[reducible] def Connected (T : FacePairing3 N) : Prop :=
  (componentsOf (Finset.univ : Finset (Fin N)) ((List.finRange N) =>> fun t =>
    (List.finRange 4) =>> fun i =>
      match T.glue t i with
      | none => []
      | some (t', g) => [(t, t')])).card = 1

/-- The full **combinatorial manifold with boundary** condition: consistent, orientable,
connected, sphere links at interior vertices and disk links at boundary vertices, cycle/path
edge links, and a closed surface boundary. -/
@[reducible] def IsCombinatorialManifoldWithBoundary (T : FacePairing3 N) : Prop :=
  T.Consistent ∧ T.Orientable ∧ T.Connected ∧
    (∀ C ∈ T.vertexClasses,
      (if T.IsBoundaryVertexClass C then T.VertexLinkIsDisk C else T.VertexLinkIsSphere C)) ∧
    (∀ E ∈ T.edgeClasses,
      (if T.IsBoundaryEdgeClass E then T.EdgeLinkIsPath E else T.EdgeLinkIsCycle E)) ∧
    T.BoundaryIsClosedSurface

/-- The **closed combinatorial manifold** condition: consistent, orientable, connected,
closed, sphere vertex links and cycle edge links. -/
@[reducible] def IsCombinatorialManifold (T : FacePairing3 N) : Prop :=
  T.Consistent ∧ T.Orientable ∧ T.Connected ∧ T.Closed ∧
    (∀ C ∈ T.vertexClasses, T.VertexLinkIsSphere C) ∧
    (∀ E ∈ T.edgeClasses, T.EdgeLinkIsCycle E)

end FacePairing3

end Triangulation3D

end D11

end Poincare
