/-
Copyright (c) 2026 Poincare Lab. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Poincare Lab (task D11-triangulation-3d)
-/
import Poincare.D11.Triangulation3D.DeltaComplex

/-!
# Explicit triangulations of 3-manifolds

This file fixes the concrete face-pairing data of the small examples and verifies, *by
computation* (`decide`), the full decidable combinatorial-manifold certificate of
`Poincare.D11.Triangulation3D.DeltaComplex` for each of them:

1. the **3-ball** `ball3` (one tetrahedron, no gluings);
2. the **3-sphere** `s3Double` (two tetrahedra glued face-to-face, the double of a
   tetrahedron) and `s3Simplex` (the boundary of the standard 4-simplex, five tetrahedra,
   one for each facet, glued along their common triangles);
3. the **solid torus** `solidTorus3` (three tetrahedra: a triangular prism with its top
   glued to its bottom by a one-third twist);
4. the **lens spaces** `lens31 = L(3,1)` and `lens21 = L(2,1) = RP³` via face pairings on
   bipyramids (the classical identification of a lens space as a bipyramid over a `p`-gon
   with the top identified with the bottom by a `q`-step rotation).

For every example the theorems record, with no postulates and no kernel bypasses:

* `Consistent`: every face is glued at most once, to a distinct face, with matching corner
  identifications (a partial involution);
* `Orientable`: the gluings are orientation-reversing after a suitable choice of tetrahedron
  orientations (the invariant manifold condition; `OrientationReversing` is the stronger
  "already coherent" form, recorded where it holds);
* the f-vector `(V, E, F, T)` and the Euler characteristic `eulerChar3 = V - E + F - T`;
* the vertex links (spheres for interior vertices, disks for boundary vertices), the edge
  links (cycles / paths), and the full `IsCombinatorialManifold(WithBoundary)` condition.

## The boundary of the 4-simplex

The five-tetrahedron triangulation `s3Simplex` of `S³` is the boundary of `Δ⁴`: tetrahedron
`t` is the facet of `Δ⁴` opposite the vertex `t`, and its corner `j` carries the vertex
label `facetVertex t j`.  The explicit face-pairing table below is the one generated by the
rule "the face of facet `t` opposite corner `j` is glued to the facet opposite the missing
vertex `facetVertex t j`, matching equal vertex labels"; the generator
`gen_s3simpkex.py` in this directory emits it and the theorem `s3Simplex_partner` below
re-checks, by computation, that every face is glued to the facet opposite the correct
vertex.
-/

set_option maxRecDepth 1000000
set_option maxHeartbeats 2000000
-- needed for the composite decidable manifold predicates (see `DeltaComplex`)
set_option synthInstance.maxSize 4096

namespace Poincare

namespace D11

namespace Triangulation3D

open FacePairing3

/-! ## The 3-ball: a single tetrahedron -/

/-- The 3-ball as one abstract tetrahedron with no gluings: all four boundary triangles are
unpaired, the vertex links are disks, the edge links are paths, and the boundary is a
2-sphere. -/
def ball3 : FacePairing3 1 := ⟨fun _ _ => none⟩

theorem ball3_consistent : ball3.Consistent := by decide

theorem ball3_orientationReversing : ball3.OrientationReversing := by decide

theorem ball3_orientable : ball3.Orientable := by decide

theorem ball3_connected : ball3.Connected := by decide

theorem ball3_notClosed : ¬ ball3.Closed := by decide

theorem ball3_fvector :
    ball3.vertexClasses.card = 4 ∧ ball3.edgeClasses.card = 6 ∧
      ball3.faceClasses.card = 4 := by
  decide

theorem ball3_euler : ball3.eulerChar3 = 1 := by decide

theorem ball3_boundaryChi : ball3.boundaryChi = 2 := by decide

theorem ball3_boundary : ball3.BoundaryIsClosedSurface := by decide

/-- The single tetrahedron with no gluings is a combinatorial 3-manifold with boundary
(the 3-ball). -/
theorem ball3_manifold : ball3.IsCombinatorialManifoldWithBoundary := by decide

/-! ## The 3-sphere: the double of a tetrahedron -/

/-- The 3-sphere as two tetrahedra glued face-to-face: face `i` of tetrahedron `0` is glued
to face `i` of tetrahedron `1` by the identity corner map.  This is the double of a
tetrahedron, i.e. of the 3-ball. -/
def s3Double : FacePairing3 2 :=
  ⟨fun t _ => some (if t = 0 then 1 else 0, 1)⟩

theorem s3Double_consistent : s3Double.Consistent := by decide

theorem s3Double_orientable : s3Double.Orientable := by decide

theorem s3Double_connected : s3Double.Connected := by decide

theorem s3Double_closed : s3Double.Closed := by decide

theorem s3Double_fvector :
    s3Double.vertexClasses.card = 4 ∧ s3Double.edgeClasses.card = 6 ∧
      s3Double.faceClasses.card = 4 := by
  decide

theorem s3Double_euler : s3Double.eulerChar3 = 0 := by decide

/-- The double of a tetrahedron is a closed combinatorial 3-manifold with vanishing Euler
characteristic (the 3-sphere). -/
theorem s3Double_manifold : s3Double.IsCombinatorialManifold := by decide

/-! ## The 3-sphere: the boundary of the 4-simplex -/

/-- The vertex `j` of the facet of the standard 4-simplex opposite vertex `i`. -/
def facetVertex (i : Fin 5) (j : Fin 4) : Fin 5 :=
  ⟨if j.val < i.val then j.val else j.val + 1, by
    by_cases h : j.val < i.val
    · simp [h]
      omega
    · simp [h]
      omega⟩

theorem facetVertex_ne (i : Fin 5) (j : Fin 4) : facetVertex i j ≠ i := by
  apply Fin.ne_of_val_ne
  by_cases h : j.val < i.val
  · have hv : (facetVertex i j).val = j.val := by simp [facetVertex, h]
    omega
  · have hv : (facetVertex i j).val = j.val + 1 := by simp [facetVertex, h]
    omega

theorem facetVertex_injective (i : Fin 5) : Function.Injective (facetVertex i) := by
  intro j1 j2 h
  apply Fin.ext
  have hv : (facetVertex i j1).val = (facetVertex i j2).val := congrArg Fin.val h
  by_cases h1 : j1.val < i.val <;> by_cases h2 : j2.val < i.val
  · have hv' : j1.val = j2.val := by simpa [facetVertex, h1, h2] using hv
    omega
  · have hv' : j1.val = j2.val + 1 := by simpa [facetVertex, h1, h2] using hv
    omega
  · have hv' : j1.val + 1 = j2.val := by simpa [facetVertex, h1, h2] using hv
    omega
  · have hv' : j1.val + 1 = j2.val + 1 := by simpa [facetVertex, h1, h2] using hv
    omega

/-- The 3-sphere as the boundary of the standard 4-simplex: five tetrahedra, tetrahedron `t`
being the facet of `Δ⁴` opposite the vertex `t`, with equal vertex labels matched.  The
table is the explicit expansion of the rule "the face of tet `t` opposite corner `j` is
glued to the facet opposite `facetVertex t j`", see `gen_s3simplex.py`; the corner maps are
products of transpositions of the corner indices. -/
def s3Simplex : FacePairing3 5 :=
  ⟨fun t i =>
    match t.val, i.val with
    | 0, 0 => some (⟨1, by decide⟩, (1 : Equiv.Perm (Fin 4)))
    | 0, 1 => some (⟨2, by decide⟩, (Equiv.swap 0 1))
    | 0, 2 => some (⟨3, by decide⟩, Equiv.swap 0 1 * Equiv.swap 1 2)
    | 0, 3 => some (⟨4, by decide⟩, Equiv.swap 0 1 * Equiv.swap 1 2 * Equiv.swap 2 3)
    | 1, 0 => some (⟨0, by decide⟩, (1 : Equiv.Perm (Fin 4)))
    | 1, 1 => some (⟨2, by decide⟩, (1 : Equiv.Perm (Fin 4)))
    | 1, 2 => some (⟨3, by decide⟩, (Equiv.swap 1 2))
    | 1, 3 => some (⟨4, by decide⟩, Equiv.swap 1 2 * Equiv.swap 2 3)
    | 2, 0 => some (⟨0, by decide⟩, (Equiv.swap 0 1))
    | 2, 1 => some (⟨1, by decide⟩, (1 : Equiv.Perm (Fin 4)))
    | 2, 2 => some (⟨3, by decide⟩, (1 : Equiv.Perm (Fin 4)))
    | 2, 3 => some (⟨4, by decide⟩, (Equiv.swap 2 3))
    | 3, 0 => some (⟨0, by decide⟩, Equiv.swap 0 2 * Equiv.swap 2 1)
    | 3, 1 => some (⟨1, by decide⟩, (Equiv.swap 1 2))
    | 3, 2 => some (⟨2, by decide⟩, (1 : Equiv.Perm (Fin 4)))
    | 3, 3 => some (⟨4, by decide⟩, (1 : Equiv.Perm (Fin 4)))
    | 4, 0 => some (⟨0, by decide⟩, Equiv.swap 0 3 * Equiv.swap 3 2 * Equiv.swap 2 1)
    | 4, 1 => some (⟨1, by decide⟩, Equiv.swap 1 3 * Equiv.swap 3 2)
    | 4, 2 => some (⟨2, by decide⟩, (Equiv.swap 2 3))
    | _, _ => some (⟨3, by decide⟩, (1 : Equiv.Perm (Fin 4)))⟩

/-- Every face of `s3Simplex` is glued to the facet opposite the correct vertex of `Δ⁴`. -/
theorem s3Simplex_partner :
    ∀ t i, ∃ g : Equiv.Perm (Fin 4), s3Simplex.glue t i = some (facetVertex t i, g) := by
  decide

theorem s3Simplex_consistent : s3Simplex.Consistent := by decide

theorem s3Simplex_orientable : s3Simplex.Orientable := by decide

theorem s3Simplex_connected : s3Simplex.Connected := by decide

theorem s3Simplex_closed : s3Simplex.Closed := by decide

theorem s3Simplex_fvector :
    s3Simplex.vertexClasses.card = 5 ∧ s3Simplex.edgeClasses.card = 10 ∧
      s3Simplex.faceClasses.card = 10 := by
  decide

theorem s3Simplex_euler : s3Simplex.eulerChar3 = 0 := by decide

/-- The boundary of the 4-simplex is a closed combinatorial 3-manifold with vanishing Euler
characteristic (the 3-sphere). -/
theorem s3Simplex_manifold : s3Simplex.IsCombinatorialManifold := by decide

/-! ## The solid torus: three tetrahedra -/

/-- The solid torus as three tetrahedra: tetrahedron `0` has corners `(a,b,c,c')`,
tetrahedron `1` corners `(a,b,c',b')` and tetrahedron `2` corners `(a,c',a',b')`.  The two
interior faces `(a,b,c')` and `(a,c',b')` are glued identically (a triangular prism split
into three tetrahedra), and the top triangle `(a,b,c)` is glued to the bottom triangle
`(a',b',c')` by the one-third twist `a ↦ b', b ↦ c', c ↦ a'`. -/
def solidTorus3 : FacePairing3 3 :=
  ⟨fun t i =>
    match t.val, i.val with
    | 0, 2 => some (⟨1, by decide⟩, Equiv.swap 2 3)
    | 0, 3 => some (⟨2, by decide⟩, Equiv.swap 0 3)
    | 1, 1 => some (⟨2, by decide⟩, Equiv.swap 1 2)
    | 1, 3 => some (⟨0, by decide⟩, Equiv.swap 2 3)
    | 2, 0 => some (⟨0, by decide⟩, Equiv.swap 0 3)
    | 2, 2 => some (⟨1, by decide⟩, Equiv.swap 1 2)
    | _, _ => none⟩

theorem solidTorus3_consistent : solidTorus3.Consistent := by decide

theorem solidTorus3_orientationReversing : solidTorus3.OrientationReversing := by decide

theorem solidTorus3_orientable : solidTorus3.Orientable := by decide

theorem solidTorus3_connected : solidTorus3.Connected := by decide

theorem solidTorus3_notClosed : ¬ solidTorus3.Closed := by decide

theorem solidTorus3_fvector :
    solidTorus3.vertexClasses.card = 3 ∧ solidTorus3.edgeClasses.card = 9 ∧
      solidTorus3.faceClasses.card = 9 := by
  decide

theorem solidTorus3_euler : solidTorus3.eulerChar3 = 0 := by decide

theorem solidTorus3_boundaryChi : solidTorus3.boundaryChi = 0 := by decide

theorem solidTorus3_boundary : solidTorus3.BoundaryIsClosedSurface := by decide

/-- The three-tetrahedron prism-with-twist is a combinatorial 3-manifold with boundary: the
solid torus (torus boundary, disk vertex links, path edge links). -/
theorem solidTorus3_manifold : solidTorus3.IsCombinatorialManifoldWithBoundary := by decide

/-! ## The lens space L(3,1): a bipyramid over a triangle -/

/-- The lens space `L(3,1)` as the bipyramid over a triangle: three tetrahedra
`tᵢ = [N, S, wᵢ, wᵢ₊₁]` (indices mod 3).  The side faces `(N,S,wᵢ₊₁)` of `tᵢ` and `tᵢ₊₁`
are glued to each other, and the top face `(N,wᵢ,wᵢ₊₁)` of `tᵢ` is glued to the bottom face
`(S,wᵢ₊₁,wᵢ₊₂)` of `tᵢ₊₁` — the classical identification of `L(3,1)` as the bipyramid with
its top identified with its bottom by the one-third rotation. -/
def lens31 : FacePairing3 3 :=
  ⟨fun t i =>
    match i.val with
    | 0 => some (⟨(t.val + 2) % 3, Nat.mod_lt _ (by decide : 0 < 3)⟩, Equiv.swap 0 1)
    | 1 => some (⟨(t.val + 1) % 3, Nat.mod_lt _ (by decide : 0 < 3)⟩, Equiv.swap 0 1)
    | 2 => some (⟨(t.val + 1) % 3, Nat.mod_lt _ (by decide : 0 < 3)⟩, Equiv.swap 2 3)
    | _ => some (⟨(t.val + 2) % 3, Nat.mod_lt _ (by decide : 0 < 3)⟩, Equiv.swap 2 3)⟩

theorem lens31_consistent : lens31.Consistent := by decide

theorem lens31_orientationReversing : lens31.OrientationReversing := by decide

theorem lens31_orientable : lens31.Orientable := by decide

theorem lens31_connected : lens31.Connected := by decide

theorem lens31_closed : lens31.Closed := by decide

theorem lens31_fvector :
    lens31.vertexClasses.card = 2 ∧ lens31.edgeClasses.card = 5 ∧
      lens31.faceClasses.card = 6 := by
  decide

theorem lens31_euler : lens31.eulerChar3 = 0 := by decide

/-- The bipyramid over a triangle with the one-third twist is a closed combinatorial
3-manifold with vanishing Euler characteristic — the lens space `L(3,1)`. -/
theorem lens31_manifold : lens31.IsCombinatorialManifold := by decide

/-! ## The lens space L(2,1) = RP³ -/

/-- The 3-cycle `(1 2 3)` of the corner indices. -/
def lens21CycleA : Equiv.Perm (Fin 4) := Equiv.swap 1 2 * Equiv.swap 2 3

/-- The 3-cycle `(1 3 2)` of the corner indices. -/
def lens21CycleB : Equiv.Perm (Fin 4) := Equiv.swap 1 2 * Equiv.swap 1 3

/-- The lens space `L(2,1) = RP³` as a four-tetrahedron bipyramid over a 2-gon: the top
cone consists of `[N,c,w₀,w₁]` and `[N,c,w₁,w₀]` glued along their two common side faces,
the bottom cone of `[S,c,w₀,w₁]` and `[S,c,w₁,w₀]`, the top of the bipyramid is glued to its
bottom by the half-turn `w₀ ↦ w₁`, and the base disks of the two cones are identified with
the same half-turn. -/
def lens21 : FacePairing3 4 :=
  ⟨fun t i =>
    match t.val, i.val with
    | 0, 2 => some (⟨1, by decide⟩, Equiv.swap 2 3)
    | 0, 3 => some (⟨1, by decide⟩, Equiv.swap 2 3)
    | 0, 1 => some (⟨3, by decide⟩, 1)
    | 0, 0 => some (⟨3, by decide⟩, lens21CycleA)
    | 1, 2 => some (⟨0, by decide⟩, Equiv.swap 2 3)
    | 1, 3 => some (⟨0, by decide⟩, Equiv.swap 2 3)
    | 1, 1 => some (⟨2, by decide⟩, 1)
    | 1, 0 => some (⟨2, by decide⟩, lens21CycleB)
    | 2, 2 => some (⟨3, by decide⟩, Equiv.swap 2 3)
    | 2, 3 => some (⟨3, by decide⟩, Equiv.swap 2 3)
    | 2, 1 => some (⟨1, by decide⟩, 1)
    | 2, 0 => some (⟨1, by decide⟩, lens21CycleA)
    | 3, 2 => some (⟨2, by decide⟩, Equiv.swap 2 3)
    | 3, 3 => some (⟨2, by decide⟩, Equiv.swap 2 3)
    | 3, 1 => some (⟨0, by decide⟩, 1)
    | 3, 0 => some (⟨0, by decide⟩, lens21CycleB)
    | _, _ => none⟩

theorem lens21_consistent : lens21.Consistent := by decide

theorem lens21_orientable : lens21.Orientable := by decide

theorem lens21_connected : lens21.Connected := by decide

theorem lens21_closed : lens21.Closed := by decide

theorem lens21_fvector :
    lens21.vertexClasses.card = 2 ∧ lens21.edgeClasses.card = 6 ∧
      lens21.faceClasses.card = 8 := by
  decide

theorem lens21_euler : lens21.eulerChar3 = 0 := by decide

/-- The four-tetrahedron bipyramid over a 2-gon with the half-turn is a closed combinatorial
3-manifold with vanishing Euler characteristic — the lens space `L(2,1) = RP³`. -/
theorem lens21_manifold : lens21.IsCombinatorialManifold := by decide

end Triangulation3D

end D11

end Poincare
