#!/usr/bin/env python3
"""Generate the L1 baseline independent axiom/dependency audit Lean module.

The generated file imports *every* authored module of the release package that Lake
built (455 of 456; `D6LedgerProbe` and `ReleaseClaims` produce no oleans and are
driver-only files compiled separately with `lake env lean`), then walks
`Environment.constants` restricted to exactly those modules and:

  * classifies each constant (axiom / def / theorem / inductive / ctor / recursor ...),
  * records its transitive axiom cone via `Lean.collectAxioms`,
  * fails closed unless every cone is contained in {propext, Classical.choice, Quot.sound},
    with the two documented negative-control modules required to be flagged,
  * dumps intra-package direct dependency edges for downstream-use analysis.

Output lines (parsed by baseline/tools/parse_axiom_audit.py):
  L1AXROW <name> <kind> <module> <axioms> <extra> <internal>
  L1DEP   <user> <dep>
  L1SUM   <key> <value>
  L1AXVERDICT PASS|FAIL ...
"""
import os
import sys

ROOT = "release"
OUT = "baseline/audit/AxiomAuditAll.lean"

# Declarations whose cones are *expected* to be unapproved: the two documented
# negative controls (an axiom and the theorem built from it).
EXPECTED_BAD = [
    "Poincare.D12.TriangulationTopology.NegControl.d12NegControlBadAxiom",
    "Poincare.D12.TriangulationTopology.NegControl.d12NegControlBadTheorem",
    "Poincare.D12.VolumeIBP.Audit.negativeControl",
]


def modules(root):
    mods = []
    for dirpath, dirnames, filenames in os.walk(root):
        if ".lake" in dirpath.split(os.sep):
            continue
        for f in sorted(filenames):
            if f.endswith(".lean"):
                p = os.path.relpath(os.path.join(dirpath, f), root)
                mods.append(p[:-5].replace(os.sep, "."))
    return sorted(mods)


def main():
    mods = modules(ROOT)
    skipped = [m for m in mods if m in ("D6LedgerProbe", "ReleaseClaims")]
    imported = [m for m in mods if m not in skipped]
    lines = []
    lines.append("/- GENERATED by baseline/tools/gen_axiom_audit.py — do not edit by hand. -/")
    for m in imported:
        lines.append(f"import {m}")
    lines.append("")
    lines.append("open Lean Elab Command")
    lines.append("")
    lines.append("namespace L1BaselineAudit")
    lines.append("")
    lines.append("/-- Modules under audit: every authored release module Lake compiled. -/")
    lines.append("def targetModules : Array Name := #[")
    lines.append(",\n".join(f"  `{m}" for m in imported))
    lines.append("]")
    lines.append("")
    lines.append("/-- Kernel axioms approved for this baseline. -/")
    lines.append("def approvedAxioms : Array Name := #[``propext, ``Classical.choice, ``Quot.sound]")
    lines.append("")
    lines.append("/-- Documented negative controls: their cones MUST be flagged. -/")
    lines.append("def expectedBad : Array Name := #[")
    lines.append(",\n".join(f"  `{n}" for n in EXPECTED_BAD))
    lines.append("]")
    lines.append("")
    lines.append("def kindOf : ConstantInfo → String")
    lines.append("  | .axiomInfo _ => \"axiom\"")
    lines.append("  | .defnInfo v =>")
    lines.append("      if v.safety == .unsafe then \"unsafe_def\"")
    lines.append("      else if v.safety == .partial then \"partial_def\" else \"def\"")
    lines.append("  | .thmInfo _ => \"theorem\"")
    lines.append("  | .opaqueInfo _ => \"opaque\"")
    lines.append("  | .quotInfo _ => \"quot\"")
    lines.append("  | .inductInfo _ => \"inductive\"")
    lines.append("  | .ctorInfo _ => \"ctor\"")
    lines.append("  | .recInfo _ => \"recursor\"")
    lines.append("")
    lines.append("end L1BaselineAudit")
    lines.append("")
    lines.append("open L1BaselineAudit in")
    lines.append("run_cmd do")
    lines.append("  let env ← getEnv")
    lines.append("  let mods := env.header.moduleNames")
    lines.append("  let rows : Array (Name × ConstantInfo × Name) :=")
    lines.append("    env.constants.fold (fun acc n ci =>")
    lines.append("      match env.getModuleIdxFor? n with")
    lines.append("      | some midx =>")
    lines.append("          let m := mods.getD midx .anonymous")
    lines.append("          if targetModules.contains m then acc.push (n, ci, m) else acc")
    lines.append("      | none => acc) #[]")
    lines.append("  let mut nDecl : Nat := 0")
    lines.append("  let mut nTheorem : Nat := 0")
    lines.append("  let mut nDef : Nat := 0")
    lines.append("  let mut nAxiom : Nat := 0")
    lines.append("  let mut nUnsafe : Nat := 0")
    lines.append("  let mut nPartial : Nat := 0")
    lines.append("  let mut nSorry : Nat := 0")
    lines.append("  let mut nNative : Nat := 0")
    lines.append("  let mut nUnexpected : Nat := 0")
    lines.append("  let mut nExpectedSeen : Nat := 0")
    lines.append("  let mut nCollectFail : Nat := 0")
    lines.append("  let mut modulesSeen : Array Name := #[]")
    lines.append("  let mut deps : Array String := #[]")
    lines.append("  for (n, ci, m) in rows do")
    lines.append("    if !modulesSeen.contains m then modulesSeen := modulesSeen.push m")
    lines.append("    nDecl := nDecl + 1")
    lines.append("    let kind := kindOf ci")
    lines.append("    if kind == \"theorem\" then nTheorem := nTheorem + 1")
    lines.append("    if kind == \"def\" || kind == \"partial_def\" then nDef := nDef + 1")
    lines.append("    if kind == \"axiom\" then nAxiom := nAxiom + 1")
    lines.append("    if kind == \"unsafe_def\" then nUnsafe := nUnsafe + 1")
    lines.append("    if kind == \"partial_def\" then nPartial := nPartial + 1")
    lines.append("    -- direct intra-package dependency edges (type + value)")
    lines.append("    let used := ci.type.getUsedConstants ++ (ci.value?.map (·.getUsedConstants)).getD #[]")
    lines.append("    for d in used do")
    lines.append("      match env.getModuleIdxFor? d with")
    lines.append("      | some didx =>")
    lines.append("          if targetModules.contains (mods.getD didx .anonymous) then")
    lines.append("            deps := deps.push s!\"{n}\\t{d}\"")
    lines.append("      | none => pure ()")
    lines.append("    let axs ←")
    lines.append("      try")
    lines.append("        Lean.collectAxioms n")
    lines.append("      catch _ =>")
    lines.append("        nCollectFail := nCollectFail + 1")
    lines.append("        pure #[]")
    lines.append("    let extra := axs.filter (fun a => !approvedAxioms.contains a)")
    lines.append("    if extra.contains `sorryAx then nSorry := nSorry + 1")
    lines.append("    if extra.any (fun a => a.toString.contains \"native\") then nNative := nNative + 1")
    lines.append("    if !extra.isEmpty then")
    lines.append("      if expectedBad.contains n then nExpectedSeen := nExpectedSeen + 1")
    lines.append("      else nUnexpected := nUnexpected + 1")
    lines.append("    IO.println s!\"L1AXROW\\t{n}\\t{kind}\\t{m}\\t{String.intercalate \",\" (axs.toList.map toString)}\\t{String.intercalate \",\" (extra.toList.map toString)}\\t{n.isInternal}\"")
    lines.append("  for d in deps do IO.println s!\"L1DEP\\t{d}\"")
    lines.append("  IO.println s!\"L1SUM\\tdeclarations\\t{nDecl}\"")
    lines.append("  IO.println s!\"L1SUM\\ttheorems\\t{nTheorem}\"")
    lines.append("  IO.println s!\"L1SUM\\tdefs\\t{nDef}\"")
    lines.append("  IO.println s!\"L1SUM\\taxioms\\t{nAxiom}\"")
    lines.append("  IO.println s!\"L1SUM\\tunsafe\\t{nUnsafe}\"")
    lines.append("  IO.println s!\"L1SUM\\tpartial\\t{nPartial}\"")
    lines.append("  IO.println s!\"L1SUM\\tsorry\\t{nSorry}\"")
    lines.append("  IO.println s!\"L1SUM\\tnative\\t{nNative}\"")
    lines.append("  IO.println s!\"L1SUM\\tunexpected_violations\\t{nUnexpected}\"")
    lines.append("  IO.println s!\"L1SUM\\texpected_negative_controls_seen\\t{nExpectedSeen}\"")
    lines.append("  IO.println s!\"L1SUM\\tcollect_failures\\t{nCollectFail}\"")
    lines.append("  IO.println s!\"L1SUM\\tpackage_modules_with_declarations\\t{modulesSeen.size}\"")
    lines.append("  IO.println s!\"L1SUM\\tdeclared_modules_imported\\t{targetModules.size}\"")
    lines.append("  IO.println s!\"L1SUM\\tdep_edges\\t{deps.size}\"")
    lines.append("  let ok := nUnexpected == 0 && nCollectFail == 0 && nSorry == 0")
    lines.append("    && nUnsafe == 0 && nNative == 0 && nExpectedSeen == expectedBad.size")
    lines.append("  if ok then")
    lines.append("    IO.println \"L1AXVERDICT\\tPASS — every audited declaration's axiom cone ⊆ {propext, Classical.choice, Quot.sound}; both negative controls detected\"")
    lines.append("  else")
    lines.append("    IO.println \"L1AXVERDICT\\tFAIL\"")
    lines.append("    throwError \"L1 baseline axiom audit FAILED (unexpected={nUnexpected}, collect_fail={nCollectFail}, sorry={nSorry}, unsafe={nUnsafe}, native={nNative}, expected_seen={nExpectedSeen}/{expectedBad.size})\"")
    lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: imports={len(imported)} skipped={skipped}")


if __name__ == "__main__":
    sys.exit(main())
