#!/usr/bin/env python3
"""Generate corrected dependency-graph drivers (proof-level edges for theorems).

Why: the first invocation's audit drivers used `ci.value?` without
`allowOpaque := true`.  In this Lean version `ConstantInfo.value?` returns `none`
for `.thmInfo` / `.opaqueInfo` unless that flag is set (Lean/Declaration.lean
v4.34.0-rc2, line 483), so `dep-edges.tsv` recorded only *type-level* constants for
theorem users -- proof-body edges such as
`..._old_recovered -> ..._of_one_le` were missing.  The axiom audit itself is
unaffected: `Lean.collectAxioms` matches `.thmInfo v` and traverses `v.value`
directly (Lean/Util/CollectAxioms.lean), which is why the negative-control theorem
was still flagged.

This generator reuses the frozen partition (baseline/audit/partition.json) and emits
drivers that write `L2DEP` lines using the corrected accessor.  No collectAxioms is
run, so the driver is only a dependency-graph rebuild.

Outputs: baseline/audit/DepAudit_G1.lean, baseline/audit/DepAudit_G2.lean
"""
import json
import os

WT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUTDIR = os.path.join(WT, "baseline/audit")

BODY = r'''
open Lean Elab Command

namespace L1DepAudit@LABEL@

/-- Modules whose declarations are enumerated in this partition. -/
def targetModules : Array Name := #[
@MODULES@
]

end L1DepAudit@LABEL@

open L1DepAudit@LABEL@ in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let rows : Array (Name × ConstantInfo × Name) :=
    env.constants.fold (fun acc n ci =>
      match env.getModuleIdxFor? n with
      | some midx =>
          let m := mods.getD midx .anonymous
          if targetModules.contains m then acc.push (n, ci, m) else acc
      | none => acc) #[]
  let mut nDecl : Nat := 0
  let mut nEdges : Nat := 0
  let mut deps : Array String := #[]
  for (n, _ci, _m) in rows do
    nDecl := nDecl + 1
    -- corrected: include theorem/opaque proof bodies (allowOpaque := true)
    let used := _ci.type.getUsedConstants
      ++ ((ConstantInfo.value? _ci (allowOpaque := true)).map (·.getUsedConstants)).getD #[]
    for d in used do
      match env.getModuleIdxFor? d with
      | some didx =>
          if targetModules.contains (mods.getD didx .anonymous) then
            deps := deps.push s!"{n}\t{d}"
            nEdges := nEdges + 1
      | none => pure ()
  IO.println s!"L2SUM\tpartition\t@LABEL@"
  IO.println s!"L2SUM\tdeclarations\t{nDecl}"
  IO.println s!"L2SUM\tedges\t{nEdges}"
  IO.println s!"L2SUM\tdistinct_declared\t{rows.size}"
  for d in deps do IO.println s!"L2DEP\t{d}"
  IO.println "L2DEPVERDICT\tDONE"
'''


def main():
    part = json.load(open(os.path.join(OUTDIR, "partition.json")))
    for lab, v in part["groups"].items():
        mods = v["modules"]
        body = ("/- GENERATED by baseline/tools/gen_dep_audit.py — corrected proof-level "
                "dependency graph; do not edit. -/\n"
                + "\n".join(f"import {m}" for m in mods) + "\n"
                + BODY.replace("@LABEL@", lab)
                .replace("@MODULES@", ",\n".join(f"  `{m}" for m in mods)))
        out = os.path.join(OUTDIR, f"DepAudit_{lab}.lean")
        open(out, "w").write(body)
        print(f"{lab}: {len(mods)} modules -> {out}")


if __name__ == "__main__":
    main()
