-- A3 declaration-kind audit for D12-geometric-compactness
-- generated by D13-cross-audit-360-cards; do not edit

import Poincare.D12.GeometricCompactness.Basic
import Poincare.D12.GeometricCompactness.Criterion
import Poincare.D12.GeometricCompactness.Frontier
import Poincare.D12.GeometricCompactness.GridFamily

set_option maxHeartbeats 400000


open Lean Elab Command

def a3KindNames : List Name := [
  `Poincare.D12.GeometricCompactness.cover_transfer_of_hausdorffDist_lt,
  `Poincare.D12.GeometricCompactness.cover_transfer_of_ghDist,
  `Poincare.D12.GeometricCompactness.cover_transfer_of_isometry,
  `Poincare.D12.GeometricCompactness.diam_transfer_of_hausdorffDist_lt,
  `Poincare.D12.GeometricCompactness.diam_transfer_of_ghDist,
  `Poincare.D12.GeometricCompactness.ghDist_congr_left,
  `Poincare.D12.GeometricCompactness.ghDist_congr_right,
  `Poincare.D12.GeometricCompactness.toGHSpace_rep_isometryEquiv,
  `Poincare.D12.GeometricCompactness.diam_rep_of_toGHSpace,
  `Poincare.D12.GeometricCompactness.uniformCovers_of_totallyBounded,
  `Poincare.D12.GeometricCompactness.totallyBounded_iff_uniformCovers,
  `Poincare.D12.GeometricCompactness.isCompact_of_uniformCovers,
  `Poincare.D12.GeometricCompactness.gromovCriterion,
  `Poincare.D12.GeometricCompactness.gh_subseq_of_compact,
  `Poincare.D12.GeometricCompactness.gh_subseq_of_uniformCovers,
  `Poincare.D12.GeometricCompactness.closure_isCompact_of_totallyBounded,
  `Poincare.D12.GeometricCompactness.gh_subseq_of_familyBounds,
  `Poincare.D12.GeometricCompactness.square_grid_dense,
  `Poincare.D12.GeometricCompactness.gridUniformCover,
  `Poincare.D12.GeometricCompactness.gridSpace_diam_le,
  `Poincare.D12.GeometricCompactness.hausdorffDist_grid_square_le,
  `Poincare.D12.GeometricCompactness.grid_gh_tendsto_square,
  `Poincare.D12.GeometricCompactness.gridSpace_card,
  `Poincare.D12.GeometricCompactness.gridGH_injective,
  `Poincare.D12.GeometricCompactness.gridFamily_infinite,
  `Poincare.D12.GeometricCompactness.gridFamily_totallyBounded,
  `Poincare.D12.GeometricCompactness.gridFamily_closure_isCompact,
  `Poincare.D12.GeometricCompactness.gridFamily_subseq,
  `Poincare.D12.GeometricCompactness.isCompact_unitSquare,
  `Poincare.D12.GeometricCompactness.zero_mem_gridSet,
  `Poincare.D12.GeometricCompactness.gridPoint_coord,
  `Poincare.D12.GeometricCompactness.harmonicCoordinatesExistence,
  `Poincare.D12.GeometricCompactness.bishopGromovVolumeComparison,
  `Poincare.D12.GeometricCompactness.curvatureBoundImpliesUniformCovers,
  `Poincare.D12.GeometricCompactness.cheegerGromovCompactness,
  `Poincare.D12.GeometricCompactness.ancientKappaCompactnessFrontier,
  `Poincare.D12.GeometricCompactness.canonicalNeighborhoodFrontier,
  `Poincare.D12.GeometricCompactness.canonicalNeighborhoodFrontier_iff,
  `Poincare.D12.GeometricCompactness.curvatureBoundImpliesUniformCovers_iff
]

run_cmd do
  let mut counts : Std.HashMap String Nat := {}
  for n in a3KindNames do
    let ci ← getConstInfo n
    let k : String ← match ci with
      | .axiomInfo _  => pure "axiom"
      | .defnInfo _   => pure "def"
      | .thmInfo _    => pure "theorem"
      | .opaqueInfo _ => pure "opaque"
      | .quotInfo _   => pure "quot"
      | .inductInfo _ => pure "inductive"
      | .ctorInfo _   => pure "ctor"
      | .recInfo _    => pure "rec"
    let res ← liftTermElabM <| Lean.Meta.forallTelescopeReducing ci.type fun _ body => do
      if ← Lean.Meta.isProp body then pure "PropResult"
      else match body with
        | .sort l => pure (match l with | .zero => "PropFormer" | _ => "TypeFormer")
        | _ => pure "DataResult"
    counts := counts.insert (k ++ ":" ++ res) (counts.getD (k ++ ":" ++ res) 0 + 1)
    logInfo m!"A3KIND\t{n}\t{k}\t{res}"
  logInfo m!"A3KIND-SUMMARY\t{toString counts.toList}"

