import Mathlib.Tactic
import Mathlib.Analysis.Calculus.Deriv.MeanValue
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.LinearAlgebra.Matrix.PosDef
import Mathlib.Analysis.SpecialFunctions.Exp

open Filter

#check hasDerivAt_pi
#check div_nonneg_iff_of_pos
#check exists_lt_of_lt_csSup
#check csSup_le
#check le_csSup
#check eventually_nhdsWithin_iff
#check Iio_mem_nhds
#check Ioi_mem_nhds
#check Matrix.dotProduct_self_eq_norm_sq
#check Matrix.vecMul_dotProduct
#check Matrix.star_mulVec
#check Matrix.IsHermitian.conjTranspose_eq
#check HasDerivAt.inv
#check Real.hasDerivAt_exp
#check Real.continuous_sqrt
#check Real.sqrt_div
#check Real.sqrt_sq_eq_abs
#check abs_pow
#check Matrix.dotProduct_sub
#check Matrix.sub_mulVec
#check Matrix.diagonal_apply
#check Matrix.mulVec_mulVec
#check ContinuousWithinAt
#check Metric.mem_nhds_iff
#check ContinuousOn.mono
#check DifferentiableAt.differentiableWithinAt
#check Real.dist_eq
#check Matrix.PosSemidef.dotProduct_mulVec_nonneg
#check Matrix.posSemidef_iff_dotProduct_mulVec
#check Matrix.PosSemidef.diagonal
#check Matrix.diagonal_pow
#check Matrix.diagonal_sub
#check Matrix.mul_apply
#check hasDerivAt_const
#check HasDerivAt.const_mul
#check HasDerivAt.deriv
#check DifferentiableAt.hasDerivAt
#check Matrix.diagonal_apply_eq
#check Matrix.diagonal_apply_ne
#check Filter.Tendsto.eventually
#check abs_neg
#check abs_div
#check Real.sqrt_sq
#check sq_nonneg
#check sub_pos
#check exists_deriv_eq_slope
