/-
Independent D13 cross-audit probe for D13-topping-ricci-adapter-plan (clean).
Generated by audit/tools/gen_probe.py. Fail-closed: any project axiom, unsafe
declaration, sorryAx / native_decide / unapproved axiom in any dependency cone
aborts elaboration.
-/
import Poincare.D13.ToppingAdapter.All
import Poincare.D13.ToppingAdapter.Audit
import Poincare.D13.ToppingAdapter.Core
import Poincare.D13.ToppingAdapter.Scalar
import Poincare.D13.ToppingAdapter.ShortTime
import Poincare.D13.ToppingAdapter.Slab
import Poincare.D13.ToppingAdapter.Volume
import Poincare.D13.UpstreamAdapter.All
import Poincare.D13.UpstreamAdapter.Audit
import Poincare.D13.UpstreamAdapter.EvansHeat
import Poincare.D13.UpstreamAdapter.EvansParametric
import Poincare.D13.UpstreamAdapter.KleinerLottKappa
import Poincare.D13.UpstreamAdapter.MorganTianShrinker
import Lean.Util.CollectAxioms

open Lean Elab Command

namespace D13XAudit_D13_topping_ricci_adapter_plan_clean

def approvedAxioms : List Name := ["propext".toName, "Classical.choice".toName, "Quot.sound".toName]

def packageRoots : List Name := [
  "Poincare".toName, "Probe".toName, "Ledger".toName, "Audit".toName,
  "ReleaseCheck".toName, "ReleaseAudit".toName, "D6AuditReport".toName]

/-- D6 baseline modules are pre-existing; every *other* reachable package module is audited. -/
def baseModules : List Name := [
  "Audit.CounterexampleAudit".toName,
  "Audit.CurvatureODEAudit".toName,
  "Audit.EvolutionAudit".toName,
  "Audit.GeometryAudit".toName,
  "Audit.PromotedEvolutionAudit".toName,
  "D6AuditReport".toName,
  "D6LedgerProbe".toName,
  "Ledger.DefinitionSmoke".toName,
  "Ledger.PerelmanDefinitions".toName,
  "Poincare.Basic".toName,
  "Poincare.Longrun.CurvatureODE".toName,
  "Poincare.Longrun.CurvatureODE.Bridge".toName,
  "Poincare.Longrun.CurvatureODE.Evolution".toName,
  "Poincare.Longrun.CurvatureODE.Invariant".toName,
  "Poincare.Longrun.CurvatureODE.Monotonicity".toName,
  "Poincare.Longrun.CurvatureODE.ScalarODE".toName,
  "Poincare.Longrun.CurvatureODE.State".toName,
  "Poincare.Longrun.Entropy".toName,
  "Poincare.Longrun.Entropy.AxiomAudit".toName,
  "Poincare.Longrun.Entropy.Bridge".toName,
  "Poincare.Longrun.Entropy.Certificate".toName,
  "Poincare.Longrun.Entropy.DiscreteHeat".toName,
  "Poincare.Longrun.Entropy.FiniteGeometry".toName,
  "Poincare.Longrun.Entropy.Functional".toName,
  "Poincare.Longrun.Evolution".toName,
  "Poincare.Longrun.Evolution.Bridge".toName,
  "Poincare.Longrun.Evolution.Continuous".toName,
  "Poincare.Longrun.Evolution.Counterexample".toName,
  "Poincare.Longrun.Evolution.Discrete".toName,
  "Poincare.Longrun.Evolution.Functional".toName,
  "Poincare.Longrun.Evolution.Gibbs".toName,
  "Poincare.Longrun.Geometry".toName,
  "Poincare.Longrun.Geometry.ConnectionAdapter".toName,
  "Poincare.Longrun.Geometry.Contraction".toName,
  "Poincare.Longrun.Geometry.LeviCivitaBlocked".toName,
  "Poincare.Longrun.Geometry.MetricData".toName,
  "Poincare.Longrun.PDE.AxiomAudit".toName,
  "Poincare.Longrun.PDE.ContinuousInterface".toName,
  "Poincare.Longrun.PDE.DiscreteMaximumPrinciple".toName,
  "Poincare.Longrun.PDE.Energy".toName,
  "Poincare.Longrun.PDE.HeatGrid".toName,
  "Poincare.Longrun.Surgery".toName,
  "Poincare.Longrun.Surgery.Axioms".toName,
  "Poincare.Longrun.Surgery.Basic".toName,
  "Poincare.Longrun.Surgery.Chain".toName,
  "Poincare.Longrun.Surgery.Missing".toName,
  "Poincare.Longrun.Surgery.Toy".toName,
  "Poincare.Longrun.Topology.AxiomAudit".toName,
  "Poincare.Longrun.Topology.Basic".toName,
  "Poincare.Longrun.Topology.CompactThreeManifold".toName,
  "Poincare.Longrun.Topology.MissingTheorems".toName,
  "Poincare.Longrun.Topology.Noncollapsing".toName,
  "Poincare.Longrun.Topology.NormalizedVolume".toName,
  "Poincare.Longrun.Topology.Stage6Bridge".toName,
  "Poincare.Stage1.CurvatureAlgebra".toName,
  "Poincare.Stage1.RiemannAdapter".toName,
  "Poincare.Stage6.SphereSimplyConnected".toName,
  "Poincare.Stage6.TopologyBridge".toName,
  "Probe.GeometryApi".toName,
  "Probe.PdeApi".toName,
  "ReleaseAudit".toName,
  "ReleaseCheck".toName,
  "ReleaseClaims".toName]

def excludedModules : List Name := [
  ]

def kindOf : ConstantInfo → String
  | .axiomInfo _ => "axiom"
  | .defnInfo v => match v.safety with
      | .«unsafe» => "unsafe_def"
      | .«partial» => "partial_def"
      | .safe => "def"
  | .thmInfo _ => "theorem"
  | .opaqueInfo _ => "opaque"
  | .quotInfo _ => "quot"
  | .inductInfo _ => "induct"
  | .ctorInfo _ => "ctor"
  | .recInfo _ => "rec"

end D13XAudit_D13_topping_ricci_adapter_plan_clean

open D13XAudit_D13_topping_ricci_adapter_plan_clean in
run_cmd do
  let env ← getEnv
  let mods := env.header.moduleNames
  let audited (m : Name) : Bool :=
    packageRoots.any (fun r => r.isPrefixOf m) && !baseModules.contains m && !excludedModules.contains m
  let rows := env.constants.fold (fun acc n ci =>
    match env.getModuleIdxFor? n with
    | some midx =>
        let m := mods.getD midx .anonymous
        if audited m then acc.push (n, ci, m) else acc
    | none => acc) #[]
  let mut moduleSet : Array Name := #[]
  for (_, _, m) in rows do
    if !moduleSet.contains m then moduleSet := moduleSet.push m
  let mut nAxiom := 0
  let mut nUnsafe := 0
  let mut nSorry := 0
  let mut nNative := 0
  let mut nOther := 0
  let mut nFail := 0
  let mut nProofWanted := 0
  let mut nPartial := 0
  let mut nThm := 0
  for (n, ci, m) in rows do
    if n.toString.contains "proof_wanted" then nProofWanted := nProofWanted + 1
    match ci with
    | .axiomInfo _ => nAxiom := nAxiom + 1
    | .defnInfo v =>
        match v.safety with
        | .«unsafe» => nUnsafe := nUnsafe + 1
        | .«partial» => nPartial := nPartial + 1
        | .safe => pure ()
    | .thmInfo _ => nThm := nThm + 1
    | _ => pure ()
    let axs ←
      try
        Lean.collectAxioms n
      catch _ =>
        nFail := nFail + 1
        pure #[]
    for a in axs do
      if a == ``sorryAx then nSorry := nSorry + 1
      else if a.toString.contains "native_decide" || a == ``ofReduceBool then nNative := nNative + 1
      else if !approvedAxioms.contains a then nOther := nOther + 1
    IO.println s!"D13XDECL	{n}	{kindOf ci}	{m}	{";".intercalate (axs.toList.map Name.toString)}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	modules	{moduleSet.size}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	declarations	{rows.size}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	theorems	{nThm}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	partial_defs	{nPartial}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	project_axioms	{nAxiom}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	unsafe	{nUnsafe}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	sorry_cones	{nSorry}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	native_decide_cones	{nNative}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	unapproved_axiom_cones	{nOther}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	collect_failures	{nFail}"
  IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	proof_wanted	{nProofWanted}"
  if nAxiom + nUnsafe + nSorry + nNative + nOther + nFail + nProofWanted > 0 then
    IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	VERDICT	FAIL"
    throwError "D13XAudit: forbidden dependency found (D13-topping-ricci-adapter-plan, clean)"
  else
    IO.println s!"D13XAUDIT	D13-topping-ricci-adapter-plan	VERDICT	PASS"
