-- A3 declaration-kind audit for D12-surgery-recognition
-- generated by D13-cross-audit-360-cards; do not edit

import Poincare.D12.SurgeryRecognition.BallGluing
import Poincare.D12.SurgeryRecognition.ConnectedSumTopology
import Poincare.D12.SurgeryRecognition.CoveringRecognition
import Poincare.D12.SurgeryRecognition.DeckTrivial
import Poincare.D12.SurgeryRecognition.ExpandedInterfaces
import Poincare.D12.SurgeryRecognition.SphereOfSpheres

set_option maxHeartbeats 400000


open Lean Elab Command

def a3KindNames : List Name := [
  `Poincare.D12.SurgeryRecognition.doubleBallHomeoSphere,
  `Poincare.D12.SurgeryRecognition.northHemisphereHomeo,
  `Poincare.D12.SurgeryRecognition.southHemisphereHomeo,
  `Poincare.D12.SurgeryRecognition.equatorHomeoS2,
  `Poincare.D12.SurgeryRecognition.sphereConnectSum_homeo_sphere,
  `Poincare.D12.SurgeryRecognition.iteratedSphereSum_homeo_sphere,
  `Poincare.D12.SurgeryRecognition.ConnectedSumDecomposition.mkV2,
  `Poincare.D12.SurgeryRecognition.endGame_finalTopology,
  `Poincare.D12.SurgeryRecognition.stage6Target_of_v2decomposition,
  `Poincare.D12.SurgeryRecognition.stage6Target_of_v2hypotheses,
  `Poincare.D12.SurgeryRecognition.finiteFreeOrbit_isQuotientCoveringMap,
  `Poincare.D12.SurgeryRecognition.antipodal_free,
  `Poincare.D12.SurgeryRecognition.antipodalQuotientCovering,
  `Poincare.D12.SurgeryRecognition.antipodalCoveringMap,
  `Poincare.D12.SurgeryRecognition.antipodal_fiber_card_two,
  `Poincare.D12.SurgeryRecognition.antipodal_two_sheets,
  `Poincare.D12.SurgeryRecognition.antipodalModel,
  `Poincare.D12.SurgeryRecognition.antipodalModel_nontrivial,
  `Poincare.D12.SurgeryRecognition.quotientHomeoOfSubsingleton,
  `Poincare.D12.SurgeryRecognition.sphericalPieceRecognition_of,
  `Poincare.D12.SurgeryRecognition.sphereThree_pathConnectedSpace,
  `Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceFormProjection,
  `Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceFormProjection_covering,
  `Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceFormFiberEquivGroup,
  `Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceForm_monodromy_trivial,
  `Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceForm_monodromy_transitive,
  `Poincare.D12.SurgeryRecognition.SphericalSpaceFormModel.spaceForm_fiber_subsingleton,
  `Poincare.D12.SurgeryRecognition.deckTrivial_of_simplyConnected_quotient,
  `Poincare.D12.SurgeryRecognition.sphericalPieceRecognition_of_spaceForm,
  `Poincare.D12.SurgeryRecognition.stage6Target_of_v3hypotheses
]

run_cmd do
  let mut counts : Std.HashMap String Nat := {}
  for n in a3KindNames do
    let ci ← getConstInfo n
    let k : String ← match ci with
      | .axiomInfo _  => pure "axiom"
      | .defnInfo _   => pure "def"
      | .thmInfo _    => pure "theorem"
      | .opaqueInfo _ => pure "opaque"
      | .quotInfo _   => pure "quot"
      | .inductInfo _ => pure "inductive"
      | .ctorInfo _   => pure "ctor"
      | .recInfo _    => pure "rec"
    let res ← liftTermElabM <| Lean.Meta.forallTelescopeReducing ci.type fun _ body => do
      if ← Lean.Meta.isProp body then pure "PropResult"
      else match body with
        | .sort l => pure (match l with | .zero => "PropFormer" | _ => "TypeFormer")
        | _ => pure "DataResult"
    counts := counts.insert (k ++ ":" ++ res) (counts.getD (k ++ ":" ++ res) 0 + 1)
    logInfo m!"A3KIND\t{n}\t{k}\t{res}"
  logInfo m!"A3KIND-SUMMARY\t{toString counts.toList}"

